### ISSUE TITLE
Option not to make a forward declaration a real type

### ISSUE THREAD

**Issue by datdinhquoc** [cython/cython#4566] opened 2022-01-13 07:05 UTC
Forward declarations in Cython are currently real types, consider this example:

mod1.pxd
```
# Forward declaration needed here coz `foo.pxd` and `bar.pxd` have circular types.
cdef public struct bar # Type1

cdef cppclass foo:
    bar* prop
    void method(bar* param)

cdef void func(bar* param) # Type1 (conflict)
```

mod1.pyx
```
# Import bar cppclass
# Need actual cimport here to have memory layout of bar
from bar cimport bar # Type2

cdef cppclass foo:
    void method(bar* param): # Type1
        cdef bar* b = new bar() # Type2
        # Accessing properties of bar here
        print(bar.someProp)

cdef void func(bar* param): # Type2 (conflict)
    pass
```

The problem is `Type1` and `Type2` in the example above are not the same in the implementation file `.pyx`:
* `bar` in param of `method` is the type from the .pxd file
* `bar` in param of `func` is the type from cimport --> Signature mismatch problem
* The rest in statements, `bar` is the type from cimport

The conflict:
* `bar` must be in pxd file due to circular structures of foo and bar
* `bar` must be cimported in pyx due to the need to have memory layout
* They are of the same name but different types, hence the type mismatch at `func` (in pyx file)

More conflicts when there are forward declarations of the same name in, for example 5 files, then there are 5 different forward declared types.

This is confusing, should the type with the same name by forward declaration and by cimport be just one type? (it seems Cython makes 2 type identifiers for them). The feature is: an empty type declaration shouldn't be a type, it should wait to match the type of the same name in cimport dependency solving. This case is already appearing in a single module when compiled, not cross-modules.

ps. My current work-around is putting all forward declarations in a master file so the same type name don't get duplicated into multiple type identifiers; and do pointer casting when needed.

**Comment by scoder** [comment] 2022-01-13 09:05
Isn't this a duplicate of #4561? `cppclass` in a .pxd file is simply not currently supported for sharing types.

That said, doesn't `import … as …` help here?

**Comment by datdinhquoc** [comment] 2022-01-13 09:17
> Isn't this a duplicate of #4561? `cppclass` in a .pxd file is simply not currently supported for sharing types.
> 
> That said, doesn't `import … as …` help here?

Not really a duplicate of #4561 , that 4561 is about accessing Python in struct members.

This issue is about forward declaration: The type created by empty `cdef struct` (in pxd) and the type created by `cimport` (in pyx) are written as the same name but are not of the same type identifier.

The fact is that `cppclass` is designed for grabbing C++ stuff (https://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html) but I wish it could be possible to write a full `cdef cppclass` in Cython. 

It's possible just to use `cdef class` instead but that won't be good to implement everything with `nogil` for real threading (not concurrency).

**Comment by scoder** [comment] 2022-01-13 09:28
Which modules in your example are `foo` and `bar`?

**Comment by datdinhquoc** [comment] 2022-01-13 09:30
> Which modules in your example are `foo` and `bar`?

`bar` can be just anything, something simple:
```
# bar.pxd
cdef cppclass bar:
    float someProp;
```

**Comment by scoder** [comment] 2022-01-13 09:41
Ok, again, you cannot currently share a `cppclass` via .pxd files. There's ticket #4561 for that issue.

And declaring a new type, well, declares a new type. If you want to avoid that, then use `cimport` to share that same type across modules. And if that leads to naming conflicts, then use `cimport … as …`. That's what that Python feature is there for.

BTW, if you can control the conflicting names yourself, then I would recommend avoiding them in the first place by making them unique. In the end, all of this might end up in the same C/C++ file of someone, which has a flat namespace.

If you want to keep the Python/Cython names the same but still use different names in C, then you can use cname strings for that to make Cython use specific C code for that name.

I'm closing this ticket since I can't see anything wrong here.

**Closed by scoder** 2022-01-13 09:41 UTC
