### ISSUE TITLE
[BUG] Error parsing templated function with const argument

### ISSUE THREAD

**Issue by isuruf** [cython/cython#5489] opened 2023-06-15 21:53 UTC
### Describe the bug

I get the error
```cython
Error compiling Cython file:
------------------------------------------------------------
...
from libcpp.memory cimport shared_ptr, make_shared

cdef foo():
    cdef  shared_ptr[const int] a = make_shared[const int](2)
                                                      ^
------------------------------------------------------------

test.pyx:4:54: Expected ']', found 'int'
```

`const int` is just to make the example small.

### Code to reproduce the behaviour:

```cython
from libcpp.memory cimport shared_ptr, make_shared

cdef foo():
    cdef  shared_ptr[const int] a = make_shared[const int](2)

```

### OS

Linux

### Python version

3.10.6

### Cython version

3.0.0rc1

### Additional context

This is not a regression and the bug is there in 0.x series as well.

**Comment by da-woods** [comment] 2023-06-16 05:41
Duplicate of https://github.com/cython/cython/issues/4180

**Closed by da-woods** 2023-06-16 05:41 UTC
