### ISSUE TITLE
enum signedness test generates warning

### ISSUE THREAD

**Issue by pitrou** [cython/cython#2186] opened 2018-03-28 15:24 UTC
I'm not sure anything can be done here, but FTR the enum signedness test generated by Cython can raise a warning with unsigned enums (you need `-Wconversion` with gcc):
```
/home/antoine/arrow/python/build/temp.linux-x86_64-3.6/lib.cxx:125758:70: warning: the result of the conversion is unspecified because '-1' is outside the range of type 'arrow::Type::type' [-Wconversion]
     const enum  arrow::Type::type neg_one = (enum  arrow::Type::type) -1, const_zero = (enum  arrow::Type::type) 0;
```

According to the warning's text, the cast result *may* be unspecified according to the standard?

**Comment by robertwb** [comment] 2018-05-01 15:24
Do you have any other ideas to check for the signedness of enum types?

**Comment by pitrou** [comment] 2018-05-01 15:26
No idea, sorry :-(

**Comment by jwilk** [comment] 2018-07-13 23:11
I think this should work:
```c
is_unsigned = (enum T)0 - 1 > 0;
```

**Comment by robertwb** [comment] 2018-07-18 05:06
Great idea.

**Comment by scoder** [comment] 2018-07-18 19:38
... except for enums in C++:
```
compiling (cpp) restaurant ... 
=== C/C++ compiler output: ===
restaurant.cpp: In function â€˜PyObject* __Pyx_PyUnicode_From_enum____pyx_t_6dishes_otherstuff(__pyx_t_6dishes_otherstuff, Py_ssize_t, char, char)â€™:
restaurant.cpp:1899:89: error: invalid conversion from â€˜intâ€™ to â€˜__pyx_t_6dishes_otherstuffâ€™ [-fpermissive]
     const enum __pyx_t_6dishes_otherstuff neg_one = (enum __pyx_t_6dishes_otherstuff) 0 - (enum __pyx_t_6dishes_otherstuff) 1, const_zero = (enum __pyx_t_6dishes_otherstuff) 0;
restaurant.cpp: In function â€˜PyObject* __Pyx_PyUnicode_From_enum____pyx_t_6dishes_otherstuff(__pyx_t_6dishes_otherstuff, Py_ssize_t, char, char)â€™:
restaurant.cpp:1899:89: error: invalid conversion from â€˜intâ€™ to â€˜__pyx_t_6dishes_otherstuffâ€™ [-fpermissive]
     const enum __pyx_t_6dishes_otherstuff neg_one = (enum __pyx_t_6dishes_otherstuff) 0 - (enum __pyx_t_6dishes_otherstuff) 1, const_zero = (enum __pyx_t_6dishes_otherstuff) 0;
```
I have no idea why this change makes a difference here, but it did make g++ unhappy.

**Comment by scoder** [comment] 2018-10-19 13:29
Ah, yes, Robert changed the code to that shortly after we noticed the C++ problems. I'll close this issue. Or was the reason for your comment that you still see this with 0.29?

**Comment by pitrou** [comment] 2018-10-19 13:30
No, nothing like that :-) Thanks for the fix!

**Comment by orivej** [comment] 2018-12-12 20:16
@pitrou Could you show the source .pyx or the generated C or C++ that causes the warning? Which compiler prints the warning? I can not reproduce it in https://github.com/cython/cython/issues/2749#issuecomment-446722993

**Comment by pitrou** [comment] 2018-12-12 21:01
@orivej As I mentioned in the first message, you need to activate `-Wconversion`. Then it is pretty much reproducible: https://godbolt.org/z/DlXIfA

**Comment by scoder** [comment] 2019-02-01 20:57
@pitrou, do you think that GH-2767 would also work for you?

**Comment by pitrou** [comment] 2019-02-02 10:02
@scoder It would certainly work for me, thank you :-)

**Comment by pitrou** [comment] 2019-02-20 14:10
it seems PR #2767 didn't fix all the warnings. I still get some of them, e.g.:
```
/home/antoine/arrow/python/build/temp.linux-x86_64-3.7/lib.cpp:143178:47: warning: the result of the conversion is unspecified because ‘-1’ is outside the range of type ‘arrow::Type::type’ [-Wconversion]
             return (enum  arrow::Type::type) -1;
                                               ^
```

I've pasted one of the generated functions here:
https://gist.github.com/pitrou/00c11653a92fa299a3187850e8e8717b

**Comment by pitrou** [comment] 2019-03-26 13:35
As written above, this is still an issue with Cython 0.29.6. Should this issue be reopened or should I create a new one?

**Comment by scoder** [comment] 2019-03-26 15:30
Sorry, must have missed your message. Please create a new issue so that I can assign a new fix version to it (when it's fixed).

**Closed by scoder** 2019-03-26 15:30 UTC
Labels: Code Generation, defect
