### ISSUE TITLE
[BUG] Declaring unordered_set of PyObject* fails

### ISSUE THREAD

**Issue by maxbachmann** [cython/cython#4189] opened 2021-05-22 22:54 UTC
**Describe the bug**
The following declaration:
```
cdef class Example:
    cdef unordered_set[PyObject*, PyObjectHash] test
```
causes the error `Expected an identifier or literal`

It works to declare it without the hash functions:
```
cdef class Example:
    cdef unordered_set[PyObject*] test
```
or when the pointer has a different type
```
cdef class Example:
    cdef unordered_set[void*, PyObjectHash] test
```

**Expected behavior**
It should work similar to the way it works for different pointer types.

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: 3.9
 - Cython version: master (about a week old)

**Comment by da-woods** [comment] 2021-05-23 05:52
You have done `from cpython cimport PyObject`? It looks to me like it just didn't know what PyObject is.

**Comment by maxbachmann** [comment] 2021-05-23 06:06
Yes I have done `from cpython cimport PyObject`

**Comment by da-woods** [comment] 2021-05-23 07:09
It looks like you can do `ctypedef PyObject* PyObjectPtr` and use `PyObjectPtr`.

The problem doesn't specifically look to be `PyObject*` but any non-builtin pointer (e.g. `double*` or `void*` works, but a `cdef struct` point doesn't)

**Comment by da-woods** [comment] 2021-05-23 07:11
I suspect this is a duplicate of https://github.com/cython/cython/issues/534, but it's clearly a little more complicated (since `int*` works here)

**Comment by scoder** [comment] 2021-05-23 07:48
Yes, looks like the same issue in the parser. Especially the fact that it works for "well known" types but not for "less known" types.

It was not a design goal of C (let alone C++) to be easy to parse. Neither by machines nor humans, one could add.

**Closed by scoder** 2021-05-23 07:48 UTC
Labels: Parsing, R: duplicate, defect

**Comment by maxbachmann** [comment] 2021-05-23 16:33
Yes it looks like the same issue.
