### ISSUE TITLE
Feature request: Support __del__() in cdef class

### ISSUE THREAD

**Issue by sonots** [cython/cython#1814] opened 2017-08-09 15:42 UTC
I want to use `__del__()` method to do some python operations when an object is released.

## Background

We have an application of cython named [cupy](https://github.com/cupy/cupy). This library uses CUDA (NVIDIA GPU API) and stores allocated GPU memory pointer on its own memory pool. We want to release a GPU memory pointer into memory pool when a memory object is released.

## Problem

We before used `__dealloc__()` as a hook to release a memory pointer into memory pool, but noticed for a statement:

ref. http://cython.readthedocs.io/en/latest/src/userguide/special_methods.html#finalization-method-dealloc

> You need to be careful what you do in a `__dealloc__()` method. By the time your `__dealloc__()` method is called, the object may already have been partially destroyed and may not be in a valid state as far as Python is concerned, so **you should avoid invoking any Python operations** which might touch the object. In particular, don’t call any other methods of the object or do anything which might cause the object to be resurrected. It’s best if you stick to just deallocating C data.

So, I first tried to change `__dealloc__()` to `__del__()` to achieve our purpose, but now I noticed that 

> Note There is no `__del__()` method for extension types.

Therefore, I had to change `cdef class` to a usual `class`. But, I observed degraded performance.

https://github.com/cupy/cupy/pull/381

## Conclusion

I want to avoid degraded performance introduced by changing `cdef class` to `class` to use `__del__()` instead of `__dealloc__()`.

I searched github issues, but I could not find any previous discussions for `__del__()`. Please let me know if there already exist previous discussions for `__del__()`.

**Comment by scoder** [comment] 2017-08-09 16:15
Ah, yes, the object holds a reference to another object in your case (the memory pool). That reference might have been cleared already during garbage collection.

With the new finalisation protocol in Py3.4, supporting ``__del__()`` does sound reasonable. Not sure how to support older Python versions, though...
https://www.python.org/dev/peps/pep-0442/

**Comment by da-woods** [comment] 2022-05-29 15:44
Duplicate of https://github.com/cython/cython/issues/3612 - now implemented

**Closed by da-woods** 2022-05-29 15:44 UTC
