### ISSUE TITLE
call_py_cy.cy_call_onearg does crash on Python 3.10 (likely also Python 3.9)

### ISSUE THREAD

**Issue by vstinner** [cython/cython#3641] opened 2020-05-26 17:10 UTC
When testing Cython on the master branch of Python (future version 3.10), I got the following crash:

```
Run command: /home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/venv/bin/python -X dev runtests.py -vv --no-pyregr in /home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/Cython-0.29.19

(...)

Doctest: call_py_cy.cy_call_noargs ... ok
cy_call_onearg (call_py_cy)
Doctest: call_py_cy.cy_call_onearg ... python: Objects/unicodeobject.c :2936 : unicode_fromformat_arg:  l'assertion « obj && _PyUnicode_CHECK(obj) » a échoué.
Fatal Python error: Aborted

Thread 0x00007fba480bc700 (most recent call first):
  File "/home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/Cython-0.29.19/runtests.py", line 2194 in time_stamper
  File "/home/vstinner/python/master/Lib/threading.py", line 888 in run
  File "/home/vstinner/python/master/Lib/threading.py", line 950 in _bootstrap_inner
  File "/home/vstinner/python/master/Lib/threading.py", line 908 in _bootstrap

Current thread 0x00007fba55cc9740 (most recent call first):
  File "<doctest call_py_cy.cy_call_onearg[1]>", line 1 in <module>
  File "/home/vstinner/python/master/Lib/doctest.py", line 1336 in __run
  File "/home/vstinner/python/master/Lib/doctest.py", line 1483 in run
  File "/home/vstinner/python/master/Lib/doctest.py", line 2198 in runTest
  File "/home/vstinner/python/master/Lib/unittest/case.py", line 550 in _callTestMethod
  File "/home/vstinner/python/master/Lib/unittest/case.py", line 593 in run
  File "/home/vstinner/python/master/Lib/unittest/case.py", line 653 in __call__
  File "/home/vstinner/python/master/Lib/unittest/suite.py", line 122 in run
  File "/home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/Cython-0.29.19/runtests.py", line 1280 in run_test
  File "/home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/Cython-0.29.19/runtests.py", line 1286 in run_forked_test
  File "/home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/Cython-0.29.19/runtests.py", line 1281 in run_doctests
  File "/home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/Cython-0.29.19/runtests.py", line 1269 in run_tests
  File "/home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/Cython-0.29.19/runtests.py", line 1251 in run
  File "/home/vstinner/python/master/Lib/unittest/case.py", line 653 in __call__
  File "/home/vstinner/python/master/Lib/unittest/suite.py", line 122 in run
  File "/home/vstinner/python/master/Lib/unittest/suite.py", line 84 in __call__
  File "/home/vstinner/python/master/Lib/unittest/suite.py", line 122 in run
  File "/home/vstinner/python/master/Lib/unittest/suite.py", line 84 in __call__
  File "/home/vstinner/python/master/Lib/unittest/suite.py", line 122 in run
  File "/home/vstinner/python/master/Lib/unittest/suite.py", line 84 in __call__
  File "/home/vstinner/python/master/Lib/unittest/runner.py", line 176 in run
  File "/home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/Cython-0.29.19/runtests.py", line 2477 in runtests
  File "/home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/Cython-0.29.19/runtests.py", line 2146 in main
  File "/home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/Cython-0.29.19/runtests.py", line 2499 in <module>
Traceback (most recent call last):
  File "/home/vstinner/python/master/Lib/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vstinner/python/master/Lib/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vstinner/myprojects/pythonci/pythonci/__main__.py", line 2, in <module>
    CI().main()
  File "/home/vstinner/myprojects/pythonci/pythonci/_ci.py", line 370, in main
    task.run_tests()
  File "/home/vstinner/myprojects/pythonci/pythonci/task/__init__.py", line 47, in run_tests
    self._run_tests()
  File "/home/vstinner/myprojects/pythonci/pythonci/task/cython.py", line 21, in _run_tests
    self.app.run_python(['runtests.py', '-vv', '--no-pyregr'],
  File "/home/vstinner/myprojects/pythonci/pythonci/_ci.py", line 115, in run_python
    return self.run_command(self.python_args + args, **kw)
  File "/home/vstinner/myprojects/pythonci/pythonci/_ci.py", line 109, in run_command
    raise Exception("%s command failed with exit code %s"
Exception: /home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/venv/bin/python -X dev runtests.py -vv --no-pyregr command failed with exit code -6
Change directory: /home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19
venv already exists: /home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/venv
Cython is already installed in: /home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/Cython-0.29.19
DIRNAME /home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/Cython-0.29.19
Run command: /home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/venv/bin/python -X dev runtests.py -vv --no-pyregr in /home/vstinner/myprojects/pythonci/work/cpython-3.10.0a0_Cython-0.29.19/Cython-0.29.19
```

**Comment by vstinner** [comment] 2020-05-26 17:21
I don't know how to only run this test to debug it. Any idea @scoder ?

**Comment by da-woods** [comment] 2020-05-26 17:58
There's probably a better way but I'd run the test with `runtest.py call_py_cy --no-cleanup` (so the so files don't get deleted); change directory to (something like) `TEST_TMP/run/c/call_py_cy`, run python in gdb, then do:

```
import doctest
import call_py_cy
doctest.testmod(call_py_cy)
```

**Comment by scoder** [comment] 2020-05-26 19:19
Looks like something that I recently ran into and fixed in a branch somewhere. Let me see.

**Comment by scoder** [comment] 2020-05-26 19:26
Very probably in #3611. That branch is not currently testing ok, though.

**Comment by scoder** [comment] 2020-05-26 19:51
(#3611 is a big cleanup of the current messy support for type specs and the limited API, which still needs some work to finish up.)

**Comment by scoder** [comment] 2020-06-03 10:17
@vstinner I tried it with the latest master of both and couldn't reproduce the crash, but 0.29.x crashes.

As I can see in gdb, `PyEval_EvalCodeEx()` calls down into `_PyEval_EvalCodeWithName()` with names set to `NULL`, and `too_many_positional()` in `ceval.c` then eventually calls
```
4020        _PyErr_Format(tstate, PyExc_TypeError,
4021                      "%U() takes %U positional argument%s but %zd%U %s given",
4022                      qualname,
…
```
and passes `qualname` unconditionally, which is still `NULL`. Looks like a bug in CPython.

**Closed by scoder** 2020-06-03 10:17 UTC
Labels: defect

**Comment by vstinner** [comment] 2020-06-03 12:21
> ... and passes qualname unconditionally, which is still NULL. Looks like a bug in CPython.

Thanks for investigating the issue! I confirm that it's a CPython regression introduced by: https://bugs.python.org/issue40679 I wrote a fix: https://bugs.python.org/issue40679#msg370658
