### ISSUE TITLE
How to import (reload) .pyx with dynamic name?

### ISSUE THREAD

**Issue by arekbulski** [cython/cython#2113] opened 2018-02-22 15:02 UTC
I have build a compiler that generates some pyx code. Can you tell me how to properly load (reload) a module using pyximport? Note that this code is run several times, and each module must remain usable. The code that doesnt work: 
```py
import pyximport
pyximport.install()
import imp
with open("construct_compile_target.pyx","wt") as f:
    f.write(source)
module = imp.load_source("construct_compile_target", "construct_compile_target.pyx")
```
Test suite uses pytest:
```py
E     File "construct_compile_target.pyx", line 10
E       cdef bytes read_bytes(io, count):
E                ^
E   SyntaxError: invalid syntax
```

**Comment by arekbulski** [comment] 2018-02-22 19:35
I was trying to repreduce the issue and found what seems to be a solution. It doesnt support dynamin name, but thats fine as lon as it supports reloading.

![zrzut ekranu z 2018-02-22 18-34-20](https://user-images.githubusercontent.com/5385838/36560028-eeee90f8-180f-11e8-8890-b318448e625c.png)

**Comment by scoder** [comment] 2018-02-23 08:40
`imp.load_source()` says: "load this file as a Python source file". Cython `.pyx` files are not Python `.py` files, so this fails.
Try either using `__import__()`, or take a look into the loader infrastructure that Python uses for its import mechanism.
Closing this as it's not a bug.

**Closed by scoder** 2018-02-23 08:40 UTC

**Comment by arekbulski** [comment] 2018-02-23 22:11
Thanks for assisstance, `__import__()` indeed supports pyx. Here is my working code, for reference. I am generating a unique random module name, so no need for reloading.
```py

modulename = "construct_compile_target_"+hexlify(os.urandom(8)).decode()
import pyximport
pyximport.install()

with open(modulename+".pyx", "wt") as f:
    f.write(source)
module = __import__(modulename)
os.remove(modulename+".pyx")
```

**Comment by arekbulski** [comment] 2018-02-24 18:55
Is there a function that allows loading pyx by passing it source, instead of filename? Like `pyximport.load_module`.
