### ISSUE TITLE
Coverage: "‘__pyx_tstate’ may be used uninitialized in this function"

### ISSUE THREAD

**Issue by pitrou** [cython/cython#2269] opened 2018-05-15 17:06 UTC
When compiling PyArrow with `-X linetrace=true` and `CYTHON_TRACE=1`, I get the following compilation warnings with gcc 4.9.4:
```
/home/antoine/arrow/python/build/temp.linux-x86_64-3.6/lib.cpp: In function ‘PyObject* PyInit_lib()’:
/home/antoine/arrow/python/build/temp.linux-x86_64-3.6/lib.cpp:130938:82: warning: ‘__pyx_tstate’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       if (__Pyx_GetException(&__pyx_t_21, &__pyx_t_20, &__pyx_t_22) < 0) __PYX_ERR(12, 26, __pyx_L18_except_error)
                                                                                  ^
/home/antoine/arrow/python/build/temp.linux-x86_64-3.6/lib.cpp:130850:20: note: ‘__pyx_tstate’ was declared here
     __Pyx_PyThreadState_declare
                    ^
/home/antoine/arrow/python/build/temp.linux-x86_64-3.6/lib.cpp:130307:93: warning: ‘__pyx_tstate’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     __pyx_t_3 = __Pyx_PyErr_ExceptionMatches(__pyx_builtin_ImportError);
                                                                                             ^
/home/antoine/arrow/python/build/temp.linux-x86_64-3.6/lib.cpp:130224:20: note: ‘__pyx_tstate’ was declared here
     __Pyx_PyThreadState_declare
                    ^
/home/antoine/arrow/python/build/temp.linux-x86_64-3.6/lib.cpp:129038:82: warning: ‘__pyx_tstate’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       if (__Pyx_GetException(&__pyx_t_22, &__pyx_t_21, &__pyx_t_20) < 0) __PYX_ERR(1, 195, __pyx_L4_except_error)
                                                                                  ^
/home/antoine/arrow/python/build/temp.linux-x86_64-3.6/lib.cpp:128901:20: note: ‘__pyx_tstate’ was declared here
     __Pyx_PyThreadState_declare
                    ^
```

**Comment by scoder** [comment] 2018-10-19 20:07
Marking as a duplicate of #2274.

**Closed by scoder** 2018-10-19 20:07 UTC
Labels: R: duplicate
