### ISSUE TITLE
python3.6 Cython nametuple TypeError

### ISSUE THREAD

**Issue by beruhan** [cython/cython#2917] opened 2019-04-10 08:35 UTC
I have a class that inherits from NamedTuple,I have compile it to pyd file on windows use cython,when I import the class  and create a object in another py file,It throws error **TypeError: __new__() takes 1 positional argument but 4 were given**, the class as follows:
```
from typing import NamedTuple


class Info(NamedTuple):
    service: str
    damage: str
    privilege: str


info = Info("http", "no", "no")
```

when I don't compile it to pyd,It can use normally,How to deal with it?

**Comment by beruhan** [comment] 2019-04-10 12:50
does any one has alternative plan? this usage is heavily used in the project.，and I don't know how to

**Comment by scoder** [comment] 2019-04-10 17:04
This is a duplicate of #2552.

**Closed by scoder** 2019-04-10 17:04 UTC

**Comment by TeamSpen210** [comment] 2019-04-10 20:19
What you can do is to simply not use `namedtuple` at all. Run this code in regular Python, then print out the `Info._source` attribute. This is a copy of the equivalent code to define the class - just cythonise that. Get rid of the `builtins` imports though, Cython can do those better.
