### ISSUE TITLE
Public variables at the module level?

### ISSUE THREAD

**Issue by will-ca** [cython/cython#3357] opened 2020-02-13 22:31 UTC
`cdef public type var`, `cpdef public type var`, and `cpdef type var` don't seem to create variables that can be accessed as attributes of their modules from elsewhere in the Python interpreter.

`cdef readonly var` causes an error message on Cythonization, but `cdef public` doesn't.

**Comment by scoder** [comment] 2020-02-14 07:55
Hmm, interesting. `public` does different things in a function class body (property) and elsewhere (C public). I had never thought about that.

The rest is a duplicate of #656, so I'll close this ticket.

**Closed by scoder** 2020-02-14 07:55 UTC
