### ISSUE TITLE
[BUG] iterating a set of shared_ptr[const T] fails to compile

### ISSUE THREAD

**Issue by isuruf** [cython/cython#5478] opened 2023-06-08 13:33 UTC
### Describe the bug

Following fails to compile with Cython 3.x series, but it compiles fine with Cython 0.29.

Error msg:
```
Error compiling Cython file:
------------------------------------------------------------
...
    ctypedef set[shared_basic] set_basic


cdef foo():
    cdef set_basic s
    for p in s:
             ^
------------------------------------------------------------

asd.pyx:15:13: Cannot assign type 'shared_ptr[Basic]' to 'value_type'
```

cc @mgorny 

### Code to reproduce the behaviour:

```cython
from libcpp.set cimport set
from libcpp.memory cimport shared_ptr

cdef extern from "<symengine/basic.h>" namespace "SymEngine":
    cdef cppclass Basic:
        pass
 
    ctypedef shared_ptr[const Basic] shared_basic

    ctypedef set[shared_basic] set_basic


cdef foo():
    cdef set_basic s
    for p in s:
        pass
```

### OS

Linux

### Python version

3.10.6

### Cython version

3.0.0.b3

**Comment by matusvalo** [comment] 2023-06-08 20:56
I did git bisect and following commit is introducing the issue: https://github.com/cython/cython/commit/d329339ba05ac76e0a83f539f173996e80cc89e1

**Comment by matusvalo** [comment] 2023-06-10 18:21
@da-woods I was able to identify the line which is causing this issue. Commit https://github.com/cython/cython/commit/d329339ba05ac76e0a83f539f173996e80cc89e1 introduced following line:

https://github.com/cython/cython/blob/0605b260541394d7b33110d0f21830be507fde76/Cython/Compiler/ExprNodes.py#L3339

Removing/Commenting out this line, the reproducer is compiled successfully (I did not check whether is runnable)

**Comment by da-woods** [comment] 2023-06-10 18:43
I'm a bit suspicious of removing const from all the template types here. But that's without really investigating too hard

**Comment by da-woods** [comment] 2023-06-10 18:48
> I'm a bit suspicious of removing const from all the template types here. But that's without really investigating too hard

Because that'll be removing the `const` from `shared_ptr[const Basic]`. I suspect it needs to be a little more targeted to just the specific problem it claims to solve.

**Comment by da-woods** [comment] 2023-06-12 17:09
Still thinking about this a bit. Here are some options:

* Revert the `remove_const` part of the change (breaking iteration over C++ maps),
* Accept that iterating over a const pointer is now broken,
* Special-case iteration over C++ maps (which'll work, but will require the type to match exactly rather than be map-like)
* Make these variables a `std::optional` and write in/out of them using `std::emplace` (removes the need to be assignable)
* As above but write our own (limited) optional type.

**Comment by isuruf** [comment] 2023-06-12 18:59
Option 6:
- Use the same hack we use for `forward` iteration in C++ maps for `reverse` iteration.

See https://github.com/cython/cython/pull/5483

**Comment by da-woods** [comment] 2023-06-15 17:57
Closed in https://github.com/cython/cython/pull/5483

**Closed by da-woods** 2023-06-15 17:57 UTC
Labels: C++, defect, Code Generation
