### ISSUE TITLE
AttributeError: type object 'pycocotools._mask.RLEs' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by backgomc** [cython/cython#3097] opened 2019-08-26 04:38 UTC
I'm trying to run Mask R-CNN with docker.
but it's not working.
how can i fix it!!

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-28-c2de524bcb09> in <module>()
     18 # Import COCO config
     19 sys.path.append(os.path.join(ROOT_DIR, "samples/coco/"))  # To find local version
---> 20 import coco
     21 
     22 get_ipython().run_line_magic('matplotlib', 'inline')

/data/data/Mask_RCNN/samples/coco/coco.py in <module>()
     40 # If the PR is merged then use the original repo.
     41 # Note: Edit PythonAPI/Makefile and replace "python" with "python3".
---> 42 from pycocotools.coco import COCO
     43 from pycocotools.cocoeval import COCOeval
     44 from pycocotools import mask as maskUtils

/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py in <module>()
     53 import copy
     54 import itertools
---> 55 from . import mask as maskUtils
     56 import os
     57 from collections import defaultdict

/usr/local/lib/python3.6/dist-packages/pycocotools/mask.py in <module>()
      1 __author__ = 'tsungyi'
      2 
----> 3 import pycocotools._mask as _mask
      4 
      5 # Interface for manipulating masks stored in RLE format.

pycocotools/_mask.pyx in init pycocotools._mask()

AttributeError: type object 'pycocotools._mask.RLEs' has no attribute '__reduce_cython__'

**Comment by scoder** [comment] 2020-04-26 07:10
Closing as duplicate of #3545.

**Closed by scoder** 2020-04-26 07:10 UTC
Labels: R: duplicate
