### ISSUE TITLE
[BUG] Compare of signed and unsigned variables

### ISSUE THREAD

**Issue by website-reader** [cython/cython#4596] opened 2022-01-27 18:49 UTC
Variables of mixed type, one is signed and one is unsigned is occurring in a Boolean compare expression. This leads to false results to the compare operation.
System:
openSUSE Leap 15.2 linux 64-bit
Linux localhost.localdomain 5.3.18-lp152.106-default #1 SMP Mon Nov 22 08:38:17 UTC 2021 (52078fe) x86_64 x86_64 x86_64
gcc version 7.5.0
Python 2.7.18
Cython version 3.0.0a10

Source code:

```cython
    cdef mod_int _new_random_prime(self, set known_primes) except 1:
        """
        Choose a new random prime for inclusion in the list of moduli,
        or raise a ``RuntimeError`` if there are no more primes.

        INPUT:

        - ``known_primes`` -- Python set of already known primes in
          the allowed interval; we will not return a prime in
          known_primes.
        """
        cdef Py_ssize_t i
        cdef mod_int p
        while True:
            if len(known_primes) >= self._num_primes:
                raise RuntimeError("there are not enough primes in the interval [%s, %s] to complete this multimodular computation"%(self._l_bound, self._u_bound))
            p = random_prime(self._u_bound, lbound =self._l_bound)
            if p not in known_primes:
                return p
```

-----------------------------
Cythonized output:
```c
  while (1) {

    /* "sage/arith/multi_modular.pyx":199
 *         cdef mod_int p
 *         while True:
 *             if len(known_primes) >= self._num_primes:             # <<<<<<<<<<<<<<
 *                 raise RuntimeError("there are not enough primes in the interval [%s, %s] to complete this multimodular computation"%(self._l_bound, self._u_bound))
 *             p = random_prime(self._u_bound, lbound =self._l_bound)
 */
    if (unlikely(__pyx_v_known_primes == Py_None)) {
      PyErr_SetString(PyExc_TypeError, "object of type 'NoneType' has no len()");
      __PYX_ERR(0, 199, __pyx_L1_error)
    }
    __pyx_t_1 = PySet_GET_SIZE(__pyx_v_known_primes); if (unlikely(__pyx_t_1 == ((Py_ssize_t)-1))) __PYX_ERR(0, 199, __pyx_L1_error)
    __pyx_t_2 = ((__pyx_t_1 >= __pyx_v_self->_num_primes) != 0);
    if (unlikely(__pyx_t_2)) {

      /* "sage/arith/multi_modular.pyx":200
 *         while True:
 *             if len(known_primes) >= self._num_primes:
 *                 raise RuntimeError("there are not enough primes in the interval [%s, %s] to complete this multimodular computation"%(self._l_bound, self._u_bound))             # <<<<<<<<<<<<<<
 *             p = random_prime(self._u_bound, lbound =self._l_bound)
 *             if p not in known_primes:
 */
```
------------------------------
PROBLEM:
```c
    __pyx_t_2 = ((__pyx_t_1 >= __pyx_v_self->_num_primes) != 0);
```

is comparing a signed versus an unsigned variable.

While l_bounds and u_bounds are unsigned integers, used later on in creating self->_num_primes which means that _num_primes is possibly set as an unsigned value, later on _num_primes is set by the call to the primes_pi() function which returns an Integer(n) value which can be negative or positive so apparently Integer() is signed.

What does the function call PySet_GET_SIZE() return? signed or unsigned?
In any case a compare between mixed types is occurring.

There are 161 warnings of this type occurring in the sage code.

**Comment by scoder** [comment] 2022-01-27 19:17
Hmm. Difficult to say if there is something we can do here. `len()` returns the usual Python C-API size type, which is signed (`ssize_t` typedefed as `Py_ssize_t`). It's signed because indexing can be negative in Python, so unsigned sizes would get in the way quickly.

If you compare a `len()` result to an unsigned integer then yes, you get a comparison between signed and unsigned. Since the normal C integer types are signed, and the users has to do something in order to get an unsigned type, I think the right way is to let the user resolve this mismatch. Meaning, you have to apply an explicit cast that goes either way. Cython cannot decide whether a signed or unsigned comparison is the safe choice here.

**Comment by scoder** [comment] 2022-01-27 19:29
I'll close this as not a bug. Users should apply a cast in this case.

**Closed by scoder** 2022-01-27 19:29 UTC
Labels: support question
