### ISSUE TITLE
[BUG] pip install cupy fail:Error compiling Cython file:cupy/_core/dlpack.pyx:152:25: Cannot assign type 'void (DLManagedTensor *) except * nogil' to 'void (*)(DLManagedTensor *) noexcept'

### ISSUE THREAD

**Issue by xiezhipeng-git** [cython/cython#5708] opened 2023-09-16 16:57 UTC
### Describe the bug

I try install cupy on wsl2.It is fail. I have not try install on windows.

... very more warning
warning: cupy_backends/cuda/api/_runtime_enum.pxd:216:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: cupy/_core/dlpack.pyx:98:6: Only extern functions can throw C++ exceptions.
      warning: cupy/_core/dlpack.pyx:217:6: Only extern functions can throw C++ exceptions.
      warning: cupy/_core/dlpack.pyx:267:5: Only extern functions can throw C++ exceptions.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          dtype.lanes = <uint16_t>1
          dtype.bits = <uint8_t>(array.dtype.itemsize * 8)
      
          dlm_tensor.manager_ctx = <void*>array
          cpython.Py_INCREF(array)
          dlm_tensor.deleter = deleter
                               ^
      ------------------------------------------------------------
      
      cupy/_core/dlpack.pyx:152:25: Cannot assign type 'void (DLManagedTensor *) except * nogil' to 'void (*)(DLManagedTensor *) noexcept'
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          dlm_tensor.manager_ctx = <void*>array
          cpython.Py_INCREF(array)
          dlm_tensor.deleter = deleter
      
          return cpython.PyCapsule_New(dlm_tensor, 'dltensor', pycapsule_deleter)
                                                               ^
      ------------------------------------------------------------
      
      cupy/_core/dlpack.pyx:154:57: Cannot assign type 'void (object) except *' to 'PyCapsule_Destructor'
      Traceback (most recent call last):
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1325, in cythonize_one_helper
          return cythonize_one(*m)
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: cupy/_core/dlpack.pyx
      [27/63] Cythonizing cupy/_core/new_fusion.pyx
      [28/63] Cythonizing cupy/_core/raw.pyx
      [29/63] Cythonizing cupy/_util.pyx
      warning: cupy/_util.pyx:12:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      [30/63] Cythonizing cupy/cuda/common.pyx
      ... very more about  4310 issue
      warning: cupy_backends/cuda/api/_runtime_enum.pxd:216:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      multiprocessing.pool.RemoteTraceback:
      """
      Traceback (most recent call last):
        File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1325, in cythonize_one_helper
          return cythonize_one(*m)
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: cupy/_core/_kernel.pyx
      """
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-glhos324/cupy_76972e58b1574136a1753c505a5bf005/setup.py", line 121, in <module>
          setup(
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
          super().run_command(command)
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-install-glhos324/cupy_76972e58b1574136a1753c505a5bf005/install/cupy_builder/_command.py", line 161, in build_extensions
          self._cythonize(num_jobs)
        File "/tmp/pip-install-glhos324/cupy_76972e58b1574136a1753c505a5bf005/install/cupy_builder/_command.py", line 140, in _cythonize
          Cython.Build.cythonize(
        File "/home/xzpwsl2/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1125, in cythonize
          result.get(99999)  # seconds
        File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
          raise self._value
      Cython.Compiler.Errors.CompileError: cupy/_core/_kernel.pyx

### Code to reproduce the behaviour:

```cython
# example code
```

### Expected behaviour

can install success on wsl2

### OS

Windows

### Python version

3.10.6 - 64bit

### Cython version

3.0.0

**Comment by matusvalo** [comment] 2023-09-16 17:39
The issue is that the cupy project does not migrate codebase to cython 3.0. At least it seems that some definitions are missing 'noexcept' keyword. See https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#exception-values-and-noexcept

**Comment by scoder** [comment] 2023-09-16 18:05
I would suggest you use Cython 0.29.x to build cupy for now, and help them migrate to Cython 3 if you can.

**Comment by matusvalo** [comment] 2023-09-17 05:56
I am closing this issue since it is ralated to the cupy project.

**Closed by matusvalo** 2023-09-17 05:56 UTC

**Comment by twmht** [comment] 2023-10-03 03:13
the suggestion from @scoder works for me

**Comment by leduy-it** [comment] 2025-01-06 02:30
@scoder thanks you,  ur suggestion works for me
