### ISSUE TITLE
[BUG] Variables annotated with `cython.pointer` are threated as `PyObject`s

### ISSUE THREAD

**Issue by 0dminnimda** [cython/cython#4299] opened 2021-07-20 00:30 UTC
**Describe the bug**
Uninitialized variables declared with annotation type `cython.pointer(<something>)` are threated as `PyObject`s
If you interested in testing `cython.declare` in same way look here (#4298), in short everything is fine except case with `float`

**To Reproduce**
```cython
cimport cython

def main():
    cdef double *a
    b: cython.pointer(cython.double)
    c: cython.p_double
    d: cython.pointer(float)

    cython.typeof(a)  # (void)(__pyx_kp_s_double);
    cython.typeof(b)  # (void)(__pyx_kp_s_Python_object);
    cython.typeof(c)  # (void)(__pyx_kp_s_double);
    cython.typeof(d)  # (void)(__pyx_kp_s_Python_object);
```

But if we will define `b` and `d` then everting will become normal:
```cython
cimport cython

def main():
    cdef double value = 5.

    b: cython.pointer(cython.double) = &value
    d: cython.pointer(float) = &value

    cython.typeof(b)  # (void)(__pyx_kp_s_double);
    cython.typeof(d)  # (void)(__pyx_kp_s_double);
```

`sizeof` helps us make sure that that's not just about `typeof`:

```c
sizeof(a)
  (void)((sizeof(__pyx_v_a)));

sizeof(b)
  if (unlikely(!__pyx_v_b)) { __Pyx_RaiseUnboundLocalError("b"); __PYX_ERR(0, 17, __pyx_L1_error) }
  (void)((sizeof(__pyx_v_b)));

sizeof(c)
  (void)((sizeof(__pyx_v_c)));

sizeof(d)
  if (unlikely(!__pyx_v_d)) { __Pyx_RaiseUnboundLocalError("d"); __PYX_ERR(0, 19, __pyx_L1_error) }
  (void)((sizeof(__pyx_v_d)));
```

![image](https://user-images.githubusercontent.com/52697657/126241455-d68afd43-f79c-4867-a0fd-fc2fe800e9cc.png)

**Expected behavior**
(am i have to say anything here? it's obvious)

Uninitialized variables declared with annotation type `cython.pointer(<something>)` should be threated as any other, like pointers and not `PyObject`s

**Environment (please complete the following information):**
 - OS: Linux, Windows
 - Python version 3.8.3, 3.9.0
 - Cython version 3.0a7, 3.0a8

**Comment by 0dminnimda** [comment] 2021-07-20 00:33
(oops)[https://github.com/cython/cython/issues/4299#event-5041363858], forgot about this 😅

**Comment by scoder** [comment] 2021-07-20 20:32
Duplicate of #4293

**Closed by scoder** 2021-07-20 20:32 UTC
Labels: R: duplicate
