### ISSUE TITLE
Cython doesn't work on Python 3.8 beta2

### ISSUE THREAD

**Issue by vstinner** [cython/cython#3034] opened 2019-07-06 02:13 UTC
Cython is been made compatible with Python 3.8 beta2 in commit 0d88839168013fd69350d31eaee5514cd2f727b9, but this commit is not part of Cython tag 0.29.11. Would it be possible to get a new release, please?

cc @scoder

**Comment by stonebig** [comment] 2019-07-06 14:52
also, I have apparent issues running
`````
%load_ext Cython
````
in latest jupyterlab/cython cgohlke/python-3.8.0b2

**Comment by scoder** [comment] 2019-07-07 08:28
Duplicate of #3031.

**Comment by Harmon758** [comment] 2019-07-25 19:00
[Cython 0.29.12](https://github.com/cython/cython/releases/tag/0.29.12) has been released with that commit/fix now.

**Comment by thedrow** [comment] 2019-08-07 11:48
Please close this issue for good measure.

**Closed** 2019-08-12 11:16 UTC
Labels: R: duplicate
