### ISSUE TITLE
Issue with pyspark udf

### ISSUE THREAD

**Issue by chnynf** [cython/cython#2619] opened 2018-09-21 16:45 UTC
I compiled my pyx with cython successfully and imported it as a library. All the functions work, except for the udfs. I got error messages like this:
Can't pickle <cyfunction my_class_name.my_method_name.<locals>.my_udf_name at 0x7f74580b4c80>

I'm not sure if it's because cython can't work with pyspark udf, or it's just my code. But my code works fine when not compiled.

**Comment by scoder** [comment] 2018-09-21 17:01
You need to use a global function, not a local one. Nested functions work in Python code because Python can pickle them including their byte code. For compiled functions, there is no byte code that could be pickled, so the state can be pickled and transferred, but the function itself must be accessible on the other side. Local functions are not accessible from anywhere outside of the function that defines it.

**Closed by scoder** 2018-09-21 17:01 UTC

**Comment by scoder** [comment] 2018-09-23 15:03
Duplicate of #2584.

**Comment by chnynf** [comment] 2018-09-24 19:37
Thanks! fixed.

**Comment by jzheng13** [comment] 2019-05-13 08:15
> 
> 
> Thanks! fixed.

Hi, can you share how you managed to fix the issue? Thanks!

**Comment by chnynf** [comment] 2019-05-13 14:44
It's been a few months, but I think instead of using the function decorator, the workaround at that time was:
1. from pyspark.sql.functions import udf
2. define a global function called xxx()
3. use "udf(xxx, xxxx return type())()"  in the script where you put the udf


> > Thanks! fixed.
> 
> Hi, can you share how you managed to fix the issue? Thanks!

**Comment by nagesh-chowdaiah** [comment] 2020-10-16 20:21
def get_dummies(self, df_sales: pd.DataFrame) -> DataFrame:
    schema_str = StructType([
        StructField(store_col_copy, DoubleType(), True),
        StructField(yrmo_col_copy, DoubleType(), True),
        StructField(sku_col_copy, DoubleType(), True),
        StructField('overfit_utilities', DoubleType(), True)])
    
    @pandas_udf(schema_str, PandasUDFType.GROUPED_MAP)
    def cnl_overfit(df_sales_sample):
        store = df_sales_sample[store_col_copy].iloc[0]
        yrmo = df_sales_sample[yrmo_col_copy].iloc[0]

        overfit_util = df_sales_sample.sort_values(sku_col_copy)
        # skus_sample = sorted(df_sales_sample[sku_col_copy].values)

        return overfit_util.drop_duplicates()

    df_sales_spark = self._spark.createDataFrame(df_sales)
    overfit_spark = df_sales_spark.groupby([store_col_copy, yrmo_col_copy]).apply(cnl_overfit)
    return overfit_spark


Even i am facing the same issue in using pandas_udf, can you guys please help me in overcomming this issue
