### ISSUE TITLE
Cythonized class lacks type annotations

### ISSUE THREAD

**Issue by athre0z** [cython/cython#2913] opened 2019-04-04 17:26 UTC
```python
from typing import get_type_hints

class Kitteh:
    attr: float = 123.

print(get_type_hints(Kitteh))
```

This pure Python code results in different outputs depending on whether it has been cythonized or not.

```shell
# Cythonized
$ python -mtestx
{}

# Pure
$ rm testx/*.c testx/*.so
$ python -mtestx
{'attr': <class 'float'>}
```

This is unfortunate for use cases where you e.g. want to perform data parsing into classes based on type hints. Is this intended behavior? I observed this with both `0.29.6` and the latest master.

I attached a small pipenv project that reproduces the issue.

[cythonbug.tar.gz](https://github.com/cython/cython/files/3044714/cythonbug.tar.gz)

**Comment by scoder** [comment] 2019-04-04 21:37
Duplicate of #2552.

**Closed by scoder** 2019-04-04 21:37 UTC
