### ISSUE TITLE
Compiler crashes when parameter annotation is string containing space

### ISSUE THREAD

**Issue by Bananach** [cython/cython#1973] opened 2017-11-02 08:31 UTC
I am using Cython 0.27.1 with Python 3.5.

**This works:**  
```
def f(M:'foobar'):
    pass
```
**This doesn't work:**
```
def f(M:'foo bar'):
    pass
```

```
> Compiling simulation/cy_sim.pyx because it changed.
> [1/1] Cythonizing simulation/cy_sim.pyx
> 
> Error compiling Cython file:
> ------------------------------------------------------------
> ...
> def f(M:'foo bar'):
>        ^
> ------------------------------------------------------------
> 
> simulation/cy_sim.pyx:1:8: Compiler crash in AnalyseDeclarationsTransform
> 
> File 'ModuleNode.py', line 122, in analyse_declarations: ModuleNode(cy_sim.pyx:1:0,
>     full_module_name = 'simulation.cy_sim')
> File 'Nodes.py', line 417, in analyse_declarations: StatListNode(cy_sim.pyx:1:0)
> File 'Nodes.py', line 2817, in analyse_declarations: DefNode(cy_sim.pyx:1:0,
>     modifiers = [...]/0,
>     name = 'f',
>     num_required_args = 1,
>     py_wrapper_required = True,
>     reqd_kw_flags_cname = '0')
> File 'Nodes.py', line 2871, in analyse_argument_types: DefNode(cy_sim.pyx:1:0,
>     modifiers = [...]/0,
>     name = 'f',
>     num_required_args = 1,
>     py_wrapper_required = True,
>     reqd_kw_flags_cname = '0')
> File 'Nodes.py', line 1678, in align_argument_type: DefNode(cy_sim.pyx:1:0,
>     modifiers = [...]/0,
>     name = 'f',
>     num_required_args = 1,
>     py_wrapper_required = True,
>     reqd_kw_flags_cname = '0')
> File 'Nodes.py', line 893, in inject_type_from_annotations: CArgDeclNode(cy_sim.pyx:1:6,
>     is_generic = 1,
>     name = 'M')
> File 'ExprNodes.py', line 1589, in analyse_as_type: StringNode(cy_sim.pyx:1:8,
>     constant_result = 'foo bar',
>     is_literal = 1,
>     is_string_literal = True,
>     result_is_used = True,
>     unicode_value = 'foo bar',
>     use_managed_ref = True,
>     value = b'foo bar')
> 
> Compiler crash traceback from this point on:
>   File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/ExprNodes.py", line 1589, in analyse_as_type
>     return _analyse_name_as_type(self.unicode_value or self.value.decode('ISO8859-1'), self.pos, env)
>   File "/usr/local/lib/python3.5/dist-packages/Cython/Compiler/ExprNodes.py", line 1375, in _analyse_name_as_type
>     return sizeof_node.arg_type.analyse_types(env)
> AttributeError: 'NoneType' object has no attribute 'analyse_types'
> Traceback (most recent call last):
>   File "setup.py", line 5, in <module>
>     ext_modules = cythonize(["simulation/cy_sim.pyx",'simulation/normrnd.pyx'])
>   File "/usr/local/lib/python3.5/dist-packages/Cython/Build/Dependencies.py", line 1039, in cythonize
>     cythonize_one(*args)
>   File "/usr/local/lib/python3.5/dist-packages/Cython/Build/Dependencies.py", line 1161, in cythonize_one
>     raise CompileError(None, pyx_file)
> Cython.Compiler.Errors.CompileError: simulation/cy_sim.pyx
```

**Comment by scoder** [comment] 2017-11-10 08:24
Duplicate of #1908, fixed in 0.27.2.

**Closed by scoder** 2017-11-10 08:24 UTC
Labels: R: duplicate
