### ISSUE TITLE
[BUG] Cython doesn't compile `pair[shared_ptr[const T], R]`

### ISSUE THREAD

**Issue by raulchen** [cython/cython#3967] opened 2021-01-04 06:54 UTC
**Describe the bug**

When I used `pair[shared_ptr[const T], R]`, I got the following error
![image](https://user-images.githubusercontent.com/2883335/103508684-6e75a300-4e9c-11eb-8bab-d2b6d8ff0d7f.png)

I worked around this by using `ctypdef shared_ptr[const T] TSharedPtr` + `pair[TSharedPtr, R]`.

This looks a bug of the Cython compiler.

**Environment (please complete the following information):**
 - OS: [e.g. Linux, Windows, macOS] macOS
 - Python version [e.g. 3.8.4] 3.6.5
 - Cython version [e.g. 0.29.18] 0.29.21

**Additional context**

**Comment by da-woods** [comment] 2021-01-04 07:12
Duplicate of https://github.com/cython/cython/issues/1355

Should be fixed in the next release I think

**Closed by da-woods** 2021-01-04 07:12 UTC

**Comment by raulchen** [comment] 2021-01-04 07:14
thanks!
