### ISSUE TITLE
Replace deprecated `distutils` package

### ISSUE THREAD

**Issue by EwoutH** [cython/cython#5133] opened 2022-11-16 10:09 UTC
The `distutils` package was deprecated in Python 3.10 and is removed in Python 3.12. It's currently used in [runtests.py](https://github.com/cython/cython/blob/1b028d34d6a3ec82f4687df1e0db598721c7a695/runtests.py#L74) among [other places](https://github.com/cython/cython/search?q=distutils).

> DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use [setuptools](https://github.com/pypa/setuptools) or check [PEP 632](https://peps.python.org/pep-0632/) for potential alternatives

**Comment by matusvalo** [comment] 2022-11-17 15:05
This migration can be rather big. Do we want to put it in 3.0? In my opinion we should release 3.0 ASAP (We are not so far - I hope) and plan this migration to 3.1 release which should also support python 3 only. Hence:

* 0.29.X will support python 2.7 - 3.11
* 3.0 will support python 2.7 - 3.11
* 3.1 will support python 3.5 - 3.12 (or later)

**Comment by matusvalo** [comment] 2022-11-18 21:12
BTW. this seems to be duplicate of #4405 which is already in Cython 3.1

**Closed** 2022-11-19 09:24 UTC
Labels: Build System, R: duplicate, cleanup
