### ISSUE TITLE
[BUG] redefinition error when partial wraps different functions with the same signature

### ISSUE THREAD

**Issue by scottbelden** [cython/cython#4019] opened 2021-02-27 00:00 UTC
Please feel free to tell me that this is an abuse of cython or that there's no point in having `foo` and `bar` be `cdef`s because once they get wrapped in `partial` they are just normal `def`s.

The redefinition error just caught me by surprise since I thought it was because I had two functions with the same name but in reality the function names and argument names were very different and so it was hard to eventually figure out first) what was going on and then second) which two functions had the same signature.

**Describe the bug**
redefinition error when partial wraps different functions with the same signature

**To Reproduce**
Code to reproduce the behaviour:
```cython
from functools import partial

cdef foo(a):
    print(a + 1)

cdef bar(b):
    print(b + " string")

partial(foo)
partial(bar)
```

**Expected behavior**
No error since `foo` and `bar` have different names

**Environment (please complete the following information):**
 - OS: macOS
 - Python version: 3.9
 - Cython version: 0.29.22

**Additional context**
If I specify the argument types for the functions, the error goes away. For example, all three of these work:

```cython
from functools import partial

cdef foo(int a):
    print(a + 1)

cdef bar(b):
    print(b + " string")

partial(foo)
partial(bar)
```

```cython
from functools import partial

cdef foo(a):
    print(a + 1)

cdef bar(str b):
    print(b + " string")

partial(foo)
partial(bar)
```

```cython
from functools import partial

cdef foo(int a):
    print(a + 1)

cdef bar(str b):
    print(b + " string")

partial(foo)
partial(bar)
```

**Comment by scoder** [comment] 2021-02-27 06:33
Thanks for the report. Might be a problem with the internal C name generation for the Python function wrappers. Your examples seem ok to me.

Could you please also try Cython 3.0? I think I remember similar issues already being fixed at some point.

**Comment by da-woods** [comment] 2021-02-27 08:11
I think this is a duplicate of https://github.com/cython/cython/issues/3716. I don't think the fix is merged yet (so trying Cython 3 probably won't help)

**Closed by da-woods** 2021-02-27 08:11 UTC

**Comment by da-woods** [comment] 2021-02-27 08:14
FWIW, there probably isn't much point in using cdef functions if you're just going to wrap them in partial (they do become pretty similar to a def function then). But none the less, it should work without bugs
