### ISSUE TITLE
[BUG] keyword arguments for @staticmethod fail

### ISSUE THREAD

**Issue by RubendeBruin** [cython/cython#3983] opened 2021-01-24 15:56 UTC
**Describe the bug**
Calling a static method of a class using keyword arguments fails.
Calling the same method without explicitly specifying the keyword arguments works.

```
demo_package.demo.say_something('Echo')                     # works
demo_package.demo.say_something(what = 'Echo')         # fails

> python runme.py
Echo
Traceback (most recent call last):
  File "runme.py", line 7, in <module>
    d.hello()
  File "demo_package.pyx", line 8, in demo_package.demo.hello
    demo.say_something(what = "Hello")
TypeError: say_something() takes no keyword arguments
```

**To Reproduce**

Code to reproduce see the code below, also attached:

1. the package
2. run-file
3. setup.py

The package (demo_package.pyx):
```cython
class demo:

    @staticmethod
    def say_something(what):
        print(what)
```

the run-file
```python
import demo_package

demo_package.demo.say_something('Echo')                     # works
demo_package.demo.say_something(what = 'Echo')         # fails
```

the setup file (used the most basic example)
```python
from setuptools import setup
from Cython.Build import cythonize

setup(
    ext_modules = cythonize("demo_package.pyx")
)
```

**Expected behavior**
when renaming demo_package.pyx to demo_package.py and running python runme.py:

```
> python runme.py
Hello
```

**Environment (please complete the following information):**
 - OS: Windows 10 with visual studio
 - Python version 3.7.9
 - Cython version 0.29.21

**Comment by da-woods** [comment] 2021-01-24 16:02
I'm pretty sure this is a duplicate of https://github.com/cython/cython/issues/3090 (and doesn't have a lot to do with `@staticmethod`)

This should work as is with Cython 3. With Cython 0.29.x you'll need to enable the `always_allow_keywords` compile option. If that does work then please let me know and I'll re-open it.

**Closed by da-woods** 2021-01-24 16:02 UTC

**Comment by RubendeBruin** [comment] 2021-01-24 16:13
Hi @da-woods , thank for the extremely quick feedback! Confirmed that adding the compiler directive solves the issue.
