### ISSUE TITLE
Is it possible to put everything into one independent executable?

### ISSUE THREAD

**Issue by hippylover** [cython/cython#2147] opened 2018-03-13 23:36 UTC
Hello iv'e just finished a pyside2 project and now i want to distribute it to windows users and other linux users in an easy to run package. I was thinking cython would allow me to compile everything into one executable which i could then give to the user for easy install(except perhaps pyside2 which is too big i assume and i should instead bundle so the user could just update the smaller binary on next update).

Is this something that is possible with cython? Could you please give me some directions on how i can achieve this as C and compiling is not my strong suit.

So far iv'e gotten the app to run with -embed but i see it linking to /usr/share/usr/lib/libpython3.6m.so.1.0 and i suppose i have to get it to link to libpython3.6m.so.1.0 in the same directory? The other issue is to get it to link to the same folder for libraries or include all the other libraries i need into the binary. How can i accomplish this.

Thank you for your thoughts.

**Comment by gabrieldemarmiesse** [comment] 2018-03-13 23:55
At the moment, due to how the python language works, it's possible to embed the python interpreter into the final executable, but not external libraries. You might want to look for a tool designed for this like pyinstaller or py2exe.

**Comment by hippylover** [comment] 2018-03-14 00:00
Ah. Ok. Iv'e actually tried pyinstaller and it creates some kind of binary blob but i think it's not as well "hidden" as with cython?

Could you tell me how to combine cython with pyinstaller so that pyinstaller finds all the required libraries and then i will have cython compile the main binary and have it use the libraries that pyinstaller have provided for me?

**Comment by gabrieldemarmiesse** [comment] 2018-03-14 00:18
Sorry, i'm not too familier with pyinstaller. I'm just familiar with using cython. I suppose you would like to create a package with a setup.py and build the cython extensions inside. After that I don't really know, I've never tried it. I just got this info from the cython wiki.

**Comment by mobiusklein** [comment] 2018-03-14 19:33
Is your goal purely to obfuscate your code, or to make a distributable bundle for your program that doesn't require your user to install Python?

**Comment by hippylover** [comment] 2018-03-17 02:10
Well, preferable both.

**Comment by mobiusklein** [comment] 2018-03-17 03:30
I've put a short tutorial in https://github.com/mobiusklein/cython_pyinstaller_example.

Do note that using Cython and PyInstaller for obfuscation isn't very strong, and will only slow down a determined individual.

**Comment by scoder** [comment] 2018-03-17 09:25
Closing as duplicate of #2011.

**Closed by scoder** 2018-03-17 09:25 UTC
