### ISSUE TITLE
Cython crashes when trying to build extension from __init__.py

### ISSUE THREAD

**Issue by Keithcat1** [cython/cython#2968] opened 2019-05-24 00:49 UTC
I've noticed this on some occasions.
When Cython tries to build an extension module with distutils, it crashes and spits out an error like this.
Here is me trying to compile a test `__init__` file from the command line.
```
C:\Users\You>cythonize -i -3 __init__.py
running build_ext
building 'You.__init__' extension
creating C:\Users\tmpo_kxxv5_\Release
creating C:\Users\tmpo_kxxv5_\Release\Users
creating C:\Users\tmpo_kxxv5_\Release\Users\You
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /
nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\python37\include -Ic:\python37\include "-IC
:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Fil
es (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x8
6)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows
Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\includ
e\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17
763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt"
/TcC:\Users\You\__init__.c /FoC:\Users\tmpo_kxxv5_\Release\Users\You\__init__.ob
j
__init__.c
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /n
ologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c
:\python37\libs /LIBPATH:c:\python37\PCbuild\amd64 "/LIBPATH:C:\Program Files (x
86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\
Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x8
6)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\W
indows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows
Kits\10\lib\10.0.17763.0\um\x64" /EXPORT:PyInit___init__ C:\Users\tmpo_kxxv5_\Re
lease\Users\You\__init__.obj /OUT:C:\Users\You\__init__.cp37-win_amd64.pyd /IMPL
IB:C:\Users\tmpo_kxxv5_\Release\Users\You\__init__.cp37-win_amd64.lib
LINK : error LNK2001: unresolved external symbol PyInit___init__
C:\Users\tmpo_kxxv5_\Release\Users\You\__init__.cp37-win_amd64.lib : fatal error
 LNK1120: 1 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\
x86_amd64\\link.exe' failed with exit status 1120
```

Not only that, but it creates pyd fieles when then crash the program if something tries to import them because there empty.
I believe the error is caused by `PyInit___init__`, which probably is aukward enough to cause the compiler to throw an error.
The contents of the __init__ file is:
'''testing file'''
pass

**Comment by scoder** [comment] 2019-05-31 11:28
This was resolved in b43bf13574669dbb10e1ac4c992f9fc66132b6f4.

**Closed by scoder** 2019-05-31 11:28 UTC

**Comment by scoder** [comment] 2019-05-31 11:33
(I don't think there was a ticket for this yet, so I'm using this one as a reference in the changelog.)

**Comment by Keithcat1** [comment] 2019-05-31 15:24
Thanks!
I guess I need to download Cython from Github and install that if I want to compipe __init__

**Comment by nagesh-chowdaiah** [comment] 2020-06-30 14:57
@Keithcat1 where did you download Cython from?

**Comment by Keithcat1** [comment] 2020-07-01 18:13
Must've been from pip.
I got my current cython version from the command:
"pip install cython==3.0a5"
Anyway, it works now, so closing.

**Comment by justinvirtualitics** [comment] 2020-08-01 05:11
I still see essentially the same issue posted above on the latest version of cython (3.0a6) when attempting to create a bdist_wheel. Here is an example of how my setup script refers to all python scripts within each package directory and subdirectory. These directories each contain empty __init__.py files, which seem to be the cause of this. 

ext_modules=cythonize(
        [
            Extension("mypkg.*", ["mypkg/*.py"]),
            Extension("mypkg.subpkg*", ["mypkg/subpkg/*.py"]),
        ],


Worth noting that this same setup script builds without issue on Mac and Linux. This appears to be a Windows-only issue. Strangely,  I'm able to repeatedly run the setup script in an attempt to build the wheel and eventually after a dozen or so failures with the LNK1120 error, the .whl is finally built.

**Comment by da-woods** [comment] 2020-08-01 07:13
For reference: [The relevant Python bug report](https://bugs.python.org/issue35893) - this is really an issue with `distutils` rather than Cython.

**Comment by scoder** [comment] 2020-08-01 08:30
@justinvirtualitics this shouldn't happen any more with the 3.0 alpha releases. Are you sure it also appears in a clean checkout?

Apart from that, is there a reason why you would want to compile empty `__init__.py` files, or is it more for the convenience of using a simple "compile all" path expression?

**Comment by richtier** [comment] 2021-05-13 10:54
@scoder as far as I can tell, imports will fail if __init__.c is not present

**Comment by zylo117** [comment] 2021-11-19 01:39
even after updating to the latest cython, the old *.c files must be deleted and regenerated

**Comment by scoder** [comment] 2021-11-19 11:54
> even after updating to the latest cython, the old *.c files must be deleted and regenerated

That is correct. Cython does not attempt to identify the Cython version that generated a .c file when it determines whether the generated file is up-to-date. That seems a reasonable choice that avoids guesses about the users' intent. If you want a clean state, clean up your workspace. If you want Cython to regenerate everything, pass `-f`.
