### ISSUE TITLE
[BUG] Compiing with cython compiles some completely random script and not the one i told it to.

### ISSUE THREAD

**Issue by Retkid** [cython/cython#4052] opened 2021-03-18 20:11 UTC
**Describe the bug**
compiling using cython creates a random script on my computer rather than whatever im trying to compile

https://user-images.githubusercontent.com/54078872/111696904-3fb86900-880b-11eb-8076-e05dc0977b26.mp4

^ example of bug

**Expected behavior**
Compile to a c file and not be weird

**Environment (please complete the following information):**
 - OS: Linux
 - Python version [e.g. 3.9.2]
 - Cython version 3.0a6

**Additional context**
Either im the worlds best cold golfer or this isn't intended behavior.

Commands I used
`Made a python file with print('Hello World!')`
'cython temp.py'
here is the C file.
 https://paste.in/ocg1sr

**Comment by da-woods** [comment] 2021-03-18 20:16
I think a more useful error report would contain (as text rather than a video) the contents of the .pyx that you're trying to compile, the command you use to compile it, and the contents of the .c file that it produces. If Cython's working correctly then the .c file should be quite long, so don't reproduce the whole thing - the first 20 lines should be enough to show what's happening.

**Comment by Retkid** [comment] 2021-03-18 20:57
> I think a more useful error report would contain (as text rather than a video) the contents of the .pyx that you're trying to compile, the command you use to compile it, and the contents of the .c file that it produces. If Cython's working correctly then the .c file should be quite long, so don't reproduce the whole thing - the first 20 lines should be enough to show what's happening.

If you'd seen the video, it has literally everything in it.

the file contents 

`print('Hello World!')`
Compiled with:
cython temp.py
.
https://paste.in/ocg1sr
^ for the c file.

**Comment by da-woods** [comment] 2021-03-18 21:02
That .c file looks pretty much like I'd expect. You are supposed to compile it with a .c compiler rather than execute it as a script (?) in the shell

**Comment by mattip** [comment] 2021-03-18 21:15
`sudo ./temp.c` is the problem. 
1) not usually a good idea to `sudo` execute stuff, it can do bad things to your machine (sudo is the "admin" way to run commands). You can execute files from the local directory with `./file-name` without `sudo`.
2) cython is used to create c-extension modules, so you still have to run the output through a python interpreter: `python -c "import temp"`
2) you are missing a compile step. You might have better luck running `cythonize -b -i temp.py` which will `b`uild a python c-extension module `i`nplace in the local directory. On my machine the output is `temp.cpython-38-x86_64-linux-gnu.so`. Moving the `temp.py` file (so that you can be sure it works) and running `python -c "import temp"` now imports that c-exension module and prints "hello world" via the python C-API.

**Comment by Retkid** [comment] 2021-03-18 21:29
> `sudo ./temp.c` is the problem.
> 
>     1. not usually a good idea to `sudo` execute stuff, it can do bad things to your machine (sudo is the "admin" way to run commands). You can execute files from the local directory with `./file-name` without `sudo`.
> 
>     2. cython is used to create c-extension modules, so you still have to run the output through a python interpreter: `python -c "import temp"`
> 
>     3. you are missing a compile step. You might have better luck running `cythonize -b -i temp.py` which will `b`uild a python c-extension module `i`nplace in the local directory. On my machine the output is `temp.cpython-38-x86_64-linux-gnu.so`. Moving the `temp.py` file (so that you can be sure it works) and running `python -c "import temp"` now imports that c-exension module and prints "hello world" via the python C-API.

OOk so, yea i guess i misunderstood cython. I did as you said, cythonize -b -i, and it spit out a binary, but renaming it to temp.py and doing python -c 'import temp' returns an error: ` File "<string>", line 1, in <module>
ValueError: source code string cannot contain null byt

unless im confused.`

**Comment by da-woods** [comment] 2021-03-18 22:03
> but renaming it to temp.py

Don't rename the binary - it will import fine with a .so file and renaming it will confuse Python. @mattip was suggesting that you move the original temp.py file out of way (so that you know that it isn't getting imported instead of the binary)

I'm going to close this issue since I think we've confirmed that it wasn't a bug. If you have further problems the Cython-users mailing list is a good place to ask.

**Closed by da-woods** 2021-03-18 22:03 UTC
