### ISSUE TITLE
Different calculation results 

### ISSUE THREAD

**Issue by charliboy** [cython/cython#2299] opened 2018-05-28 05:45 UTC
re= 60275.87757428171
pr=9.738635711237386
nu = 0.0162 * (re ** 0.834) *(pr ** (1/3))
the nu in python 3.5.3 is 335.47031943927516
but in Cython 0.28.3 the value is 157.09223864709324

**Comment by gabrieldemarmiesse** [comment] 2018-05-28 07:50
I think this is a duplicate of #2133, can you check it @charliboy ? Thanks!

**Comment by charliboy** [comment] 2018-05-28 09:12
thanks @gabrieldemarmiesse ,I checked each each item of the expression,the problem is in python,1/3 is equal to 0.3333333..... ,in cython,1/3 is equal to 0.

**Comment by gabrieldemarmiesse** [comment] 2018-05-28 09:38
I found the issue, your file is compiled with the python 2 semantics instead of python 3. Please put this line at the top of your file:

```
#cython: language_level=3
```

See https://cython.readthedocs.io/en/latest/src/reference/compilation.html#compiler-directives

**Comment by charliboy** [comment] 2018-05-30 00:53
@gabrieldemarmiesse ,thank you very much,when I add '#cython language_level=3' on the top file,the calculation result is Ok.

**Closed** 2018-05-30 00:53 UTC
