### ISSUE TITLE
Add support for GCC style dependency file

### ISSUE THREAD

**Issue by jpakkane** [cython/cython#1459] opened 2016-09-14 16:23 UTC
GCC supports writing a dependency file during compilation with the `-M` family of compiler arguments. This makes it easy to integrate into build systems and have all dependencies be exact. Cython should add support for generating an output file in the same format when compiling. Something like this:

```
cython3 foo.pyx -o foo_pyx.c --depfile foo.pyx.d
```

**Comment by jdemeyer** [comment] 2016-10-13 14:33
See #243

**Comment by scoder** [comment] 2021-12-22 07:46
Duplicate of https://github.com/cython/cython/issues/1214

**Closed by scoder** 2021-12-22 07:46 UTC
Labels: R: duplicate
