### ISSUE TITLE
[ENH] Separate shadowing package

### ISSUE THREAD

**Issue by Bluenix2** [cython/cython#4481] opened 2021-11-24 19:01 UTC
## Summary

I would like to add Cython to a package of mine, but Cython would be highly optional using the Pure Python mode. The issue is that I would like to avoid having users install the huge 26 MB transpiler that Cython has become - compared to the 15 KBs that the Shadow.py file takes up!

## Preferred Solution

The best solution for my case would be a separate `cython-shadow` package which would trigger when trying to import `Cython` (or `cython`) like it does right now.

That would allow me to have the main package `Cython` as a development dependency and my package would be compiled if Cython is present, but would fall onto the much smaller *required* dependency consisting only of the shadow code.

## Alternatives

If this can't be done I would be forced to somehow vendor in this fallback (if even possible) or publish this myself as a fork.

**Comment by da-woods** [comment] 2021-11-24 19:13
Duplicate of https://github.com/cython/cython/issues/1981

**Closed by da-woods** 2021-11-24 19:13 UTC
