### ISSUE TITLE
The Local function are not recognized when packaged with cython code. 

### ISSUE THREAD

**Issue by nagesh-chowdaiah** [cython/cython#3880] opened 2020-10-16 06:11 UTC
**Is your feature request related to a problem? Please describe.**
In my code we have used a local function pandas_udf inside method of a class. But when we package this code, i am
getting picking error. 
_pickle.PicklingError: Can't pickle <cyfunction Overfit.get_dummies.<locals>.overfit at 0x000002DF651BC528>: it's not found as tools.estimation.Overfit.Overfit.get_dummies.<locals>.overfit
 [...]
```cython
# add use case related code here
    def get_dummies(self, df_sales: pd.DataFrame) -> DataFrame:

        schema_str = StructType([
            StructField(store_col_copy, DoubleType(), True),
            StructField(yrmo_col_copy, DoubleType(), True),
            StructField(sku_col_copy, DoubleType(), True),
            StructField('utilities', DoubleType(), True)])

        @pandas_udf(schema_str, PandasUDFType.GROUPED_MAP)
        def overfit(df_sales_sample):
            store = df_sales_sample[store_col_copy].iloc[0]
            yrmo = df_sales_sample[yrmo_col_copy].iloc[0]

            overfit_util = pd.Series({u: dummies[i] for (i, u) in enumerate(skus_sample)}).to_frame().reset_index()
            overfit_util.columns = [sku_col_copy, 'overfit_utilities']
            overfit_util[store_col_copy] = store
            overfit_util[yrmo_col_copy] = yrmo
            return overfit_util.drop_duplicates()

        df_sales_spark = self._spark.createDataFrame(df_sales)
        overfit_spark = df_sales_spark.groupby([store_col_copy, yrmo_col_copy]).apply(overfit)
        return overfit_spark
```

**Describe the solution you'd like**
Please add the feature so that internal function is recognized when python code is packaged using cython
```cython
# add a proposed code/syntax example here
```

**Describe alternatives you've considered**
```cython
# add alternative code/syntax proposals here
```

**Additional context**
Add any other context about the feature request here.

**Comment by da-woods** [comment] 2020-10-16 06:37
I don't think this is specifically a Cython issue - if you try to pickle a Python nested function then it'll also fail.

With that said it might be possible for Cython to do better here provided that all the captured variables are pickleable.

**Comment by nagesh-chowdaiah** [comment] 2020-11-09 14:28
@da-woods by when can we expect this feature. We are highly dependent on this.

**Comment by scoder** [comment] 2020-11-09 15:10
Duplicate of #2584

**Closed by scoder** 2020-11-09 15:10 UTC
