### ISSUE TITLE
[BUG] C++ overloaded traits are dropped from Cython "cppclass"es when the cppclass inheriting from an extern cppclass is itself not extern

### ISSUE THREAD

**Issue by BlindChickens** [cython/cython#4524] opened 2021-12-24 14:10 UTC
**Describe the bug**
C++ overloaded traits are dropped from Cython "cppclass"es when the cppclass inheriting from an extern cppclass is itself not extern, in other words a non-extern cppclass drops overloaded traits/methods from an extern cppclass which defines these C++ overloaded traits.

**To Reproduce**
Code to reproduce the behaviour:
```cython
cdef:
	extern from "cpp_source.h":
		cppclass testclass:
			testclass()
			void a()
			void a(unsigned int i)
	cppclass testclass2(testclass): # a() is dropped
		testclass2()

	testclass t1 = testclass()
	testclass2 t2 = testclass2()


t1.a()
t1.a(1)

t2.a() # Call with wrong number of arguments (expected 1, got 0)
t2.a(2)
```

**Expected behavior**
It is expected that the overloaded `a` method works with no arguments.

**Environment (please complete the following information):**
 - OS: Linux
 - Python version: 3.9
 - Cython version: 3.0.0 alpha 10

**Additional context**

**Comment by da-woods** [comment] 2021-12-24 17:45
I think this may be a duplicate of https://github.com/cython/cython/issues/1357 and be one of the bugs in https://github.com/cython/cython/pull/4228.

Thanks for producing a fix PR!

**Comment by BlindChickens** [comment] 2021-12-24 18:29
@da-woods Hi, ok thanks for pointing out the duplicate issue. My search obviously did not catch that one. Do I need to rather refer to that issue in my PR, and close my issue?

**Comment by da-woods** [comment] 2021-12-24 19:13
No need to do anything. I was only mentioning it so they could be closed too when we merge the PR (if I'm right and they are the same issue)

**Comment by BlindChickens** [comment] 2021-12-24 19:25
Ok cool. Who needs to approve the workflow on my PR? I want to see if all the tests pass.

**Comment by scoder** [comment] 2021-12-25 12:18
Duplicate of https://github.com/cython/cython/issues/1357

**Closed by scoder** 2021-12-25 12:18 UTC
Labels: C++, defect, R: duplicate, Type Analysis
