### ISSUE TITLE
[BUG] Compiled `prange` loop isn't able to exit section

### ISSUE THREAD

**Issue by david-cortes** [cython/cython#5564] opened 2023-07-25 18:30 UTC
### Describe the bug

ref https://github.com/david-cortes/hpfrec/issues/14

With the latest cython==3.0.0, some 'for' loops using `prange` in `.pyx` files are being compiled into something that isn't able to finish the loop (this is about just deterministically-numbered for's), but will work correctly (that is, the program is able to exit from the loop) if switched to regular `range` or if compiled with an older cython version.

I haven't been able to produce a minimally reproducible example and am not sure what exactly is wrong, nor how to debug it, but I have this particular example here:
https://github.com/david-cortes/hpfrec/blob/aac53899f9b93071a1a2267f41f61f603c4a33d9/hpfrec/cython_loops.pxi#L579

If adding `printf` lines, I am seeing that the code is able to enter the loop, and at least some individual iterations are able to reach the last line inside the 'for' chunk if I add a printf in each loop iteration, but if adding a `printf` statement right outside of the 'for' indentation, it never reaches that line.

The issue happens with both GCC and CLANG.

Attached is the generated C file in case it helps. The translated chunk starts at L21624 in the C file.
[cython_double_nonwindows.zip](https://github.com/cython/cython/files/12164391/cython_double_nonwindows.zip)

### Code to reproduce the behaviour:

https://github.com/david-cortes/hpfrec/blob/aac53899f9b93071a1a2267f41f61f603c4a33d9/hpfrec/cython_loops.pxi#L579

### Expected behaviour

The `prange` loop should reach the end of the execution in the code above, which is deterministic and not dependant on any variable that would get modified inside the loop.

### OS

Linux

### Python version

3.9

### Cython version

3.0.0

**Comment by da-woods** [comment] 2023-07-26 07:50
Are there any instructions saying that we'd need to run the in that example if we wanted to reproduce it?

My current theory is that it's re-acquiring the GIL to check if some function has errored and we're ending up with a dead-lock there. You could try marking any functions/function pointers that you use in the loop as `noexcept` to prevent that.

That's a complete semi-informed guess though so don't take it too seriously

**Comment by david-cortes** [comment] 2023-07-26 14:34
> Are there any instructions saying that we'd need to run the in that example if we wanted to reproduce it?
> 
> My current theory is that it's re-acquiring the GIL to check if some function has errored and we're ending up with a dead-lock there. You could try marking any functions/function pointers that you use in the loop as `noexcept` to prevent that.
> 
> That's a complete semi-informed guess though so don't take it too seriously

Thanks for the hint. It's definitely related as adding compiler directive `legacy_implicit_noexcept=True` makes the problem go away.

However, in this case, the `cdef`'d function that hangs is only calling functions from `libc.math` and `scipy.special.cython_special`, which I understand are declared from "extern" and thus should be implicit `noexcept`s according to [the docs](https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#error-return-values).

(BTW if `prange` calling a non-`noexcept` function is something that will end up hanging, it'd be nice to turn it into a compilation error intead)

As for an example to trigger the bug - sorry, forgot about that part. Steps would be to clone the repository, reset to the commit above, then build the extension, and then execute the example in the readme of the repository. As code:
```shell
git clone https://github.com/david-cortes/hpfrec.git
cd hpfrec
git reset --hard aac53899f9b93071a1a2267f41f61f603c4a33d9
python setup.py build_ext --inplace --force
```

Then launch python and execute the following:
```python
import numpy as np
from scipy.sparse import random as sp_random
from hpfrec import HPF

X = sp_random(100, 100, random_state=123)
HPF().fit(X)
```

**Comment by da-woods** [comment] 2023-07-26 19:22
Thanks for confirming.

> However, in this case, the cdef'd function that hangs is only calling functions from libc.math and scipy.special.cython_special, which I understand are declared from "extern" and thus should be implicit noexcepts according to [the docs](https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#error-return-values).

I think the complication is that you go through a function pointer which is declared non-externally. So the function pointer exception won't have the implicit `noexcept`.

> (BTW if prange calling a non-noexcept function is something that will end up hanging, it'd be nice to turn it into a compilation error intead)

My hope is we can fix it rather than have to turn it into an error. But either way we should definitely do something better than hang.

Thanks for the information - that should be enough to dig into it a little more, time permitting

**Comment by da-woods** [comment] 2023-07-29 21:24
I think I've got to the bottom of this, although I tested it on the simpler example in #5577 rather than your code.

I believe there's probably a subtle error in your code: a `nogil` function says that it *can* be run without the GIL, but doesn't guarantee that it's run without the GIL. `prange` blocks *must* be run without the GIL (although you get away with it most of the time unless you hit something that needs to re-acquire the GIL).

Frankly that's so subtle that I'm not sure anyone can be expected to spot it. Therefore my proposed fix is to get rid of the requirement and make absolutely 100% sure that the GIL is released before entering a `prange` block.

**Comment by david-cortes** [comment] 2023-07-30 18:48
> I think I've got to the bottom of this, although I tested it on the simpler example in #5577 rather than your code.
> 
> I believe there's probably a subtle error in your code: a `nogil` function says that it _can_ be run without the GIL, but doesn't guarantee that it's run without the GIL. `prange` blocks _must_ be run without the GIL (although you get away with it most of the time unless you hit something that needs to re-acquire the GIL).
> 
> Frankly that's so subtle that I'm not sure anyone can be expected to spot it. Therefore my proposed fix is to get rid of the requirement and make absolutely 100% sure that the GIL is released before entering a `prange` block.

Adding an explicit `with nogil:` before entering the `prange` part doesn't seem to solve the issue either.

**Comment by da-woods** [comment] 2023-07-30 21:16
Do you know if it's the `with nogil:` that makes it run slower? or does `with nogil` plus `legacy_implicit_noexcept=True` run at normal speed?

 Just considering what to do here
* f the `with nogil:` is an appreciable slowdown then I should think twice about adding it implicitly.
* With the `legacy_implicit_noexcept` we know if does have a performance hit in some circumstances - the question is what the best way to tell users about it is.

**Comment by david-cortes** [comment] 2023-07-31 16:15
> Do you know if it's the `with nogil:` that makes it run slower? or does `with nogil` plus `legacy_implicit_noexcept=True` run at normal speed?
> 
> Just considering what to do here
> 
> * f the `with nogil:` is an appreciable slowdown then I should think twice about adding it implicitly.
> * With the `legacy_implicit_noexcept` we know if does have a performance hit in some circumstances - the question is what the best way to tell users about it is.

If adding `with nogil` before entering the `prange`, it seems to run slower than if compiled with older cython, and it seems to prevent the code from running fully in parallel inside the `prange`. The slowdown goes beyond just the loss of multi-threading.

Adding `legacy_implicit_noexcept=True` seems to fix the speed issue, regardless of whether there is a `with nogil` or not, so the `with nogil` is probably not to blame.

**Comment by da-woods** [comment] 2023-08-01 06:51
Thanks again. That suggests to me my proposed fix is probably fine, but we should get people some better diagnostics when they're using `except *` functions (especially those where the `except *` has been added implicitly by Cython) in `nogil` sections.

**Comment by david-cortes** [comment] 2023-08-01 16:14
> Thanks again. That suggests to me my proposed fix is probably fine, but we should get people some better diagnostics when they're using `except *` functions (especially those where the `except *` has been added implicitly by Cython) in `nogil` sections.

The problem still happens with functions that are declared from `extern`, even when not accessed through a function pointer. I haven't been able to create a minimal example, but the same repository above was updated to avoid going through function pointers and the issue persists. I guess it might have to do with using `cimport as` or `ctypedef` but I'm not 100% sure.

Here it would show a slowdown if one removes the compiler directive `legacy_implicit_noexcept=True` from file `cython_float_nonwindows.pyx`. It might not be very noticeable in this example, but as the data sizes grow, it becomes very noticeable compared to the old implicit `noexcept` logic:
```shell
git clone https://github.com/david-cortes/hpfrec.git
cd hpfrec
git reset --hard ca11bd17d9125d46591f9c18c86bde4231f098f8
python setup.py build_ext --inplace --force
```
```python
import numpy as np
from scipy.sparse import random as sp_random
from hpfrec import HPF

X = sp_random(100, 100, random_state=123)
HPF().fit(X)
```

**Comment by da-woods** [comment] 2023-08-02 07:10
It looks like the functions that are causing issues are the scipy special ones:

```
__pyx_t_8 = __pyx_fuse_1__pyx_f_5scipy_7special_14cython_special_psi((__pyx_v_G_sh[(__pyx_v_uid_st + __pyx_v_j)]), 0); if (unlikely(__Pyx_ErrOccurredWithGIL())) __PYX_ERR(0, 569, __pyx_L6_error)
```

(The thing to search for the in the C code to identify this is `__Pyx_ErrOccurredWithGIL`). This looks like a fused function rather than something purely extern. I haven't been able to identify where it comes from in Scipy but I'll report it to them to see if it can be made `noexcept`

**Comment by da-woods** [comment] 2023-08-21 20:07
I think this is closed by https://github.com/cython/cython/commit/3c54aad4698a5ac9f5febeea1f1fdbf543a22790

There's definitely more stuff I'd like to do about improving fused functions, and improving diagnostics for this. But I think the immediate "it crashes" issue is done.

**Closed by da-woods** 2023-08-21 20:07 UTC
