### ISSUE TITLE
Cython class is not calling the magic reflected methods. 

### ISSUE THREAD

**Issue by ibaris** [cython/cython#3718] opened 2020-07-02 12:23 UTC
Cython does not call the reflected methods (`__rsub__`, `__rmul__`, etc.) of the class. Here is an example with `sub` and `rsub`:

```cython
cdef class VectorTest:
    cdef object __array
    cdef int __dim

    def __cinit__(self, array):
        cdef:
            np.ndarray[np.double_t, ndim=1, mode="c"] array_1d = np.ascontiguousarray(array.flatten().astype(np.double))
            double[:] array_1d_view = array_1d
            int dim = len(array_1d)

        self.__array = array_1d
        self.__dim = dim

    def __repr__(self):
        return "<{class_name} {dim}D ({array})>".format(class_name=self.__class__.__name__,
                                                        dim=self.dim,
                                                        array=self.array)

    def __sub__(self, other):
        other = other.array if isinstance(other, VectorTest) else other
        return self.__class__(self.array.__sub__(other))

    def __rsub__(self, other):
        other = other.array if isinstance(other, VectorTest) else other
        return self.__class__(self.array.__rsub__(other))

    @property
    def array(self):
        return self.__array

    @property
    def dim(self):
        return self.__dim

```

After compiling the code the behavior between `VectorTest` classes and the **right handed** subtraction with arbitrary numbers are as expected:

```python
import numpy as np
from . import VectorTest

array1 = np.array([1, 2, 3]).astype(np.double)
array2 = np.array([6, 23, 1]).astype(np.double)


v1 = rpy.geometry.VectorTest(array1)
v2 = rpy.geometry.VectorTest(array2)
```

```console
>>> v1 - v2
<VectorTest 3D ([ -5. -21.   2.])>

>>> v2 - v1 
<VectorTest 3D ([ 5. 21. -2.])>

>>> v1 - 2
<VectorTest 3D ([-1.  0.  1.])>
```

But if I try to subtract the `VectorTest` class with an arbitrary number the other way around it produces the following error:

```console
>>> 2 - v1
  File ".\vector.pyx", line 62, in .VectorTest.__sub__
    return self.__class__(self.array.__sub__(other))

   AttributeError: 'int' object has no attribute 'array'
```

As one can see, the `VectorTest.__sub__` is called and not the `VectorTest.__rsub__` method. If I compile the class as 

```cython
class VectorTest:

    def __init__(self, array):
        ....
```

the `__rsub__` method is called as expected.

**Comment by scoder** [comment] 2020-07-02 13:25
Duplicate of #2056.

**Closed by scoder** 2020-07-02 13:25 UTC
Labels: R: duplicate
