### ISSUE TITLE
[BUG] Dataclass AttributeError

### ISSUE THREAD

**Issue by YoSTEALTH** [cython/cython#4741] opened 2022-04-16 02:26 UTC
Trying out `dataclasses`. Running current master branch, give me:

``` Cython
# test.pyx

from cython.dataclasses import dataclass

@dataclass
cdef class Testing:
    cdef public object obj
```

``` bash
Traceback (most recent call last):
  File "/.../setup.py", line 25, in <module>
    ext_modules=cythonize([extension],
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1143, in cythonize
    cythonize_one(*args)
    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1289, in cythonize_one
    result = compile_single(pyx_file, options, full_module_name=full_module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Main.py", line 576, in compile_single
    return run_pipeline(source, options, full_module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Main.py", line 504, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Pipeline.py", line 394, in run_pipeline
    data = run(phase, data)
           ^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Pipeline.py", line 371, in run
    return phase(data)
           ^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/ModuleNode.py", line 206, in process_implementation
    self.generate_c_code(env, options, result)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/ModuleNode.py", line 518, in generate_c_code
    self.generate_module_init_func(modules[:-1], env, globalstate['init_module'])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/ModuleNode.py", line 3101, in generate_module_init_func
    self.body.generate_execution_code(code)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 409, in generate_execution_code
    stat.generate_execution_code(code)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 409, in generate_execution_code
    stat.generate_execution_code(code)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 409, in generate_execution_code
    stat.generate_execution_code(code)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 355, in generate_execution_code
    self.body.generate_execution_code(code)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 409, in generate_execution_code
    stat.generate_execution_code(code)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 5340, in generate_execution_code
    self.body.generate_execution_code(code)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 409, in generate_
execution_code
    stat.generate_execution_code(code)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 355, in generate_
execution_code
    self.body.generate_execution_code(code)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 409, in generate_
execution_code
    stat.generate_execution_code(code)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 5773, in generate
_execution_code
    self.generate_rhs_evaluation_code(code)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 6072, in generate
_rhs_evaluation_code
    self.rhs.generate_evaluation_code(code)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/ExprNodes.py", line 1806, in gene
rate_evaluation_code
    self.result_code = code.get_py_string_const(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Code.py", line 1948, in get_py_st
ring_const
    return self.globalstate.get_py_string_const(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Code.py", line 1389, in get_py_st
ring_const
    c_string = self.get_string_const(text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11/lib/python3.11/site-packages/Cython/Compiler/Code.py", line 1360, in get_strin
g_const
    if text.is_unicode:
       ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'is_unicode'
```

**Comment by da-woods** [comment] 2022-04-16 07:18
I'm fairly sure this is a duplicate of https://github.com/cython/cython/issues/4704 so should be fixed on the absolutely most up-to-date master branch. If that isn't the case then let me know and I can reopen and investigate properly

**Closed by da-woods** 2022-04-16 07:18 UTC

**Comment by YoSTEALTH** [comment] 2022-04-16 17:31
@da-woods Thanks, its the current master branch `bbcb924e0852da8772106e016de4788327489306`

**Comment by YoSTEALTH** [comment] 2022-04-16 17:54
@da-woods Actually I was using `Python 3.11.0a5`, so fresh installed `Python 3.11.0a7` and installed `Cython` and tried to compile again... Its working good now. Just weird, this can remain closed :)
