### ISSUE TITLE
locals broken in generator expressions

### ISSUE THREAD

**Issue by da-woods** [cython/cython#3122] opened 2019-09-03 11:52 UTC
In the following testcase:

* `get_locals` works
*  `get_locals_keys1`, `get_locals_keys3` and `get_locals_keys4` fail, returning empty containers
*  `not_locals` works - proving that this is to do with locals and not just a generator expression problem.

My guess is that it's picking up a `locals` scoped only to the generator expression, but I haven't really dug into it to be sure.

```
# mode: run
# tag: purepy2 purepy3

def get_locals(a=1):
    """
    >>> list(get_locals().keys())
    ['a']
    """
    return locals()

def get_locals_keys1(a=1):
    """
    >>> get_locals_keys1()
    ['a']
    """
    return list(k for k in locals().keys())

def get_locals_keys2(a=1):
    """
    >>> get_locals_keys2()
    ['a']
    """
    return [k for k in locals().keys()]

def get_locals_keys3(a=1):
    """
    >>> list(get_locals_keys3())
    ['a']
    """
    return {k for k in locals().keys()}

def get_locals_keys4(a=1):
    """
    >>> get_locals_keys4()
    {'a': None}
    """
    return {k: None for k in locals().keys()}

def not_locals():
    """
    >>> not_locals()
    ['a']
    """
    d = {'a': 1}
    return list(k for k in d.keys())
```

**Comment by da-woods** [comment] 2019-09-03 14:35
You can kind of fix it by editing ExprNodes.py:

```
def LocalsExprNode(pos, scope_node, env):
    if env.is_module_scope:
        return GlobalsExprNode(pos)
    if env.is_py_class_scope:
        return PyClassLocalsExprNode(pos, scope_node.dict)
    if env.is_genexpr_scope or env.is_closure_scope:
        env = env.outer_scope
    return FuncLocalsExprNode(pos, env)
```

However - that gets tripped up by functions that are turned into closures (so fails test "generator_expression_and_locals". It also can't tell where in a generator expression locals actually is, so fails:

```
def locals_actually_in_generator():
    """
    >>> "x" in locals_actually_in_generator()
    True
    """
    return list(locals() for x in range(1))

def locals_actually_in_dictexpr():
    """
    >>> "x" in locals_actually_in_dictexpr()
    True
    """
    return {'a': locals() for x in range(1)}
```

I think this is beyond me (and pretty unimportant really - I only ran into it when trying to prepare some test-cases for something else)

**Comment by scoder** [comment] 2019-09-06 05:25
There is a ticket already about the outermost iterable being looked up in the wrong scope. Python special cases it, Cython currently does not. This is a duplicate.

**Comment by scoder** [comment] 2019-09-06 05:57
Duplicate of #1159.

**Closed by scoder** 2019-09-06 05:57 UTC
Labels: R: duplicate
