### ISSUE TITLE
[BUG] bytes and bytearray data decoding to str are not compatible

### ISSUE THREAD

**Issue by Telapsess** [cython/cython#4223] opened 2021-06-11 18:31 UTC
**Describe the bug**
For bytes and bytearray data, if they are decoded to str by their decoding method, that works well. But if the data is iterated by each byte, then use chr() function to convert that byte to a char, bytes and bytearray data wouldn't work in a same way. 

**To Reproduce**
Code to reproduce the behaviour:

a .py code is as following:
```
def test_bytes_and_bytearray_to_str():
    data_bytes = bytes(b'hello world')
    s = ""
    for d in data_bytes:
        s += chr(d)
    print(s)

    data_bytearray = bytearray(data_bytes)
    s = ""
    for d in data_bytearray :
        s += chr(d)
    print(s)

test_bytes_and_bytearray_to_str()
```
Then compile this source file by Cython and execute it, you will see that data_bytes is converted to str successfully while data_bytearray not(for data_bytearray, either a null string or some unrecognizable codes is printed to the console). But in python itself, these two types of data work the same with chr() and all can be converted to str normally.

I don't know this is really a bug or just that I am not using Cython properly.

**Expected behavior**
Both bytes and bytearray data should be converted to string normally by chr() function.

**Environment (please complete the following information):**
 - OS: Linux
 - Python version 3.7.10
 - Cython version 0.29.2

**Comment by da-woods** [comment] 2021-06-11 19:21
Duplicate of https://github.com/cython/cython/issues/3473 (I think).

I think there is a fix that's awaiting being merged. If "0.29.2" is true you might want to upgrade anyway (but it isn't fixed in the 0.29.x yet)

**Closed by da-woods** 2021-06-11 19:21 UTC
