### ISSUE TITLE
failing test with python3.12rc1

### ISSUE THREAD

**Issue by mattip** [cython/cython#5628] opened 2023-08-15 20:00 UTC
### Describe your issue

Noticed this when looking at 3.12-dev CI runs on #5620 

[`pstats_profile_test`](https://github.com/cython/cython/actions/runs/5867996550/job/15909904350#step:6:16470) and `pstats_profile_test_pyfunc` are failing on 3.12. [This is the source](https://github.com/cython/cython/blob/6f592646c069c4fd9fee76f96d4abbe060412e65/tests/run/pstats_profile_test_pycfunc.pyx#L1). Maybe the expected profiling output has changed for 3.12 due to [inlining comprehensions](https://docs.python.org/3.12/whatsnew/3.12.html#pep-709-comprehension-inlining).

That seems to be the only failing test on HEAD with 3.12rc1.

**Comment by scoder** [comment] 2023-08-29 07:02
Duplicate of #5470

**Closed by scoder** 2023-08-29 07:02 UTC
Labels: R: duplicate
