### ISSUE TITLE
[BUG] Returning a fused typed argument causes a compiler crash

### ISSUE THREAD

**Issue by ilayn** [cython/cython#3835] opened 2020-09-18 13:23 UTC
**Describe the bug**
When the return type is a fused type that is a subset of the input fused type, the compiler crashes while `AnalyseDeclarationsTransform`

**To Reproduce**

```cython
%%cython -3 -a -f
cimport cython

ctypedef fused lapack_t:
    float
    double
    (float complex)
    (double complex)

ctypedef fused lapack_sd_t:
    float
    double

ctypedef fused lapack_f_t:
    float
    (float complex)

# cython.floating can be replaced with `lapack_sd_t` too
cpdef cython.floating anorm(lapack_t[::1] a, lapack_t[::1] b) nogil:
    cdef int n = <int>len(a)
    cdef int k
    cdef float anorm_f = 0.0
    cdef double anorm_d = 0.0

    # some code to do max(abs(a)+abs(b))
    for k in xrange(n):
        a[k] = abs(a[k]) + abs(b[k])

    # here I want to test whether the input type is float or (float complex)
    if lapack_t in lapack_f_t:
        for k in xrange(n):
            anorm_f = max(anorm_f, a[k].real)
        return anorm_f
    else:
        for k in xrange(n):
            anorm_d = max(anorm_d, a[k].real)
        return anorm_d
```

**Expected behavior**

What I am trying to achieve is that the input args can be any of the `lapack_t` type. `a` and `b` are guaranteed to be of the same type. Depending on the float or double precision of the input, I'd like to return either a float or a double. But it seems that I can't convey this message to the code. 

Is there any other canonical way to do this?

**Environment (please complete the following information):**

  - OS: Windows 10.1904
  - Python version 3.8.0
  - Cython version 0.29.21

**Additional context**
Crash details 

<details>

```bash
Error compiling Cython file:
------------------------------------------------------------
...

ctypedef fused lapack_d_t:
    double
    (double complex)

cpdef cython.floating anorm(lapack_t[::1] a, lapack_t[::1] b) nogil:
     ^
------------------------------------------------------------

C:\Users\Ilhan Polat\.ipython\cython\_cython_magic_b9a167bbddb74d7bbc885fffbe56521e.pyx:22:6: Compiler crash in AnalyseDeclarationsTransform

ModuleNode.body = StatListNode(_cython_magic_b9a167bbddb74d7bbc885fffbe56521e.pyx:2:0)
StatListNode.stats[5] = StatListNode(_cython_magic_b9a167bbddb74d7bbc885fffbe56521e.pyx:22:6)
StatListNode.stats[0] = CFuncDefNode(_cython_magic_b9a167bbddb74d7bbc885fffbe56521e.pyx:22:6,
    args = [...]/2,
    has_fused_arguments = True,
    modifiers = [...]/0,
    overridable = 1,
    visibility = 'private')

Compiler crash traceback from this point on:
  File "Cython\Compiler\Visitor.py", line 180, in Cython.Compiler.Visitor.TreeVisitor._visit
  File "c:\users\ilhan polat\appdata\local\programs\python\python38\lib\site-packages\Cython\Compiler\ParseTreeTransforms.py", line 1896, in visit_FuncDefNode
    node = self._create_fused_function(env, node)
  File "c:\users\ilhan polat\appdata\local\programs\python\python38\lib\site-packages\Cython\Compiler\ParseTreeTransforms.py", line 1837, in _create_fused_function
    node = FusedNode.FusedCFuncDefNode(node, env)
  File "Cython\Compiler\FusedNode.py", line 61, in Cython.Compiler.FusedNode.FusedCFuncDefNode.__init__
  File "Cython\Compiler\FusedNode.py", line 144, in Cython.Compiler.FusedNode.FusedCFuncDefNode.copy_cdef
  File "c:\users\ilhan polat\appdata\local\programs\python\python38\lib\site-packages\Cython\Compiler\PyrexTypes.py", line 2940, in specialize
    result = CFuncType(self.return_type.specialize(values),
  File "c:\users\ilhan polat\appdata\local\programs\python\python38\lib\site-packages\Cython\Compiler\PyrexTypes.py", line 1655, in specialize
    return values[self]
KeyError: FusedType(name='floating')
```

</details>

**Comment by da-woods** [comment] 2020-09-21 19:59
This is a bug in the sense that it should give you a helpful error message rather than a compiler crash.

I don't think there's a good way of doing what you want (deduce the return type from one of the inputs without the return type being one of the inputs). In this case I'd probably just return `double` in all cases.

**Comment by ilayn** [comment] 2020-09-21 20:40
> In this case I'd probably just return double in all cases.

Yes, probably that makes sense. It's an overkill for a simple number anyways. Thanks.

**Comment by da-woods** [comment] 2020-09-27 09:41
duplicate of https://github.com/cython/cython/issues/3820

**Closed by da-woods** 2020-09-27 09:41 UTC
Labels: Error Reporting
