### ISSUE TITLE
[BUG] inspect returns signature base class

### ISSUE THREAD

**Issue by DavidDevoogdt** [cython/cython#4713] opened 2022-04-05 08:31 UTC
**Describe the bug**
`inspect.signature( x.__init__) ` returns the signature of base class instead of the child class.

**To Reproduce**
File cythonclass.pyx contains same class definition, once for cython and once for pure python
```
import cython

class p1:
    def __init__(self,*args,**kwargs) -> None:
        pass

class p2(p1):
    def __init__(self,a,b):
        self.a = a
        self.b = b

cdef class c1:
    def __init__(self,*args,**kwargs) -> None:
        pass

cdef class c2(c1):
    cdef int a,b
    def __init__(self,int a, int b):
        self.a = a
        self.b = b
```
The test file to produce the bug is:
```
from cythonclass import c2, p2
import inspect

myp2 = p2(1, 1)
myc2 = c2(1, 1)

print("C sig {}".format(inspect.signature(myc2.__init__)))
print("Pyton sig {}".format(inspect.signature(myp2.__init__)))
```

**Expected behavior**
Both should give the same output, but the output is

```
C sig (*args, **kwargs)
Pyton sig (a, b)
```

**Environment (please complete the following information):**
 - OS: Ubuntu 21.10
 - Python version: 3.8.2
 - Cython version 0.29.28

**Comment by scoder** [comment] 2022-04-05 11:58
Thanks for the report. If you change the signature of the class `c1` to anything else, you'll notice that it makes no difference to the output of `inspect`. Thus, the issue is not related to subclassing, it's a general problem with `inspect`.

Duplicate of #3873.

**Closed by scoder** 2022-04-05 11:58 UTC
Labels: R: duplicate
