### ISSUE TITLE
different modulo behavior on windows vs linux since python3

### ISSUE THREAD

**Issue by tshirtman** [cython/cython#2192] opened 2018-03-30 17:03 UTC
I seem to have hit a different issue with modulo on windows versus linux.

if i cast the number to a float, or just put it inline before the modulo, it works as i expected.

```python
num = 3316_000_000_000
print(num % 999)

num = float(3316_000_000_000)
print(int(num % 999))

print(3316_000_000_000 % 999)
```

```python
from distutils.core import setup
from Cython.Build import cythonize

setup(
    ext_modules=cythonize(['test.pyx'])
)
```

```bash
pyinstaller@3d46c498e294:/app$ python setup.py build_ext --inplace
Compiling test.pyx because it changed.
[1/1] Cythonizing test.pyx
running build_ext
building 'test' extension
C:\mingw64\bin\gcc.exe -mdll -O -Wall -IC:\Python36\include -IC:\Python36\include -c test.c -o build\temp.win-amd64-3.6\Release\test.o
writing build\temp.win-amd64-3.6\Release\test.cp36-win_amd64.def
C:\mingw64\bin\gcc.exe -shared -s build\temp.win-amd64-3.6\Release\test.o build\temp.win-amd64-3.6\Release\test.cp36-win_amd64.def -LC:\Python36\libs -LC:\Python36\PCbuild\amd64 -lpython36 -o Z:\app\test.cp36-win_amd64.pyd
pyinstaller@3d46c498e294:/app$ python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import test
935
319
319
```

As you can see i'm building using mingw64, so this might be a factor, but the fact that it works either casting as float or inlining makes me think it's a cython bug.

```bash
gabriel@dev-desk-1:/tmp> python3.6 setup.py build_ext --inplace
running build_ext
building 'test' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/gabriel/.virtualenvs/kivy36/include/python3.6m -c test.c -o build/temp.linux-x86_64-3.6/test.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/test.o -o /tmp/test.cpython-36m-x86_64-linux-gnu.so
18:54:51 30/03/18 red argv[1] 94%kivy36 390                                       
gabriel@dev-desk-1:/tmp> python3.6 
Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import test
319
319
319
```

Doing these operation in python directly always results in 319, on both platform.

the docker image used to build can be found on docker hub (https://hub.docker.com/r/tshirtman/kpmwine/)

```
docker run -ti -v $PWD:/app -v /tmp/pipcache:"/wine/drive_c/users/pyinstaller/Local Settings/application data/pip/cache/" tshirtman/kpmwine bash
```

**Comment by scoder** [comment] 2018-03-30 17:47
I obviously cannot reproduce this without Windows, but I added your example to get it tested on appveyor. Are you using the latest Cython 0.28.1 release?

As for potentially relevant platform differences, `long` is 32 bits on Windows64 and 64 bits on Linux64, and I'm not sure what the size of a `PyLong` digit is on Windows.

In any case, the code that Cython generates is correctly typed and analysed. I don't see anything obviously wrong with it. The result is calculated in the generated helper function `__Pyx_PyInt_RemainderObjC()`, specifically by the code that handles `PyLong` values.

**Comment by scoder** [comment] 2018-03-31 07:47
Appveyor seems quite happy with the test:
https://ci.appveyor.com/project/cython/cython/build/master-1898

**Comment by tshirtman** [comment] 2018-03-31 14:03
Yes i was using the latest from pip, 0.28.1, i did integrate your test in my code to be sure there is no subtle difference, and it does generate the bug on my side, so i guess next step for me is to setup a windows build environment with visual studio and see if i can reproduce here.

Thanks for looking into it :).

**Comment by scoder** [comment] 2018-04-08 12:17
I'm able to reproduce this with your docker image. In your setup, MinGW finds this config:
```
sizeof(digit) = 2
sizeof(long) = 4
sizeof(long long) = 8
PyLong_SHIFT = 15
PyLong_BASE = 32768
```
However, this is clearly not what CPython uses in your docker image:
```
$ wine python -c 'import sys; print([sys.getsizeof(i) for i in (0, 1, 2**15-1, 2**15, 2**30-1, 2**30, 2**30+1, 2**45-1, 2**45, 2**60-1, 2**60)])'
[24, 28, 28, 28, 28, 32, 32, 32, 32, 32, 36]
```
The integer object size increases by 4 bytes every 2**30 integers, which suggests a `PyLong` digit size of 30 bits, not 15.

I have no idea how to fix the setup here. If you need to use it, you may consider disabling direct `PyLong` usage in Cython by defining `-D CYTHON_USE_PYLONG_INTERNALS=0`. But that will slow things down a bit.

I'll close this ticket since it's not a bug in Cython.

**Closed by scoder** 2018-04-08 12:17 UTC
