### ISSUE TITLE
[BUG]: annotating argument as list[some_type] raises CompileError

### ISSUE THREAD

**Issue by jbrockmendel** [cython/cython#4214] opened 2021-06-05 19:34 UTC
Trying to add pure-py annotation [here](https://github.com/pandas-dev/pandas/blob/master/pandas/_libs/internals.pyx#L161)

```
-def append(self, others) -> BlockPlacement:
+def append(self, others: list[BlockPlacement]) -> BlockPlacement:
```

raises

```
pandas/_libs/internals.pyx:166:57: Compiler crash in IterationTransform
```

**Comment by da-woods** [comment] 2021-06-05 20:08
I assume this is 0.29.x you're using (although the same bug probably exists on 3.0a)?

Ultimately https://github.com/cython/cython/pull/3910 should help with this sort of thing (although it currently only looks at the `typing` module and doesn't make the built-in types subscriptable; that's probably a fairly easy change for the future though).

For the moment Cython's unlikely to use the `[BlockPlacement]` information, so one solution would be to omit that. Obviously you may want it for your own documentation though.

I imagine the likely outcome is that 0.29.x will end up treating this as `object` (but not crashing) but at some point 3.0x will recognise it correctly as `list`.

**Comment by jbrockmendel** [comment] 2021-06-05 23:04
> I assume this is 0.29.x you're using (although the same bug probably exists on 3.0a)?

ive only tried this on 0.29.23

> For the moment Cython's unlikely to use the [BlockPlacement] information, so one solution would be to omit that. Obviously you may want it for your own documentation though.

yah, this is basically cosmetic in this context

**Comment by da-woods** [comment] 2021-06-06 11:22
FWIW this was a duplicate of https://github.com/cython/cython/issues/2811. It looks like that didn't get backported. I've created a PR with a minimal bit backported, but it's possible that this isn't the cleanest way to fix it.

**Closed** 2021-06-09 11:33 UTC
Labels: Pure Python Mode, Type Analysis, defect
