### ISSUE TITLE
 Cythonized data classes allow omission of required arguments. 

### ISSUE THREAD

**Issue by kollmats** [cython/cython#3776] opened 2020-08-12 07:55 UTC
**Describe the bug**

When instantiating a data class, it usually detects if a required argument is missing and raises an error. In Cython, nothing happens until you try to access the missing field and an AttributeError is thrown:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "main.py", line 24, in init main
> AttributeError: 'Bb' object has no attribute 'a1'

**To Reproduce**
```
from dataclasses import dataclass

@dataclass                                                                                           
class Aa:                                                                                            
    a1: str                                                                                          
    a2: str = '100'                                                                                  
    a3: str = None                                                                                   
                                                                                                      
class Bb(Aa):                                                                                        
    b1: str = '123'                                                                                  
    b2: str = None                                                                                   
                                                                                                      
bb = Bb()
print(bb.a1)
```

**Expected behavior**
Without Cython, the above yields the following traceback _when calling the constructor_:

> Traceback (most recent call last):
>   File "main.py", line 23, in <module>
>     bb = Bb()
> TypeError: __init__() missing 1 required positional argument: 'a1'

**Environment (please complete the following information):**

    OS: Ubuntu 
    Version: 18.0.4

**Additional context**
Python 3.6.9, Cython 0.29.21, dataclasses 0.7 (backport)

**Comment by scoder** [comment] 2020-08-12 09:08
Duplicate of #2552.

**Closed by scoder** 2020-08-12 09:08 UTC
