### ISSUE TITLE
[ENH] Error messages should use full path of file

### ISSUE THREAD

**Issue by rickmark** [cython/cython#5322] opened 2023-03-17 19:39 UTC
### Is your feature request related to a problem? Please describe.

I would like to be able to use pycharm navigation to error lines.

Today pycharm will happily identify full paths in build output, and allow one click navigation to the file and line.  This does not work with cython since the relative path is used.  Tracebacks for errors use fully qualified paths, and cython should here too.  The only downside is that the full path is longer and therefore placing it and the error message on the same line would be excessive.  The suggestion is to put these on separate lines and use full paths.  (Similar to how clang would output a compilation error anyway)

**Comment by da-woods** [comment] 2023-03-25 12:25
Duplicate of #2873.

This does seem like a good idea - it sounds like it'd make multiple editors happier. A PR would definitely be welcome

**Closed by da-woods** 2023-03-25 12:25 UTC
Labels: R: duplicate
