### ISSUE TITLE
[BUG] Some aliases are unavailable in Python mode (p_uchar)

### ISSUE THREAD

**Issue by vytas7** [cython/cython#5934] opened 2024-01-01 13:04 UTC
### Describe the bug

I'm trying to write some code using the so-called pure Python mode, but apparently there is no full parity between types and constants in the compiled and pure Python modes.

### Code to reproduce the behaviour:

```python
import cython

ptr: cython.p_uchar

```

```
$ python test.py 
<...>
AttributeError: module 'cython' has no attribute 'p_uchar'. Did you mean: 'p_char'?
```

However `cythonize` works just fine:
```
$ cythonize -i test.py 
Compiling /tmp/test.py because it changed.
(Some warnings about 'language_level' not set, compiles fine otherwise.)
```

### Expected behaviour

If Cython pure-Python mode code compiles, I expect it to be importable even when not compiled.

### OS

Linux

### Python version

CPython 3.10.12

### Cython version

3.0.7

**Comment by scoder** [comment] 2024-01-01 15:38
Duplicate of https://github.com/cython/cython/issues/4227

**Comment by scoder** [comment] 2024-01-01 15:55
Sorry, my fault. I checked and the unsigned and signed pointer types are really missing. I'll add them.
Thanks for the report.

**Closed** 2024-01-01 16:15 UTC
