### ISSUE TITLE
[BUG] initialization of extension type with buffer view after `__new__` makes Segfaults

### ISSUE THREAD

**Issue by jimy-byerley** [cython/cython#4034] opened 2021-03-14 15:40 UTC
Hello, I noticed some strange crash when using the `Py_buffer` objects together with `__new__` constructor of extension types:
Here is the matter: I use the `__new__` function of a `WrapperClass` as detailed [in the doc](https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#existing-pointers-instantiation)
and the `WrapperClass` has a member which is a `Py_buffer`

```python
from cpython cimport PyObject, PyTypeObject, Py_buffer
from cpython.buffer cimport PyBUF_SIMPLE, PyObject_CheckBuffer, PyObject_GetBuffer, PyBuffer_Release


cdef class WrapperClass:
	''' A wrapper class for a C/C++ data structure '''
	
	cdef Py_buffer view
	
	def __init__(self, buffer):
		''' build the object from a buffer (using __init__) '''
		if not PyObject_CheckBuffer(buffer):
			raise TypeError('the input object must support the buffer protocol')
		
		PyObject_GetBuffer(buffer, &self.view, PyBUF_SIMPLE)

	def __dealloc__(self):
		PyBuffer_Release(&self.view)

	@property
	def ptr(self):
		return <size_t>self.view.buf
		
	@property
	def size(self):
		return <size_t>self.view.len
		
	@staticmethod
	cdef WrapperClass from_raw(void * ptr, size_t size, owner):
		"""Factory function to create WrapperClass objects from given my_c_struct pointer.

			Setting ``owner`` flag to ``True`` causes the extension type to ``free`` the structure pointed to by ``_ptr`` when the wrapper object is deallocated.
		"""
		# Call to __new__ bypasses __init__ constructor
		cdef WrapperClass wrapper = WrapperClass.__new__(WrapperClass)
		wrapper.view.buf = ptr
		wrapper.view.len = size
		wrapper.view.obj = owner
		wrapper.view.itemsize = 1
		wrapper.view.ndim = 1
		wrapper.view.format = 'B'
		return wrapper


def build_wrapped(buffer):
	''' build the object from a buffer (the same but using __new__ instead of __init__)'''
	
	# in this example, the buffer is taken the same way __init__ is doing, but in my real project I do get it from an other source ... this is not changing the issue
	cdef Py_buffer view
	if not PyObject_CheckBuffer(buffer):
		raise TypeError('the input object must support the buffer protocol')
	
	PyObject_GetBuffer(buffer, &view, PyBUF_SIMPLE)
	
	cdef WrapperClass wrapped = WrapperClass.from_raw(view.buf, view.len, view.obj)
	return wrapped
```
So this class can be built using 2 different ways:
- using the constructor `__init__`
- using its static method `from_raw`

setting its fields attributes only works well in the 1st case:

```python
from extension_type import WrapperClass, build_wrapped

# build the object using __init__
w1 = WrapperClass(b'a protocol-compatible object')
print('w1', w1.ptr, w1.size)

# build the object using __new__ then filling the fields
w2 = build_wrapped(b'a protocol-compatible object')
print('w2', w2.ptr, w2.size)
```
output:
```
w1 139932419840976 28
Segmentation fault (core dumped)
```
So the second methods is crashing (It seems even to always crash at setting `view->obj` at the INCREF/DECREF/GOTREF/... operations)  

I would expect these 2 methodesto  be roughly equivalent to build a `WrapperClass`
It seems that when the object is build using `__new__` the attributes cannot be set to an object, or is there anything wrong in my use of it ?

I'm using 
- Ubuntu/Linux latest
- Python 3.8.5  (from repo)
- Cython 0.29.22  (from pip)

**Comment by jimy-byerley** [comment] 2021-03-14 15:43
By the way, I didn't realized there was so few people working on that project. That's really an amazing job ! congratulation !

**Comment by scoder** [comment] 2021-03-14 16:02
The problem is that `Py_buffer.obj` is defined as a (ref-counted) object reference, but here it is NULL. Setting it to `owner` will assume that it's a valid reference to an object and `DECREF()` it.

Cython could potentially special-case this internally (I guess), but for now, I think you should do the ref-counting yourself on the first assignment, by casting to `PyObject*` and calling `INCREF()` yourself.

**Comment by jimy-byerley** [comment] 2021-03-14 18:54
Ah, sounds correct. But when I try to assign it as a pointer I get this:
```python
view->obj = <PyObject*> owner
```

```
Cannot convert 'PyObject *' to Python object
```
So it seems Cython is requesting a proper `object` in the assignment. How can I assign it ?

**Comment by da-woods** [comment] 2021-03-14 19:41
I suspect you don't want to cast it to `PyObject*` but do want to incref it first. So:

```
Py_INCREF(owner)
wrapper.view.obj = owner
```

However, I wonder if really you shouldn't be copying `Py_buffer` element-by-element - I don't know whether CPython promises that there won't be any private fields added to the structure that could catch you out in future. Perhaps it'd make more sense to do:

```
cdef WrapperClass wrapped = WrapperClass.__new__(WrapperClass)
PyObject_GetBuffer(buffer, &wrapped.view, PyBUF_SIMPLE)
return wrapped
```

**Comment by jimy-byerley** [comment] 2021-03-14 20:55
Well I'm trying to create an arrayview structure:
- it must keep the Py_buffer object alive to make sure the buffer provider will keep its hooks on, so I'm using the Py_buffer as internal data structure of the arrayview
- it must be used as array slice view, so the __getitem__ of the array must provide a view pointing to a different pointer than its own, so I cannot just use the buffer from the original object

That sample code was just some minimal example of what I tried to do ... But I think I really need such a `from_ptr` method :thinking: 

>  suspect you don't want to cast it to `PyObject*` but do want to incref it first. So:

If the problem is that the object ref is NULL initially, then incrementing the owner ref before won't fix that cython tries to `DECREF` the initially NULL ref, right ?

**Comment by jimy-byerley** [comment] 2021-03-14 20:56
Also I tried to `Py_INCREF(owner)` before to assign it, but it still Segfault the same way

**Comment by jimy-byerley** [comment] 2021-03-14 21:05
It seems to me that filling the `Py_buffer` structure only works when in `__getbuffer__` because only then the `obj` field is set to `None` before the function starts ... what I cannot achieve in a different context.

Then the only solution would be to have a way to assign that object pointer without having to deal with it as an `object`

**Comment by da-woods** [comment] 2021-03-14 21:08
> If the problem is that the object ref is NULL initially, then incrementing the owner ref before won't fix that cython tries to DECREF the initially NULL ref, right ?

You're right. I managed to miss that.

I think Py_Buffer is pretty special-cased (normally we don't allow `object` to be attributes of a struct because it ends up unclear what Cython has to reference-count. That does make it pretty hard to come up with a good solution to this.

**Comment by jimy-byerley** [comment] 2021-03-14 21:13
Hum, but why is `Py_buffer.obj` typed as `object` ?
It should be a PyObject* in the exact CPython header, so it's been redefined by cython as `object` right ?

Would it make sense that `Py_buffer.obj` would be typed as `PyObject*` as it would be in any user-defined C-structure ?
Or eventually to have `Pyx_DECREF` check for possible NULL pointers ?

I'm just considering ..

**Comment by jimy-byerley** [comment] 2021-03-14 21:39
We can also anticipate that issue to appear on cython extension types that contain fields typed `object` when the extension type instance is created using `__new__` that leaves all fields null (thus not None)

**Comment by da-woods** [comment] 2021-03-14 21:54
> We can also anticipate that issue to appear on cython extension types that contain fields typed `object` when the extension type instance is created using `__new__` that leaves all fields null (thus not None as when cython initialize it)

No - that doesn't happen. Extension type attributes are automatically initialized to `None` in `tp_new`

> Would it make sense that Py_buffer.obj would be typed as PyObject* as it would be in any user-defined C-structure ?
Or eventually to have Pyx_DECREF check for possible NULL pointers ?

The disadvantage of typing it as `PyObject*` is that the standard user-usecase inside `__getbuffer__` would then require manual reference counting (and break existing code). `XDECREF` might be better - as far as I'm aware this is the only place Cython uses an `object` in a struct.

-------------------

I think you could get away with defining a small C helper function to do the assigment

```
# untested
cdef extern from *:
    """
    void assign_buffer_obj(Py_Buffer* buf, PyObject* o) {
        Py_INCREF(o);
        buf->obj = o;
    }
    """
    void assign_buffer_obj(Py_Buffer* buf, object o)
```

I still think it'd be better not to be manually assigning buffer fields, but I'll take your word that you don't want to do that.

**Comment by jimy-byerley** [comment] 2021-03-15 07:43
I came to the same conclusion for the C function ;)
thanks for that piece it's nice to have it inside my pyx file.
I just tried and it works ! still I feel strange to use a helper just to set a value.

> I still think it'd be better not to be manually assigning buffer fields,

I'm doing so for the sakes of memory safety:  
when the Py_buffer is released, the buffer provider __releasebuffer__ method will acknowledge that it can now free the pointed memory. To avoid that, I'm try to keep the Py_buffer alive as long as I use the memory pointed. 
So as the arrayview has to contain that structure, I thought it would be better to use it as the arrayview ptr, which must be able to be set to whatever pointer and length inside the buffer ....

Do you have a better option ?

**Comment by da-woods** [comment] 2021-03-15 18:33
My alternative suggestion was to only modify the `Py_Buffer` that's part of your class. Thus

```
def build_wrapped(buffer):
    if not PyObject_CheckBuffer(buffer):
		raise TypeError('the input object must support the buffer protocol')
    cdef WrapperClass wrapped = WrapperClass.__new__(WrapperClass)
    PyObject_GetBuffer(buffer, &wrapped.view, PyBUF_SIMPLE)
    return wrapped
```

There may be other issues that I'm missing, in which case I really don't have any suggestions

**Comment by jimy-byerley** [comment] 2021-03-15 20:25
Okay, got it ^^
Well thanks for your help, [my module](https://github.com/jimy-byerley/arrex/blob/main/arrex/_arrex.pyx) is now working :+1:

**Comment by scoder** [comment] 2021-04-05 18:34
Closing. It doesn't feel like there is something Cython should do differently here.

**Closed by scoder** 2021-04-05 18:34 UTC
Labels: R: wontfix
