### ISSUE TITLE
Python `bytearray` not accepted for Cython `bytes` argument

### ISSUE THREAD

**Issue by Flameeyes** [cython/cython#3488] opened 2020-04-04 13:52 UTC
This seems like a mistake, as Python's `bytearray` is a strict superset of Python's `bytes` — so when accepting a `bytes` argument, I can't think of a good reason not to accept a `bytearray` object, but right now this fails:

```
# iscsi.pyx

cdef class Task:
    cdef scsi_task *_task

    def __init__(self, bytes cdb, scsi_xfer_dir direction, size_t xferlen):
        self._task = scsi_create_task(len(cdb), cdb, direction, xferlen)

    @property
    def status(self):
        return scsi_task_get_status(self._task, NULL)
```

```
# iscsi_test.py
class TaskTest(unittest.TestCase):
    def test_bytearray(self):
        task = iscsi.Task(
            bytearray(b"\x12\x00\x00\x00\x60\x00"), iscsi.SCSI_XFER_READ, 96
        )
        self.assertIsNotNone(task)
```

Output:

```
self = <tests.iscsi_test.TaskTest testMethod=test_bytearray>

    def test_bytearray(self):
>       task = iscsi.Task(
            bytearray(b"\x12\x00\x00\x00\x60\x00"), iscsi.SCSI_XFER_READ, 96
        )
E       TypeError: Argument 'cdb' has incorrect type (expected bytes, got bytearray)

tests/iscsi_test.py:28: TypeError
```

**Comment by da-woods** [comment] 2020-04-04 14:49
This looks correct to me:

```
>>> isinstance(bytearray(), bytes)
False
```

I'd have thought there's two options:
1. don't type it, in which case Python duck-typing solves your problems.
2. Type it using a const memoryview, which'll accept both: `const unsigned char[::1] cdb`

**Comment by Flameeyes** [comment] 2020-04-04 14:58
I guess that part that confuses me is that this is unlike the way Python's own typing works (with both mypy and pytype):

```
$ cat example.py
def foo(b: bytes):
    return b

foo(b'')
foo(bytearray(b''))
foo('')
$ mypy example.py 
example.py:6: error: Argument 1 to "foo" has incompatible type "str"; expected "bytes"
Found 1 error in 1 file (checked 1 source file)
```

When typing with PEP484 `bytes` accept both

**Comment by da-woods** [comment] 2020-04-04 15:13
If you search for "mypy bytearray" or similar it looks like they've taken the deliberate decision to accept this because they feel the Python interface is sufficiently similar even though it isn't strictly true.

Cython is using the C interface where the two types aren't the same and so it would break useful optimizations if Cython accepted this. I'm reasonably sure more people use Cython for the useful optimizations than as a static type-checker.

**Comment by Flameeyes** [comment] 2020-04-04 15:56
Fair point. Although I think that the mypy implementation is currently redefining `bytes` to the buffer protocol, but that's also a different topic here.

Is it okay if I reuse this issue to add notes to the documentation about this?

**Comment by da-woods** [comment] 2020-04-04 16:04
It looks like there's already something to this effect in the documentation:

https://cython.readthedocs.io/en/latest/src/tutorial/strings.html#accepting-strings-from-python-code

> In the case that the API only deals with byte strings, i.e. binary data or encoded text, it is best not to type the input argument as something like bytes, because that would restrict the allowed input to exactly that type and exclude both subtypes and other kinds of byte containers, e.g. bytearray objects or memory views.

The challenge is always to find the place in the documentation where the information will be seen might the right people who need to see it. I'm sure improvements to the documentation are welcome (although I won't be the one deciding if they're accepted)

**Comment by Flameeyes** [comment] 2020-04-04 16:06
Thanks for the pointer! Indeed I have skipped over that paragraph because of the "strings" in the title, and missed that part :)

I guess I'll have a think through of how to make it more explicit.

**Comment by scoder** [comment] 2020-04-14 18:21
I'll close this ticket since it works as designed. Feel free to send a PR for the docs.

**Closed by scoder** 2020-04-14 18:21 UTC
