### ISSUE TITLE
pxd files not found

### ISSUE THREAD

**Issue by skoudoro** [cython/cython#2843] opened 2019-02-14 15:32 UTC
Hi Cython Devs!

Since #2836 has been merged, we have an issue in our Travis build. All ours `*.pxd` are not found as you can see [here](https://travis-ci.org/nipy/dipy/jobs/488560118#L1412). 

What should I update on my [setup.py](https://github.com/nipy/dipy/blob/master/setup.py) to fix the issue? Why does it not find our `includes` directories?

Thanks for your feedback!

**Comment by scoder** [comment] 2019-02-15 13:21
My guess is that this is not related to #2836 but to #2796. If so, either set `language_level=2`, or fix up your code to work with Python 3 semantics, such as absolute imports (which I would always recommend).

I'm also a bit surprised about [the source](https://travis-ci.org/nipy/dipy/jobs/488560118#L635) that your build uses for Cython. Is this a bleeding edge integration build?

In any case, closing this ticket since it is not a bug.

**Closed by scoder** 2019-02-15 13:21 UTC
Labels: support question

**Comment by skoudoro** [comment] 2019-02-15 16:02
Thank you for this information @scoder, It seems that we forgot some relative path. 

> I'm also a bit surprised about [the source](https://travis-ci.org/nipy/dipy/jobs/488560118#L635) that your build uses for Cython

For one of our Travis matrix, We use this server to anticipate future release error. [This project](https://github.com/MacPython) builds and upload future wheels from different projects.
