### ISSUE TITLE
Cython does not include implicit namespace packages (PEP 420)

### ISSUE THREAD

**Issue by samufi** [cython/cython#3301] opened 2020-01-02 18:12 UTC
**Description**

When cimporting extensions from external packages, cython considers only folders that contain an `__init__.*` file. Hence, cython does not search implicit namespace packages, i.e. superfolders of packages, as described in [PEP 420](https://www.python.org/dev/peps/pep-0420/). 

**Tested cython version**

Cython 0.29.15 with Python 3.7 on Windows 10 x64.

**Steps to reproduce**

Create a namespace package with the following structure:

	├── nsp
	│   └── A
	|       ├── extension.pxd
	|       ├── extension.pyx
	│       └── __init__.py
	└── setup.py

whereby `nsp` is the namespace package and `A` is the actual package. Try `cimport nsp.A.extension` in any other cython file after installing `nsp.A`. You will obtain an error indicating that `extension.pxd` has not been found (see also [here](https://stackoverflow.com/questions/59545750/cython-c-level-interface-of-package-pxd-files-are-not-found)).

**Workaround**

Create an empty file `__init__.pxd` in the folder `nsp`. This file should be ignored by regular python, as it is not a `*.py` file, but allows cython to classify the folder `nsp` as package.

**Steps to fix**

Change the mechanism that determines whether a file name describes a package. For example, change the method `is_package_dir` in `Utils.py` to recursively check subdirectories.

**Comment by CnlPepper** [comment] 2020-01-06 10:40
Hello, I fixed this for Cython 3. See #2918. It would be useful if it were back ported to 0.29.x, but unfortunately I have no time at present.

**Comment by scoder** [comment] 2020-01-24 09:49
Duplicate of #2918.

**Closed by scoder** 2020-01-24 09:49 UTC
