### ISSUE TITLE
[BUG] Posix `time_t` isn't always `long`

### ISSUE THREAD

**Issue by kukrimate** [cython/cython#6142] opened 2024-04-11 14:02 UTC
### Describe the bug

Cython/Includes/posix/types.pxd hard-codes time_t as long, which isn't correct on 32-bit Linux using 64-bit time_t.

This results in an incorrect struct stat layout specified by Cython/Includes/posix/stat.pxd, leading to much sadness, undefined behavior and broken programs.

**Comment by scoder** [comment] 2024-04-11 14:32
Thanks for the report. Since these are `extern` definitions, Cython does not use them directly but only the declared typedef names, i.e. `time_t` in this case, and leaves the rest to the C compiler, which sees the correct, platform-specific definitions.

Could you clarify where exactly this hurts? Do you have short a code example that exposes this?

**Comment by kukrimate** [comment] 2024-04-11 15:15
@scoder Sorry I don't have a reduced example currently, but I can try producing one if desired.

The failure I was seeing in Ubuntu, which now switched to 64-bit time_t on 32-bit ARM is pyfuse3, which seems to rely on the above referred to struct stat definition.

It reads struct stat's incorrectly unless I patch cython to use time_t as long long on armhf

**Comment by scoder** [comment] 2024-04-12 08:23
The error that you see might actually be due to code in pyfuse3, not Cython. They define access macros that explicitly return `long`:
```cython
cdef extern from "macros.c" nogil:
    long GET_BIRTHTIME(struct_stat* buf)
    long GET_ATIME_NS(struct_stat* buf)
    long GET_CTIME_NS(struct_stat* buf)
    long GET_MTIME_NS(struct_stat* buf)
    long GET_BIRTHTIME_NS(struct_stat* buf)
```
https://github.com/libfuse/pyfuse3/blob/9cd9699a8c2f4a83f5228feb1211585eaf49a621/src/pyfuse3/macros.pxd#L14-L19
This makes Cython generate code that uses `long` internally, e.g. for temporary variables.

That said, `long long` seems a better typedef for `time_t`, so I'll change the declaration in Cython. This probably has no direct impact on pyfuse3, though.

**Comment by scoder** [comment] 2024-04-12 08:44
> That said, `long long` seems a better typedef for `time_t`

Hmm. I take that back. The comment at the top of `posix/types.pxd` actually suggests that we might end up with a (slight) performance and usability regression if we replace `long` by `long long`, due to generally larger types being handled and potential changes to the conversion functions being used.
https://github.com/cython/cython/blob/16994b9df3461b1a6f4e5971ab8a7b72f2a4b006/Cython/Includes/posix/types.pxd#L1-L11

So, not sure what to do here. The declarations are actually ok and work, but the question is what users expect. If they want to be platform independent, they need to either use `time_t` and friends in their code, or use `long long` to be on the safe side.

To me, it seems best to use `time_t` also in user code. That's what the typedef is there for, and it's explicitly marked as platform specific in the Posix specs. Relying on it being either `long` or `long long` seems to produce more problems than it solves.

**Comment by kukrimate** [comment] 2024-04-12 10:07
long long is also problematic because some platforms (i386) on some distros still use 32-bit time_t but `long long` is still 64-bit on those platforms, so I don't think that `long long` is an universally valid solution.

**Comment by scoder** [comment] 2024-04-12 11:38
Anyway, could you please report the issue to pyfuse3, so that they can solve it on their side?

**Comment by kukrimate** [comment] 2024-04-12 12:43
I am not entirely sure what is the fix for pyfuse3 here? To not use the the cython exported struct_stat definition?

**Comment by kukrimate** [comment] 2024-04-12 12:48
So do you believe this is only related to the wrong return types of the pyfuse3 macros?

Is the struct defined in Cython/Includes/posix/stat.pxd never used as a layout for accessing platform provided struct stats?

My errors seems to have went away by changing the cython time_t type without touching pyfuse3 yesterday.

**Comment by scoder** [comment] 2024-04-12 15:35
>So do you believe this is only related to the wrong return types of the pyfuse3 macros?

No, I only saw the wrong definitions and considered them a clear source of bugs. I did not validate that they actually have a problematic effect in the current implementation.


>Is the struct defined in Cython/Includes/posix/stat.pxd never used as a layout for accessing platform provided struct stats?

Struct access is always resolved at C compile time, which sees the platform specific definition. Cython does not even need to know all fields in the struct, it's happy if you declare those that the code uses.


>My errors seems to have went away by changing the cython time_t type without touching pyfuse3 yesterday.

I cannot comment on this because I do not know exactly how pyfuse3 uses the declarations.

**Comment by scoder** [comment] 2024-08-05 12:48
Can we close this ticket or is there anything that we can realistically do? It's still unclear whether this is an issue in Cython at all.

**Closed** 2024-08-14 08:40 UTC
Labels: defect, Library
