### ISSUE TITLE
Provide public APIs to get parse tree/syntax errors

### ISSUE THREAD

**Issue by fabioz** [cython/cython#2592] opened 2018-09-03 15:47 UTC
This is a feature request to provide an API in cython which provides users a way of getting the parse tree (AST) as well as syntax errors for cython files.

Ideally it'd be a call where the contents are passed (to deal with working files) and a syntax error is raised or the generated AST is returned.

**Comment by scoder** [comment] 2018-09-03 17:13
Sounds good to me. PR welcome.

Look at the `TreeFragment` class. It's not designed as an external API, but it comes very close to what you want.

**Comment by scoder** [comment] 2018-12-02 17:49
Closing as duplicate of #1628.

**Closed by scoder** 2018-12-02 17:49 UTC
