### ISSUE TITLE
Notes on profiling on Python 3.12+

### ISSUE THREAD

**Issue by da-woods** [cython/cython#5813] opened 2023-11-11 16:05 UTC
### Describe your issue

Profiling on Py3.12+ is currently broken. Here are my notes from looking into it:

* `PyEval_SetProfile` is now "legacy". It still works, and I believe Cython would still interact correctly with it if it were used. However, the standard library profile modules don't use it.
* The current preferred way is via [`sys.monitoring`](https://docs.python.org/3/library/sys.monitoring.html#module-sys.monitoring), and this is what profile/cProfile do.
* `PyEval_SetProfile` sets up functions using the new "monitoring" approach, however, things that use the new "monitoring" approach don't trigger the old `PyEval_SetProfile` way. Therefore, if we want to interact with all profiling tools we really need to use the new "monitoring" approach.
* I think the right thing to do would be to call [`_Py_call_instrumentation`](https://github.com/python/cpython/blob/fa84e5fe0a3bd8e77c33b20867d71ac6bee270f9/Python/instrumentation.c#L1035C1) (or something similar). Unfortunately these are internal symbols so fail at the link stage (even if include the internal headers).
* There doesn't seem to be an easy way to check if profiling is enabled. However, `_Py_call_instrumentation` looks to return very quickly if it isn't, so I think that's OK.
* The linking errors are largely where I got stuck - there doesn't seem to be any accessible way to trigger a profiling event manually.

**Comment by scoder** [comment] 2023-11-11 19:19
Thank you for the investigations, @da-woods.

So, basically, the monitoring [PEP-669](https://peps.python.org/pep-0669/) turned something that was relatively simple to use from C into something hugely complicated that entirely lacks a C-API and was so locked down that it is only partly accessible even from Python. I'm not even sure yet that it would be enough to copy the event signalling code from CPython here, that also looks impressively complex, fills some 300-400 lines of C code, and uses CPython internals that we'd probably not all find exposed and would need to work around as well. At least figuring out the currently registered tools that need to be notified can be done in "have a coffee" time through Python code.

Designing an event signalling mechanism that prevents users from signalling events is not entirely free of humour. :]

I guess we can give up on Python 3.12 and make sure the internal CPython functions become (or gain) a public C-API in 3.13. But let's see if there's any valuable input on that from the CPython side.

@markshannon @vstinner

**Comment by scoder** [comment] 2023-11-11 21:15
This issue was first reported in https://github.com/cython/cython/issues/5470

**Comment by scoder** [comment] 2023-11-12 08:29
I created https://github.com/python/cpython/issues/111997 for designing a new signalling C-API in CPython.

Closing as a duplicate of #5470.

**Closed by scoder** 2023-11-12 08:29 UTC
