### ISSUE TITLE
A number of warning messages during docs make build procedure

### ISSUE THREAD

**Issue by stefanos82** [cython/cython#6071] opened 2024-03-13 11:14 UTC
### Describe your issue

I face more or less the same issue as #4217 while I attempt to generate documentation for offline use and would like to know whether there's a workaround to solve this problem.

```shell
WARNING: unknown config value 'latex_paper_size' in override, ignoring
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output... 
building [singlehtml]: all documents
updating environment: [new config] 62 added, 0 changed, 0 removed
reading sources... [100%] src/userguide/wrapping_CPlusPlus
/home/stefanos/tmp/repos/cython/docs/src/tutorial/embedding.rst:175: WARNING: Title underline too short.

Problems with multiprocessing and pickle
---------------------------------------
/home/stefanos/tmp/repos/cython/docs/src/tutorial/embedding.rst:175: WARNING: Title underline too short.

Problems with multiprocessing and pickle
---------------------------------------
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/stefanos/tmp/repos/cython/docs/src/reference/interfacing_with_other_code.rst: WARNING: document isn't included in any toctree
/home/stefanos/tmp/repos/cython/docs/src/reference/limitations.rst: WARNING: document isn't included in any toctree
/home/stefanos/tmp/repos/cython/docs/src/reference/special_mention.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
assembling single document... src/quickstart/index src/quickstart/overview src/quickstart/install src/quickstart/build src/quickstart/cythonize src/tutorial/index src/tutorial/cython_tutorial src/tutorial/external src/tutorial/clibraries src/tutorial/cdef_classes src/tutorial/pxd_files src/tutorial/caveats src/tutorial/profiling_tutorial src/tutorial/strings src/tutorial/memory_allocation src/tutorial/embedding src/tutorial/pure src/tutorial/numpy src/tutorial/array src/tutorial/parallelization src/tutorial/readings src/tutorial/related_work src/tutorial/appendix src/userguide/index src/userguide/language_basics src/userguide/extension_types src/userguide/special_methods src/userguide/sharing_declarations src/userguide/external_C_code src/userguide/source_files_and_compilation src/userguide/early_binding_for_speed src/userguide/wrapping_CPlusPlus src/userguide/fusedtypes src/userguide/pypy src/userguide/migrating_to_cy30 src/userguide/limitations src/userguide/pyrex_differences src/userguide/memoryviews src/userguide/buffer src/userguide/parallelism src/userguide/debugging src/userguide/numpy_tutorial src/userguide/numpy_ufuncs src/userguide/numpy_pythran src/userguide/nogil src/userguide/troubleshooting src/userguide/faq src/userguide/glossary src/reference/index src/reference/compilation src/reference/special_methods_table CONTRIBUTING src/changes /home/stefanos/tmp/repos/cython/docs/src/tutorial/clibraries.rst:765: WARNING: Unparseable C cross-reference: 'void*'                                       
Invalid C declaration: Expected identifier in nested name, got keyword: void [error at 4]                                                                                                      
  void*                                                                                                                                                                                        
  ----^                                                                                                                                                                                        
/home/stefanos/tmp/repos/cython/docs/src/tutorial/clibraries.rst:839: WARNING: Unparseable C cross-reference: 'void*'
Invalid C declaration: Expected identifier in nested name, got keyword: void [error at 4]                                                                                                      
  void*                                                                                                                                                                                        
  ----^                                                                                                                                                                                        
/home/stefanos/tmp/repos/cython/docs/src/tutorial/clibraries.rst:839: WARNING: Unparseable C cross-reference: 'void*'
Invalid C declaration: Expected identifier in nested name, got keyword: void [error at 4]                                                                                                      
  void*                                                                                                                                                                                        
  ----^                                                                                                                                                                                        
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:169: WARNING: Unparseable C cross-reference: 'char*'
Invalid C declaration: Expected identifier in nested name, got keyword: char [error at 4]                                                                                                      
  char*                                                                                                                                                                                        
  ----^                                                                                                                                                                                        
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:174: WARNING: Unparseable C cross-reference: 'char*'
Invalid C declaration: Expected identifier in nested name, got keyword: char [error at 4]                                                                                                      
  char*                                                                                                                                                                                        
  ----^                                                                                                                                                                                        
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:328: WARNING: Unparseable C cross-reference: 'char*'
Invalid C declaration: Expected identifier in nested name, got keyword: char [error at 4]                                                                                                      
  char*                                                                                                                                                                                        
  ----^                                                                                                                                                                                        
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:352: WARNING: Unparseable C cross-reference: 'std::string'
Invalid C declaration: Expected end of definition. [error at 3]                                                                                                                                
  std::string                                                                                                                                                                                  
  ---^                                                                                                                                                                                         
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:481: WARNING: Unparseable C cross-reference: 'char'
Invalid C declaration: Expected identifier in nested name, got keyword: char [error at 4]                                                                                                      
  char                                                                                                                                                                                         
  ----^                                                                                                                                                                                        
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:495: WARNING: Unparseable C cross-reference: 'char'
Invalid C declaration: Expected identifier in nested name, got keyword: char [error at 4]                                                                                                      
  char                                                                                                                                                                                         
  ----^                                                                                                                                                                                        
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:495: WARNING: Unparseable C cross-reference: 'char'
Invalid C declaration: Expected identifier in nested name, got keyword: char [error at 4]                                                                                                      
  char                                                                                                                                                                                         
  ----^                                                                                                                                                                                        
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:513: WARNING: Unparseable C cross-reference: 'char'
Invalid C declaration: Expected identifier in nested name, got keyword: char [error at 4]                                                                                                      
  char                                                                                                                                                                                         
  ----^                                                                                                                                                                                        
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:513: WARNING: Unparseable C cross-reference: 'unsigned char'
Invalid C declaration: Expected identifier in nested name, got keyword: unsigned [error at 8]                                                                                                  
  unsigned char                                                                                                                                                                                
  --------^                                                                                                                                                                                    
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:537: WARNING: Unparseable C cross-reference: 'long'
Invalid C declaration: Expected identifier in nested name, got keyword: long [error at 4]                                                                                                      
  long                                                                                                                                                                                         
  ----^                                                                                                                                                                                        
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:537: WARNING: Unparseable C cross-reference: 'unsigned long'
Invalid C declaration: Expected identifier in nested name, got keyword: unsigned [error at 8]                                                                                                  
  unsigned long                                                                                                                                                                                
  --------^                                                                                                                                                                                    
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:537: WARNING: Unparseable C cross-reference: 'int'
Invalid C declaration: Expected identifier in nested name, got keyword: int [error at 3]                                                                                                       
  int                                                                                                                                                                                          
  ---^                                                                                                                                                                                         
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:618: WARNING: Unparseable C cross-reference: 'char*'
Invalid C declaration: Expected identifier in nested name, got keyword: char [error at 4]                                                                                                      
  char*                                                                                                                                                                                        
  ----^                                                                                                                                                                                        
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:657: WARNING: Unparseable C cross-reference: 'Py_UNICODE*'
Invalid C declaration: Expected end of definition. [error at 10]                                                                                                                               
  Py_UNICODE*                                                                                                                                                                                  
  ----------^                                                                                                                                                                                  
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:667: WARNING: Unparseable C cross-reference: 'wchar_t*'
Invalid C declaration: Expected end of definition. [error at 7]                                                                                                                                
  wchar_t*                                                                                                                                                                                     
  -------^                                                                                                                                                                                     
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:677: WARNING: Unparseable C cross-reference: 'Py_UNICODE*'
Invalid C declaration: Expected end of definition. [error at 10]                                                                                                                               
  Py_UNICODE*                                                                                                                                                                                  
  ----------^                                                                                                                                                                                  
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:677: WARNING: Unparseable C cross-reference: 'char*'
Invalid C declaration: Expected identifier in nested name, got keyword: char [error at 4]                                                                                                      
  char*                                                                                                                                                                                        
  ----^                                                                                                                                                                                        
/home/stefanos/tmp/repos/cython/docs/src/tutorial/strings.rst:683: WARNING: Unparseable C cross-reference: 'Py_UNICODE*'
Invalid C declaration: Expected end of definition. [error at 10]                                                                                                                               
  Py_UNICODE*                                                                                                                                                                                  
  ----------^                                                                                                                                                                                  
/home/stefanos/tmp/repos/cython/docs/src/tutorial/pure.rst:226: WARNING: undefined label: '<cython_and_gil>'
/home/stefanos/tmp/repos/cython/docs/src/userguide/language_basics.rst:604: WARNING: unknown keyword: 'None'
/home/stefanos/tmp/repos/cython/docs/src/userguide/language_basics.rst:604: WARNING: unknown keyword: 'False'
/home/stefanos/tmp/repos/cython/docs/src/userguide/language_basics.rst:604: WARNING: unknown keyword: 'NULL'
/home/stefanos/tmp/repos/cython/docs/src/userguide/external_C_code.rst:98: WARNING: Unparseable C cross-reference: 'int'
Invalid C declaration: Expected identifier in nested name, got keyword: int [error at 3]                                                                                                       
  int                                                                                                                                                                                          
  ---^                                                                                                                                                                                         
/home/stefanos/tmp/repos/cython/docs/src/userguide/external_C_code.rst:98: WARNING: Unparseable C cross-reference: 'int'
Invalid C declaration: Expected identifier in nested name, got keyword: int [error at 3]                                                                                                       
  int                                                                                                                                                                                          
  ---^                                                                                                                                                                                         
/home/stefanos/tmp/repos/cython/docs/src/userguide/wrapping_CPlusPlus.rst:591: WARNING: unknown keyword: 'enum class'
/home/stefanos/tmp/repos/cython/docs/src/userguide/pypy.rst:66: WARNING: Unparseable C cross-reference: 'char*'
Invalid C declaration: Expected identifier in nested name, got keyword: char [error at 4]                                                                                                      
  char*                                                                                                                                                                                        
  ----^                                                                                            
```

Is it a buggy behavior?

Please advice.

Regards,

Stefanos

P.S.: By the way, is there a particular reason that the official documentation from https://readthedocs.org/projects/cython/downloads/ is not available?

**Comment by da-woods** [comment] 2024-03-13 19:35
Closing as a duplicate of #4217 since I don't see why we need a second issue.

Yes ideally we'd like it to have no warnings. However, warnings shouldn't prevent you from building it so I don't think a workaround is really needed.

PR welcome if you can fix some/all of the warnings

**Closed by da-woods** 2024-03-13 19:35 UTC

**Comment by stefanos82** [comment] 2024-03-13 19:54
The issue with the warnings or any other undiscovered behavior is that code sections that demonstrate a Python or Cython syntax are actually empty and cannot follow the logic of the page I'm currently reading; that is not the case with the official documentation though, only with my local build.

**Comment by da-woods** [comment] 2024-03-14 07:49
> that code sections that demonstrate a Python or Cython syntax are actually empty

That sounds like you might be missing the sphinx-tabs plugin (or have a different version than we use)?

https://github.com/cython/cython/blob/master/doc-requirements.txt is our requirements file to build the docs, so you could create a venv with that and you'd be using exactly the same versions as us.

**Comment by stefanos82** [comment] 2024-03-14 09:10
> > that code sections that demonstrate a Python or Cython syntax are actually empty
> 
> That sounds like you might be missing the sphinx-tabs plugin (or have a different version than we use)?
> 
> https://github.com/cython/cython/blob/master/doc-requirements.txt is our requirements file to build the docs, so you could create a venv with that and you'd be using exactly the same versions as us.

That's exactly what I did by following the instructions from https://github.com/cython/cython/blob/master/docs/README.md and of course I have `sphinx-tabs` installed as it's already included in `doc-requirements.txt` which is version `sphinx-tabs==3.4.4`.

**Comment by da-woods** [comment] 2024-03-14 18:26
If I build "singlehtml" I can reproduce your issue with the missing code examples although everything seems to work fine for me building "html".

I still don't think it's related to the warnings you see - it'll be something to do with `sphinx-tabs` (but I don't know what).

Feel free to create an issue for "singlehtml doesn't work". I'm not sure how to debug it personally though.

**Comment by stefanos82** [comment] 2024-03-14 18:38
The issue is not only with `singlehtml`, but with all options.

I have tested it with `html`, `singlehtml`, and `epub`; the result is always the same as I have already shared above.
