### ISSUE TITLE
"SystemError: Bad call flags in _PyMethodDef_RawFastCallDict" from atexit.register callback on Python 3.7.5 - 3.7.7 on macOS

### ISSUE THREAD

**Issue by wesm** [cython/cython#3572] opened 2020-05-04 17:29 UTC
Weird issue we're trying to understand 

https://issues.apache.org/jira/browse/ARROW-8684

On Python 3.7.5 and higher (but not 3.7.4 and lower, it seems) on macOS, a Cython extension that uses `atexit.register` fails with the following exception

```
 >>> import pyarrow
>>> exit()
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
{{ File "pyarrow/types.pxi", line 2638, in pyarrow.lib._unregister_py_extension_types}}
SystemError: Bad call flags in _PyMethodDef_RawFastCallDict. METH_OLDARGS is no longer supported!
```

We used Cython 0.29.17 to produce the binaries. There instructions for reproducing in the JIRA issue -- I can see if I can make a more minimal reproducer that doesn't depend on building pyarrow

**Comment by scoder** [comment] 2020-05-04 18:17
Could be due to the `METH_FASTCALL` flag, maybe? Cython 0.29.x doesn't use it for its own functions, so I wonder how a CPython function ends up seeing that flag.

Or, since this is running at exit time, i might also be some type/object cleanup issue, I don't know.

Would be good to know whether it is Cython _calling_ a function on this failure or a Cython function being called. But since Cython doesn't use the `_PyMethodDef_RawFastCallDict` function itself, it seems more like it's a call coming from Python.

**Comment by scoder** [comment] 2020-05-05 13:44
[This CPython change](https://github.com/python/cpython/commit/6a12676b1910d52c85561bdf4f1e20aa13fc8f46) would make it easier to debug, but it won't be released before Py 3.7.8 in June. :-/

The only CPython change that I can see in that corner is https://github.com/python/cpython/commit/d092caf096fa48baadfc0900792206bb5aa0192d. It deals with a refcounting issue, so might be related – or not, can't say.

**Comment by pitrou** [comment] 2020-05-06 10:15
For the record, the code in question is here:
https://github.com/apache/arrow/blob/68475dd8eafec8e51711ff69070a872c06d01714/python/pyarrow/types.pxi#L2638

Note the function being called from within the `atexit` handler is itself a Cython-defined Python function:
https://github.com/apache/arrow/blob/68475dd8eafec8e51711ff69070a872c06d01714/python/pyarrow/types.pxi#L820

**Comment by pitrou** [comment] 2020-05-06 10:17
I also wasn't able to find any change between Python 3.7.4 and 3.7.5 that seemed related to this issue (neither in the `atexit` module, nor in `Objects/call.c`).

**Comment by pitrou** [comment] 2020-05-06 10:21
@wesm Does the following work or crash for you?
```python
>>> import pyarrow as pa                                                                                                                                                   
>>> pa.unregister_extension_type("arrow.py_extension_type")
```

**Comment by kszucs** [comment] 2020-05-06 11:49
```python
Python 3.7.5 (default, Oct 25 2019, 10:52:18)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow as pa
>>> pa.unregister_extension_type("arrow.py_extension_type")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: Bad call flags in _PyMethodDef_RawFastCallKeywords. METH_OLDARGS is no longer supported!
```

I'm only able to reproduce it by installing the wheel, building pyarrow locally on python 3.7.5 works fine (the wheel is built on [3.7.5](https://travis-ci.org/github/ursa-labs/crossbow/builds/683697356#L3422))

**Comment by pitrou** [comment] 2020-05-06 11:51
Do the conda-forge packages work fine too?

**Comment by pitrou** [comment] 2020-05-06 11:53
Also, perhaps you can put a gdb breakpoint on `__pyx_pf_7pyarrow_3lib_110_unregister_py_extension_types` (I hope the name is the same on macOS).

**Comment by kszucs** [comment] 2020-05-06 11:55
> Do the conda-forge packages work fine too?

Yes.

**Comment by kszucs** [comment] 2020-05-06 12:57
> Also, perhaps you can put a gdb breakpoint on `__pyx_pf_7pyarrow_3lib_110_unregister_py_extension_types` (I hope the name is the same on macOS).

I can't reproduce without the wheels which are built in release mode. Wa can try to produce wheels with debug symbols.

**Comment by scoder** [comment] 2020-05-07 07:03
I prefer building release wheels with `-g1`, which gives readable user side stack traces with a (for me) acceptable size overhead. YMMV.

**Comment by wesm** [comment] 2020-05-12 14:49
We've been trying to track down this issue, which is proving very difficult to reproduce consistently. In this internal Cython function

```
static CYTHON_INLINE PyObject* __Pyx_PyObject_CallOneArg(PyObject *func, PyObject *arg) {
#if CYTHON_FAST_PYCALL
    if (PyFunction_Check(func)) {
        return __Pyx_PyFunction_FastCall(func, &arg, 1);
    }
#endif
    if (likely(PyCFunction_Check(func))) {
        if (likely(PyCFunction_GET_FLAGS(func) & METH_O)) {
            return __Pyx_PyObject_CallMethO(func, arg);
#if CYTHON_FAST_PYCCALL
        } else if (PyCFunction_GET_FLAGS(func) & METH_FASTCALL) {
            return __Pyx_PyCFunction_FastCall(func, &arg, 1);
#endif
        }
    }
    return __Pyx__PyObject_CallOneArg(func, arg);
}
```

the check `PyCFunction_Check(func)` is failing on the Cython-generated pure Python function `unregister_extension_type`, here's the view inside lldb

```
(lldb) p (*func->ob_type)
(_typeobject) $8 = {
  ob_base = {
    ob_base = {
      ob_refcnt = 26
      ob_type = 0x00000001002de288
    }
    ob_size = 0
  }
  tp_name = 0x000000010029eff6 "builtin_function_or_method"
  tp_basicsize = 48
  tp_itemsize = 0
  tp_dealloc = 0x00000001000843e0 (python`meth_dealloc)
  tp_print = 0x0000000000000000
  tp_getattr = 0x0000000000000000
  tp_setattr = 0x0000000000000000
  tp_as_async = 0x0000000000000000
  tp_repr = 0x00000001000844f0 (python`meth_repr)
  tp_as_number = 0x0000000000000000
  tp_as_sequence = 0x0000000000000000
  tp_as_mapping = 0x0000000000000000
  tp_hash = 0x0000000100084580 (python`meth_hash)
  tp_call = 0x000000010002d6d0 (python`PyCFunction_Call)
  tp_str = 0x00000001000a18c0 (python`object_str)
  tp_getattro = 0x0000000100089bb0 (python`PyObject_GenericGetAttr)
  tp_setattro = 0x000000010008ac00 (python`PyObject_GenericSetAttr)
  tp_as_buffer = 0x0000000000000000
  tp_flags = 806912
  tp_doc = 0x0000000000000000
  tp_traverse = 0x0000000100084650 (python`meth_traverse)
  tp_clear = 0x0000000000000000
  tp_richcompare = 0x00000001000846a0 (python`meth_richcompare)
  tp_weaklistoffset = 40
  tp_iter = 0x0000000000000000
  tp_iternext = 0x0000000000000000
  tp_methods = 0x00000001002d9bb0
  tp_members = 0x00000001002d9bf0
  tp_getset = 0x00000001002d9c40
  tp_base = 0x00000001002de0f8
  tp_dict = 0x000000010804a3c0
  tp_descr_get = 0x0000000000000000
  tp_descr_set = 0x0000000000000000
  tp_dictoffset = 0
  tp_init = 0x00000001000a1a30 (python`object_init)
  tp_alloc = 0x00000001000a1af0 (python`PyType_GenericAlloc)
  tp_new = 0x0000000000000000
  tp_free = 0x00000001001e2fd0 (python`PyObject_GC_Del)
  tp_is_gc = 0x0000000000000000
  tp_bases = 0x0000000108045dd0
  tp_mro = 0x000000010804a640
  tp_cache = 0x0000000000000000
  tp_subclasses = 0x0000000000000000
  tp_weaklist = 0x0000000108049770
  tp_del = 0x0000000000000000
  tp_version_tag = 37
  tp_finalize = 0x0000000000000000
```

then `__Pyx__PyObject_CallOneArg` fails when invoking `tp_call`.

**Comment by pitrou** [comment] 2020-05-12 16:02
Culprit is https://github.com/cython/cython/issues/3603

**Comment by scoder** [comment] 2020-05-12 20:56
Closing this as a 'duplicate' of #3603, since that is the clearer ticket.

**Closed** 2020-05-12 20:56 UTC
Labels: R: duplicate
