### ISSUE TITLE
[BUG] Slash+newline mismatch inside multi-line F-string

### ISSUE THREAD

**Issue by wh-timme** [cython/cython#6444] opened 2024-10-23 09:29 UTC
### Describe the bug

'\\\\'+'\n' inside f'''...''' should be interpreted as empty string continuation instead of raw string.

### Code to reproduce the behaviour:

```cython
print(f'''a\
b''')
```

a\\
b

### Expected behaviour

ab

### OS

CentOS 7.9

### Python version

3.8.20

### Cython version

3.0.11

**Comment by da-woods** [comment] 2024-10-23 18:15
Duplicate of https://github.com/cython/cython/issues/6113

**Closed by da-woods** 2024-10-23 18:15 UTC
