### ISSUE TITLE
Using contextlib with cython

### ISSUE THREAD

**Issue by AnishN** [cython/cython#1750] opened 2017-06-24 17:26 UTC
I am interested in using `contextlib` with a `cdef` class in cython in order to nicely wrap some OpenGL code. I had asked [this question](https://stackoverflow.com/questions/44733520/using-contextlib-with-cython/44738561) on stackoverflow. While the workaround I had received worked (using `__enter__` and `__exit__`), 

Here is the test code for `vbo.pyx` that was in that answer for reference:

```
import contextlib

cdef class Vbo:

    def __init__(self):
        pass

    @contextlib.contextmanager
    def bind(self):
        self.do_something()
        try:
            yield
        finally:
            print("Finally")

    def do_something(self):
        print("something")
```

This code works for me if I remove the `cdef` but this should not be necessary. If I use the sample code as is, I get an error message like this when I use that `cdef` class from python: 

```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import vbo
  File "vbo.pyx", line 21, in init vbo (vbo.c:15766)
    @contextlib.contextmanager
  File "C:\Python27\lib\contextlib.py", line 82, in contextmanager
    @wraps(func)
  File "C:\Python27\lib\functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'method_descriptor' object has no attribute '__module__'
```

It appears that this behavior might be a possible regression as this works apparently in cython 0.25.1 and python 3.6.1.  I am using cython 0.25.2 and python 2.7.12.

**Comment by scoder** [comment] 2017-06-24 17:40
Enabling the "binding" directive would probably fix this, i.e. put this comment at the top of your source file:
```# cython: binding=True```
http://docs.cython.org/en/latest/src/reference/compilation.html#compiler-directives

I'm closing this as "not a bug", please reopen if that seems wrong to me, but you're probably best off asking on the Cython users mailing list instead.

**Closed by scoder** 2017-06-24 17:40 UTC
Labels: R: invalid

**Comment by AnishN** [comment] 2017-06-24 20:52
Thanks for pointing me to that page, it is very helpful! Unfortunately, after adding `# cython: binding=True` to the top of the `vbo.pyx`, I now get a different error, which looks like this.

```
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    with v.bind():
  File "C:\Python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
AttributeError: 'GeneratorContextManager' object has no attribute 'next'
```

Any ideas would be appreciated.

**Comment by jdemeyer** [comment] 2017-06-26 10:00
With `binding=True`, you are probably hitting #1724. Can you try Cython master to check if it works now?

**Comment by AnishN** [comment] 2017-07-09 05:26
Didn't realize this question was still being looked at after it got closed! I updated to Cython master using `python setup.py install` (Cython version 0.26b0) and tested out my `vbo.pyx` file. Whatever was done in the new update, it absolutely works and I can now use `contextlib` again instead of [this ugly hack](https://stackoverflow.com/a/44738561/2588654). Thank you!

**Comment by rainwoodman** [comment] 2017-08-10 18:29
Hi, I bumped into this issue and realized the documentation of the 'binding' directive may need some additional explanation by adding an example (such as this case). Reading it twice I still have little clue what 'len' and 'binding to an instance' really means. Thanks!
(actually perhaps all of the directives need more documentation...)

**Comment by scoder** [comment] 2017-08-10 21:40
Is this better? 7d61c7782704237477e883de6bfbfc3526074385
If you have anything to clarify or add, I'd be happy about a pull request.

**Comment by jdemeyer** [comment] 2017-08-11 07:37
Allow me to point to a blogpost of mine which explains some of this: http://opendreamkit.org/2017/06/09/CythonSphinx/
