### ISSUE TITLE
Function returning a struct cannot be declared nogil

### ISSUE THREAD

**Issue by symbolique** [cython/cython#1713] opened 2017-05-24 16:44 UTC
Example:
```cython
cdef struct Structure:
    double x

cdef Structure build() nogil:
    return Structure(0.0)
```

**Comment by robertwb** [comment] 2017-07-09 04:37
The bug is actually due to Structure (0.0) looking like a Python call.

**Comment by c-f-h** [comment] 2018-02-11 15:05
I believe this is a duplicate of #1642.

**Comment by matusvalo** [comment] 2023-12-14 21:12
I am not able to replicate it on master branch anymore (commit https://github.com/cython/cython/commit/0b3c45b59626858a9d6717583429496f50b9f441):

```
$ cat delete.pyx
cdef struct Structure:
    double x

cdef Structure build() nogil:
    return Structure(0.0)

$ cythonize -3fib delete.pyx
[1/1] Cythonizing /Users/matus/dev/cython/test/delete.pyx
performance hint: delete.pyx:4:5: Exception check on 'build' will always require the GIL to be acquired. Declare 'build' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
running build_ext
building 'delete' extension
creating /Users/matus/dev/cython/test/tmpw6ba0rju/Users
creating /Users/matus/dev/cython/test/tmpw6ba0rju/Users/matus
creating /Users/matus/dev/cython/test/tmpw6ba0rju/Users/matus/dev
creating /Users/matus/dev/cython/test/tmpw6ba0rju/Users/matus/dev/cython
creating /Users/matus/dev/cython/test/tmpw6ba0rju/Users/matus/dev/cython/test
clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/matus/dev/cython311/include -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c /Users/matus/dev/cython/test/delete.c -o /Users/matus/dev/cython/test/tmpw6ba0rju/Users/matus/dev/cython/test/delete.o
/Users/matus/dev/cython/test/delete.c:1754:41: warning: unused function '__pyx_f_6delete_build' [-Wunused-function]
static struct __pyx_t_6delete_Structure __pyx_f_6delete_build(void) {
                                        ^
1 warning generated.
clang -bundle -undefined dynamic_lookup /Users/matus/dev/cython/test/tmpw6ba0rju/Users/matus/dev/cython/test/delete.o -o /Users/matus/dev/cython/test/delete.cpython-311-darwin.so
$ python -c 'import delete'
$
```

**Closed** 2023-12-14 21:12 UTC
