### ISSUE TITLE
asyncio.iscoroutinefunction(connect) returns false for Socket.IO Asyncio Client

### ISSUE THREAD

**Issue by Muzzamil1** [cython/cython#3190] opened 2019-10-17 09:56 UTC
Hi!
I was trying to use Socket.IO Asyncio Client with Cython. But
`print(asyncio.iscoroutinefunction(connect))`
returns `false`
https://github.com/miguelgrinberg/python-socketio/issues/363

**Comment by scoder** [comment] 2019-10-18 07:45
Duplicate of #2273.

**Closed by scoder** 2019-10-18 07:45 UTC
Labels: R: duplicate
