### ISSUE TITLE
when release the version of 3.0.0 alpha 7 ?

### ISSUE THREAD

**Issue by sunshineinwater** [cython/cython#4073] opened 2021-03-30 23:52 UTC
when release the version of 3.0.0 alpha 7 ?

**Comment by da-woods** [comment] 2021-03-31 05:51
Duplicate of https://github.com/cython/cython/issues/4022

Probably in the next week or so. But I'm not sure that posting issues about it will speed up the process

**Closed by da-woods** 2021-03-31 05:51 UTC
