### ISSUE TITLE
[ENH] Collapse multiple submodule to one cython extension

### ISSUE THREAD

**Issue by liukangcc** [cython/cython#4289] opened 2021-07-16 08:59 UTC
Collapse multiple submodule to one cython extension: 

![image](https://user-images.githubusercontent.com/44889940/125921974-7655a354-f55f-4d10-b767-d89a4a3a8e56.png)

**Comment by scoder** [comment] 2021-07-16 09:06
duplicate of #2849

**Closed by scoder** 2021-07-16 09:06 UTC
Labels: R: duplicate
