### ISSUE TITLE
How to fix Snappy Library exception during Python to executable conversion on linux based aws-ec2 instance?

### ISSUE THREAD

**Issue by pythonianits** [cython/cython#2911] opened 2019-04-03 07:10 UTC
I am trying to convert my python code to an executable file on ec2-instance. I am successfully able to convert the code into executable using pyinstaller, however when I run the executable, I was getting

**`'Sqlite3, OperationalError: unable to open database file'.`**

Once I changed the uri parameter to the function(connect_to_db) inside

**`"~/snappy-manifolds/database.py"`**

file mentioned in the error. I got another error

**`"SnapPy.PresentationMatrix has not attribute _reduce_cython_".`**

I am using Fastavro, Pandavro for reading and writing into an 'avro' file. However these libraries seem to have some dependencies on Snappy library as it is failing while fetching some data from Snappy library folders. I changed the uri parameter for 'connect_to_db' function defined in

**`"~/snappy-manifolds/database.py"`**

which led me into getting another error:

**`"SnapPy.PresentationMatrix has not attribute _reduce_cython_".`**

I don't know what to do next.

**Error Traceback:**
```
Traceback (most recent call last):
  File "NVS_Main_V2.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/local/SNETACLOUD/svc-sdtm/anaconda3/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "NVS_Utility_Services.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/local/SNETACLOUD/svc-sdtm/anaconda3/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/fastavro/__init__.py", line 48, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/local/SNETACLOUD/svc-sdtm/anaconda3/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/fastavro/write.py", line 2, in <module>
  File "fastavro/_write.pyx", line 578, in init fastavro._write
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/local/SNETACLOUD/svc-sdtm/anaconda3/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/snappy/__init__.py", line 7, in <module>
  File "cython/core/abelian_group.pyx", line 128, in init SnapPy
  AttributeError: type object 'SnapPy.PresentationMatrix' has no attribute 
  '__reduce_cython__'
  [29827] Failed to execute script NVS_Main_V2
```

uri is /home/local/SNETACLOUD/svc-sdtm/anaconda3/lib/python3.6/site-packages/snappy_manifolds/sqlite_files/manifolds.sqlite

**This is the uri that I am currently passing to the connect_to_db function
File "NVS_Utility_Services.py", line 18, in**

**This statement in "NVS_Utility_Services.py" code is "import fastavro"**

Expected result would be that the executable file successfully runs and perform the operation. When I'm running the python code on EC2 instance, it executes successfully but when I convert it into an executable, it breaks giving the error mentioned above

**Comment by scoder** [comment] 2019-04-03 18:01
Looks like a duplicate of #1953.

**Comment by scoder** [comment] 2019-04-05 10:06
In short, ask for a new release of Snappy that is built with Cython 0.28+, preferably 0.29.x (because, why not).

**Closed by scoder** 2019-04-05 10:06 UTC
