### ISSUE TITLE
Cython for python2.7 not support __file__ ?

### ISSUE THREAD

**Issue by toplinuxsir** [cython/cython#3219] opened 2019-10-31 07:58 UTC
Cython for python2.7 not support __file__ ?

When I compile the code with cython
`
print(__file__)
`

when executed, error prone:
 `
__file__ is not defined
`

**Comment by da-woods** [comment] 2019-10-31 12:05
Duplicate of https://github.com/cython/cython/issues/1035; it's supported on later versions of Python.

**Closed** 2019-10-31 20:59 UTC
Labels: R: duplicate
