### ISSUE TITLE
Pickling nested Cython function results in PicklingError

### ISSUE THREAD

**Issue by deatinor** [cython/cython#2758] opened 2018-12-14 12:51 UTC
I have the following code:

    def decorator(func):

        @functools.wraps(func)
        def other_func():
            print('other func')

        return other_func
 
    @decorator
    def func():
        pass

If I try to pickle `func` everything works. However if I compile the module as a Cython extension it fails. Here is the error:

    >>>> pickle.dumps(module.func)

    PicklingError: Can't pickle <cyfunction decorator.<locals>.other_func at 0x102a45a58>: attribute lookup other_func on module failed

The same happens if I use `dill` instead of `pickle`.

Is this an expected behaviour or is it a bug?

**Comment by scoder** [comment] 2018-12-14 13:58
Duplicate of #2584.

**Closed by scoder** 2018-12-14 13:58 UTC
