### ISSUE TITLE
Faster array creation and conversion

### ISSUE THREAD

**Issue by cmpute** [cython/cython#3661] opened 2020-06-02 19:47 UTC
I have question on two kinds operation in cython: array creation and conversion.

## Array creation
Say if I want a function that creates an empty float64 array and return (like numpy.empty), I can do following
```cython
cimport numpy as np
np.import_array()
cdef double[:] empty(int n):
    cdef np.npy_intp[1] dims = [n]
    return np.PyArray_EMPTY(1, dims, np.NPY_DOUBLE, 0)
```
or use cython array
```cython
from cython.view cimport array
cdef double[:] empty(int n):
    return array(shape=(n,), itemsize=sizeof(double), format=b"d")
```

Although the latter one produces more python code according to annotations, the latter one is still faster according to my test. Is there anyway to make the latter one even faster with less python size code? The annoation indicates that many intermediate python variables are created:
```cpp
  __pyx_t_1 = __Pyx_PyDict_NewPresized(3); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 22, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_t_2 = __Pyx_PyInt_From_int(__pyx_v_n1); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 22, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_2);
  __pyx_t_3 = __Pyx_PyInt_From_int(__pyx_v_n2); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 22, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_3);
  __pyx_t_4 = PyTuple_New(2); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 22, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_4);
  __Pyx_GIVEREF(__pyx_t_2);
  PyTuple_SET_ITEM(__pyx_t_4, 0, __pyx_t_2);
  __Pyx_GIVEREF(__pyx_t_3);
  PyTuple_SET_ITEM(__pyx_t_4, 1, __pyx_t_3);
  __pyx_t_2 = 0;
  __pyx_t_3 = 0;
  if (PyDict_SetItem(__pyx_t_1, __pyx_n_s_shape, __pyx_t_4) < 0) __PYX_ERR(0, 22, __pyx_L1_error)
  __Pyx_DECREF(__pyx_t_4); __pyx_t_4 = 0;
  __pyx_t_4 = __Pyx_PyInt_FromSize_t((sizeof(double))); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 22, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_4);
  if (PyDict_SetItem(__pyx_t_1, __pyx_n_s_itemsize, __pyx_t_4) < 0) __PYX_ERR(0, 22, __pyx_L1_error)
  __Pyx_DECREF(__pyx_t_4); __pyx_t_4 = 0;
  if (PyDict_SetItem(__pyx_t_1, __pyx_n_s_format, __pyx_n_b_d) < 0) __PYX_ERR(0, 22, __pyx_L1_error)
  __pyx_t_4 = __Pyx_PyObject_Call(((PyObject *)__pyx_array_type), __pyx_empty_tuple, __pyx_t_1); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 22, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_4);
  __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;
  __pyx_t_5 = __Pyx_PyObject_to_MemoryviewSlice_dsds_double(__pyx_t_4, PyBUF_WRITABLE); if (unlikely(!__pyx_t_5.memview)) __PYX_ERR(0, 22, __pyx_L1_error)
  __Pyx_DECREF(__pyx_t_4); __pyx_t_4 = 0;
  __pyx_v_arr = __pyx_t_5;
  __pyx_t_5.memview = NULL;
  __pyx_t_5.data = NULL;
```
It seems that although the initialization of Cython array is defined with __cinit__, we still cannot directly pass the arguments as C variables (unlike np.PyArray_EMPTY does)

## Array conversion
After dealing with created array, usually we would like to return it to use as numpy array. It seems that the only way will be `np.asarray`, but this will also produces a lot of python code, for example
```
cdef double[:,:,:] matrix = empty(n1, n2, n3)
# some processing
ret = np.asarray(matrix)
```
The line with `np.asarray` produces
```cpp
  __Pyx_GetModuleGlobalName(__pyx_t_34, __pyx_n_s_np); if (unlikely(!__pyx_t_34)) __PYX_ERR(0, 1128, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_34);
  __pyx_t_35 = __Pyx_PyObject_GetAttrStr(__pyx_t_34, __pyx_n_s_asarray); if (unlikely(!__pyx_t_35)) __PYX_ERR(0, 1128, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_35);
  __Pyx_DECREF(__pyx_t_34); __pyx_t_34 = 0;
  __pyx_t_34 = __pyx_memoryview_fromslice(__pyx_v_matrix, 3, (PyObject *(*)(char *)) __pyx_memview_get_double, (int (*)(char *, PyObject *)) __pyx_memview_set_double, 0);; if (unlikely(!__pyx_t_34)) __PYX_ERR(0, 1128, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_34);
  __pyx_t_36 = NULL;
  if (CYTHON_UNPACK_METHODS && unlikely(PyMethod_Check(__pyx_t_35))) {
    __pyx_t_36 = PyMethod_GET_SELF(__pyx_t_35);
    if (likely(__pyx_t_36)) {
      PyObject* function = PyMethod_GET_FUNCTION(__pyx_t_35);
      __Pyx_INCREF(__pyx_t_36);
      __Pyx_INCREF(function);
      __Pyx_DECREF_SET(__pyx_t_35, function);
    }
  }
  __pyx_t_33 = (__pyx_t_36) ? __Pyx_PyObject_Call2Args(__pyx_t_35, __pyx_t_36, __pyx_t_34) : __Pyx_PyObject_CallOneArg(__pyx_t_35, __pyx_t_34);
  __Pyx_XDECREF(__pyx_t_36); __pyx_t_36 = 0;
  __Pyx_DECREF(__pyx_t_34); __pyx_t_34 = 0;
  if (unlikely(!__pyx_t_33)) __PYX_ERR(0, 1128, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_33);
  __Pyx_DECREF(__pyx_t_35); __pyx_t_35 = 0;
  __pyx_v_ret = __pyx_t_33;
  __pyx_t_33 = 0;
```
Is there any better way to avoid these python side code? Or do we need to patch cython to achieve these two optimizations?

**Comment by scoder** [comment] 2020-06-03 04:44
Are you saying that creating a Cython array is faster for you than creating a NumPy array? That contradicts https://github.com/cython/cython/issues/1349, which claims the opposite. Could you back that with benchmark numbers?

I would consider this a duplicate of that ticket, although this one looks more on the caller side than the internal array creation side. For a Cython internal type, that's probably still special enough to consider it part of https://github.com/cython/cython/issues/1349. We might be able to optimise away the keyword arguments in this specific case. Not sure if that's the main issue here, though. Profiling would tell.

Note that „more C code” is not necessarily bad. Cython often generates more code that the C compiler can then optimise away, or that special cases certain likely situations at runtime, such as calling a method. (Which doesn't happen here, but that doesn't hurt much.)

BTW, instead of creating a new NumPy array from a memory view that is already backed by a NumPy array that you created yourself, you could also just return the original NumPy array. But I guess your real world code is more complex than your example here.

We could probably override some NumPy methods and functions with more direct cdef versions, but that should be done on NumPy side since they own the Cython declarations for NumPy now.

**Comment by scoder** [comment] 2020-06-03 09:02
Closing as duplicate of #1349.

**Closed by scoder** 2020-06-03 09:02 UTC
Labels: R: duplicate

**Comment by cmpute** [comment] 2020-06-03 19:31
I didn't find any numbers in that issue, this is my little benchmark @scoder :
`lib.pyx`:
```cython
 
cimport numpy as np
np.import_array()
cdef double[:] empty_np1(int n):
    cdef np.npy_intp[1] dims = [n]
    return np.PyArray_EMPTY(1, dims, np.NPY_DOUBLE, 0)
cdef double[:,:] empty_np2(int n1, int n2):
    cdef np.npy_intp[2] dims = [n1, n2]
    return np.PyArray_EMPTY(2, dims, np.NPY_DOUBLE, 0)

from cython.view cimport array
cdef double[:] empty_cy1(int n):
    return array(shape=(n,), itemsize=sizeof(double), format=b"d")
cdef double[:,:] empty_cy2(int n1, int n2):
    return array(shape=(n1, n2), itemsize=sizeof(double), format=b"d")

def test_np1(int n):
    cdef double[:] data = empty_np1(n)
    return data

def test_np2(int n1, int n2):
    cdef double[:,:] data = empty_np2(n1, n2)
    return data

def test_cy1(int n):
    cdef double[:] data = empty_cy1(n)
    return data

def test_cy2(int n1, int n2):
    cdef double[:,:] data = empty_cy2(n1, n2)
    return data
```
`setup.py`:
```python
 
import numpy as np
from setuptools import setup
from Cython.Build import cythonize

setup(
    name='test',
    ext_modules=cythonize("lib.pyx", include_path=[np.get_include()]),
    include_dirs=[np.get_include()],
    zip_safe=False
)
```
`test.py`:
```cython
import timeit

n = 1000
m = 1000
setup = "from lib import test_np1, test_np2, test_cy1, test_cy2"

print(timeit.timeit(f"test_np1({n})", number=m, setup=setup))
print(timeit.timeit(f"test_cy1({n})", number=m, setup=setup))

print(timeit.timeit(f"test_np2({n}, {n})", number=m, setup=setup))
print(timeit.timeit(f"test_cy2({n}, {n})", number=m, setup=setup))
```

The result on my computer is
```
0.0007574100745841861
0.0005825329571962357
0.0012563359923660755
0.0006479700095951557
```

**Comment by cmpute** [comment] 2020-06-03 19:33
Even if I increase n to `n=10000`, it still seems that cython version is faster
```
0.0007353579858317971
0.000572100980207324
0.007961040013469756
0.006955094053409994
```

For numpy array conversion, I think I will create an issue in Numpy repo, thanks for the info.
