### ISSUE TITLE
pure-python mode: nogil + ccall

### ISSUE THREAD

**Issue by paugier** [cython/cython#3169] opened 2019-10-07 13:57 UTC
This code works fine:
```cython
# cython: language_level=3
import cython

cpdef inline cython.int add(cython.int a, cython.int b) nogil:
    return a + b

def use_add(cython.int n):
    cdef Py_ssize_t i
    cdef cython.int result = 1
    with cython.nogil:
        for i in range(n):
            result = add(result, result)
    return result
```

However, the equivalent code in pure-Python mode does not compile:

```python
# cython: language_level=3
import cython

@cython.ccall
@cython.inline
@cython.returns(cython.int)
@cython.locals(a=cython.int, b=cython.int)
@cython.nogil
def add(a, b):
    return a + b

@cython.locals(n=cython.int, i=Py_ssize_t, result=cython.int)
def use_add(n):
    result = 1
    with cython.nogil:
        for i in range(n):
            result = add(result, result)
    return result
```

And it works if I replace `@cython.ccall` by `@cython.cfunc`. But it is no longer equivalent to the first code.

The error log:
```
Compiling pure_wo_pxd_ccall.py because it changed.
[1/1] Cythonizing pure_wo_pxd_ccall.py

Error compiling Cython file:
------------------------------------------------------------
...
@cython.ccall
@cython.inline
@cython.returns(cython.int)
@cython.locals(a=cython.int, b=cython.int)
@cython.nogil
def add(a, b):
^
------------------------------------------------------------

pure_wo_pxd_ccall.py:10:0: Constructing Python function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
@cython.ccall
@cython.inline
@cython.returns(cython.int)
@cython.locals(a=cython.int, b=cython.int)
@cython.nogil
def add(a, b):
^
------------------------------------------------------------

pure_wo_pxd_ccall.py:10:0: Constructing Python tuple not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
@cython.ccall
@cython.inline
@cython.returns(cython.int)
@cython.locals(a=cython.int, b=cython.int)
@cython.nogil
def add(a, b):
       ^
------------------------------------------------------------

pure_wo_pxd_ccall.py:10:8: Operation not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
@cython.ccall
@cython.inline
@cython.returns(cython.int)
@cython.locals(a=cython.int, b=cython.int)
@cython.nogil
def add(a, b):
          ^
------------------------------------------------------------

pure_wo_pxd_ccall.py:10:11: Operation not allowed without gil

...

  File "/home/users/me/.pyenv/versions/3.7.3/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1096, in cythonize
    cythonize_one(*args)
  File "/home/users/me/.pyenv/versions/3.7.3/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1219, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: pure_wo_pxd_ccall.py

```

Could you please confirm that it is indeed a bug? It would be great to tell where to start to try to fix it.

**Comment by robertwb** [comment] 2019-10-08 04:37
Yes, this is a bug. I'm not sure where the bug is, but it almost looks like it's trying to apply the nogil to the creation of the wrapper and not just the body of the function itself.

**Comment by paugier** [comment] 2019-10-12 21:41
The same bug also happens with pure Python mode with a pxd file:

The Python file:
```python
# cython: language_level=3
import cython

def add(a, b):
    return a + b

def use_add(n):
    result = 1
    with cython.nogil:
        for i in range(n):
            result = add(result, result)
    return result
```

The .pxd file:
```cython
cimport cython
cdef inline int add(int a, int b) nogil

@cython.locals(n=int, i=int, result=int)
cpdef int use_add(int n)
```

This works but if I replace `cdef` by `cpdef`, it does not compile.

**Comment by matusvalo** [comment] 2023-08-08 22:35
It seems that the issue is fixed in master. I am able to compile the reproducer.

**Closed by matusvalo** 2023-08-08 22:35 UTC
