### ISSUE TITLE
[BUG] segfault when calling method after upcast

### ISSUE THREAD

**Issue by saraedum** [cython/cython#4646] opened 2022-02-16 07:43 UTC
In a Python class that inherits from multiple Cython classes we found that sometimes method calls don't work as expected for `cpdef` functions that are overridden in the Python class. This results in the wrong (completely unrelated) functions being called or, as in the example below, a segfault.

**To Reproduce**

```cython
cdef class A:
    cdef f(self): pass

cdef class B(A):
    cpdef g(self):
        print("B")

cdef class C(A):
    cdef A a

class D(B, C):
    def g(self):
        print("D")

def crash(x):
    x.g()
    (<B>x).g()

crash(D())
```

```sh
$ cythonize -a -i crash.pyx
$ python -c 'import crash'
D
segmentation fault
```

**Expected behavior**
We expected this not to segfault.

We understand that multiple inheritance is not always possible so maybe this is not supposed to actually work. However, Python did not complain about a lay-out problem here when creating the type `D`.

**Environment:**
 - OS: Linux
 - Python version 3.10.1
 - Cython version, both 0.29.27 & 3.0.0a10 (as shipped by [conda-forge](https://github.com/conda-forge/cython-feedstock).)

**Comment by da-woods** [comment] 2022-02-16 07:52
I haven't looked in detail yet but I wonder if it's related to https://github.com/cython/cython/issues/4350. It could well have a similar origin (an improperly initialized vtab)

**Comment by mattip** [comment] 2022-02-16 09:27
Maybe also related to #3651?

**Comment by da-woods** [comment] 2022-02-16 19:32
Having looked in more detail `tp_new` for `C` and `A` are called, but not for `B`. Therefore the vtab for `B` is never initialized and so you get a segmentation fault. Therefore it is a duplicate of #4350.

I did have a WIP PR to try to identify this and warn against it. I ran into the problem that we do you similar inheritance patterns in Cython's internal build. I think the PR needed to be a little narrower - this kind of inheritance is sometimes OK (if there is no non-trivial constructor)

**Closed by da-woods** 2022-02-16 19:32 UTC

**Comment by da-woods** [comment] 2022-02-16 19:33
> Maybe also related to https://github.com/cython/cython/issues/3651?

I don't think so here. You are supposed to be able to override a `cpdef` function with a `def` function I believe.
