### ISSUE TITLE
[BUG] const pointer types not parsed correctly when using templated cython declarations

### ISSUE THREAD

**Issue by Blake-Johnson** [cython/cython#5081] opened 2022-10-11 20:27 UTC
### Describe the bug

The cython parser seems to be having issues parsing a const pointer when using a templated cython declaration. When I add template parameters, I get errors complaining about the const syntax. Removing the template parameters or the const keyword seemed to address the error. I was able to validate the const pointer was the issue by adding a new c function that did not return a const pointer and updating the cython declaration to not be const.

A workaround is to declare a ctypedef:
ctypedef const PredictionLog const_PredictionLog 

This seems to avoid the issue by cutting out the white space.

I noticed a couple of other issues that may be related:

- https://issues.apache.org/jira/browse/ARROW-12899
- https://github.com/cython/cython/issues/2211#issuecomment-383650416

Here's the error I was seeing:
Error compiling Cython file:
```
    flume.PCollection[prediction_log.PredictionLog] operator()(
      const string&, const flume.PCollection[string]&) const

  cdef cppclass RunInferencePerModel:
    RunInferencePerModel(vector[bulk_inference_config.Model])
    flume.PCollection[flume.KV[KeyType, vector[shared_ptr[const prediction_log.PredictionLog]]]] operator()[KeyType, InputType] (

                                                               ^
Expected ']', found 'prediction_log'
```

### Code to reproduce the behaviour:

Here was the original c function signature (PTable is a type alias for PCollection<KV<>>. The explicit type was used in the cython declaration at the botton):
```
  template <typename KeyType, typename InputType>
  flume::PCollection<
      flume::KV<KeyType, std::vector<std::shared_ptr<const PredictionLog>>>>
  operator()(const std::string& stage_name,
             const flume::PTable<KeyType, InputType>& examples) const {
```

Here's the pxd declaration that did not work:
```cython
  cdef cppclass RunInferencePerModel:
    RunInferencePerModel(vector[bulk_inference_config.Model])
    flume.PCollection[flume.KV[KeyType, vector[shared_ptr[const prediction_log.PredictionLog]]]] operator()[KeyType, InputType] (
      const string&, const flume.PCollection[flume.KV[KeyType, InputType]]&) const
```

### Expected behaviour

Should be able to declare a const pointer return type while using templated parameters in cython.

### Environment

OS: Linux
Python version: 3.9.14
Cython version: 0.29.32.

**Comment by da-woods** [comment] 2022-10-11 20:53
Duplicate of https://github.com/cython/cython/issues/4180 I think

**Closed by da-woods** 2022-10-11 20:53 UTC
