### ISSUE TITLE
[BUG] Compile errors on iteration in 3.0a6 that didn't exist on 0.29

### ISSUE THREAD

**Issue by amol-** [cython/cython#4171] opened 2021-05-18 16:54 UTC
**Describe the bug**
On PyArrow we are seeing compile errors in for loops when using Cython master checkout. 
See https://issues.apache.org/jira/browse/ARROW-12825
Those seem to be related to Cython using a wrong type for the indexing variable

```
Error compiling Cython file:
------------------------------------------------------------
...
    def column_types(self):
        """
        Explicitly map column names to column types.
        """
        d = {frombytes(item.first): pyarrow_wrap_data_type(item.second)
             for item in self.options.column_types}
                        ^
------------------------------------------------------------

pyarrow/_csv.pyx:491:25: Cannot assign type 'pair[string,shared_ptr[CDataType]]' to 'shared_ptr[CDataType]'
```

`self.options.column_types` is a `unordered_map[c_string, shared_ptr[CDataType]] column_types`

The issue can be worked around by explicitly declaring the types that were previously implicit ( https://github.com/apache/arrow/pull/10352/files ) but shouldn't previous code continue to work?

**To Reproduce**
Try to compile https://github.com/apache/arrow/python with a master checkout of Cython

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Linux and OSX
 - Python version 3.9.4 and 3.9.5
 - Cython version 3.0a6

**Comment by da-woods** [comment] 2021-05-18 17:20
The issue seems to have been introduced in 415c049611f118e2ecdd31ee1210d230e823f83e

Simpler test-code:
```
# distutils: language=c++

from libcpp.unordered_map cimport unordered_map
from libcpp.string cimport string

cdef f(unordered_map[string, double] m):
    return { (x.first, x.second) for x in m }
```

**Comment by scoder** [comment] 2021-05-18 17:34
Seems that there was a reason for the `self.mark_assignment(target, node.item)` after all. :)

**Comment by scoder** [comment] 2021-05-18 17:38
> shouldn't previous code continue to work?

Yes. This is a regression. Thanks for the report.

**Comment by scoder** [comment] 2021-05-18 17:43
`IndexNode` isn't always the right class to delegate the type inference to. If the object supports iteration, then we need to ask the iterator for its item type, not any artificially constructed index access.

**Comment by scoder** [comment] 2021-05-18 18:18
`NextNode(IterationNode)` should be capable of doing the necessary type inference. Since we're dealing with a for-loop anyway, we should just leave it to that.

**Comment by scoder** [comment] 2021-05-21 12:52
`self.mark_assignment(target, node.item)` would delegate the inference to the `NextNode`, which should then know how to handle this. However, it seems that it does not specialise the template parameters of the item type yet, so maybe the `CppIteratorNode` needs its own `infer_types()` implementation? Don't have the time to look into that right now.

**Comment by scoder** [comment] 2021-05-24 13:20
I'll revert #4077 for now, until we have a proper fix.

**Comment by scoder** [comment] 2021-07-04 17:54
Since #4077 is reverted now, I'll close this ticket.

**Closed by scoder** 2021-07-04 17:54 UTC
Labels: C++, Type Analysis, defect
