### ISSUE TITLE
Memory leak with buffer_get_info

### ISSUE THREAD

**Issue by rainwoodman** [cython/cython#1857] opened 2017-09-05 06:13 UTC
We are able to trigger a memory leak when assigning an numpy array into a `cdef np.ndarray[]` variable. 

Please see the valgrind report here

https://github.com/scipy/scipy/issues/7829

Here is the relevant code segment. If the commented out line is enabled we detect the leak.

```
    def __init__(cKDTree self, data, np.intp_t leafsize=16, compact_nodes=True,𝄾
            copy_data=False, balanced_tree=True, boxsize=None):
        # cdef np.ndarray[np.float64_t, ndim=2] data_arr
        cdef np.float64_t *tmp
        cdef int _median, _compact
        cdef np.ndarray[np.float64_t, ndim=1] boxsize_arr
        data_arr = np.ascontiguousarray(data, dtype=np.float64)
        if copy_data and (data_arr is data):
            data_arr = data_arr.copy()
        self.data = data_arr
        self.n = data_arr.shape[0]
        self.m = data_arr.shape[1]
        self.leafsize = leafsize
        if self.leafsize<1:
```

Cython version 0.26, running on Python 3.5.3 debug build with numpy 1.13.1.

**Comment by scoder** [comment] 2017-09-05 07:13
Quick check: can you confirm that this still happens with 0.26.1?
Does it only happen when a copy is created, or always? (i.e. is the `.copy()` call needed for reproducing?)
What happens if you avoid the double buffer unpacking in the copy case like this:
```
cdef np.ndarray[np.float64_t, ndim=2] data_arr
d = np.ascontiguousarray(data, dtype=np.float64)
data_arr = d.copy() if copy_data and (d is data) else d
```
(That's preferable anyway, because unpacking buffers isn't for free.)

**Comment by scoder** [comment] 2017-09-13 05:23
Any feedback?

**Comment by rainwoodman** [comment] 2017-09-13 06:46
Sorry I was swamped. I will be able to look at this tomorrow.

**Comment by rainwoodman** [comment] 2017-09-15 04:09
First, a correction:

The version of the source code that produced the leak is with Cython 0.25.2 (I checked the head of the file)

Next: I can confirm 0.26.1 also has the same issue.

Last: I can confirm 0.26.1 after your suggested modification the leak is still there.

**Comment by scoder** [comment] 2017-09-15 05:42
One more thing that I noticed: I guess that self.data is also declared as buffer. Could you replace `data_arr` with `self.data` entirely, so that the buffer is really only acquired once? (It was probably acquired 3x in the original code.)

**Comment by scoder** [comment] 2017-09-15 05:43
Oh, and thanks for trying :)

**Comment by rainwoodman** [comment] 2017-09-15 07:14
No self.data is not declared as buffer. it is a typed object, np.ndarray:

```
    cdef:
        vector[ckdtreenode]      *tree_buffer
        ckdtreenode              *ctree𝄾
        readonly cKDTreeNode     tree𝄾
        readonly np.ndarray      data
        np.float64_t             *raw_data
        readonly np.intp_t       n, m
        readonly np.intp_t       leafsize
        readonly np.ndarray      maxes
        np.float64_t             *raw_maxes
        readonly np.ndarray      mins
        np.float64_t             *raw_mins
        readonly np.ndarray      indices
        np.intp_t                *raw_indices
        np.ndarray               _median_workspace
        readonly object          boxsize
        np.ndarray               boxsize_data
        np.float64_t             *raw_boxsize_data
        readonly np.intp_t       size

```

**Comment by scoder** [comment] 2017-09-18 19:01
See comment in https://github.com/scipy/scipy/issues/7829#issuecomment-329697559.
I'll close this ticket, assuming that it is a misinterpretation of NumPy's behaviour by valgrind. Please reopen if you find new evidence that it could still be Cython related and/or Cython could do something about it.

**Closed by scoder** 2017-09-18 19:01 UTC
