### ISSUE TITLE
[BUG]cython_freeze generatedprogram does not run with Python 3.11 on Linux 

### ISSUE THREAD

**Issue by rjungbeck** [cython/cython#5146] opened 2022-11-23 14:06 UTC
### Describe the bug

Error when run with Python 3.11
````
testbld: /usr/include/python3.11/cpython/methodobject.h:59: PyCFunction_GET_FLAGS: Assertion `PyCFunction_Check(func)' failed.
Aborted (core dumped)
````

### Code to reproduce the behaviour:

testbld.py  is a trivial hello world program (just importing argparse)
````
import argparse

def main():
    parser = argparse.ArgumentParser(description="Build Test",
                                        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parms = parser.parse_args()

if __name__ == "__main__":
    main()
````
Use Cython and cython_freeze
````
cython_freeze -o build/_start.c  testbld.py
cython -3 --no-docstrings --output-file build/testbld.c testbld.py

````

Compile into executable

````

import sys
import sysconfig
from setuptools._distutils.ccompiler import new_compiler

compiler = new_compiler()
compiler.add_include_dir(sysconfig.get_path("include"))

    if sys.platform == "linux":
        compiler.add_library(sysconfig.get_config_var("LIBRARY")[3:-2])

objects = compiler.compile(["build/_start.c", "build/testbld.c"])
compiler.link_executable(objects, "testbld", output_dir="build")
````

### Expected behaviour

This code generates a working executable with Python 3.10.6 on Linux and Windows and Python 3.11 on Windows.

NB: This is only  very simplified version of the actual problem. My actual context includes many Python files and libraries.

### Environment

Ubuntu 20.4

**Comment by da-woods** [comment] 2022-11-23 18:28
I think this is a duplicate of https://github.com/cython/cython/issues/4804. It's obviously something we should fix (although none of the fixes are hugely satisfactory. The platform differences are almost certainly due to the default flags set, but you probably need to turn debug mode off.

**Closed by da-woods** 2022-11-23 18:28 UTC
