### ISSUE TITLE
Valid python, Invalid cython (cannot find static variables in classes in generators)

### ISSUE THREAD

**Issue by tzickel** [cython/cython#1552] opened 2016-12-12 12:19 UTC
valid Python 2 & 3, but not Cython.

```pyhton
class Test(object):
	a = {'a': 'b', 'c': 'd'}
	b = ((v,k) for (k, v) in a)
```
the error is:
```
Error compiling Cython file:
------------------------------------------------------------
...
class Test(object):
	a = {'a': 'b', 'c': 'd'}
	b = ((v,k) for (k, v) in a)
                          ^
------------------------------------------------------------

a.py:3:27: undeclared name not builtin: a
```

**Comment by grayfall** [comment] 2016-12-23 20:48
I know this is not the answer you are looking for, but your Python code is broken, too.

**Comment by dscunkel** [comment] 2017-02-07 01:09
What's broken about that python code?  It's odd to make a static that is a generator expression, but I don't see anything invalid about it.

Here are a couple of similar examples:

```
class X(object):
    P = [1, 2, 3]

    # OK
    Q = [x for x in P]

    # ge.py:8:21: undeclared name not builtin: P
    S = list(x for x in P)

    # ge.py:11:25: undeclared name not builtin: P
    T = dict((v, v) for v in P)
```

**Comment by scoder** [comment] 2017-02-07 06:35
Duplicate of #1351.

**Closed by scoder** 2017-02-07 06:35 UTC
Labels: R: duplicate
