### ISSUE TITLE
Any plans to move from `master` branch to `main` branch usage?

### ISSUE THREAD

**Issue by pnemade** [cython/cython#5118] opened 2022-11-07 07:35 UTC
Hi,
Many Git projects have moved to use default branch name from `master` to `main`. Does this project have any plans to do the same here? I see there is this information available on how to do that https://github.com/github/renaming

I tried to search if this request is already available/reported but sorry could not find it here.

Regards

**Comment by da-woods** [comment] 2022-11-07 08:13
Duplicate of https://github.com/cython/cython/issues/3684

Last time this was discussed I think we decided there wasn't a compelling reason to do so and renaming it probably wasn't worth the disruption. Personally I'd probably start a *new* project with "main" rather than "master" but don't really see the value in changing existing projects.

**Closed by da-woods** 2022-11-07 08:13 UTC
