### ISSUE TITLE
[BUG] C tests fail with Python 3.11

### ISSUE THREAD

**Issue by EwoutH** [cython/cython#4781] opened 2022-05-10 11:40 UTC
**Describe the bug**
In shards 1 and 6 of the C tests some of the test don't pass on Python 3.11 (`3.11.0-beta.1`). See the full log below.

**To Reproduce**
Run Tools/ci-run.sh as [defined](https://github.com/cython/cython/blob/master/.github/workflows/ci.yml#L226) in the CI configuration with Python 3.11. See [this test run](https://github.com/cython/cython/runs/6368576607?check_suite_focus=true).

**Expected behavior**
All CI tests pass, as on other Python versions.

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 18.04)
 - Python version: `3.11.0-beta.1`
 - Cython version: 812585935131125f8988c38417bb73bfd5a81c05

<details><summary>Full error log</summary>

```
Sharded tests run in 590 seconds (9.8 minutes)
Errors found in shards 1, 6

Errors from shard 1:
======================================================================
FAIL: fail_on_line_trace (line_trace)
Doctest: line_trace.fail_on_line_trace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.0-beta.1/x64/lib/python3.11/doctest.py", line 2217, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Failed doctest test for line_trace.fail_on_line_trace
  File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line unknown line number, in fail_on_line_trace

----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    result = fail_on_line_trace(None, py_add, py_add_with_nogil)
Expected nothing
Got:
    unsupported operand type(s) for -: 'NoneType' and 'int'
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    len(result)
Expected:
    17
Got:
    3
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    result[:5]  # py
Expected:
    ['NO ERROR', ('call', 0), ('line', 1), ('line', 2), ('return', 2)]
Got:
    ['NO ERROR', ('call', 2), ('line', 2)]
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    result[5:10]  # py
Expected:
    [('call', 0), ('line', 1), ('line', 2), ('line', 3), ('line', 4)]
Got:
    []
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    result[10:14]  # py
Expected:
    [('call', 0), ('line', 1), ('line', 2), ('return', 2)]
Got:
    []
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    result[14:]  # py
Expected:
    [('line', 2), ('line', 5), ('return', 5)]
Got:
    []
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    result = fail_on_line_trace('py_add_with_nogil', py_add, py_add_with_nogil)  # py
Expected:
    failing line trace!
Got:
    unsupported operand type(s) for -: 'NoneType' and 'int'
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    result  # py
Expected:
    ['py_add_with_nogil', ('call', 0), ('line', 1), ('line', 2), ('return', 2), ('call', 0)]
Got:
    ['NO ERROR', ('call', 2), ('line', 2)]
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    result = fail_on_line_trace('py_add', py_add, py_add_with_nogil)  # py
Expected:
    failing line trace!
Got:
    unsupported operand type(s) for -: 'NoneType' and 'int'
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    result[:5]  # py
Expected:
    ['py_add', ('call', 0), ('line', 1), ('line', 2), ('return', 2)]
Got:
    ['NO ERROR', ('call', 2), ('line', 2)]
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.fail_on_line_trace
Failed example:
    result[5:]  # py
Expected:
    [('call', 0), ('line', 1), ('line', 2), ('line', 3), ('line', 4), ('call', 0)]
Got:
    []


======================================================================
FAIL: run_trace (line_trace)
Doctest: line_trace.run_trace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.0-beta.1/x64/lib/python3.11/doctest.py", line 2217, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Failed doctest test for line_trace.run_trace
  File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line unknown line number, in run_trace

----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.run_trace
Failed example:
    run_trace(py_add, 1, 2)
Exception raised:
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.11.0-beta.1/x64/lib/python3.11/doctest.py", line 1346, in __run
        exec(compile(example.source, filename, "single",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<doctest line_trace.run_trace[2]>", line 1, in <module>
        run_trace(py_add, 1, 2)
        ^^^^^^^^^^^^^^^^^^^^^^^
      File "tests/run/line_trace.pyx", line 231, in line_trace.run_trace (line_trace.c:7047)
        func(*args)
      File "tests/run/line_trace.pyx", line 60, in line_trace.trace_trampoline (line_trace.c:3507)
        raise
      File "tests/run/line_trace.pyx", line 54, in line_trace.trace_trampoline (line_trace.c:3406)
        result = callback(frame, what, arg)
      File "tests/run/line_trace.pyx", line 81, in line_trace._create_trace_func._trace_func (line_trace.c:3974)
        trace.append((map_trace_types(event, event), frame.f_lineno - frame.f_code.co_firstlineno))
    TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/1/run/c/line_trace/line_trace.cpython-311-x86_64-linux-gnu.so", line ?, in line_trace.run_trace
Failed example:
    run_trace(py_add, 1, 2, with_sys=True)
Exception raised:
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.11.0-beta.1/x64/lib/python3.11/doctest.py", line 1346, in __run
        exec(compile(example.source, filename, "single",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<doctest line_trace.run_trace[4]>", line 1, in <module>
        run_trace(py_add, 1, 2, with_sys=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "tests/run/line_trace.pyx", line 231, in line_trace.run_trace (line_trace.c:7047)
        func(*args)
      File "<doctest line_trace.run_trace[0]>", line 3, in py_add
        return x
        ^^^^^^^^
      File "tests/run/line_trace.pyx", line 81, in line_trace._create_trace_func._trace_func (line_trace.c:3974)
        trace.append((map_trace_types(event, event), frame.f_lineno - frame.f_code.co_firstlineno))
    TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'



Errors from shard 6:
======================================================================
FAIL: test_deduplicated_args (tuple_constants)
Doctest: tuple_constants.test_deduplicated_args
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.0-beta.1/x64/lib/python3.11/doctest.py", line 2217, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Failed doctest test for tuple_constants.test_deduplicated_args
  File "/home/runner/work/cython/cython/TEST_TMP/6/run/c/tuple_constants/tuple_constants.cpython-311-x86_64-linux-gnu.so", line unknown line number, in test_deduplicated_args

----------------------------------------------------------------------
File "/home/runner/work/cython/cython/TEST_TMP/6/run/c/tuple_constants/tuple_constants.cpython-311-x86_64-linux-gnu.so", line ?, in tuple_constants.test_deduplicated_args
Failed example:
    test_deduplicated_args()
Exception raised:
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.11.0-beta.1/x64/lib/python3.11/doctest.py", line 1346, in __run
        exec(compile(example.source, filename, "single",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<doctest tuple_constants.test_deduplicated_args[0]>", line 1, in <module>
        test_deduplicated_args()
        ^^^^^^^^^^^^^^^^^^^^^^^^
      File "tests/run/tuple_constants.pyx", line 40, in tuple_constants.test_deduplicated_args (tuple_constants.c:3004)
        assert func1.__code__.co_varnames is func2.__code__.co_varnames
    AssertionError
```
</details>

**Comment by da-woods** [comment] 2022-05-10 16:42
The issues with line trace are probably a legitimate unresolved bug.

It's possible that the `test_deduplicated_args` is just a change in how code objects handle `co_varnames` in Python 3.11. It needs investigating to confirm that, but it may well just need disabling. It doesn't look like a major bug to me.

**Comment by EwoutH** [comment] 2022-05-20 11:12
@da-woods Could you help me describe the bug in `line_trace.run_trace` a bit better? That might help if someone wants to resolve this bug. Feel free to suggest or even change the bug report and/or title of this issue.

**Comment by scoder** [comment] 2022-05-20 13:59
>  Could you help me describe the bug in `line_trace.run_trace` a bit better?

I don't think anyone has investigated it yet. In short, line tracing is broken in Py3.11, probably due to changes in the frame stack handling. I'd say, someone needs to debug this (at the C level) to see where it goes wrong.

**Comment by da-woods** [comment] 2022-06-19 11:08
I've turned off the `test_deduplicated_args` test in Python 3.11 (https://github.com/cython/cython/pull/4850). it looks like the underlying implementation has changed and it no longer works (https://github.com/python/cpython/blob/3cd1a5d3ec487e23e3d976e7dd235329f04cfc73/Objects/codeobject.c#L1343)

**Comment by da-woods** [comment] 2022-06-19 11:26
I think the line tracing errors all come from when we call the equivalent Python functions as comparisons (rather than from the Cython functions themselves).

The only one that's ambiguous is

> ```
> Failed example:
>    len(result)
> Expected:
>    17
> Got:
>    16
> ```

which could be from two places (but I think is probably the Python function).

Thus the Python behaviour has changed. I'm not sure whether it's a bug or an expected change. I'm leaning towards "bug".

So I'm not absolutely certain, but I don't think there's an underlying Cython issue, and we're probably best just waiting to see if it gets fixed before the release rather than modifying tests.

**Comment by EwoutH** [comment] 2022-06-19 11:28
Thanks for looking into this! Should a issue be filed over at [python/cpython](https://github.com/python/cpython)?

**Comment by da-woods** [comment] 2022-06-19 11:43
> Thanks for looking into this! Should a issue be filed over at [python/cpython](https://github.com/python/cpython)?

Maybe. Although it probably involves:
1. reducing the test to something that doesn't involve Cython
2. checking that it isn't already filed (when I search their issue tracker for tracing there's quite a few issues)
3. Understanding the expected output well enough to know if this could be a legitimate change.

I've diagnosed it to the point of saying "I don't *think* it's a Cython problem". But I'm not sure I've made enough effort to start throwing the problem elsewhere.

**Comment by da-woods** [comment] 2022-06-19 12:34
I think it may be specifically to do with functions defined in doctest docstrings. It works if I define them in an `exec` call (although this breaks the test on Python 2 for reasons I also don't understand...)

**Comment by da-woods** [comment] 2022-06-19 12:53
Line tracing should be fixed in https://github.com/cython/cython/pull/4851

**Comment by da-woods** [comment] 2022-06-19 13:22
I didn't really come to the conclusion whether it was a Python bug or not and if it should be reported. I failed to make something that could reproduce it independently of Cython. If someone wants to investigate more thoroughly then they're welcome to.

**Comment by da-woods** [comment] 2022-07-13 10:20
Closed by https://github.com/cython/cython/commit/858b1a5ad2237cb439965450c221a15dfedd1295, and a combination of https://github.com/cython/cython/commit/a79e447ea9faea118f39a94b54d0498baad8ad17 and a bugfix in CPython.

**Closed by da-woods** 2022-07-13 10:20 UTC
