### ISSUE TITLE
[BUG] Cython fails to compile when annotated function is already declared in pxd

### ISSUE THREAD

**Issue by matusvalo** [cython/cython#4541] opened 2021-12-28 10:52 UTC
**Describe the bug**
Based on documentation https://cython.readthedocs.io/en/latest/src/userguide/sharing_declarations.html#sharing-c-functions Cython should support declaration in .pxd file. This is 100% working for cython language. For annotated pure python mode it is not working properly - see example below (picked from documentation). 

> Note: I am not 100% sure whether this should be supported or not since cython supports annotating of plain function - https://cython.readthedocs.io/en/latest/src/tutorial/pure.html#augmenting-pxd

**To Reproduce**
Code to reproduce the behaviour (based on example in documentation):
- `volume.pxd` file:
```cython
cdef float cube(float)
```

- `volume.py` file:
```python
import cython

@cython.cfunc
def cube(x: cython.float) -> cython.float:
    return x * x * x
```

Compiling this code fails:
```
$ cython -3a volume.py

Error compiling Cython file:
------------------------------------------------------------
...
import cython

@cython.cfunc
^
------------------------------------------------------------

volume.py:3:0: Function signature does not match previous declaration
```

**Expected behavior**

Compiling should succeed.

**Environment (please complete the following information):**
 - OS: macOS
 - Python version 3.9.7
 - Cython version master

**Additional context**

Equivalent code in cython syntax is successfully compiled:

- `volume.pxd` file:
```cython
cdef float cube(float)
```
- `volume.pyx` file:
```cython
cdef float cube(float x):
    return x * x * x
```

**Comment by da-woods** [comment] 2021-12-28 11:16
Duplicate of https://github.com/cython/cython/issues/4388

**Closed by da-woods** 2021-12-28 11:16 UTC
