### ISSUE TITLE
Cython emits Python 3 code for __prepare__ in Python 2

### ISSUE THREAD

**Issue by thanatos** [cython/cython#1936] opened 2017-10-13 21:16 UTC
Cython is emitting the following code in Python 2:

```
/* Py3ClassCreate */
  static PyObject *__Pyx_Py3MetaclassPrepare(PyObject *metaclass, PyObject *bases, PyObject *name,
                                           PyObject *qualname, PyObject *mkw, PyObject *modname, PyObject *doc) {
    PyObject *ns;
    if (metaclass) {
        PyObject *prep = __Pyx_PyObject_GetAttrStr(metaclass, __pyx_n_s_prepare);
        if (prep) {
            PyObject *pargs = PyTuple_Pack(2, name, bases);
            if (unlikely(!pargs)) {
                Py_DECREF(prep);
                return NULL;
            }
            ns = PyObject_Call(prep, pargs, mkw);
            Py_DECREF(prep);
            Py_DECREF(pargs);
        } else {
```

This code finds the `__prepare__` attribute, and, if it exists, calls it as if it were a function. `__prepare__` does not exist in Python 2, and should not be called in Python 2, however, Cython will errantly call it.

Typically, it won't exist, so this path is never triggered. Unfortunately, `six` just added (in 1.11.0) a `__prepare__` function to a dummy class that gets generated upon a call to `with_metaclass` (in [this commit](https://github.com/benjaminp/six/commit/96b93280fc4c70d65be0af5949f80f46f5c679ca)).

That means that the following code:

```python
import six

class SomeBase(object):
    pass

class SomeMeta(type):
    def __new__(cls, name, bases, dct):
        new_cls = super(SomeMeta, cls).__new__(cls, name, bases, dct)
        #new_cls = type.__new__(cls, name, bases, dct)
        return new_cls


#import ipdb; ipdb.set_trace()
class Derived(six.with_metaclass(SomeMeta, SomeBase)):
    pass
```

will work just fine in Python 2 on its own, but if compiled w/ cython, will result in the above stack trace, since Cython will incorrectly call `__prepare__`, whereas CPython will not.

**Comment by scoder** [comment] 2017-10-14 05:59
It's difficult to say what to do here. Basically, if code wants to use this feature in Cython, it feels wrong to prevent it from doing so, just because it happens to *run* in Python 2.x.

I could imagine enabling this only for code that uses `language_level=3`, but honestly, that feels like artificially restricting an otherwise perfectly well defined feature. Even your description suggests that six isn't using `__prepare__()` for anything but class dict creation.

I think the easiest fix here is to not use six in Cython code. It is generally not very helpful. Cython does not understand it, so it only prevents some optimisations without giving any benefit. Cython has most of the functionality already built-in.

**Comment by thanatos** [comment] 2017-10-16 23:04
> Basically, if code wants to use this feature in Cython, it feels wrong to prevent it from doing so, just because it happens to run in Python 2.x

We disagree then; I feel that that code should never execute, because the real interpreter, and the language specification, say that it shouldn't. I think users expect Cython to faithfully emulate the language (either Python 2 *or* 3), not some weird mash-up between the two.

That *some* uses of `__prepare__` *happen* to function doesn't justify the behavior if Cython is supposed to be a compiler/optimizer for the Python language, since according to the language specification, that behavior should not occur; it is immaterial that it happens to occur in a later version of the language. Further, other uses of `__prepare__` can and will fail, and this is just confusing and troublesome.

> I think the easiest fix here is to not use six in Cython code. It is generally not very helpful. Cython does not understand it, so it only prevents some optimisations without giving any benefit. Cython has most of the functionality already built-in.

I have to disagree here; even though it might prevent some optimizations, it provides a world of benefit in porting a legacy codebase to modern versions of Python. I fully expect some minor inefficiencies from its use, but that's not it's selling point.

**Comment by scoder** [comment] 2017-10-17 17:29
> "some weird mash-up", "essentially running random code at random times", etc.

I can understand that you're upset, but I really wouldn't call it weird. It's rather pragmatic. We basically support all new features also in older Python versions if they a) can be backported at all and b) do not interfere with the old Python versions. You can use async/await in Cython code also under Py2.6, for example. Why? Because there is no reason not to support it. The same applies to the Py3 metaclass keyword syntax. It's just so much better than all those corresponding Py2 quirks that it would be annoying for users not to allow it.

> [six] provides a world of benefit in porting a legacy codebase to modern versions of Python

I'm not contradicting that at all, but it applies only to regular interpreted Python code. There is really no point in using six in Cython compiled code, because Cython is designed to apply as many Python version adaptations as possible under the hood, not even just for Py2/3. It's meant to be "translate once, build anywhere". In fact, Cython allows you to write Python 3 code, and then compile it to make it run in Python 2.6. It's *way* better than six! ;)

That being said, I do agree that picking up `__prepare__` in Python 2 *code* is stretching the adaptation part a bit. But this has been supported since 2010, for seven years now, and you're the first to complain about it. If the problem appeared with a recent change in six, then maybe six can be changed to not include a (useless and apparently conflict prone) `__prepare__` in Py2?

**Comment by jdemeyer** [comment] 2017-10-18 19:40
> I think the easiest fix here is to not use six in Cython code.

...especially not for metaclasses. Just use the Python 3 metaclass syntax!

> It's way better than six! ;)

:+1:

**Comment by jdemeyer** [comment] 2017-10-18 19:43
> If the problem appeared with a recent change in six

That's indeed what happened.

**Comment by scoder** [comment] 2017-10-20 06:48
Yes, it's a bug in six that was introduced here:
https://github.com/benjaminp/six/pull/178
It unconditionally calls `meta.__prepare__()`, which is not always available in Py2.

**Comment by scoder** [comment] 2017-10-20 06:55
Closing as "third party, not a bug in Cython".

**Closed by scoder** 2017-10-20 06:55 UTC
Labels: R: invalid

**Comment by jdemeyer** [comment] 2017-10-20 08:31
Fixed in https://github.com/benjaminp/six/pull/211
