### ISSUE TITLE
Cython coverage report doesn't match cdef/cpdef/ctypedef lines

### ISSUE THREAD

**Issue by alexveden** [cython/cython#2065] opened 2018-01-11 10:08 UTC
I'm trying to achieve 100% coverage for my Cython files but some lines are still showed in coverage report as missing. Actually, only cdef, ctypedef and cpdef definition lines are affected, the code inside the cdef functions is covered as expected.

I thought that these lines are excluded due to RegEx mismatch, but my investigation showed that they are mapped correctly.
I checked this part of code:  https://github.com/cython/cython/blob/master/Cython/Coverage.py#L213

## Sample project coverage
![image](https://user-images.githubusercontent.com/18488560/34819969-b6f8d8f0-f6d8-11e7-9571-4b3b92a15ca3.png)

I included the sample project, with coverage report and source files, to run it call:
`python setup.py build_ext --force --inplace`
`coverage run ./test_hello2.py`
`coverage html`
Open `htmlcov/hello_pyx.html` in the browser.

My OS:
Linux uberhome 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Packages information:
coverage
Version: 4.4.1

Cython
Version: 0.27.3

[hello_cython.zip](https://github.com/cython/cython/files/1622065/hello_cython.zip)

**Comment by scoder** [comment] 2018-01-12 13:59
Duplicate of #1461.

**Closed by scoder** 2018-01-12 13:59 UTC
