### ISSUE TITLE
Compiler crash: NoneType has no attribute 'analyse_types' using string types

### ISSUE THREAD

**Issue by klaussfreire** [cython/cython#1934] opened 2017-10-13 19:36 UTC
Using pure python mode, declaring locals to be of a pointer type declared with a string, causes a compiler crash:

```
(test)claudiofreire@klaumpptophp:~/src/sharedbuffers> cython --annotate test.py

Error compiling Cython file:
------------------------------------------------------------
...
import cython

@cython.locals(buf = 'const char *')
                    ^
------------------------------------------------------------

test.py:3:21: Compiler crash in AnalyseDeclarationsTransform

ModuleNode.body = StatListNode(test.py:1:0)
StatListNode.stats[1] = StatListNode(test.py:4:0)
StatListNode.stats[0] = CompilerDirectivesNode(test.py:4:0)
CompilerDirectivesNode.body = StatListNode(test.py:4:0)
StatListNode.stats[0] = DefNode(test.py:4:0,
    modifiers = [...]/0,
    name = u'blah',
    np_args_idx = [...]/0,
    num_required_args = 1,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0')
File 'ExprNodes.py', line 1589, in analyse_as_type: StringNode(test.py:3:21,
    is_literal = 1,
    is_string_literal = True,
    result_is_used = True,
    unicode_value = u'const char *',
    use_managed_ref = True,
    value = 'const char *')

Compiler crash traceback from this point on:
  File "/home/claudiofreire/venv/test/lib/python2.7/site-packages/Cython/Compiler/ExprNodes.py", line 1589, in analyse_as_type
    return _analyse_name_as_type(self.unicode_value or self.value.decode('ISO8859-1'), self.pos, env)
  File "/home/claudiofreire/venv/test/lib/python2.7/site-packages/Cython/Compiler/ExprNodes.py", line 1375, in _analyse_name_as_type
    return sizeof_node.arg_type.analyse_types(env)
AttributeError: 'NoneType' object has no attribute 'analyse_types'
```

Where test.py is:

``` python
import cython

@cython.locals(buf = 'const char *')
def blah(x):
   buf = cython.NULL
   return x
```

This seems to happen with any pointer type declared as string.

Affected version Cython 0.27.1

Last known-good version Cython 0.27.0

Found this because [sharedbuffers](https://github.com/jampp/sharedbuffers/) stopped building with Cython 0.27.1

**Comment by scoder** [comment] 2017-10-13 21:54
Duplicate of #1908.

**Closed by scoder** 2017-10-13 21:54 UTC
Labels: R: duplicate
