### ISSUE TITLE
3.0a1 breaks several SciPy functions

### ISSUE THREAD

**Issue by larsoner** [cython/cython#3516] opened 2020-04-14 17:49 UTC
The full list can be seen in [these](https://travis-ci.org/github/scipy/scipy/jobs/674918740) [two](https://travis-ci.org/github/scipy/scipy/jobs/674918743) travis builds in a [PR to enable it](https://github.com/scipy/scipy/pull/11855). But here are roughly the four categories of failures with relevant tracebacks:
```
FAILED ../../io/matlab/tests/test_mio.py::test_read_opts
Current thread 0x00007f8ee7560700 (most recent call first):
904  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.8/site-packages/scipy/io/matlab/mio5.py", line 248 in read_var_array
905  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.8/site-packages/scipy/io/matlab/mio5.py", line 288 in get_variables
906  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.8/site-packages/scipy/io/matlab/tests/test_mio.py", line 823 in test_read_opts
```

```
FAILED scipy/sparse/csgraph/tests/test_shortest_path.py::test_directed
Current thread 0x00007f121fcbf700 (most recent call first):
1164  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.8/site-packages/scipy/sparse/csgraph/tests/test_shortest_path.py", line 98 in check
1165  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.8/site-packages/scipy/sparse/csgraph/tests/test_shortest_path.py", line 103 in test_directed
```

```
FAILED ../../spatial/tests/test_kdtree.py::test_ckdtree_pickle
Current thread 0x00007fe2493c0700 (most recent call first):
1341  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.8/site-packages/scipy/spatial/tests/test_kdtree.py", line 947 in test_ckdtree_pickle
```

```
FAILED ../../signal/tests/test_upfirdn.py::TestUpfirdn::test_extensions[constant]
_upfirdn_apply.pyx:241: in scipy.signal._upfirdn_apply.__pyx_fused_cpdef
    ???
E   TypeError: Expected dict, got int
```
I haven't looked into why this is the case, but wanted to post this here in case people have ideas for what can cause any of these.

**Comment by scoder** [comment] 2020-04-14 18:10
Thanks for the report. This is a duplicate of #3511.

**Closed by scoder** 2020-04-14 18:10 UTC

**Comment by scoder** [comment] 2020-04-15 18:37
Could you give the latest Cython master branch a try? It has a fix.

**Comment by larsoner** [comment] 2020-05-06 16:10
Indeed this fixed things for me, thanks!
