### ISSUE TITLE
[ENH] Automatic conversion of array of char * to list of bytes

### ISSUE THREAD

**Issue by Celelibi** [cython/cython#4020] opened 2021-02-27 01:29 UTC
**Initial problem**
Converting an array of `char *` into a python `list` of `bytes` seems to be only implemented when the array size is a constant.
```cython
cdef extern char *array_static[10]
def foo():
    return array_static
```
Which produce C code like this.
```c
__pyx_t_1 = __Pyx_carray_to_py_char___2a_(array_static, 10); 
```

But it is not supported when the array size is dynamic. (Of course, cython has no way of knowing the array size.)
```cython
cdef extern char **array_dynamic
def foo():
    return array_dynamic
```

But the array size doesn't have to be a known constant for the automatic conversion to take place. For instance in this case.
```cython
cdef extern const int asize
cdef extern char *myarray[asize]
def foo():
    return myarray
```
Which produces.
```c
__pyx_t_1 = __Pyx_carray_to_py_char___2a_(myarray, asize);
```

I guess there would be a way to trick cython into thinking the array size is a constant when it's actually a variable. And I could modify that variable in the function `foo`. But that'd be a pretty ugly solution.

**Solution I'd like**
It is already possible to convert a `char *` to a `bytes` object when its length is already known by using the slice notation.
```cython
cdef extern char *s
def foo():
    return s
def bar():
    return s[:42]
```
Where `foo` is compiled using `__Pyx_PyBytes_FromString(s)` while `bar` uses `__Pyx_PyBytes_FromStringAndSize(s + 0, 42 - 0)`.

So I'd suggest using the same notation to make the array size known to cython and be able to use the automatic conversion to `list` of `bytes`.

```cython
cdef extern char **array_dynamic
def foo():
    cdef int size = 42
    return array_dynamic[:size]
```

**Alternatives**
The workarounds are quite obvious. Like building the list item by item, using the automatic `char *` to `bytes` conversion on each element. Or using the CPython C API; Basically reimplmementing some functions from `Utility/CConvert.pyx`.

**Comment by da-woods** [comment] 2021-02-27 08:19
Duplicate of https://github.com/cython/cython/issues/2159.

There is a WIP fix pull request (https://github.com/cython/cython/pull/3151) - don't know how close to acceptance it is

**Closed by da-woods** 2021-02-27 08:19 UTC
