### ISSUE TITLE
Can't Install on Raspbian

### ISSUE THREAD

**Issue by thgdc** [cython/cython#1849] opened 2017-08-30 16:13 UTC
Hello everyone! I need some help. I'm trying to install Cython (an version) into my Raspberry Pi3b with Raspbian Jessie, using:
`sudo pip install cython`
or with "==[version]", but I keep getting this:

    Downloading/unpacking cython
        Downloading Cython-0.26.1.tar.gz (1.7MB): 1.7MB downloaded
        Running setup.py (path:/tmp/pip-build-818NBw/cython/setup.py) egg_info for package cython
            Unable to find pgen, not compiling formal grammar

            warning: no files found matching 'Doc/*'
            warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
            warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
            warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    Installing collected packages: cython
        Running setup.py install for cython
        Unable to find pgen, not compiling formal grammar.

(then there is some erros for a lot of *.c files and at the end I still don't have cython)

What can I do to fix it? Thanks

ps.: I already have the build-essential and everything is updated.

**Comment by scoder** [comment] 2017-08-30 21:26
You probably just have to let it continue running. On a slow machine, it can take a while to compile the sources. Note that compilation is optional here, but speeds up the Cython usage quite a bit.

**Comment by scoder** [comment] 2017-09-03 17:05
Closing, not a bug.

**Closed by scoder** 2017-09-03 17:05 UTC
Labels: R: invalid
