### ISSUE TITLE
Make current frame information available for logging

### ISSUE THREAD

**Issue by Huarong** [cython/cython#2203] opened 2018-04-17 05:14 UTC
I complied `.py` files to `.so` files using cython's cythonize function.
And found the code line number in logging informations are wrong.

For example, I have the following code structure.

```
web
├── boot.so
├── handlers.so
├── __init__.py
├── __init__.so
├── server.py
└── server.so
```

The logging data is like these:

```
INFO: 2018-04-17 13:05:47: web.py:1510 * 140329485150016 Get next question of step: 2
INFO: 2018-04-17 13:05:47: web.py:1510 * 140329485150016 Timer: {'postprocess_last_status_None': 0, 'get_next_question': 4}
INFO: 2018-04-17 13:05:47: web.py:1510 * 140329485150016 logstash###...
INFO: 2018-04-17 13:05:47: web.py:2064 * 140329485150016 200 POST /which_drug_bot_app (192.168.10.12) 22.06ms
```

The logging data tells all the code line numbers are in `web.py` which is not a actual code file.

**So my question is how to write the right logging information with cython ?**

**Comment by tzickel** [comment] 2018-09-20 16:32
You can't
https://cython.readthedocs.io/en/latest/src/userguide/limitations.html

**Comment by tzickel** [comment] 2018-09-21 06:32
@scoder maybe this should be more explicit in limitations page (logging support for line/file/func) ?

**Comment by scoder** [comment] 2018-09-21 06:50
Note sure if enabling support for profiling or tracing helps here. Worth a try, I guess.
If not, then yes, seems worth mentioning it explicitly. PR welcome.

**Comment by tzickel** [comment] 2018-09-21 16:29
@scoder I am not an expert on the codebase, but cpython runs sys._getframe(3) to get the execution point information for logging display (in 2.7 as well):
https://github.com/python/cpython/blob/b46ad5431d2643f61e929c1ffec48766b2fafd75/Lib/logging/__init__.py#L154
AFAIK cython never touches the current thread state's frame information, thus this information will always be wrong (even with profiling or tracing which again don't insert a fake / non fake frame instance in there) ?

**Comment by scoder** [comment] 2018-09-21 16:51
Probably right, yes.
Then I'd recommend naming your loggers (e.g. with the usual `logging.getLogger(__name__)` pattern) and using that information for logging. Or do you really need the line numbers?

Cython could certainly hook the frames it generates for profiling also into the thread state (e.g. when requested by a module level directive), but that's probably not as trivial at it might look. I'll keep it as a valid feature request, though.

**Comment by tzickel** [comment] 2018-09-21 18:40
I am not the opener of this thread, just had the same issue (I solved it by preprocessing the .py file with RedBaron and adding this information at compile time), sometimes people do need the line numbers for debugging.

Is there a reason not to do it in regular cases as well (as an compiler directive option) ?

**Comment by scoder** [comment] 2018-09-21 18:47
"do it" == "connect the frames"?
It's not currently being done because a) there are no frames by default and b) the frames that we generate for tracing are not necessarily suitable for other purposes. Needs investigation and probably fixing. #93 is related here, which would allow using a single frame for a whole function, which we currently don't. That would probably be required before we connect it to the thread state, though.

**Comment by tzickel** [comment] 2018-09-21 19:34
Maybe we can start with something more simple like PyCode_NewEmpty for logging information, and in the future add more upon it if needed ?

**Comment by scoder** [comment] 2018-09-21 19:48
Well, look at the code that Cython generates for profiling and tracing. It's pretty much all there, just needs some putting together, debugging and fixing.

**Comment by tzickel** [comment] 2018-09-22 09:28
BTW, for anybody who wants to do it in an preprocessing stage:

https://gist.github.com/tzickel/0abbed10de4dd18c82d7ef618e6236b5

**Comment by scoder** [comment] 2018-09-22 12:41
Closing as a duplicate of #1373.

**Closed by scoder** 2018-09-22 12:41 UTC
Labels: Code Generation, Python Semantics, feature
