### ISSUE TITLE
[BUG] Nested double quotes supported by python 3.12 not supported in cython

### ISSUE THREAD

**Issue by mironleon** [cython/cython#6208] opened 2024-05-21 12:02 UTC
### Describe the bug

Trying to cythonize an f-string with nested double quotes fails with an error message. This might be wholly intentional and reasonable, but the nested double quotes are valid in python 3.12 and the `cython-lint` tool automatically formats your code to use them (also filed a [bug report](https://github.com/MarcoGorelli/cython-lint/issues/111) for cython-lint)

```
Error compiling Cython file:
------------------------------------------------------------
...
def function():
    a = f"foo [{"bar"}]"
                 ^
------------------------------------------------------------

test.pyx:2:17: empty expression not allowed in f-string

Error compiling Cython file:
------------------------------------------------------------
...
def function():
    a = f"foo [{"bar"}]"
                 ^
------------------------------------------------------------

test.pyx:2:17: missing '}' in format string expression

Error compiling Cython file:
------------------------------------------------------------
...
def function():
    a = f"foo [{"bar"}]"
                 ^
------------------------------------------------------------
```

### Code to reproduce the behaviour:

```cython
def function():
    a = f"foo [{"bar"}]"
    print(a)
```

### Expected behaviour

Cythonizing correctly and when calling the function outputting:

`foo ["bar"]`

### OS

Linux (Ubuntu 22.04)

### Python version

3.12.3

### Cython version

3.0.10

**Comment by da-woods** [comment] 2024-05-21 16:22
Duplicate of https://github.com/cython/cython/issues/5452. Just hasn't been done yet.

**Closed by da-woods** 2024-05-21 16:22 UTC
Labels: R: duplicate
