### ISSUE TITLE
[BUG] After converting a Python file to a Cython file, the order of the user-defined decorator and static method decorator is changed.

### ISSUE THREAD

**Issue by raj1234556** [cython/cython#4705] opened 2022-03-29 06:27 UTC
Case 1: Success In Python and Fail in Cython

from inspect import signature
import tracestack

def decfun(fun1):
      print("something data")
      obj = signature(fun1)
      return fun1

class A(object):
    
    @staticmethod
    @decfun
    def fun():
          print("dummy")

Case 2: Fail In Python and Cython 

from inspect import signature
import tracestack

def decfun(fun1):
      print("something data")
      obj = signature(fun1)
      return fun1

class A(object):

    @decfun
    @staticmethod
    def fun():
        print("dummy")

If it has already been updated, please let me know which version it is, or when I will get the latest update package.

**Comment by da-woods** [comment] 2022-03-29 07:03
Probably a duplicate of https://github.com/cython/cython/issues/1434. There's a PR that fixes that issue - you might want to try it on yours.

**Comment by da-woods** [comment] 2022-03-29 07:09
I'm not convinced case 2 fails in very recent versions of Python any more by the way. (But that's somewhat irrelevant to your issue)

**Closed** 2022-03-29 19:10 UTC
