### ISSUE TITLE
[BUG] Compiler crash on type annotation

### ISSUE THREAD

**Issue by emanuellima1** [cython/cython#4002] opened 2021-02-08 16:41 UTC
**Describe the bug**
When I try to compile the following Cython code, the compiler crashes with the error __Compiler crash in IterationTransform__ :

```cython
from typing import List

def func(time_seq: range) -> List[int]:
    time_seq: List[int] = [x + 1 for x in time_seq]
    return time_seq
```

But when I compile this, it compiles without error:

```cython
from typing import List

def func(time_seq) -> List[int]:
    time_seq: List[int] = [x + 1 for x in time_seq]
    return time_seq
```

I don't understand why typing the argument would make the compilation fail.  
The setup.py:

```python
from distutils.core import setup
from Cython.Build import cythonize

setup(name="Test",
      ext_modules=cythonize("test.pyx", language_level="3", compiler_directives={'annotation_typing': True}))
```

**Environment:**
 - Linux (Kubuntu 20.10) with Python 3.8.6 and Cython 0.29.21

**Comment by da-woods** [comment] 2021-02-08 18:23
This was fixed in 43bdeb03e2390e2f44d6bd7ff78aed56d4a726f0 on the current master branch.

None of the types you're giving it are particularly useful to Cython - I don't think it can do anything with `range` and `typing.List[]` currently just makes a small difference to iteration (but that's it at the moment). So given that they're breaking it, you'd probably be better omitting them (or turning annotation_typing off)

**Comment by da-woods** [comment] 2021-02-08 18:24
Duplicate of https://github.com/cython/cython/issues/2811

**Closed by da-woods** 2021-02-08 18:24 UTC

**Comment by scoder** [comment] 2021-02-09 16:52
> you'd probably be better omitting them

If it wasn't just for making it work at all (assuming you depend on Cython 0.29.x), I'd rather not recommend against having these annotations in the code. Once they are written down, Cython can eventually add support for them, and the code will benefit at some point in the future. If you omit them now, you'd probably forget to add them back when this happens.
