### ISSUE TITLE
Problem with c++ classes inside classes

### ISSUE THREAD

**Issue by foradan** [cython/cython#3132] opened 2019-09-06 09:00 UTC
The code:

```cython
cimport libcpp.string
cdef libcpp.string.string.interator i
```

Gives the error: "'libcpp.string.string' is not a cimported module".  While the code:

```cython
cimport libcpp.vector
cdef libcpp.vector.vector[int].iterator i
```

Compiles without error.

The above error also happens for other situations where a class inside a non-template class is used.

I am using cython version 0.29.7.

**Comment by foradan** [comment] 2019-09-06 11:07
The above problem can be circumvented with:

```cython
from libcpp.string cimport string
cdef string.iterator i
```

**Comment by foradan** [comment] 2019-09-06 11:15
But the circumvention doesn't work in the case of classes inside classes inside classes.

test.cxx:
```c++
class A {
    class B {
        class C {
        };
    };
};
```

```cython
from test cimport A
cdef A.B.C i
```
still fails.

**Comment by rickmark** [comment] 2023-02-28 03:53
Seeing the same issue, something about resolution failing on nodes deeper then one, which is why they work as long as they are only on one navigation.

**Comment by 0dminnimda** [comment] 2023-02-28 10:13
I think this is duplicate of #3074

**Comment by da-woods** [comment] 2023-03-05 11:54
Hopefully fixed in https://github.com/cython/cython/commit/85945aae8ad42440fc3bf5f7c9be64a0a68b2952

**Closed** 2023-03-05 11:54 UTC
