### ISSUE TITLE
[BUG] Memory view arrays cannot be size 0

### ISSUE THREAD

**Issue by mrakgr** [cython/cython#3996] opened 2021-02-02 16:57 UTC
**Describe the bug**
```
cimport cython
cpdef void main():
    cdef object [::1] v0 = cython.view.array(shape=(0,), itemsize=sizeof(void *), format='O')
```
```
ValueError: Invalid shape in axis 0: 0.
```

**To Reproduce**
Run the above.

**Expected behavior**
That the array with no elements would get created

**Environment (please complete the following information):**
 - OS: Win 10
 - Python version: 3.8.5
 - Cython version: 0.29.21

**Additional context**
[One of the tests](https://github.com/mrakgr/The-Spiral-Language/blob/1592cf7ee6805ef2f2ed13351c121d61828f7c42/Spiral%20Compilation%20Tests/compilation_tests/test45/test.spi) for the Spiral language does a breath first search using nested arrays instead of a queue, so it can have a size of zero towards the end after all the moves get filtered.

I have no idea why this weird restriction is in place here. This wasn't the case with the Numpy arrays or pretty much any kind of array in any language I've looked at.

**Comment by da-woods** [comment] 2021-02-02 17:01
Duplicate of https://github.com/cython/cython/issues/3334. I'm pretty sure it should work given that you can get a size-0 memoryview by creatively slicing another memoryview.

**Closed by da-woods** 2021-02-02 17:01 UTC

**Comment by mrakgr** [comment] 2021-02-03 08:49
It is good that this will be easy to fix. I've gone back to Numpy arrays until this gets resolved, so please do so.
