### ISSUE TITLE
[BUG] Conflict between typing module and Cython 0.29.31

### ISSUE THREAD

**Issue by tyralla** [cython/cython#4933] opened 2022-07-28 13:49 UTC
**Describe the bug**

error C2106: '=' : left operand must be l-value

**To Reproduce**

```cython
from typing import *
cdef double[:] xs
```

**Expected behavior**

Successful compilation

**Environment**

 - OS: Windows
 - Python 3.8.5
 - Cython 0.29.31

**Additional context**

The relevant line in the C file:

CYTHON_ATOMICS = __Pyx_PyObject_IsTrue(o); if (unlikely((CYTHON_ATOMICS == (int)-1) && PyErr_Occurred())) __PYX_ERR(1, 26, __pyx_L2_error)

The problem did not occur for Cython 0.29.30 and earlier versions.

**Comment by da-woods** [comment] 2022-07-28 13:58
Duplicate of https://github.com/cython/cython/issues/4927.

The conflict is with `import *` rather than with typing specifically.

**Closed by da-woods** 2022-07-28 13:58 UTC
