### ISSUE TITLE
Exceptions are not caught, if a global tuple is used as exception types

### ISSUE THREAD

**Issue by mbuesch** [cython/cython#2426] opened 2018-06-26 17:49 UTC
The commit 6cc0a3a758937921fd5889eecb301ae4c65c7f5c broke exception handling, if the exception type is a tuple of exceptions.

The following code
```
MyExceptions = (KeyError, ValueError)
def a():
        _MyExceptions = MyExceptions
        try:
                int("x")
        except _MyExceptions as e:
                print("Handling exception a")
def b():
        try:
                int("x")
        except MyExceptions as e:
                print("Handling exception b")
a()
b()
```

gives this result with CPython and Cython before 6cc0a3a758937921fd5889eecb301ae4c65c7f5c:

```
Handling exception a
Handling exception b
```

With commit 6cc0a3a758937921fd5889eecb301ae4c65c7f5c or later it does not catch the first and the second exception anymore in Cython:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test.pyx", line 13, in init test
    a()
  File "test.pyx", line 5, in test.a
    int("x")
ValueError: invalid literal for int() with base 10: 'x'  
```

In current Cython master branch it is a bit better in that is succeeds to catch the first exception with the local tuple, but still fails to catch the second one with the global tuple.

```
Handling exception a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test.pyx", line 14, in init test
    b()
  File "test.pyx", line 10, in test.b
    int("x")
ValueError: invalid literal for int() with base 10: 'x'
```

**Comment by scoder** [comment] 2018-06-26 20:05
Duplicate of #2425.

**Closed by scoder** 2018-06-26 20:05 UTC
Labels: R: duplicate
