### ISSUE TITLE
How to install cython on windows?

### ISSUE THREAD

**Issue by PROgramJEDI** [cython/cython#3472] opened 2020-03-27 12:39 UTC
I have tried to install MinGW - C compiler to compile .c files after doing the command on the setup file but it keeps giving an errors. I also tried to add MinGW to the environment variable, which didn't affect it all. After I'm doing the ```python setup.py build_ext --inplace``` command, it translates the .pyx to a .c, but when I try to compile the .c, it keeps showing me that there is no 'Python.h' file, and others. I tried to add the folder of the file to envv but didn't worked...

**Comment by mattip** [comment] 2020-03-27 12:57
In general this issue tracker is for problems with cython. Since cython successfully generates the C file, your situation is better suited to a general forum for problems with setuptools/distutils. 

Are you compiling without using distutils/setuptools? They query your version of Python to emit flags used to find the include path for Python.h via a call to values of `sysconfig.get_config_vars('CC', 'CXX', 'OPT', 'BASECFLAGS','CCSHARED', 'LDSHARED')`, which are fixed when compiling python, and the appropriate flags are added to the compile command. 

When you report this in another forum, you will want to copy-paste the text (not a screen shot) of the exact calls you are making, including showing the compiler call with all flags to better help people reproduce your problem.

**Comment by scoder** [comment] 2020-03-27 12:59
There's a bit of documentation about usage on Windows and also with MinGW available in the docs and the github wiki.

Closing, since it's not a bug or issue with Cython.

**Closed by scoder** 2020-03-27 12:59 UTC

**Comment by PROgramJEDI** [comment] 2020-03-28 08:56
> In general this issue tracker is for problems with cython. Since cython successfully generates the C file, your situation is better suited to a general forum for problems with setuptools/distutils.
> 
> Are you compiling without using distutils/setuptools? They query your version of Python to emit flags used to find the include path for Python.h via a call to values of `sysconfig.get_config_vars('CC', 'CXX', 'OPT', 'BASECFLAGS','CCSHARED', 'LDSHARED')`, which are fixed when compiling python, and the appropriate flags are added to the compile command.
> 
> When you report this in another forum, you will want to copy-paste the text (not a screen shot) of the exact calls you are making, including showing the compiler call with all flags to better help people reproduce your problem.

Thank you. I know this question is more suitable for forum website, but the biggest forum called **'StackOverflow'**, decides every once in a while to limit the amount of questions I can ask, if they'r not getting enough reputation or if the quality of them is "not enough". 

**StackOverflow is sucks.**
And I don't want to go to Reddit or Quora, because those websites are not mainly concentrated in this target.
Can you recommend me some other forums?
