### ISSUE TITLE
[BUG] 'NoneType' object has no attribute 'cname'

### ISSUE THREAD

**Issue by padix-key** [cython/cython#5654] opened 2023-08-26 18:24 UTC
### Describe the bug

The code (see below) raises following exception on Cython compilation:

```
Traceback (most recent call last):
  File "/home/kunzmann/conda/envs/biotite-dev/bin/cython", line 11, in <module>
    sys.exit(setuptools_main())
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 757, in setuptools_main
    return main(command_line = 1)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 785, in main
    result = compile(sources, options)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 676, in compile
    return compile_multiple(source, options)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 650, in compile_multiple
    result = run_pipeline(source, options,
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 542, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/Pipeline.py", line 398, in run_pipeline
    data = run(phase, data)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/Pipeline.py", line 375, in run
    return phase(data)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/ModuleNode.py", line 222, in process_implementation
    self.generate_c_code(env, options, result)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/ModuleNode.py", line 516, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 404, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 3499, in generate_function_definitions
    self.defaults_getter.generate_function_definitions(env.global_scope(), code)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 3506, in generate_function_definitions
    FuncDefNode.generate_function_definitions(self, env, code)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 2200, in generate_function_definitions
    self.generate_function_body(env, code)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 1953, in generate_function_body
    self.body.generate_execution_code(code)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 6856, in generate_execution_code
    value.generate_evaluation_code(code)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/ExprNodes.py", line 831, in generate_evaluation_code
    self.generate_subexpr_evaluation_code(code)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/ExprNodes.py", line 846, in generate_subexpr_evaluation_code
    node.generate_evaluation_code(code)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/ExprNodes.py", line 837, in generate_evaluation_code
    self.generate_result_code(code)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/ExprNodes.py", line 8017, in generate_result_code
    self.generate_operation_code(code)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/ExprNodes.py", line 8576, in generate_operation_code
    self.generate_sequence_packing_code(code)
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/ExprNodes.py", line 8084, in generate_sequence_packing_code
    code.put_incref(arg.result(), arg.ctype())
  File "/home/kunzmann/conda/envs/biotite-dev/lib/python3.9/site-packages/Cython/Compiler/ExprNodes.py", line 10113, in result
    self.defaults_struct.lookup(self.arg.name).cname)
AttributeError: 'NoneType' object has no attribute 'cname'
```

### Code to reproduce the behaviour:

```cython
from enum import IntEnum


class SomeEnum(IntEnum):
    SOME = 0

def func(dict a=None, b=SomeEnum.SOME):
    pass
```

### OS

Ubuntu 22.04

### Python version

3.9.7

### Cython version

3.0.1

### Additional context

Interestingly this exception disappears when either parameter of `func()`is removed.

**Comment by scoder** [comment] 2023-08-26 18:59
Duplicate of https://github.com/cython/cython/issues/5643

**Closed by scoder** 2023-08-26 18:59 UTC
Labels: R: duplicate
