### ISSUE TITLE
Combining @staticmethod and @abc.abstractmethod fails at runtime

### ISSUE THREAD

**Issue by DanielHerding** [cython/cython#2651] opened 2018-10-11 07:55 UTC
I'm trying to convert one of my Python modules using Cython. Cython successfully generates a .pyd file, but when I try to import it, it fails:

```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import example
hello 5**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "example.py", line 10, in init example
    @abc.abstractmethod
  File "C:\Program Files\Python3\lib\abc.py", line 23, in abstractmethod
    funcobj.__isabstractmethod__ = True
AttributeError: attribute '__isabstractmethod__' of 'staticmethod' objects is not writable
```

The same error occurs on a different Python version on Linux with a Cython-generated .so file:
```
Python 3.4.2 (default, Sep 25 2018, 22:02:39)
[GCC 4.9.2] on linux
>>> import example
hello 5**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "example.py", line 10, in init example
    @abc.abstractmethod
  File "/usr/lib/python3.4/abc.py", line 25, in abstractmethod
    funcobj.__isabstractmethod__ = True
AttributeError: attribute '__isabstractmethod__' of 'staticmethod' objects is not writable
```

My module contains a method which is both abstract and static:

```
#!python
#cython: language_level=3

import abc

print('hello', 5, end='**\n') # Python3 syntax, breaks on Python2

class c(abc.ABC):
    @staticmethod
    @abc.abstractmethod
    def foo():
        raise NotImplementedError
```

According to https://docs.python.org/3/library/abc.html#abc.abstractmethod this is legal, as long as the `@staticmethod` decorator comes first. If I remove the `@abstractmethod` annotation, I can cythonize and import the module. It also works if i use `@abstractstaticmethod`, but that decorator is deprecated in abc.

Hint: In pure Python, a "`'__isabstractmethod__' of 'staticmethod' objects is not writable`" occurs when placing `@abc.abstractmethod` before `@staticmethod`: https://bugs.python.org/issue16267
Maybe Cython changes the decorator order?

**Comment by SaravananM21** [comment] 2018-11-27 18:55
+1 hit the same issue

**Comment by paperManu** [comment] 2019-03-08 19:52
Same issue here too!

**Comment by scoder** [comment] 2019-03-10 18:24
As a workaround, it should be enough to rename the builtin decorator, e.g. to "asyncstaticmethod".

**Comment by scoder** [comment] 2019-03-30 20:13
Duplicate of #1434.

**Closed by scoder** 2019-03-30 20:13 UTC
Labels: R: duplicate

**Comment by XtremeGood** [comment] 2020-07-07 17:07
AttributeError: attribute '__isabstractmethod__' of 'staticmethod' objects is not writable . Please help. Python 3.7+


```

class GeneralRequestView(TemplateView, ABC):
    template_name = "base/request.html"

    @staticmethod
    @abstractmethod
    def self_name():
        pass

    @staticmethod
    @abstractmethod
    def self_text():
        pass

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form_types"] = [(i.self_name(), i.self_name())
                                 for i in FORM_TYPES]
        return context
    
  
class ProjectRequestView(GeneralRequestView):
    @staticmethod
    def self_name():
        return "base-Project"

    @staticmethod
    def self_text():
        return "Project Request View"
    
    def render_to_response(self, context, **response_kwargs):
        return HttpResponseRedirect(reverse(ProjectRequestView.self_name(), args=(response_kwargs["form_type"],)))
      
```

**Comment by da-woods** [comment] 2020-07-07 17:29
@XtremeGood The bug-tracker is for reporting/diagnosing bugs; not user support. You can try the [cython-users mailing list](https://groups.google.com/forum/#!forum/cython-users) for ideas for working around this bug.

**Comment by XtremeGood** [comment] 2020-07-07 17:32
oops sorry.

**Comment by duyi1990** [comment] 2021-08-09 08:42
+1 hit the same issue
