### ISSUE TITLE
"maximum recursion depth exceeded" in deepcopy() in fresh_finally_clause()

### ISSUE THREAD

**Issue by jdemeyer** [cython/cython#1744] opened 2017-06-21 13:54 UTC
Using Cython master on Python 2.7.13:

This code
```
cdef inline bint g(int x, int y): return True

cdef cython_bug(int u):
    try:
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
        g(u, u)
    finally:
        g(u, u)
```
hits Python's recursion limit of 1000 frames:
```
Traceback (most recent call last):
  File "/usr/local/src/sage-config/local/bin/cython", line 11, in <module>
    load_entry_point('Cython==0.26a0', 'console_scripts', 'cython')()
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 694, in setuptools_main
    return main(command_line = 1)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 711, in main
    result = compile(sources, options)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 686, in compile
    return compile_multiple(source, options)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 664, in compile_multiple
    result = run_pipeline(source, options, context=context)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 494, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 340, in run_pipeline
    data = phase(data)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 53, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython/Compiler/ModuleNode.py", line 137, in process_implementation
    self.generate_c_code(env, options, result)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython/Compiler/ModuleNode.py", line 365, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 418, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 1920, in generate_function_definitions
    self.generate_function_body(env, code)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 1683, in generate_function_body
    self.body.generate_execution_code(code)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 424, in generate_execution_code
    stat.generate_execution_code(code)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 7034, in generate_execution_code
    fresh_finally_clause().generate_execution_code(code)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/Cython/Compiler/Nodes.py", line 7022, in fresh_finally_clause
    node_copy = copy.deepcopy(node)
  File "/usr/local/src/sage-config/local/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/src/sage-config/local/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
[...long traceback involving deepcopy...]
```

It's not an infinite recursion since `sys.setrecursionlimit(2000)` fixes the problem.

**Comment by robertwb** [comment] 2017-06-21 15:48
This works fine for me. Are there some different options/directives I should be passing?

**Comment by jdemeyer** [comment] 2017-06-21 16:47
Maybe it depends on the Python version. Are you using 2.7.13?

**Comment by jdemeyer** [comment] 2017-06-21 16:50
> Are there some different options/directives I should be passing?

No, this is just executing `cython test.pyx` with `test.pyx` the file in the issue description.

**Comment by jdemeyer** [comment] 2017-06-22 08:43
What is worrying here is that the required stack depth is `O(n)` in the number of statements inside the `try` clause.

**Comment by jdemeyer** [comment] 2017-06-22 09:15
```
f8b3405e926d2ba9bc2ee24d79848235875ee12e is the first bad commit
commit f8b3405e926d2ba9bc2ee24d79848235875ee12e
Author: Robert Bradshaw <robertwb@gmail.com>
Date:   Thu Jun 15 15:51:15 2017 -0700

    Don't override unknown inherited __reduce__.
```

**Comment by robertwb** [comment] 2017-06-23 04:41
Yeah, that is worrying. I built a fresh 2.7.13 Python and cloned a fresh branch of cython/master and I still can't reproduce, e.g.

`python cython.py lots_of_asserts.pyx`

works just fine for me, even doubling the number of asserts.

**Comment by jdemeyer** [comment] 2017-06-23 08:04
Well, Sage is using a slightly patched version of Python 2.7.13 so it could always be that some of those patches are relevant. I'll investigate further.

**Comment by jdemeyer** [comment] 2017-06-23 08:33
It is failing on Travis CI, see #1745.

Could it be OS-specific? I'm on Linux and I guess Travis CI also.

**Comment by robertwb** [comment] 2017-06-23 08:46
I tried that test (thanks) on two separate Linux (Ubuntu) installs as well as my OS X laptop, and had no issues. But I do see the error up on Travis. The code touched at f8b3405e926d2ba9bc2ee24d79848235875ee12e shouldn't even get invoked if there aren't any cdef classes, so something really strange is going on here...

**Comment by robertwb** [comment] 2017-06-23 08:56
Here it's actually copying the finally clause, which shouldn't be sensitive to the size of the body. (I've always considered literally copying the finally for each exit to be a bit hackish though...maybe this will be the motivation to re-write, though I'd like to understand why there's such a deep stack here.)

**Comment by robertwb** [comment] 2017-07-06 08:43
I finally figured it out--the repro required a compiled Cython (which is also why the pickling code was actually involved). 

This should be fixed at https://github.com/cython/cython/commit/114fe16bdaa527bb5024c975a8accfc1e052ab68

**Comment by jdemeyer** [comment] 2017-07-06 09:17
Nice!

**Closed** 2017-07-06 19:04 UTC
