### ISSUE TITLE
Python 3.7: from __future__ import annotations

### ISSUE THREAD

**Issue by matkuki** [cython/cython#2950] opened 2019-05-08 07:26 UTC
Hi,

I'm on Windows 10, Python 3.7.1, Cython 0.29.7.

I have some pure python code that I wanted to compile that uses
`from __future__ import annotations`, but compiling it throws:
```
Error compiling Cython file:
------------------------------------------------------------
...
# -*- coding: utf-8 -*-

from __future__ import annotations
                      ^
------------------------------------------------------------

app.py:6:23: future feature annotations is not defined
Traceback (most recent call last):
  File "D:\app\compile_with_cython.py", line 59, in <module>
    main()
  File "D:\app\compile_with_cython.py", line 54, in main
    language_level=3,
  File "C:\Python37\lib\site-packages\Cython\Build\Dependencies.py", line 1097, in cythonize
    cythonize_one(*args)
  File "C:\Python37\lib\site-packages\Cython\Build\Dependencies.py", line 1220, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: app/app.py
```
It is used to type annotate some `self` method parameters that need to reference itself.
I'm guessing that this is a not yet supported feature of CPython 3.7? Is there a way to bypass this without removing the `from __future__ import annotations` code?

Matic

**Comment by scoder** [comment] 2019-05-19 17:36
Duplicate of #2863.

**Closed by scoder** 2019-05-19 17:36 UTC

**Comment by shaolo1** [comment] 2020-03-18 21:40
#2863 made it into Cython version 0.29.15, but the reported issue is still a problem (ie, was not a duplicate).

Still generates future feature annotations is not defined error.

**Comment by McSinyx** [comment] 2020-03-19 04:04
I'm not sure if I get the problem correctly, but `from __future__ import annotations` is basically a CPython hack to get a Python 4 behavior.  With GH-3285 merged, this can be achieved by setting `binding=True`.

**Comment by da-woods** [comment] 2020-03-19 08:55
@McSinyx The problem is that `from __future__ import annotations` should still be valid code. Although the feature is always enabled in Cython (post https://github.com/cython/cython/pull/3285)  the `__future__` statement shouldn't break anything.

However @shaolo1 as far as I can tell it didn't make it in to 0.29.15. It's in the changelog for Cython 3.0. Given that 0.29.x doesn't support to, generating an error message is the correct behaviour. If you download the "master" branch it'll work.

**Comment by scoder** [comment] 2020-03-19 11:49
> should still be valid code

Yes. It should just be ignored, as with all outdated "future" imports.

**Comment by da-woods** [comment] 2020-03-19 12:02
> > should still be valid code
> 
> Yes. It should just be ignored, as with all outdated "future" imports.

Yes - that is what happens (in the master branch).

**Comment by shaolo1** [comment] 2020-03-19 14:07
@McSinyx enabling binding did not fix the problem.  (also tried setting on command line with cython -X binding=True foo.py)

# cython: language_level=3, binding=True

from __future__ import annotations
                      ^
------------------------------------------------------------

foo.py:3:23: future feature annotations is not defined

**Comment by McSinyx** [comment] 2020-03-19 14:27
@shalolo1, I think as mentioned above, it is fixed in `master`.  What I say was that enabling `binding` gives you the same effect.

**Comment by shaolo1** [comment] 2020-03-19 14:35
@McSinyx I tried enabling binding as you suggested.  It did not help.  So, I guess I'm confused as to what binding has to do with it.

**Comment by shaolo1** [comment] 2020-03-19 14:39
@da-woods, @McSinyx  Yes, using master does indeed ignore the import (and setting binding was not required).  Thanks!

**Comment by da-woods** [comment] 2020-03-19 14:44
@shaolo1 Glad to know you have it fixed.

Just to try to clarify: the effect of "binding" is to make functions defined in Cython look more like a regular Python function. I think it's necessary for `__annotations __` to appear as an attribute of the function (but I'm not completely sure). It's enabled by default on `def` functions anyway.

It isn't required for the `__future__` statement to work.

**Comment by 8greg8** [comment] 2020-04-07 15:44
> @da-woods, @McSinyx Yes, using master does indeed ignore the import (and setting binding was not required). Thanks!

I'm using the latest master 30c891e0dc36a553455df9064ecb1f13414a12d2 and getting the same error.

**Comment by dzpt** [comment] 2020-08-24 10:33
python 3.8.1
cython 0.29.21
still get this error

**Comment by scoder** [comment] 2020-08-24 13:47
@dzpt use Cython 3.0 (in which case you don't need it because it's the default, but at least you won't get an exception for it).
Cython 0.29 will not support this.
