### ISSUE TITLE
Cython and python 3.8 walrus operator

### ISSUE THREAD

**Issue by spmsh** [cython/cython#3672] opened 2020-06-09 08:01 UTC
Hi,

Didn't find anything about walrus operator issue in the existing issues, so posting a new here.

I am getting the error when trying to "cythonize" my code that uses the new introduced walrus operator `:=` in python 3.8

`
if user_to_register := User.query.filter(User.pin_code == user_input).first():
`

*------------------------------------------------------------
app\navigator\utils.py:24:25: Expected an identifier or literal
Traceback (most recent call last):
  File "cythonize.py", line 22, in <module>
    ext_modules=cythonize(
  File "D:\CODE\oomnis\FLEXO\FLEXO-PORTAL\venv38\lib\site-packages\Cython\Build\Dependencies.py", line 1110, in cythonize
    cythonize_one(*args)
  File "D:\CODE\oomnis\FLEXO\FLEXO-PORTAL\venv38\lib\site-packages\Cython\Build\Dependencies.py", line 1277, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: app/navigator\utils.py
*------------------------------------------------------------

If I remove the walrus operator, then all is fine:

```
user_to_register = User.query.filter(User.pin_code == user_input).first()
if user_to_register:
```

Is there anything I can do to keep my code with the walrus operator and still be able to cythonize it ?

Using:
- Python **3.8.2** (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
- Cython Version: **3.0a5** (also tried with cython **0.29.19** and get same error)

Thanks.

**Comment by scoder** [comment] 2020-06-09 08:45
Duplicate of #2636.

**Closed by scoder** 2020-06-09 08:45 UTC
