### ISSUE TITLE
[BUG] Exponentiations with function parameters return double as result

### ISSUE THREAD

**Issue by loocars** [cython/cython#5713] opened 2023-09-20 17:05 UTC
### Describe the bug

When using a function parameter as an exponent the type is not correctly inferred even if it is statically typed.

### Code to reproduce the behaviour:

Code:
```cython
cdef main(int n):
  cdef int iterations = 2**n
  for _ in range(iterations):
    ...
```

Compiler Output:
```
cdef main(int n):
    cdef int iterations = 2**n
                           ^
------------------------------------------------------------

binary_trees.pyx:17:27: Cannot assign type 'double' to 'int'
```

Fix:
```cython
cdef main(int n):
  cdef int iterations = int(2**n)
  for _ in range(iterations):
    ...
```

### Expected behaviour

It should not be necessary to add the int() cast

### OS

Linux

### Python version

3.11

### Cython version

3.0.2

**Comment by da-woods** [comment] 2023-09-20 18:35
The is working as intended (and a breaking change in Cython 3). If `n` is negative then the result won't be integer, therefore the result can't be integer.

You can restore the old behaviour using the `cpow` directive (https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives).

I think we were a bit cleverer about guessing user intent with double**double exponents (which now become complex) - in this case we'd assume you wanted the old behaviour because of what you assigned it to. In hindsight we possibly should have done the same for `int`, but I don't think we want to go back and start adding new cases - it's complicated enough already.

**Closed by da-woods** 2023-09-20 18:35 UTC

**Comment by scoder** [comment] 2023-09-20 19:37
> we'd assume you wanted the old behaviour because of what you assigned it to. In hindsight we possibly should have done the same for `int`

The question is whether we'd hide bugs on user side that way. If someone called `main(-3)` above, we'd have to raise a runtime exception, or do something else that would avoid returning an unexpected value from the computation. It's easy to forget that something as ubiquitous and innocent as `int` can trigger an invalid computation on exponentiation.
