### ISSUE TITLE
memory view over 'bytes', incorrect doc?

### ISSUE THREAD

**Issue by leftys** [cython/cython#1682] opened 2017-04-23 11:35 UTC
Hi! I was trying to write a function accepting string/bytes and returning string/bytes again. I found an example of accepting strings in the documentation: https://cython.readthedocs.io/en/latest/src/tutorial/strings.html#accepting-strings-from-python-code

but it doesn't work:

```
def process_byte_data(unsigned char[:] data):
    length = data.shape[0]
    first_byte = data[0]
    slice_view = data[1:-1]

b = b'asd'
process_byte_data(b)
```

results in 

> BufferError: Object is not writable.

(Relevant topic in mailing list: https://groups.google.com/d/topic/cython-users/32CMgaLrNhc/discussion)

**Comment by gnbl** [comment] 2017-11-21 06:48
Likely a duplicate of #1605.

**Comment by JonasT** [comment] 2018-10-12 01:48
So will the documentation be updated or not? Because the docs still claim `unsigned char[:]` works for bytes.

Or does this actually work in a newer version of Cython now?

**Comment by TeamSpen210** [comment] 2018-10-12 09:33
You need to specify it as `const`, since `bytes` is readonly. That should probably be highlighted more in the tutorial.

**Comment by JonasT** [comment] 2018-10-12 09:37
The tutorial currently doesn't mention this **at all**, so yeah, it really should! It suggests `unsigned char[:]` right after saying "well you want to support bytearray, bytes, string, all of that!" without any note that doesn't actually support all of those, so it is very misleading right now. (At least was for me, it is a bit subjective after all)

**Closed** 2020-01-30 10:14 UTC
Labels: Documentation
