### ISSUE TITLE
With default language_level and Python 3 runtime: surprising size_t division results

### ISSUE THREAD

**Issue by kadler15** [cython/cython#2728] opened 2018-11-21 22:56 UTC
Test program:

```
def run():
  test_list = ['a']
  test_list_len = len(test_list)
  div1 = 1/(test_list_len + 1)
  div2 = 1/(len(test_list) + 1)
  print(div1)
  print(div2)
```

Results of test.run() in Python 3.5.2, it's clear the results of `div1` and `div2` are not the same:
```
0.5
0
```

Here is the C code generated for each line:
```
  /* "test.py":4
 *   test_list = ['a']
 *   test_list_len = len(test_list)
 *   div1 = 1/(test_list_len + 1)             # <<<<<<<<<<<<<<
 *   div2 = 1/(len(test_list) + 1)
 *   print(div1)
 */
  __pyx_t_1 = __Pyx_PyInt_AddObjC(__pyx_v_test_list_len, __pyx_int_1, 1, 0); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 4, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_t_3 = __Pyx_PyNumber_Divide(__pyx_int_1, __pyx_t_1); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 4, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_3);
  __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;
  __pyx_v_div1 = __pyx_t_3;
  __pyx_t_3 = 0;
```

```
  /* "test.py":5
 *   test_list_len = len(test_list)
 *   div1 = 1/(test_list_len + 1)
 *   div2 = 1/(len(test_list) + 1)             # <<<<<<<<<<<<<<
 *   print(div1)
 *   print(div2)
 */
  __pyx_t_2 = PyList_GET_SIZE(__pyx_v_test_list); if (unlikely(__pyx_t_2 == ((Py_ssize_t)-1))) __PYX_ERR(0, 5, __pyx_L1_error)
  __pyx_t_4 = (__pyx_t_2 + 1);
  if (unlikely(__pyx_t_4 == 0)) {
    PyErr_SetString(PyExc_ZeroDivisionError, "integer division or modulo by zero");
    __PYX_ERR(0, 5, __pyx_L1_error)
  }
  else if (sizeof(Py_ssize_t) == sizeof(long) && (!(((Py_ssize_t)-1) > 0)) && unlikely(__pyx_t_4 == (Py_ssize_t)-1)  && unlikely(UNARY_NEG_WOULD_OVERFL$
    PyErr_SetString(PyExc_OverflowError, "value too large to perform division");
    __PYX_ERR(0, 5, __pyx_L1_error)
  }
  __pyx_v_div2 = __Pyx_div_Py_ssize_t(1, __pyx_t_4);
```

I can see that `__Pyx_PyNumber_Divide` changes based on the detected Python runtime, while `__Pyx_div_Py_ssize_t` is the same in either runtime:

```
static CYTHON_INLINE Py_ssize_t __Pyx_div_Py_ssize_t(Py_ssize_t a, Py_ssize_t b) {
    Py_ssize_t q = a / b;
    Py_ssize_t r = a - q*b;
    q -= ((r != 0) & ((r ^ b) < 0));
    return q;
}
```

I plan to set `'language_level': 3` in my compiler directives, because this will suit my needs, but I was pretty surprised by the behavior. I expected both lines to use int division or float division, but not a mixture!

**Comment by kadler15** [comment] 2018-11-21 23:57
Related, the behavior of `div0 = 1 / 2`:

```
  /* "test.py":3
 * def run():
 *   len1 = len([1, 2])
 *   div0 = 1 / 2             # <<<<<<<<<<<<<<
 *   div1 = 1 / len1
 *   div2 = 1 / len([1, 2])
 */
  __pyx_v_div0 = 0;
```
So the generated code is optimized to 0, which is unexpected with Python 3.

**Comment by scoder** [comment] 2018-11-23 21:37
This is due to type inference.
```
def run():
  test_list = ['a']
  test_list_len = len(test_list)   # -> result is `Py_ssize_t`
  div1 = 1/(test_list_len + 1)    # -> representing `test_list_len` as C integer is unsafe (can overflow)
  div2 = 1/(len(test_list) + 1)    # -> result of `len()` is `Py_ssize_t`, expression is evaluated in C
  print(div1)
  print(div2)
```
If you typed `test_list_len` as `Py_ssize_t`, you would get the same (C-ish) result for both. Cython's (safe) type inference decides that it cannot safely type `test_list_len` as C integer and therefore calculates it in Python space, where the result depends on the runtime Python version.

Do I understand correctly that you did not yet enable 'language_level=3` in the example above?

**Comment by scoder** [comment] 2018-11-23 21:44
When I try it (with the latest master and `language_level=3`), I get a float result for `div2`, as expected. Closing as not a bug.

**Closed by scoder** 2018-11-23 21:44 UTC
Labels: R: worksforme

**Comment by kadler15** [comment] 2018-11-27 00:41
Thanks for your response. You're correct that I had not enabled `language_level=3` in the example above. With `language_level=3` I get a float result for both `div1` and `div2`. With `language_level=2` with Python 3 runtime, I get a float for `div1` and what looks like an int for `div2`.
