### ISSUE TITLE
Is it possible to generate an AST for Cython file

### ISSUE THREAD

**Issue by kush96** [cython/cython#3732] opened 2020-07-07 13:38 UTC
i was going through the code base to check if it is possible to generate an AST for a cython file (pyx pxd or pxi), passing the source code string as input to some method within the project. My goal was to traverse the ast for basic source code analysis like getting number of imports , counting loops etc.

**Comment by da-woods** [comment] 2020-07-07 13:41
Duplicate of https://github.com/cython/cython/issues/1628

**Closed by da-woods** 2020-07-07 13:41 UTC

**Comment by da-woods** [comment] 2020-07-07 13:44
There's a few similar issues in the issue tracker (e.g. https://github.com/cython/cython/issues/3462).

The upshot is "not really officially", although it probably would be possible to use Cython's parser and take the output of that. I think it's something that we're reluctant to support officially since it commits us to providing a stable API rather that generating whatever is most useful for Cython's purposes.
