### ISSUE TITLE
[BUG] Cython 3 regression when using Python 3 typehints - runs 10x slower

### ISSUE THREAD

**Issue by mattharrison** [cython/cython#5811] opened 2023-11-11 03:03 UTC
### Describe the bug

When I convert my code to type annotated syntax, it runs much slower. (10X in my case):

code to reproduce:
```python
import numpy as np # 1.23.5
import pandas as pd # 2.1.1
import cython # 3.0.4

import io
billing_data = \
'''cancel_date,period_start,start_date,end_date,rev,sum_payments
12/1/2019,1/1/2020,12/15/2019,5/15/2020,999,50
,1/1/2020,12/15/2019,5/15/2020,999,50
,1/1/2020,12/15/2019,5/15/2020,999,1950
1/20/2020,1/1/2020,12/15/2019,5/15/2020,499,0
,1/1/2020,12/24/2019,5/24/2020,699,100
,1/1/2020,11/29/2019,4/29/2020,799,250
,1/1/2020,1/15/2020,4/29/2020,799,250'''

def tweak_bill202(df_):
    return (df_
            .assign(cancel_date=pd.to_datetime(
                df_.cancel_date.replace('<NA>', ''), format='%m/%d/%Y')
                   )
           )

bill_df = tweak_bill202(pd.read_csv(io.StringIO(billing_data),
    dtype_backend='pyarrow',                 
    parse_dates=['cancel_date', 'period_start', 'start_date',
                 'end_date']))
bill_100k = bill_df.sample(100_000, replace=True)

# this is the code I want to cythonize
def calc_unbilled_rec(vals):
    cancel_date, period_start, start_date, end_date, rev, \
         sum_payments = vals
    if cancel_date < period_start:
        return np.nan#float('nan')
    if start_date < period_start and end_date > period_start:
        if rev > sum_payments:
            return rev - sum_payments
        else:
            return 0
```

Here is my *fast* cython code:

```
%%cython

cimport cython
import numpy as np
cimport numpy as np

@cython.boundscheck(False)
@cython.wraparound(False)
cpdef calc_unbilled_cy(np.ndarray[np.int64_t] cancel_date, 
                        np.ndarray[np.int64_t] period_start, 
                        np.ndarray[np.int64_t] start_date, 
                        np.ndarray[np.int64_t] end_date, 
                        np.ndarray[np.int64_t] rev, 
                        np.ndarray[np.int64_t] sum_payments):
    cdef np.ndarray[np.float64_t ] results = np.full(rev.shape[0], np.nan, dtype=np.float64)
    cdef long cd, pd, sd, ed;
    for i in range(rev.shape[0]):
        cd = cancel_date[i]
        ps = period_start[i]
        sd = start_date[i]
        ed = end_date[i]
        if cd > 0 and cd < ps:
            continue
        elif sd < ps < ed:
            if rev[i] > sum_payments[i]:
                results[i] = rev[i] - sum_payments[i]
            else:
                results[i] = 0
    return results

```

Here is the slow code. I just changed the type annotations to Python 3:

```
%%cython

import cython
import numpy as np

@cython.boundscheck(False)
@cython.wraparound(False)
def calc_unbilled_cy2(cancel_date: np.ndarray[np.int64_t],
                    period_start: np.ndarray[np.int64_t],
                    start_date: np.ndarray[np.int64_t],
                    end_date: np.ndarray[np.int64_t],
                    rev: np.ndarray[np.int64_t],
                    sum_payments: np.ndarray[np.int64_t]):
    results: np.ndarray[np.float64_t] = np.full(rev.shape[0], np.nan, dtype=np.float64)
    i: cython.int
    
    for i in range(rev.shape[0]):
        cd:cython.long = cancel_date[i]
        ps:cython.long = period_start[i]
        sd:cython.long = start_date[i]
        ed:cython.long = end_date[i]
        if cd > 0 and cd < ps:
            continue
        elif sd < ps < ed:
            if rev[i] > sum_payments[i]:
                results[i] = rev[i] - sum_payments[i]
            else:
                results[i] = 0
    return results

```

### Code to reproduce the behaviour:

This is fast

```pycon
>>> %%timeit
>>> calc_unbilled_cy(*(ser.astype(int).to_numpy() for name, ser in bill_100k.items()))
```

This is slow
```pycon
>>> %%timeit
>>> calc_unbilled_cy2(*(ser.astype(int).to_numpy() for name, ser in bill_100k.items()))
```

### Expected behaviour

The code using Python 3 annotations runs at the same speed as the "cython" code.

### OS

mac02

### Python version

3.10.13

### Cython version

3.0.4

**Comment by da-woods** [comment] 2023-11-11 09:30
My guess would be that `np.ndarray[np.int64_t]` isn't handled when in an annotation. Part of the issue is that  the full np.ndarray syntax isn't valid Python Syntax (e.g `np.ndarray[np.int64_t, ndim=2]` so can't really go in an annotation.

Although you aren't using that here, I think it's the reason we haven't yet supported that feature in annotations.

**Comment by scoder** [comment] 2023-11-11 14:39
> `np.ndarray[np.int64_t]` isn't handled when in an annotation.

Right. The canonical answer is: use memoryviews.

**Comment by mattharrison** [comment] 2023-11-30 00:10
Here's my attempt at using memory views. It appears to compile fine but gives a `NameError` when running:

```python
%%cython

import cython
import numpy as np

@cython.boundscheck(False)
@cython.wraparound(False)
def calc_unbilled_cy3(cancel_date: cython.long[:],
        period_start: cython.long[:],
        start_date: cython.long[:],
        end_date: cython.long[:],
        rev: cython.long[:],
        sum_payments: cython.long[:]) -> cython.double[:]:
    results: cython.double[:] = np.full(rev.shape[0], np.nan, 
                                        dtype=cython.double)
    i: cython.int
    
    for i in range(rev.shape[0]):
        cd:cython.long = cancel_date[i]
        ps:cython.long = period_start[i]
        sd:cython.long = start_date[i]
        ed:cython.long = end_date[i]
        if cd > 0 and cd < ps:
            continue
        elif sd < ps < ed:
            if rev[i] > sum_payments[i]:
                results[i] = rev[i] - sum_payments[i]
            else:
                results[i] = 0
    return results

```

Result:
```
>>> %%timeit
>>> calc_unbilled_cy3(*(ser.astype(int).to_numpy() for name, ser in bill_100k.items()))
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[12], line 1
----> 1 get_ipython().run_cell_magic('timeit', '', 'calc_unbilled_cy3(*(ser.astype(int).to_numpy() for name, ser in bill_100k.items()))\n')

File ~/.envs/menv/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2422, in InteractiveShell.run_cell_magic(self, magic_name, line, cell)
   2420 with self.builtin_trap:
   2421     args = (magic_arg_s, cell)
-> 2422     result = fn(*args, **kwargs)
   2423 return result

File ~/.envs/menv/lib/python3.10/site-packages/IPython/core/magics/execution.py:1162, in ExecutionMagics.timeit(self, line, cell, local_ns)
   1160 for index in range(0, 10):
   1161     number = 10 ** index
-> 1162     time_number = timer.timeit(number)
   1163     if time_number >= 0.2:
   1164         break

File ~/.envs/menv/lib/python3.10/site-packages/IPython/core/magics/execution.py:156, in Timer.timeit(self, number)
    154 gc.disable()
    155 try:
--> 156     timing = self.inner(it, self.timer)
    157 finally:
    158     if gcold:

File <magic-timeit>:1, in inner(_it, _timer)

File _cython_magic_e06ed44ab6c6521b766c7429289f0b3928f3e961.pyx:14, in _cython_magic_e06ed44ab6c6521b766c7429289f0b3928f3e961.calc_unbilled_cy3()

NameError: name 'cython' is not defined
```

**Comment by da-woods** [comment] 2023-11-30 07:04
`dtype=cython.double` -> `dtype=np.float64`.

This isn't a compile-time directive for Cython but if just an object you're passing to Numpy at runtime

**Comment by mattharrison** [comment] 2023-11-30 07:24
@da-woods 🙏🤦‍♀️

**Comment by scoder** [comment] 2023-11-30 08:35
> ```python
>     results: cython.double[:] = np.full(rev.shape[0], np.nan, 
>                                         dtype=cython.double)
> ```

I thought about allowing this but am against it because it would almost never do what users expect. You really want an explicit `np.float64` here, not just a Python `float` type that this could map to. Even worse, you'd get a bare Python `int` type instead of a specific native integer type if we allowed `cython.int` etc.

We should make sure that we warn about such a usage, though. Or even error out on left-over usages of `cython.*` after replacing all valid usages.

**Comment by scoder** [comment] 2023-11-30 08:37
I'm closing this as "won't fix" because we're not planning to support the old buffer notation in Python syntax.

**Closed by scoder** 2023-11-30 08:37 UTC
Labels: R: wontfix

**Comment by scoder** [comment] 2023-11-30 08:41
> ```python
> @cython.boundscheck(False)
> @cython.wraparound(False)
> def calc_unbilled_cy3(cancel_date: cython.long[:],
>         period_start: cython.long[:],
>         start_date: cython.long[:],
>         end_date: cython.long[:],
>         rev: cython.long[:],
>         sum_payments: cython.long[:]) -> cython.double[:]:
>     results: cython.double[:] = np.full(rev.shape[0], np.nan, 
>                                         dtype=np.float64)
>     i: cython.int
>     
>     for i in range(rev.shape[0]):
>         cd:cython.long = cancel_date[i]
>         ps:cython.long = period_start[i]
>         sd:cython.long = start_date[i]
>         ed:cython.long = end_date[i]
> ```

Note, BTW, that this is dangerous code. You have disabled `boundscheck` but without validating the bounds yourself. If someone passes views of different lengths into the six arguments, you will get invalid memory reads and likely also crashes. Always make sure that you remove safety belts only if you know that you won't need them.

If you have further questions, please ask them on the cython-users mailing list. The bug tracker is not the right place.

**Comment by mattharrison** [comment] 2023-11-30 08:57
Got it. I put my code here for future searchers who run into the same issue.
