### ISSUE TITLE
AssertionError:  (__pyx_v_id == ((unsigned char *)NULL)) && PyErr_Occurred()

### ISSUE THREAD

**Issue by Flexximo** [cython/cython#3749] opened 2020-07-22 08:15 UTC
In my .pyx file I have following structure declarations where to be stored C++ **uuid8_t[16]** data.

```
cdef extern from "uuid/uuid.h":
    ctypedef unsigned char uuid_t[16]

cdef extern from "fr_common.h":
    cdef:
        int UUID_SIZE = 16
        const int FR_DETECTION_LANDMARKS_COUNT = 5
        const int FR_PLANE_COUNT_MAX = 8

    ctypedef uuid_t fr_id_t

    ctypedef struct fr_object_t:
        fr_id_t id
        fr_descriptor_t descriptor
        fr_detection_t detection
        fr_image_t snapshot
```

These stucture, e. i., `fr_object_t is going to be filled with valid data with C++ functions of course. For **fr_object_t** I have following.

```cdef class FrObject:
    cdef:
        fr_id_t _id
        Descriptor _descriptor
        Detection _detection
        Image _snapshot

    def __cinit__(self, fr_id_t id, Descriptor descriptor, Detection detection, Image snapshot):
        self._id = id
        self._descriptor = descriptor
        self._detection = detection
        self._snapshot = snapshot

    @staticmethod
    cdef FrObject from_c(fr_object_t fr_object):
        return FrObject(
            fr_object.id,
            Descriptor.from_c(fr_object.descriptor),
            Detection.from_c(fr_object.detection),
            Image.from_c(fr_object.snapshot),
        )
```
So while compiling the .pyx file into .so file I caught the following traceback of error.
```
WARNING: The wheel package is not available.
running install
running bdist_egg
running egg_info
writing teye_fr.egg-info/PKG-INFO
writing dependency_links to teye_fr.egg-info/dependency_links.txt
writing top-level names to teye_fr.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'teye_fr.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying teyefr/_teyefr.pyx -> build/lib.linux-x86_64-3.8/teyefr
running build_ext
cythoning teyefr/_teyefr.pyx to teyefr/_teyefr.cpp
/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/dmitriyravdel/teyefr/teye-fr/python/teyefr/_teyefr.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    setuptools.setup(
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib64/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/setuptools/command/bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/setuptools/command/bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "/usr/lib64/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib64/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/usr/lib64/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib64/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 346, in cython_sources
    result = cython_compile(source, options=options,
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Main.py", line 778, in compile
    return compile_single(source, options, full_module_name)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Main.py", line 727, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Main.py", line 515, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
    data = run(phase, data)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
    return phase(data)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/ModuleNode.py", line 143, in process_implementation
    self.generate_c_code(env, options, result)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/ModuleNode.py", line 385, in generate_c_code
    self.body.generate_function_definitions(env, code)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 442, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 442, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 4853, in generate_function_definitions
    self.body.generate_function_definitions(self.scope, code)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 442, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 442, in generate_function_definitions
    stat.generate_function_definitions(env, code)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 3173, in generate_function_definitions
    self.py_wrapper.generate_function_definitions(env, code)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 3360, in generate_function_definitions
    self.generate_argument_parsing_code(lenv, code)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 3507, in generate_argument_parsing_code
    self.generate_tuple_and_keyword_parsing_code(self.args, end_label, code)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 3752, in generate_tuple_and_keyword_parsing_code
    self.generate_arg_assignment(arg, "values[%d]" % i, code)
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/Nodes.py", line 3779, in generate_arg_assignment
    code.putln(arg.type.from_py_call_code(
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/PyrexTypes.py", line 511, in from_py_call_code
    return self.typedef_base_type.from_py_call_code(
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/PyrexTypes.py", line 511, in from_py_call_code
    return self.typedef_base_type.from_py_call_code(
  File "/home/dmitriyravdel/teyefr/teye-fr/frtester/.venv/lib64/python3.8/site-packages/Cython/Compiler/PyrexTypes.py", line 2486, in from_py_call_code
    assert not error_condition, '%s: %s' % (error_pos, error_condition)
AssertionError: (<FileSourceDescriptor:/home/dmitriyravdel/teyefr/teye-fr/python/teyefr/_teyefr.pyx>, 356, 24): (__pyx_v_id == ((unsigned char *)NULL)) && PyErr_Occurred()

```
Seems like a bag according to stackoverflow review.

**Comment by da-woods** [comment] 2020-07-22 16:37
Duplicate of https://github.com/cython/cython/issues/2517

Thanks for reporting it.

**Closed by da-woods** 2020-07-22 16:37 UTC
