### ISSUE TITLE
[ENH] Pylance support

### ISSUE THREAD

**Issue by alexreg** [cython/cython#4752] opened 2022-04-21 00:31 UTC
It would be great to get Pylance support for Cython. See [this issue](https://github.com/microsoft/pylance-release/issues/674), and in particular [the following comment](https://github.com/microsoft/pylance-release/issues/674#issuecomment-1104545520) by @erictraut (pylance author/maintainer).

> I think the right answer here is for Cython toolchain to add support for generating stub files with docstrings. Those stubs can then be distributed along with the library. Any other approach I can think of (including scraping based on runtime reflection) will produce results that leave significant gaps in terms of completeness and correctness. The maintainers of Cython are in a much better place to do this work than the Pylance team. We are happy to work with the Cython community in an advisory manner.

**Comment by scoder** [comment] 2022-04-21 04:21
Duplicate of #3150

**Closed by scoder** 2022-04-21 04:21 UTC
