### ISSUE TITLE
cython requires visual c++ 14.0

### ISSUE THREAD

**Issue by TheSiker** [cython/cython#4598] opened 2022-01-27 19:07 UTC
Whenever i try to compile, Cython requires Visual c++ 14.0.
How do i fix it?
Log:
`C:\Users\fanda\OneDrive\Dokumenter\Blazing>python setup.py build_ext --inplace
running build_ext
building 'hello' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads
`

**Comment by mattip** [comment] 2022-01-27 19:15
Cython converts python-like code to C. In order to compile the C you must have a C/C++ compiler installed. When one cannot be found, python suggests the python that was used to compile your python. At the time your python was released, that link led to the correct compiler. But in your case this is Visual 14.0, or [visual studio 2015](https://en.wikipedia.org/wiki/Microsoft_Visual_Studio) which is quite old. You can try to dig around here https://visualstudio.microsoft.com/vs/older-downloads/ to find that version, or try your luck with a newer compiler.

**Comment by scoder** [comment] 2022-01-27 19:21
Are you using Python 2.7? That requires such an old MSVC version. If you can, use Python 3.x instead.

**Comment by scoder** [comment] 2022-01-27 19:22
Closing as not a bug. This is not a Cython issue but a general problem with distutils.

**Closed by scoder** 2022-01-27 19:22 UTC
Labels: support question
