### ISSUE TITLE
[BUG] Incorrect result for power operation with integer literals

### ISSUE THREAD

**Issue by alex-stefa** [cython/cython#3911] opened 2020-11-17 21:43 UTC
There may be deeper issues, but I discovered that the power operation between an **integer literal base** and a **negative integer literal exponent** produces 0 instead of the correct floating point result such as in CPython. 

**To Reproduce**
```cython
print(10 ** -2)
```
The above prints 0 after passing the code through cythonize with -3 option.

**Expected behavior**
Expecting 0.01 according to the [language spec](https://docs.python.org/3/reference/expressions.html#the-power-operator).

Curiously, these work as expected:
```cython
b = 10
print(b ** -2)

e = -2
print(10 ** e)
```

**Environment (please complete the following information):**
 - OS: Linux
 - Python version 3.6.8
 - Cython version 0.29.21 and 0.29.13

**Additional context**
This seems to be a somewhat known issue. I've seen #2866 and #687 (links pointing to the old discussion no longer work). Is there a solution or workaround?

**Comment by scoder** [comment] 2020-11-17 21:52
Duplicate of #2133.

**Closed by scoder** 2020-11-17 21:52 UTC

**Comment by alex-stefa** [comment] 2020-11-17 22:14
For other readers, it's not obvious from #2133 what the conclusion is. By #2868 it's apparently fixed in Cython 3, now in alpha.
