### ISSUE TITLE
Erase returns void in cython unordered_map.pxd

### ISSUE THREAD

**Issue by MichaelWS** [cython/cython#1901] opened 2017-09-29 19:35 UTC
https://github.com/cython/cython/blob/master/Cython/Includes/libcpp/unordered_map.pxd

Erase returns void in the pxd.  In C++, it returns an iterator in these cases.  Can I issue a pull request to make it
iterator erase(iterator)

**Comment by scoder** [comment] 2017-09-29 19:46
See https://github.com/cython/cython/pull/1490

**Comment by scoder** [comment] 2017-09-29 19:46
Duplicate of #1484.

**Closed by scoder** 2017-09-29 19:46 UTC

**Comment by MichaelWS** [comment] 2017-09-29 19:54
sorry removing.  Thank you
