### ISSUE TITLE
Cython wrongfully parses 4**(-2)*3

### ISSUE THREAD

**Issue by Volker-Weissmann** [cython/cython#3564] opened 2020-04-30 16:24 UTC
Let the contents of "test.pyx" be `print(4**(-2)*3)`.
If you run `python test.pyx` it outputs 0.1875 (as it should).
If you compile it with cython and run it, it outputs 0, which is wrong.

**Comment by scoder** [comment] 2020-04-30 17:24
Duplicate of #2133. Did you try the 3.0 alpha releases?

**Closed** 2020-04-30 17:34 UTC
Labels: R: duplicate
