### ISSUE TITLE
Why cython+pypy combination env using diskcache arises error: AttributeError: 'builtin_function_or_method' object has no attribute '__qualname__' 

### ISSUE THREAD

**Issue by bsnresearcher** [cython/cython#5182] opened 2022-12-20 06:50 UTC
An env of either Cython or pypy only have not raised this error. 
However, an env installed both pypy+cython raised this error.

The standalone env of either pypy and cython can run correctly is equivalent that each mechanism can deal with __qualname__ method. However, the env installed both cannot deal with that I expected.

Please give me any solution for this problem.

# env
    - pypy: 7.3.9(v3.9.12) via miniconda
    - CPython: 3.9.15
    - diskcache: 0.5.4
    - Cython==0.29.32
    - MacOS: 12.6.2

# PyPy Only Env
- source: try1_diskcache_pypy_try.py

```python
from diskcache import FanoutCache
cache = FanoutCache()
@cache.memoize(typed=True, expire=1, tag='fib')
def fibonacci(number):
    if number == 0:
        return 0
    elif number == 1:
        return 1
    else:
        return fibonacci(number - 1) + fibonacci(number - 2)
print(sum(fibonacci(value) for value in range(100)))
```

```bash
# Run by PyPy
pypy try1_diskcache_pypy_try.py 
573147844013817084100
```

## Env of CPython+Cython or PyPy+Cython

- source: `try2_diskcache.pyx`
```python
# cython: language_level=3

from diskcache import FanoutCache
cache = FanoutCache()
@cache.memoize(typed=True, expire=1, tag='fib')
def fibonacci(number):
    if number == 0:
        return 0
    elif number == 1:
        return 1
    else:
        return fibonacci(number - 1) + fibonacci(number - 2)
```

- source: try2_main.py
```python
# cython: language_level=3
import cython
import pyximport;pyximport.install()
from try2_diskcache import fibonacci
print(sum(fibonacci(value) for value in range(100)))
```

- Result by CPython installed cython
```text
> python try2_main.py 
573147844013817084100
```

- Result by PyPy installed cython
```bash
pypy try2_main.py 

Traceback (most recent call last):
  File "/opt/miniconda3/envs/rt_pypy39/lib/pypy3.9/site-packages/pyximport/pyximport.py", line 216, in load_module
    mod = imp.load_dynamic(name, so_path)
  File "/opt/miniconda3/envs/rt_pypy39/lib/pypy3.9/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<builtin>/frozen importlib._bootstrap_external", line 1186, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "try2_diskcache.pyx", line 5, in init try2_diskcache
    @cache.memoize(typed=True, expire=1, tag='fib')
  File "/opt/miniconda3/envs/rt_pypy39/lib/pypy3.9/site-packages/diskcache/core.py", line 1868, in decorator
    base = (full_name(func),) if name is None else (name,)
  File "/opt/miniconda3/envs/rt_pypy39/lib/pypy3.9/site-packages/diskcache/core.py", line 25, in full_name
    return func.__module__ + '.' + func.__qualname__
AttributeError: 'builtin_function_or_method' object has no attribute '__qualname__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "try2_main.py", line 9, in <module>
    from try2_diskcache import fibonacci
  File "/opt/miniconda3/envs/rt_pypy39/lib/pypy3.9/site-packages/pyximport/pyximport.py", line 459, in load_module
    module = load_module(fullname, self.path,
  File "/opt/miniconda3/envs/rt_pypy39/lib/pypy3.9/site-packages/pyximport/pyximport.py", line 231, in load_module
    raise exc.with_traceback(tb)
  File "/opt/miniconda3/envs/rt_pypy39/lib/pypy3.9/site-packages/pyximport/pyximport.py", line 216, in load_module
    mod = imp.load_dynamic(name, so_path)
  File "/opt/miniconda3/envs/rt_pypy39/lib/pypy3.9/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<builtin>/frozen importlib._bootstrap_external", line 1186, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "try2_diskcache.pyx", line 5, in init try2_diskcache
    @cache.memoize(typed=True, expire=1, tag='fib')
  File "/opt/miniconda3/envs/rt_pypy39/lib/pypy3.9/site-packages/diskcache/core.py", line 1868, in decorator
    base = (full_name(func),) if name is None else (name,)
  File "/opt/miniconda3/envs/rt_pypy39/lib/pypy3.9/site-packages/diskcache/core.py", line 25, in full_name
    return func.__module__ + '.' + func.__qualname__
ImportError: Building module try2_diskcache failed: ["AttributeError: 'builtin_function_or_method' object has no attribute '__qualname__'\n"]
```

**Comment by mattip** [comment] 2022-12-20 10:42
I think this is due to a shortcoming in the cpyext layer of PyPy that emulates the Python c-api. A reproducer without using diskcache, (assuming this is run inside a venv created with PyPy3):
```
$ cat << EOF > simple.pyx
# cython: language_level=3

def func(number):
    return 42
EOF

$ cythonize -b simple.pyx
...

$ python -c "import try2_diskcache; simple.func.__qualname__"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'builtin_function_or_method' object has no attribute '__qualname__'
```

While Cython has an excellent test suite, some of the tests are skipped due to shortcomings in PyPy. The skipped tests are in [`test/pypy2_bugs.txt`](https://github.com/cython/cython/blob/master/tests/pypy2_bugs.txt), [`test/pypy_bugs.txt`](https://github.com/cython/cython/blob/master/tests/pypy_bugs.txt), [`tests/pypy_crash_bugs.txt`](https://github.com/cython/cython/blob/master/tests/pypy_crash_bugs.txt), [tests/pypy_implementation_detail_bugs.txt](https://github.com/cython/cython/blob/master/tests/pypy_implementation_detail_bugs.txt), but I don't see where that skips [`tests/run/qualname.pyx`](https://github.com/cython/cython/blob/master/tests/run/qualname.pyx). Or maybe that test is not exactly this case?

**Comment by mattip** [comment] 2022-12-20 10:44
(FWIW, if you already have a pure-python implementation of your code, you would see better performance by skipping Cython + PyPy and going with the pure-python version under PyPy).

**Comment by mattip** [comment] 2022-12-20 11:47
xref the PyPy issue https://foss.heptapod.net/pypy/pypy/-/issues/3878

**Comment by bsnresearcher** [comment] 2022-12-20 15:29
Thank you very much! I wait for fixing.

Combination of JIT(PyPy) + AOT(Cython/Numba) may make best performance on Python, which leads to selecting python  than other language for researcher especially I guess. The best performance Python may give researcher times dedicated into their research by saving learning another language. I hope.

**Comment by mattip** [comment] 2022-12-20 16:18
> Combination of JIT(PyPy) + AOT(Cython/Numba) may make best performance on Python

Please be sure to measure this on your application. Benchmarking is hard but should be the first step in optimizing. There is [a large overhead](https://www.pypy.org/posts/2018/09/inside-cpyext-why-emulating-cpython-c-8083064623681286567.html) for using the Python c-api on alternative interpreters not based in C like PyPy and GraalPython. We (the PyPy team) are hopeful [HPy](https://hpyproject.org/) can make a dent in this, but it will take a while to happen. Even once it does, it is hard for me to believe that converting [diskcache](https://grantjenks.com/docs/diskcache/) into C will make it faster on PyPy: there will be missed JIT opportunities when code is frozen into C.

**Comment by da-woods** [comment] 2022-12-20 17:24
Your qualname issue *may* be fixed by using the compiler directive `binding=True` (which makes the functions use Cython's own function type rather than the base builtin function). However, I haven't tested this suggestion, and if it doesn't work it's likely to be the same PyPy limitation (so we don't really need to follow it up here if it doesn't work)

**Comment by bsnresearcher** [comment] 2022-12-23 00:51
>> Mr. mattip
Yes, I should be care what you indicate. In addition, I remember PyPy does not seems good at I/O than CPython. I took wrong on my best solution plan. (My problem needs calc high load calculation an interval time, which I want own to cython. The others are intent to apply to PyPy. However, I will measure performance according to you advice.) Thank you very much!!

>> Mr. da-woods
Your advice was very useful! That error has not rise yet. Thank you very much!!

**Comment by scoder** [comment] 2022-12-23 09:56
> I think this is due to a shortcoming in the cpyext layer of PyPy

CPython has the same issue, probably. C implemented functions in the C-API do not have a `__qualname__` automatically (and what should its value be?), that's why the `binding` directive is needed here to make Cython implemented functions behave more like Python functions.

Closing this issue because it's not a problem in Cython.

**Closed by scoder** 2022-12-23 09:56 UTC
Labels: support question

**Comment by mattip** [comment] 2022-12-23 10:02
FWIW, there were some places where CPython was adding `__qualname__` when calling `PyCFunction_New` and PyPy was not. I think I fixed them (for PyPy3.9), details in the PyPy issue listed above. This will be part of the next PyPy3.9 release.
