### ISSUE TITLE
 LINK : error LNK2001: unresolved external symbol PyInit___init__

### ISSUE THREAD

**Issue by gejinhuan** [cython/cython#4371] opened 2021-09-11 07:46 UTC
When I install cynetworkx by using command "pip install cynetworkx", I got the fatal error as follow. How can I do to fix it?
 **C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\administrator\appdata\local\programs\python\python37\include -Ic:\users\administrator\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tccynetworkx/algorithms/approximation/__init__.c /Fobuild\temp.win-amd64-3.7\Release\cynetworkx/algorithms/approximation/__init__.obj
    __init__.c
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\administrator\appdata\local\programs\python\python37\libs /LIBPATH:c:\users\administrator\appdata\local\programs\python\python37\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" /EXPORT:PyInit___init__ build\temp.win-amd64-3.7\Release\cynetworkx/algorithms/approximation/__init__.obj /OUT:build\lib.win-amd64-3.7\cynetworkx\algorithms\approximation\__init__.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\cynetworkx/algorithms/approximation\__init__.cp37-win_amd64.lib
    LINK : error LNK2001: unresolved external symbol PyInit___init__
    build\temp.win-amd64-3.7\Release\cynetworkx/algorithms/approximation\__init__.cp37-win_amd64.lib : fatal error LNK1120: 1 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\administrator\appdata\local\programs\python\python37\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-ux7vcxwp\\cynetworkx_2e972a11e70b48c3a9cf6e626c0d9731\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-ux7vcxwp\\cynetworkx_2e972a11e70b48c3a9cf6e626c0d9731\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-j7gu9dl0\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\administrator\appdata\local\programs\python\python37\Include\cynetworkx' Check the logs for full command output.**

**Comment by da-woods** [comment] 2021-09-11 08:08
1) Please ask support questions on the cython-users mailing list rather than here.
2) Duplicate of https://github.com/cython/cython/issues/2968

**Closed by da-woods** 2021-09-11 08:08 UTC
