### ISSUE TITLE
Cython.Coverage fails to find source file when using src/ layout

### ISSUE THREAD

**Issue by godlygeek** [cython/cython#4999] opened 2022-08-26 23:02 UTC
When trying to run `coverage` against the code in https://github.com/godlygeek/cython-issue-4999, coverage spits out an error:
```
Couldn't parse '/tmp/cython-issue-4999/src/hello_world/_impl.pyx' as Python source: 'invalid syntax' at line 2
```
because the `Cython.Coverage` plugin doesn't report that it can handle the `_impl.pyx` file, because it can't resolve its path (it goes looking for it in `cython-issue-4999/hello_world` instead of `cython-issue-4999/src/hello_world`).

To reproduce:
```shell-session
$ cd /tmp
$ git clone https://github.com/godlygeek/cython-issue-4999
Cloning into 'cython-issue-4999'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 11 (delta 0), reused 11 (delta 0), pack-reused 0
Receiving objects: 100% (11/11), done.
$ cd cython-issue-4999
$ python3.10 -m venv venv
$ venv/bin/pip install . cython coverage
...
Successfully installed coverage-6.4.4 cython-0.29.32 hello-world-0.0.1
$ venv/bin/coverage run test.py
Hello, Cython!
$ venv/bin/coverage report
Couldn't parse '/tmp/cython-issue-4999/src/hello_world/_impl.pyx' as Python source: 'invalid syntax' at line 2
```

**Comment by da-woods** [comment] 2022-08-30 18:02
I suspect this is a duplicate of https://github.com/cython/cython/issues/3636

We should probably look at the linked PR for that. Unfortunately I don't know coverage very well myself, but I'll try look into it a bit when I have time.

I suspect it won't make it to the 0.29.x branch though - probably only the 3.0 branch

**Comment by da-woods** [comment] 2022-09-24 07:11
The fix for the duplicate issue is now merged

**Closed** 2022-09-24 07:11 UTC
