### ISSUE TITLE
[ENH] Make async funcions inspectable as coroutinefunction

### ISSUE THREAD

**Issue by alex-eri** [cython/cython#3849] opened 2020-09-28 11:57 UTC
For example asyncache[ uses inspect ](https://github.com/hephex/asyncache/blob/27ec0ad90ccb2a86ffaa8dcf55bb388059b484a0/asyncache/__init__.py#L46)to determine that function is async. But this check failed because  compiled function is `cyfunction` without flags.

We need `CO_COROUTINE` (128) flag in `func.__code__.co_flags`

**Comment by scoder** [comment] 2020-09-28 16:48
Duplicate of #2092. Also see #2273.
`inspect.iscoroutinefunction()` is not the right thing to use, in almost all cases outside of CPython.

**Closed by scoder** 2020-09-28 16:48 UTC
Labels: R: duplicate
