### ISSUE TITLE
memory leak with typed ndarray and memory views

### ISSUE THREAD

**Issue by jhauschild** [cython/cython#2828] opened 2019-02-08 19:06 UTC
Hi,
I found a memory leak when using the `np.ndarray[np.intp_t, ndim=2]` syntax or memory views of dimension at least 2.
Strangely, the memory leak only appears if the second dimension is 0, irregardless of the other dimensions. I checked that it also appears with ndim=3 (also if the *second* dimension is zero).

Minimal example:
    # a.pyx
    # compile: cythonize -bi a.pyx
    # run: python -c 'import a; a.main()'

    cimport numpy as cnp
    import numpy as np
    import psutil

    cnp.import_array()

    def check_memleak(var):
        cdef cnp.ndarray[cnp.intp_t, ndim=2] c_var = var  # commenting this out prevents the leak
        #cdef cnp.intp_t[:, :] c_var = var  # memory views have the same problem
        return True

    def mem():
        print(str(round(psutil.Process().memory_info().rss/1024./1024., 2)) + ' MB')

    def main():
        for shape in [(2, 2), (2, 0), (0, 2), (0, 0)]:
            print("shape = ", shape)
            var = np.zeros(shape, dtype=np.intp)
            mem()
            for i in range(100000):
                check_memleak(var)
            mem()

Sample output:

    $python -c 'import a; a.main()'
    ('shape = ', (2, 2))
    27.95 MB
    27.95 MB
    ('shape = ', (2, 0))
    27.95 MB
    43.81 MB
    ('shape = ', (0, 2))
    40.21 MB
    40.21 MB
    ('shape = ', (0, 0))
    40.21 MB
    43.82 MB

Any ideas what might cause this strange behaviour?

**Comment by scoder** [comment] 2019-02-15 16:16
I looked into this a bit and could reproduce it. Not sure where the problem is, though. It would help to see if moving either NumPy or Cython out of the way would show the same issue, so that we can see if it's due to Cython or NumPy.

Also, arrays with a zero dimension, while certainly not useless, do not seem like a particularly critical use case to fix. That might also be the reason why it's not been found and/or reported so far.

**Comment by da-woods** [comment] 2021-02-01 18:21
I'm fairly confident this was https://github.com/numpy/numpy/issues/16934 and should now be fixed in Numpy. And testing it now (with Numpy 1.19.5) seems to show that the bug has gone.

**Closed by da-woods** 2021-02-01 18:21 UTC
Labels: Buffers, defect

**Comment by seberg** [comment] 2021-02-01 18:34
Yeah, I agree, was about to post as well :).
