### ISSUE TITLE
TypeError: Class-level classmethod() can only be called on a method_descriptor or instance method

### ISSUE THREAD

**Issue by beruhan** [cython/cython#3658] opened 2020-06-02 13:04 UTC
Environment:
```
Cython version: 0.29.19
OS: ubuntu 18.04
Python version: 3.6
GCC:7.5.0
```
I use cython and gcc to  compile my python file to exe.But I throw the following error when run the exe:
```
Traceback (most recent call last):
  File "cls_test.py", line 6, in init cls_test
    @classmethod
TypeError: Class-level classmethod() can only be called on a method_descriptor or instance method.
```
My test file as follows:
```
# -*- coding: utf-8 -*-
from functools import lru_cache


class Test(object):
    @classmethod
    @lru_cache(maxsize=1024)
    def test(cls):
        pass


if __name__ == '__main__':
    pass
```
The command I used as follows:
```
cython -3 cls_test.py
gcc -o cls_test cls_test.c -Wl,-s -O3 -I /usr/include/python3.6 -lpython3.6m
```
Does I have some thing wrong or Cython dosn't support the usage currently?

**Comment by da-woods** [comment] 2020-06-02 16:21
Duplicate of https://github.com/cython/cython/issues/1434 - `classmethod` and `staticmethod` are special-cased and so this doesn't work right now.

I'm claiming https://github.com/cython/cython/pull/3383 will fix it (but we'll see).

**Comment by da-woods** [comment] 2020-06-02 16:25
I think some people have have had success with something like:

```
classmethod_ = classmethod

class Test(object):
    @classmethod_
    @lru_cache(maxsize=1024)
    def test(cls):
        pass
```

(i.e. trying to confuse Cython into not applying the special-casing). I'm not 100% sure if that'll cause other problems though.

**Comment by da-woods** [comment] 2020-06-02 17:17
Re-opened this because I don't think it is a duplicate actually. This issue is specifically in in:

https://github.com/cython/cython/blob/3ee066283d503d9ed494f90793ee89e6973904f8/Cython/Utility/CythonFunction.c#L1495-L1498.

I don't think this code should be there - it should just call `PyClassMethod_New` and fail at runtime (like CPython does).

**Closed** 2020-06-02 19:05 UTC
Labels: Python Semantics, defect
