### ISSUE TITLE
[BUG] TypeError: event registered must be a coroutine function error

### ISSUE THREAD

**Issue by amtsgv** [cython/cython#3978] opened 2021-01-14 15:10 UTC
getting this error when trying to compile my discord.py bot, code works perfectly fine when running on python normally, but just wouldnt work using cython. 
![image](https://user-images.githubusercontent.com/63860086/104609074-54ea0d80-568b-11eb-9b91-48580bdbdf30.png)

**Comment by da-woods** [comment] 2021-01-14 17:15
Duplicate of https://github.com/cython/cython/issues/2273

Probably fixed in the current master branch. It's probably that discord's Python interface is too strict about testing for coroutines (i.e. requiring an exact type) and you might have more success raising the issue there.

**Closed by da-woods** 2021-01-14 17:15 UTC
