### ISSUE TITLE
unguarded omp.h include

### ISSUE THREAD

**Issue by jschueller** [cython/cython#1518] opened 2016-11-10 11:26 UTC
when compiling pyfmi, cython generates a master.c in which I found an unguarded omp include,
which causes compile error on msvc 10:
```
#include <omp.h>
#include "pythread.h"
#ifdef _OPENMP
#include <omp.h>
#endif /* _OPENMP */
```

The guarded part is from:
https://github.com/cython/cython/blob/master/Cython/Compiler/ModuleNode.py#L739

I guess the unguarded part is from https://github.com/cython/cython/blob/a0bbb940c847dfe92cac446c8784c34c28c92836/Cython/Includes/openmp.pxd

**Comment by robertwb** [comment] 2016-11-10 22:42
This should only happen if you explicitly `cimport openmp` to use those functions directly (which, of course, would mean that it's not optional). 

I checkout out https://github.com/modelon/PyFMI and did a `python setup.py build_ext --inplace` and it looks like all three references to omp.h are properly guarded.

**Comment by robertwb** [comment] 2016-11-18 06:17
Closing this as not reproducible.

**Closed by robertwb** 2016-11-18 06:17 UTC

**Comment by jschueller** [comment] 2016-11-19 09:39
It's ok on the git version of PyFMI you're right, but not if you compile the 2.3.1 version from the pypi tarball:
```
wget https://pypi.python.org/packages/66/60/26664b2b2cad4a7fae409214e2f8901177322d78bfb11ef61e580115c9b8/PyFMI-2.3.1.zip -P /tmp/
unzip /tmp/PyFMI-2.3.1.zip
cd PyFMI-2.3.1
rm src/pyfmi/*.c # will rerun cython with latest version
python setup.py build_ext --inplace --fmil-home=/usr
```

This time you'll find in src/pyfmi/master.c:420
```
#include "fmilib.h"
#include <omp.h>              -----------------> unguarded
#include "pythread.h"
#ifdef _OPENMP
#include <omp.h>
#endif /* _OPENMP */
```

**Comment by jschueller** [comment] 2016-11-19 09:39
@robertwb should we reopen ?

**Comment by robertwb** [comment] 2016-11-19 16:52
This is because of the explicit `cimport openmp` in master.pyx

https://svn.jmodelica.org/PyFMI/branches/PyFMI-2.3.x/src/pyfmi/master.pyx

which makes openmp a hard requirement as its API is used directly.

**Comment by jschueller** [comment] 2016-11-19 17:50
ok, thanks a lot
