### ISSUE TITLE
BUG: method in cdef class raises if called with keyword kwarg

### ISSUE THREAD

**Issue by jbrockmendel** [cython/cython#3604] opened 2020-05-12 19:57 UTC
```
cdef class _Timestamp(datetime):
    [...]

class Timestamp(_Timestamp):
   def tz_convert(self, tz):
      [...]
```

If I move tz_convert up to the base class, I get test failures when calling `tz_convert(tz=foo)` as opposed to `tz_convert(foo)`:

```
>>> ts = pd.Timestamp.utcnow()

>>> ts.tz_convert("US/Pacific")
Timestamp('2020-05-12 12:56:36.212212-0700', tz='US/Pacific')

>>> ts.tz_convert(tz="US/Pacific")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: tz_convert() takes no keyword arguments
```

**Comment by da-woods** [comment] 2020-05-12 20:01
Is this a variant of https://github.com/cython/cython/issues/3090?

**Comment by jbrockmendel** [comment] 2020-05-12 20:07
> Is this a variant of #3090?

Definitely similar.  I dont know if the optimization mentioned in #3090 also applies to methods in addition to functions.

**Comment by scoder** [comment] 2020-05-12 20:12
Duplicate of #3090.

**Closed by scoder** 2020-05-12 20:12 UTC
Labels: R: duplicate
