### ISSUE TITLE
Dataclasses do not work with Cython due to annotations being stripped out.

### ISSUE THREAD

**Issue by ghost** [cython/cython#3336] opened 2020-01-29 10:03 UTC
It would appear that dataclasses now do not work since https://github.com/cython/cython/commit/3dc2b9dfc23638fbef2558d619709b5235d5df08 was implemented.

Using the most recent master commit at the time of writing:
```py
# test.py
import dataclasses

@dataclasses.dataclass()
class Foo:
    bar: str = dataclasses.field(default="hello")

print(Foo("hi"))
print(Foo())
```
```bash
>>> cythonize test.py -3i
Compiling /home/.../code/cython-bug/test.py because it changed.
[1/1] Cythonizing /home/.../code/cython-bug/test.py
running build_ext
building 'test' extension
creating /home/.../code/cython-bug/tmpbh4j4lqe/home
creating /home/.../code/cython-bug/tmpbh4j4lqe/home/
creating /home/.../code/cython-bug/tmpbh4j4lqe/home//code
creating /home/.../code/cython-bug/tmpbh4j4lqe/home///code/cython-bug
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/home/.../code/hikari/.venv/include -I/usr/include/python3.8 -c /home/.../code/cython-bug/test.c -o /home/.../code/cython-bug/tmpbh4j4lqe/home/.../code/cython-bug/test.o
gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now /home/.../code/cython-bug/tmpbh4j4lqe/home/.../code/cython-bug/test.o -L/usr/lib -o /home/.../code/cython-bug/test.cpython-38-x86_64-linux-gnu.so

>>> python -c "import test"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test.py", line 3, in init test
    @dataclasses.dataclass()
  File "/usr/lib/python3.8/dataclasses.py", line 1011, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/lib/python3.8/dataclasses.py", line 885, in _process_class
    raise TypeError(f'{name!r} is a field but has no type annotation')
TypeError: 'bar' is a field but has no type annotation
```

Version info:
```bash
>>> python -V
Python 3.8.1
>>> pip freeze | grep -i cython
Cython==3.0a0
```

**Comment by scoder** [comment] 2020-01-29 12:42
Isn't this just #2552? Did this ever work for you before? What does `Foo.__annotations__` give?

**Comment by scoder** [comment] 2020-09-10 05:22
Closing as duplicate of #2552.

**Closed by scoder** 2020-09-10 05:22 UTC
Labels: R: duplicate
