### ISSUE TITLE
@cython.compile does not accept directives as decorators

### ISSUE THREAD

**Issue by ram-bv** [cython/cython#3504] opened 2020-04-12 13:40 UTC
Here is a code sample:

```python
import time as time_module
import contextlib
import cython


class Floof:
    def _get_dicts(self):
        return (
            {1: 2, 2: 4,}, 
            {1: 20, 2: 40,}, 
            {1: 2, 2: 4, 5: 800,}, 
            {1: 2, 2: 4, 500: 'floofy',}, 
        )
        
    @cython.compile
    @cython.binding(True)
    def __iter__(self):
        visited = set()
        for d in self._get_dicts():
            # for key, value in d.items():
            for key in d:
                # if (key in visited) or (not value):
                if (key in visited) or (not d.get(key)):
                    continue
                else:
                    visited.add(key)
                    yield key


@contextlib.contextmanager
def time():
    start_time = time_module.time()
    try:
        yield
    finally:
        end_time = time_module.time()
        duration = end_time - start_time
        print(f'Duration: {duration:.2f}')

def benchmark():
    floof = Floof()
    with time():
        for _ in range(1_000_000):
            tuple(floof)

benchmark()
```

It results in this error, both under 3.0a1 and the latest stable release:
```
  File "<string>", line 1, in <module>
  File "/foo/floof3.py", line 46, in <module>
    benchmark()
  File "/foo/floof3.py", line 44, in benchmark
    tuple(floof)
  File "/opt/virtenv/lib/python3.6/site-packages/Cython/Build/Inline.py", line 381, in __call__
    all = getcallargs(self._f, *args, **kwds)
  File "/usr/lib/python3.6/inspect.py", line 1360, in getcallargs
    _missing_arguments(f_name, req, True, arg2value)
  File "/usr/lib/python3.6/inspect.py", line 1290, in _missing_arguments
    "" if missing == 1 else "s", s))
TypeError: __iter__() missing 1 required positional argument: 'self'
```

**Comment by scoder** [comment] 2020-04-12 14:08
Note that this code example is way more complex than it needs to be for a test: it uses methods instead of functions, and it even uses a special method instead of a normal method. Both may actually be bugs (i.e. worth a ticket) in their own right, if they don't work as such.

**Comment by da-woods** [comment] 2020-04-14 07:30
Duplicate of https://github.com/cython/cython/issues/1293 ?

**Comment by scoder** [comment] 2020-04-14 07:35
@da-woods yes, thanks.

**Closed by scoder** 2020-04-14 07:35 UTC
Labels: Build System, R: duplicate, enhancement
