### ISSUE TITLE
Compiler error using fused type in __cinit__

### ISSUE THREAD

**Issue by jakirkham** [cython/cython#2538] opened 2018-08-07 20:12 UTC
When using a fused type in `__cinit__` as shown below, got an error from the compiler (also shown below).

<details>
<summary>Code:</summary>

```cython
cdef fused int_or_float:
    int
    float

cdef class MyFusedNum:
    def __cinit__(self, int_or_float num):
        pass
```

</details>

<br>

<details>
<summary>Traceback:</summary>

```python
/Users/kirkhamj/.ipython/cython/_cython_magic_4d47ddbd96a2e0b9916e5dde1f14cca3.c:1681:118: error: expected expression
static PyMethodDef __pyx_fuse_0__pyx_mdef_46_cython_magic_4d47ddbd96a2e0b9916e5dde1f14cca3_10MyFusedNum_3__cinit__ = static int __pyx_fuse_0__pyx_pw_...
                                                                                                                     ^
/Users/kirkhamj/.ipython/cython/_cython_magic_4d47ddbd96a2e0b9916e5dde1f14cca3.c:1742:118: error: expected expression
static PyMethodDef __pyx_fuse_1__pyx_mdef_46_cython_magic_4d47ddbd96a2e0b9916e5dde1f14cca3_10MyFusedNum_5__cinit__ = static int __pyx_fuse_1__pyx_pw_...
                                                                                                                     ^
2 errors generated.
---------------------------------------------------------------------------
DistutilsExecError                        Traceback (most recent call last)
/zopt/conda3/envs/cython/lib/python3.6/distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    117             self.spawn(compiler_so + cc_args + [src, '-o', obj] +
--> 118                        extra_postargs)
    119         except DistutilsExecError as msg:

/zopt/conda3/envs/cython/lib/python3.6/distutils/ccompiler.py in spawn(self, cmd)
    908     def spawn(self, cmd):
--> 909         spawn(cmd, dry_run=self.dry_run)
    910 

/zopt/conda3/envs/cython/lib/python3.6/distutils/spawn.py in spawn(cmd, search_path, verbose, dry_run)
     35     if os.name == 'posix':
---> 36         _spawn_posix(cmd, search_path, dry_run=dry_run)
     37     elif os.name == 'nt':

/zopt/conda3/envs/cython/lib/python3.6/distutils/spawn.py in _spawn_posix(cmd, search_path, verbose, dry_run)
    158                           "command %r failed with exit status %d"
--> 159                           % (cmd, exit_status))
    160             elif os.WIFSTOPPED(status):

DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

CompileError                              Traceback (most recent call last)
<ipython-input-12-00a4b89d3c1f> in <module>()
----> 1 get_ipython().run_cell_magic('cython', '', 'cdef fused int_or_float:\n    int\n    float\n\ncdef class MyFusedNum:\n    def __cinit__(self, int_or_float num):\n        pass')

/zopt/conda3/envs/cython/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2165             magic_arg_s = self.var_expand(line, stack_depth)
   2166             with self.builtin_trap:
-> 2167                 result = fn(magic_arg_s, cell)
   2168             return result
   2169 

<decorator-gen-118> in cython(self, line, cell)

/zopt/conda3/envs/cython/lib/python3.6/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/zopt/conda3/envs/cython/lib/python3.6/site-packages/Cython/Build/IpythonMagic.py in cython(self, line, cell)
    327 
    328         self._build_extension(extension, lib_dir, pgo_step_name='use' if args.pgo else None,
--> 329                               quiet=args.quiet)
    330 
    331         module = imp.load_dynamic(module_name, module_path)

/zopt/conda3/envs/cython/lib/python3.6/site-packages/Cython/Build/IpythonMagic.py in _build_extension(self, extension, lib_dir, temp_dir, pgo_step_name, quiet)
    437             if not quiet:
    438                 old_threshold = distutils.log.set_threshold(distutils.log.DEBUG)
--> 439             build_extension.run()
    440         finally:
    441             if not quiet and old_threshold is not None:

/zopt/conda3/envs/cython/lib/python3.6/distutils/command/build_ext.py in run(self)
    337 
    338         # Now actually compile and link everything.
--> 339         self.build_extensions()
    340 
    341     def check_extensions_list(self, extensions):

/zopt/conda3/envs/cython/lib/python3.6/distutils/command/build_ext.py in build_extensions(self)
    446             self._build_extensions_parallel()
    447         else:
--> 448             self._build_extensions_serial()
    449 
    450     def _build_extensions_parallel(self):

/zopt/conda3/envs/cython/lib/python3.6/distutils/command/build_ext.py in _build_extensions_serial(self)
    471         for ext in self.extensions:
    472             with self._filter_build_errors(ext):
--> 473                 self.build_extension(ext)
    474 
    475     @contextlib.contextmanager

/zopt/conda3/envs/cython/lib/python3.6/distutils/command/build_ext.py in build_extension(self, ext)
    531                                          debug=self.debug,
    532                                          extra_postargs=extra_args,
--> 533                                          depends=ext.depends)
    534 
    535         # XXX outdated variable, kept here in case third-part code

/zopt/conda3/envs/cython/lib/python3.6/distutils/ccompiler.py in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends)
    572             except KeyError:
    573                 continue
--> 574             self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    575 
    576         # Return *all* object filenames, not just the ones we just built.

/zopt/conda3/envs/cython/lib/python3.6/distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    118                        extra_postargs)
    119         except DistutilsExecError as msg:
--> 120             raise CompileError(msg)
    121 
    122     def create_static_lib(self, objects, output_libname,

CompileError: command 'gcc' failed with exit status 1
```

</details>

**Comment by scoder** [comment] 2018-08-07 20:16
Duplicate of #2120.

**Comment by jakirkham** [comment] 2018-08-07 21:35
Oops, sorry, missed that while searching. Feel free to close or leave open as you see fit.

**Closed** 2018-11-18 13:47 UTC
Labels: R: duplicate

**Comment by compholio** [comment] 2019-09-13 21:12
If someone else runs across this, as a workaround you can use `__cinit__` without a type and call another function that has the fused type defined:
```
cdef class MyFusedNum:
    def __cinit__(self, num):
        self.__real_init__(num)
    def __real_init__(self, int_or_float num):
        pass
```
