### ISSUE TITLE
Fused types do not work with extension types

### ISSUE THREAD

**Issue by cycomanic** [cython/cython#2120] opened 2018-02-25 00:43 UTC
This might be already known, but I was trying to use the technique described [in the cdef classed tutorial](http://cython.readthedocs.io/en/latest/src/tutorial/cdef_classes.html) together with fused types. However, when I try to do this I get gcc errors due to duplicate members.
```python
cimport cython

cdef extern from "math.h":
    double sin(double)

cdef class Function:
    cpdef double evaluate(self, cython.floating x) except *:
        return 0

cdef class SinOfSquareFunction(Function):
    cpdef double evaluate(self, cython.floating x) except *:
        return sin(x**2)

def integrate(Function f, double a, double b, int N):
    cdef int i
    cdef double s, dx
    if f is None:
        raise ValueError("f cannot be None")
    s = 0
    dx = (b-a)/N
    for i in range(N):
        s += f.evaluate(a+i*dx)
    return s * dx

print(integrate(SinOfSquareFunction(), 0, 1, 10000))
```

results in the following gcc error:
```
$gcc -shared -pthread -fPIC -fwrapv -O2 -Wall -fno-strict-aliasing -I/usr/include/python3.6 -o testing.so testing.c
testing.c:672:12: error: duplicate member ‘__pyx_fuse_0evaluate’
   double (*__pyx_fuse_0evaluate)(struct __pyx_obj_7testing_Function *, float, int __pyx_skip_dispatch);
            ^~~~~~~~~~~~~~~~~~~~
testing.c:673:12: error: duplicate member ‘__pyx_fuse_1evaluate’
   double (*__pyx_fuse_1evaluate)(struct __pyx_obj_7testing_Function *, double, int __pyx_skip_dispatch);
            ^~~~~~~~~~~~~~~~~~~~
```

**Comment by scoder** [comment] 2018-08-07 20:18
Not sure if this can be supported, but we should at least report this as an error, instead of generating invalid C code.

**Comment by da-woods** [comment] 2020-04-11 14:22
This seems to be fixed in both master and 0.29.16 (although I have no idea when it was fixed and what fixed it).

I'm not convinced https://github.com/cython/cython/issues/3283 is actually a duplicate of this issue. This one seems to be a specific code generation failure while #3283 is a feature request for fused attributes.

**Comment by scoder** [comment] 2020-04-11 16:13
@da-woods hmm, yeah, I think I misread the ticket … completely. I guess I thought there was a fused attribute involved, whereas it's about fused methods only.

So, this is a duplicate of #1389, in fact.

**Closed by scoder** 2020-04-11 16:13 UTC
Labels: R: duplicate

**Comment by scoder** [comment] 2020-04-11 16:22
Thanks for the comment @da-woods, I appreciate it.
