### ISSUE TITLE
[ENH] pyximport/pyximport.py:51: DeprecationWarning: the imp module is deprecated

### ISSUE THREAD

**Issue by ssche** [cython/cython#4024] opened 2021-03-03 22:40 UTC
**Is your feature request related to a problem? Please describe.**

When importing `pyximport`, the following deprecation warning occurs.

```
pyximport/pyximport.py:51: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
import imp
```

This warning is equivalent to the one reported in #3306 and can be traced back to this line
https://github.com/cython/cython/blob/master/pyximport/pyximport.py#L51

```cython
import pyximport
```

**Describe the solution you'd like**

A similar replacement of `import imp` as in this PR https://github.com/cython/cython/pull/3350/commits/be284d62bc9fdff691530e0d9a9bb40a93941464 could be employed

**Comment by matusvalo** [comment] 2022-08-01 20:11
@scoder @da-woods I think this issue can be closed.

**Comment by da-woods** [comment] 2022-08-01 20:50
Duplicate of https://github.com/cython/cython/issues/4560 (admittedly this issue came first, but doesn't really matter for the sake of getting things closed...)

**Closed by da-woods** 2022-08-01 20:50 UTC
