### ISSUE TITLE
Cython compilation fails for valid nested generator comprehension.

### ISSUE THREAD

**Issue by gwk** [cython/cython#1479] opened 2016-10-07 19:29 UTC
The following is legitimate CPython code:

```
d = {}
works = { k : [n for n in names] for k, names in d.items() }
fails = { k : set(n for n in names) for k, names in d.items() }
```

The "fails" line causes the following error:
cython_defect.py:3:34: local variable 'names' referenced before assignment

This may have the same root cause as #1351 (based purely on the description).

**Comment by shalabhc** [comment] 2017-01-24 20:50
Another failure that looks related is below (cython v0.25.2). The entire code is in the error message:

```
Error compiling Cython file:
------------------------------------------------------------
...
class C(object):
  a = {}
  b = list(k for k in a)
                      ^
------------------------------------------------------------

/tmp/x.py:3:23: undeclared name not builtin: a
```

**Comment by scoder** [comment] 2017-02-07 06:36
Duplicate of #1351.

**Closed by scoder** 2017-02-07 06:36 UTC
Labels: R: duplicate

**Comment by scoder** [comment] 2017-08-18 15:02
Or rather #1159.

**Comment by embray** [comment] 2017-09-07 12:50
This still seems to be a bug in Cython 0.26 but only with `language_level=3`:

```
$ cat itertest.pyx
xs = [(1, 2), (3, 4), (5, 6)]
print([sum(a for a in x) for x in xs])
$ cythonize itertest.pyx                       
Compiling itertest.pyx because it changed.
[1/1] Cythonizing itertest.pyx
$ rm -f itertest.c
$ cythonize -3 itertest.pyx
Compiling itertest.pyx because it changed.
[1/1] Cythonizing itertest.pyx

Error compiling Cython file:
------------------------------------------------------------
...
xs = [(1, 2), (3, 4), (5, 6)]
print([sum(a for a in x) for x in xs])
                      ^
------------------------------------------------------------

itertest.pyx:2:23: local variable 'x' referenced before assignment
Traceback (most recent call last):
...
Cython.Compiler.Errors.CompileError: itertest.pyx
```

This code of course works in pure Python 3.

**Comment by scoder** [comment] 2017-09-07 13:26
I didn't close the ticket because it's fixed but because it's a duplicate. Fixes welcome for #1159.

**Comment by embray** [comment] 2017-09-07 14:43
I was a little confused about the status of #1159, since it mentions something about a commit where this was fixed, and indeed it doesn't seem to be a problem for me except with `language_level=3` which that ticket didn't mention...

**Comment by scoder** [comment] 2017-09-07 15:00
Ah, yes, it was a bit messed up by the initial github import. I've cleaned it up a little.
