### ISSUE TITLE
C++ Template argument can't be a pointer

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [cython/cython#1838] opened 2017-08-24 10:41 UTC
C++ template arguments can't be pointers, as the compiler then fails with syntax error, so for example `libcpp.cast.dynamic_cast` is useless.

**Comment by robertwb** [comment] 2017-08-25 07:23
A workaround is to declare a typedef.

**Comment by scoder** [comment] 2017-12-21 21:41
Duplicate of #534.

**Closed by scoder** 2017-12-21 21:41 UTC
Labels: R: duplicate
