### ISSUE TITLE
[BUG] ValueError: numpy.ndarray size changed

### ISSUE THREAD

**Issue by louisabraham** [cython/cython#4452] opened 2021-11-05 15:39 UTC
When trying to import a package that was compiled against numpy 1.20 from an installation with numpy 1.19, we get:

    ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

It looks like at some point, this error was a warning (https://stackoverflow.com/q/40845304/5133167) that one would safely ignore.

What is the best way to prebuild packages that will be importable accross all numpy versions?

(Many people are not able to update numpy because of tensorflow requirements)

**Comment by da-woods** [comment] 2021-11-05 20:12
It's an error if the size goes down and a warning if the size goes up. I believe the right thing to do is to build it with the earliest version of Numpy that you aim to support (so if you build it with 1.19 it should work with both, and if you can go back further that's even better).

I think Numpy are hoping for some changes to this message (for similar reasons): https://github.com/cython/cython/issues/4366.

I'll close this as support question / duplicate of #4366

**Closed by da-woods** 2021-11-05 20:12 UTC
