### ISSUE TITLE
How can I generate an AST?

### ISSUE THREAD

**Issue by Keithcat1** [cython/cython#3462] opened 2020-03-25 15:19 UTC
Hi,
How can I generate an abstract syntax tree from some Cython code?
Also, is there a way to generate code directly from that AST, instead of running Cython.Build.cythonize and internally generating another AST?
I need to get a lot of information on a module, such as weather it's C or C++, what it imports, what the docstring is, and other things.
Thanks

**Comment by da-woods** [comment] 2020-03-25 18:43
You probably want to insert something into [the pipeline](https://github.com/cython/cython/blob/master/Cython/Compiler/Pipeline.py) at an early stage just after parsing?

**Comment by Keithcat1** [comment] 2020-03-25 19:00
Sounds good, but how do I do that? Is there an example somewhere?

**Comment by scoder** [comment] 2020-03-26 09:29
Look at the [TreeFragment](https://github.com/cython/cython/blob/master/Cython/Compiler/TreeFragment.py) class. It builds its own partial pipeline. Also look at the `PrintTree` class in `Pipeline.py`.

Closing this since it's not a bug/issue in Cython.

**Closed by scoder** 2020-03-26 09:29 UTC
