### ISSUE TITLE
Unstable Cython builds

### ISSUE THREAD

**Issue by FFY00** [cython/cython#5275] opened 2023-02-27 23:23 UTC
Continuing from #5238. I think it makes sense to discuss this in a dedicated issue.

The current default on CPython is `CYTHON_COMPILING_IN_CPYTHON`, which uses the CPython private API, and this isn't documented anywhere, resulting in many grievances in both users and developers.

In #5238, I said

> There are a couple things, some very simple, we can do to help mitigate this.
> 
> 1) Document the compilation stability contracts
> 
> ~~2) Detect unsafe uses~~
> 
> ~~When loading a Cython module that was built against a different CPython version, issue a warning.~~
> 
> 3) Adopt a safe default
> 
> This would be the biggest change. Currently, Cython is defaulting to `CYTHON_COMPILING_IN_CPYTHON` when building on CPython. Like mentioned above, this comes with a very strict stability contract, having it as a default is problematic.
> IMO the unsafe option should be opt-in, rather than opt-out. Users that build packages in this mode need to be aware of contract. `CYTHON_COMPILING_IN_LIMITED_API` should be the default, or at least we should require the user to explicitly specify which option to use.
> 
> If you really want to keep `CYTHON_COMPILING_IN_CPYTHON` as the default, the only option I see is to validate compatibility against each Python release ~~(including each patch digit)~~ and only default to it on those versions.
> 
> With a bit more work, a better compromise could be reached, where Cython could support a CPython public API mode, which would be a more performant safe default, and the current CPython private API mode, for users for whom the stability contract is suitable.
> Most of the code should be the same between the two modes anyway, and as offered above, the CPython upstream would work with the Cython devs to fill the gaps in the public API.

**Comment by FFY00** [comment] 2023-02-28 04:04
It seems ABI resulting from private API is supposed to be stable, barring from critical issues, so 2) is not needed.

**Comment by da-woods** [comment] 2023-02-28 07:39
I'm going to claim this is a duplicate of https://github.com/cython/cython/issues/5249. That issue is about introducing a "compatible as possible" mode, and this is mostly arguing for that mode to be the default.

Note that the limited API mode isn't really ready yet, so we definitely don't want to make it default now!

**Closed by da-woods** 2023-02-28 07:39 UTC
