### ISSUE TITLE
[BUG] Using a dataclass with positional and non-positional args causes a runtime exception

### ISSUE THREAD

**Issue by Mnkras** [cython/cython#4934] opened 2022-07-28 18:19 UTC
**Describe the bug**
Execute the code below after cythonizing it and it will generate a runtime exception.
Vanilla Python has no issues

**To Reproduce**
Code to reproduce the behaviour:
```python
from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class PipelineTiming:
    initiated: datetime
    started: Optional[datetime] = None
    stopped: Optional[datetime] = None


def testing():
    return PipelineTiming(datetime.utcnow())

print(testing())
```

```
>>> import test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test.py", line 16, in init test
    print(testing())
  File "test.py", line 14, in test.testing
    return PipelineTiming(datetime.utcnow())
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Expected behavior**
I expect the code to run, and not crash at runtime
```
PipelineTiming(initiated=datetime.datetime(2022, 7, 28, 18, 14, 8, 100560), started=None, stopped=None)
```

**Environment (please complete the following information):**
 - OS: Linux and macOS
 - Python version: 3.8.4
 - Cython version: 0.29.31

**Additional context**
There seems to be other weirdness with dataclasses as well, I can file issues for those as well.

**Comment by da-woods** [comment] 2022-07-28 18:27
Cython 0.29.x doesn't support class annotations (and won't support class annotations). Therefore dataclasses will not usefully work with it.

They will work with the Cython 3 alpha branch.

Duplicate of https://github.com/cython/cython/issues/2552

**Closed by da-woods** 2022-07-28 18:27 UTC

**Comment by da-woods** [comment] 2022-07-28 18:28
It just doesn't generate the `__annotations__` attribute so the dataclass decorator has nothing to work with. There's some useful workarounds in the linked issue, but the best advice is to use the Cython 3 alpha branch.

**Comment by Mnkras** [comment] 2022-07-28 18:29
Is 3 considered stable enough? I would love to use these python features, but not at the risk of destabilizing our application

**Comment by da-woods** [comment] 2022-07-28 18:38
Considered by whom? 0.29.31 isn't a great story of not breaking things right now...

It's reasonably stable I think, but it obviously depends on what the risk is. The current 3.0a10 release has been out for a while without major issue. The next release may well break some `typing` related things (because it's starting to try to use those intelligently, and new features obviously come with a bit of risk)

**Comment by Mnkras** [comment] 2022-07-28 18:42
I'm on an older cython than 0.29.31, I just tried to to make sure it wasn't fixed in the latest.

Thanks, ill give it a try

**Comment by da-woods** [comment] 2022-07-28 18:55
> is 3 published to anaconda?

It doesn't look it it unfortunately
