### ISSUE TITLE
Cython compile decorator fails when given type hints

### ISSUE THREAD

**Issue by brandonwillard** [cython/cython#3670] opened 2020-06-08 22:38 UTC
Type hints for function arguments cause `cython.compile` decorator to fail.  

For example,
```python
import cython

@cython.compile
def test_fn(x: int):
    return x + 1

test_fn(1)
```
results in the following error message:
```python
CompileError: 
Error compiling Cython file:
------------------------------------------------------------
...
int):
  ^
------------------------------------------------------------

(tree fragment):1:3: Syntax error in simple statement list
```

I'm observing this on Cython version 0.29.19.

**Comment by da-woods** [comment] 2020-06-09 04:46
Duplicate of https://github.com/cython/cython/issues/3317

**Closed** 2020-06-09 06:14 UTC
Labels: R: duplicate
