### ISSUE TITLE
Initializing a typing.Dict subclass leads to runtime errors.

### ISSUE THREAD

**Issue by nekokatt** [cython/cython#3794] opened 2020-08-28 09:00 UTC
**Describe the bug**
Initializing a subclass of typing.Dict results in a runtime error.

**To Reproduce**
Code to reproduce the behaviour:
`test.py`
```cython
import typing

class MyDict(typing.Dict[int, float]):
    pass
```
`$ cython test.py -3 --inplace`
`$ python -c "import test"`
```
Python 3.8.5 (default, Jul 27 2020, 08:42:51) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test.py", line 4, in init test
    class MyDict(typing.Dict[int, float]):
TypeError: __init__() takes 3 positional arguments but 4 were given
```

**Expected behavior**
It should initialize successfully.

Using `dict` instead of `typing.Dict` works fine, but `typing.Dict` has `dict` in its MRO anyway, so I am not sure why this isn't working.

```py
>>> typing.Dict.mro()
[<class 'dict'>, <class 'object'>]
```

**Environment (please complete the following information):**
 - OS: [e.g. Linux, Windows, macOS]
`$ uname -a`
```
Linux z170x 5.8.1-3-MANJARO #1 SMP PREEMPT Sat Aug 15 19:17:30 UTC 2020 x86_64 GNU/Linux
```
 - Python version [e.g. 3.8.4]
`$ python -VV`
```
Python 3.8.5 (default, Jul 27 2020, 08:42:51) 
[GCC 10.1.0]
```
 - Cython version [e.g. 0.29.18]
[`git+https://github.com/cython/cython@4d54aeff34753551cf0ac9977d50c292dbf9d5d5` - origin/master](https://github.com/cython/cython/commit/4d54aeff34753551cf0ac9977d50c292dbf9d5d5)

----

I have made a diff of the generated source between using `class MyDict(dict)` which works and `class MyDict(typing.Dict[int, float])` which doesn't.

[generated.diff.txt](https://github.com/cython/cython/files/5141149/generated.diff.txt)

I can also confirm that it still breaks if I use `MyDict(typing.Dict)` without typevars, so it is the call to one of the subclassing hooks, rather than the class getitem.

----

Looks like it is definitely this line that is causing the issue:
`2091      __pyx_t_4 = __Pyx_Py3ClassCreate(__pyx_t_2, __pyx_n_s_MyDict, __pyx_t_1, __pyx_t_3, NULL, 0, 0); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 4, __pyx_L1_error)`. I'll try installing cygdb and see if I can get any other details.

**Comment by nekokatt** [comment] 2020-08-28 09:39
Ok, from what I can tell, it looks like the class is being initialized with `(NULL, name, bases, dict)` when it is only expecting `(NULL, name, bases)`. 

Is this an overly easy fix?

**Comment by da-woods** [comment] 2020-08-28 11:32
I think this requires support for `__class_getitem__` which was added in https://github.com/cython/cython/pull/3518. That feature is only in the Cython 3 alpha releases at the moment so you may need to upgrade to one of those.

I don't know if this is the full extent of the issue though - perhaps the error reporting is failing us a little in Cython 0.29.x?

**Comment by da-woods** [comment] 2020-08-28 11:36
Duplicate of https://github.com/cython/cython/issues/3537

Looks like we don't support it at the moment. Obviously if you get anywhere with your investigations the a PR (or further details) would be welcome.

**Closed by da-woods** 2020-08-28 11:36 UTC
