### ISSUE TITLE
Error: command 'build_ext' has no such option 'cython_c_in_temp'

### ISSUE THREAD

**Issue by dmitry-kabanov** [cython/cython#2071] opened 2018-01-14 15:31 UTC
I use the following command

    python setup.py build_ext --cython-c-in-temp --inplace

and get the error:

    command 'build_ext' has no such option 'cython_c_in_temp'

However,

    python setup.py build_ext --help

says that option `--cython-c-in-temp` is available.

I use Ubuntu 16.04 and have Python/Cython installed with Anaconda3-5.0 distrution (Python 3.6 and Cython 0.26.1).

**Comment by thorsummoner** [comment] 2018-11-30 10:19
reproduced on Ubuntu 18 with apt python3 (3.6.3-0ubuntu3) + cython3 (0.25.2-2build3)

**Comment by FeatureCreep** [comment] 2019-05-29 20:19
I hit this too, but found you can workaround this defect by specifying the output_dir and build_dir with a setup.py file like this:
```import os
from distutils.core import setup
from Cython.Build import cythonize

os.environ['CFLAGS'] = '-fPIE'
kwargs={"output_dir":"./junk/","build_dir":"./junk/",}

setup(
    name = 'dl_server',
    ext_modules = cythonize(["*.py"], **kwargs),
)
```
This will place the generated C code into a subdir `./junk/`. You can invoke the cythonization with: `python setup.py build_ext`

**Comment by scoder** [comment] 2020-04-22 18:14
This refers to `Cython.Distutils.old_build_ext.old_build_ext`. My guess is that you didn't register that class with distutils.

If the docs are unclear here, PR welcome.

**Comment by matusvalo** [comment] 2021-12-15 13:35
@scoder I think we can close this issue after #4339. I checked it manually:

```
$ cat setup.py
from setuptools import setup, Extension
from Cython.Build import cythonize
from Cython.Distutils.build_ext import new_build_ext as build_ext

setup(
    name='Hello world app',
    ext_modules=[Extension('hello', ["hello.pyx"])],
    cmdclass={'build_ext': build_ext},
    zip_safe=False,
)


$ python setup.py build_ext --cython-c-in-temp --inplace
running build_ext
Compiling hello.pyx because it changed.
[1/1] Cythonizing hello.pyx
/Users/matus/dev/cython/Cython/Compiler/Main.py:346: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /Users/matus/dev/cython/test/hello.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
building 'hello' extension
creating build/temp.macosx-10.15-x86_64-3.9/build
creating build/temp.macosx-10.15-x86_64-3.9/build/temp.macosx-10.15-x86_64-3.9
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/matus/dev/cython39/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c build/temp.macosx-10.15-x86_64-3.9/hello.c -o build/temp.macosx-10.15-x86_64-3.9/build/temp.macosx-10.15-x86_64-3.9/hello.o
creating build/lib.macosx-10.15-x86_64-3.9
clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk build/temp.macosx-10.15-x86_64-3.9/build/temp.macosx-10.15-x86_64-3.9/hello.o -L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite/lib -o build/lib.macosx-10.15-x86_64-3.9/hello.cpython-39-darwin.so
copying build/lib.macosx-10.15-x86_64-3.9/hello.cpython-39-darwin.so ->


$ cat setup.py
from setuptools import setup, Extension
from Cython.Build import cythonize
from Cython.Build import build_ext

setup(
    name='Hello world app',
    ext_modules=[Extension('hello', ["hello.pyx"])],
    cmdclass={'build_ext': build_ext},
    zip_safe=False,
)

$ python setup.py build_ext --cython-c-in-temp --inplace
running build_ext
cythoning hello.pyx to hello.c
/Users/matus/dev/cython/Cython/Compiler/Main.py:346: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /Users/matus/dev/cython/test/hello.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
building 'hello' extension
creating build
creating build/temp.macosx-10.15-x86_64-3.9
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/matus/dev/cython39/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c hello.c -o build/temp.macosx-10.15-x86_64-3.9/hello.o
clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk build/temp.macosx-10.15-x86_64-3.9/hello.o -L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite/lib -o /Users/matus/dev/cython/test/hello.cpython-39-darwin.so
```

**Comment by scoder** [comment] 2021-12-15 17:43
Since it was unclear from the beginning what the issue was, I'm closing this.
Thanks for testing it, @matusvalo.

**Closed by scoder** 2021-12-15 17:43 UTC
Labels: Build System, R: worksforme
