### ISSUE TITLE
0.26b0 fresh_finally_clause: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by totaam** [cython/cython#1760] opened 2017-07-06 05:52 UTC
Sorry if the minimum example needed to reproduce is a bit long, I trimmed it down from ~2500 lines to ~250 but now removing almost any of the remaining lines of code "fixes things" and allows it to be cythonized?!

We've had issues with this same source file a few years back (circa Cython 0.23):
https://mail.python.org/pipermail/cython-devel/2015-August/004492.html
So hopefully the fix will be similar.

To reproduce, just try to cythonize this with 0.26b0 (tested on Fedora 26 x86_64):
```
import time
from libc.stdint cimport uint8_t, uint16_t, uint32_t, int32_t, uint64_t

cdef extern from "nvEncodeAPI.h":
    ctypedef int NVENCSTATUS
    ctypedef void* NV_ENC_INPUT_PTR
    ctypedef void* NV_ENC_OUTPUT_PTR
    ctypedef void* NV_ENC_REGISTERED_PTR

    ctypedef enum NV_ENC_DEVICE_TYPE:
        NV_ENC_DEVICE_TYPE_CUDA

    ctypedef enum NV_ENC_INPUT_RESOURCE_TYPE:
        NV_ENC_INPUT_RESOURCE_TYPE_DIRECTX
        NV_ENC_INPUT_RESOURCE_TYPE_CUDADEVICEPTR
        NV_ENC_INPUT_RESOURCE_TYPE_CUDAARRAY

    ctypedef enum NV_ENC_BUFFER_FORMAT:
        NV_ENC_BUFFER_FORMAT_UNDEFINED

    ctypedef enum NV_ENC_PIC_FLAGS:
        NV_ENC_PIC_FLAG_FORCEIDR
        NV_ENC_PIC_FLAG_OUTPUT_SPSPPS

    ctypedef enum NV_ENC_PIC_STRUCT:
        NV_ENC_PIC_STRUCT_FRAME

    ctypedef enum NV_ENC_PIC_TYPE:
        NV_ENC_PIC_TYPE_P
        NV_ENC_PIC_TYPE_IDR

    ctypedef enum NV_ENC_SLICE_TYPE:
        NV_ENC_SLICE_TYPE_DEFAULT
        NV_ENC_SLICE_TYPE_I


    ctypedef struct NV_ENC_LOCK_BITSTREAM:
        uint32_t    reservedBitFields   
        void*       outputBitstream     
        uint32_t    bitstreamSizeInBytes
        uint64_t    outputTimeStamp     
        void*       bitstreamBufferPtr  
        NV_ENC_PIC_TYPE     pictureType 
        NV_ENC_PIC_STRUCT   pictureStruct   

    ctypedef struct NV_ENC_LOCK_INPUT_BUFFER:
        NV_ENC_INPUT_PTR inputBuffer    
        void*       bufferDataPtr       
        uint32_t    pitch               

    ctypedef struct NV_ENC_MAP_INPUT_RESOURCE:
        void*       inputResource       
        NV_ENC_REGISTERED_PTR registeredResource    
        NV_ENC_INPUT_PTR mappedResource 
        NV_ENC_BUFFER_FORMAT mappedBufferFmt    

    ctypedef struct GUID:
        uint32_t Data1
        uint16_t Data2
        uint16_t Data3
        uint8_t  Data4[8]

    ctypedef struct NV_ENC_PIC_PARAMS_H264:
        uint32_t    displayPOCSyntax    
        uint32_t    refPicFlag          
        uint32_t    colourPlaneId       

    ctypedef union NV_ENC_CODEC_PIC_PARAMS:
        NV_ENC_PIC_PARAMS_H264 h264PicParams    

    ctypedef struct NV_ENC_PIC_PARAMS:
        uint32_t    inputWidth          
        uint32_t    inputHeight         
        uint32_t    inputPitch          
        uint32_t    encodePicFlags      
        uint32_t    frameIdx            
        uint64_t    inputTimeStamp      
        NV_ENC_INPUT_PTR  inputBuffer   
        NV_ENC_OUTPUT_PTR outputBitstream 
        NV_ENC_BUFFER_FORMAT bufferFmt  
        NV_ENC_PIC_STRUCT pictureStruct 
        NV_ENC_PIC_TYPE pictureType     
        NV_ENC_CODEC_PIC_PARAMS codecPicParams  

    ctypedef NVENCSTATUS (*PNVENCENCODEPICTURE)             (void* encoder, NV_ENC_PIC_PARAMS* encodePicParams) nogil
    ctypedef NVENCSTATUS (*PNVENCLOCKBITSTREAM)             (void* encoder, NV_ENC_LOCK_BITSTREAM* lockBitstreamBufferParams) nogil
    ctypedef NVENCSTATUS (*PNVENCUNLOCKBITSTREAM)           (void* encoder, NV_ENC_OUTPUT_PTR bitstreamBuffer) nogil
    ctypedef NVENCSTATUS (*PNVENCMAPINPUTRESOURCE)          (void* encoder, NV_ENC_MAP_INPUT_RESOURCE* mapInputResParams) nogil
    ctypedef NVENCSTATUS (*PNVENCUNMAPINPUTRESOURCE)        (void* encoder, NV_ENC_INPUT_PTR mappedInputBuffer) nogil

    ctypedef struct NV_ENCODE_API_FUNCTION_LIST:
        PNVENCENCODEPICTURE             nvEncEncodePicture
        PNVENCLOCKBITSTREAM             nvEncLockBitstream
        PNVENCUNLOCKBITSTREAM           nvEncUnlockBitstream
        PNVENCMAPINPUTRESOURCE          nvEncMapInputResource
        PNVENCUNMAPINPUTRESOURCE        nvEncUnmapInputResource


cdef class Encoder:
    cdef unsigned int input_width
    cdef unsigned int input_height
    cdef unsigned int encoder_width
    cdef unsigned int encoder_height
    cdef object encoding
    cdef object kernel
    cdef NV_ENCODE_API_FUNCTION_LIST *functionList
    cdef void *context
    cdef GUID codec
    cdef NV_ENC_REGISTERED_PTR inputHandle
    cdef object inputBuffer
    cdef object cudaInputBuffer
    cdef object cudaOutputBuffer
    cdef unsigned int inputPitch
    cdef unsigned int outputPitch
    cdef void *bitstreamBuffer
    cdef NV_ENC_BUFFER_FORMAT bufferFmt
    cdef uint64_t first_frame_timestamp
    cdef unsigned long frames
    cdef uint64_t bytes_out

    cdef object __weakref__

    cdef do_compress_image(self, image, options={}):
        cdef NV_ENC_PIC_PARAMS picParams
        cdef NV_ENC_MAP_INPUT_RESOURCE mapInputResource
        cdef NV_ENC_LOCK_BITSTREAM lockOutputBuffer
        cdef size_t size
        cdef unsigned int x, y, stride
        cdef unsigned int i
        cdef NVENCSTATUS r
        assert self.context, "context is not initialized"
        start = time.time()
        print("compress_image(%s, %s)", image, options)
        cdef unsigned int w = image.get_width()
        cdef unsigned int h = image.get_height()
        pixels = image.get_pixels()
        cdef unsigned int image_stride = image.get_rowstride()
        cdef unsigned long input_size = self.inputPitch * self.input_height

        #copy to input buffer:
        cdef object buf
        buf = self.inputBuffer
        cdef unsigned long pix_len = len(pixels)

        cdef uint32_t blockw = 32
        cdef uint32_t blockh = 32
        cdef uint32_t gridw = w//(blockw)
        cdef uint32_t gridh = h//(blockh)
        if gridw*blockw<w:
            gridw += 1
        if gridh*blockh<h:
            gridh += 1
        cdef unsigned int in_w = self.input_width
        cdef unsigned int in_h = self.input_height
        if self.scaling!=(1,1):
            in_w, in_h = w, h

        csc_start = time.time()
        args = (self.cudaInputBuffer, int(in_w), int(in_h), int(stride),
               self.cudaOutputBuffer, int(self.encoder_width), int(self.encoder_height), int(self.outputPitch),
               int(w), int(h))
        print("calling %s%s with block=%s, grid=%s", self.kernel, args, (blockw,blockh,1), (gridw, gridh))
        self.kernel(*args, block=(blockw,blockh,1), grid=(gridw, gridh))
        csc_end = time.time()
        print("compress_image(..) kernel %s took %.1f ms", self.kernel, (csc_end - csc_start)*1000.0)

        r = self.functionList.nvEncMapInputResource(self.context, &mapInputResource)
        cdef NV_ENC_INPUT_PTR mappedResource = mapInputResource.mappedResource

        try:
            picParams.bufferFmt = self.bufferFmt
            picParams.pictureStruct = NV_ENC_PIC_STRUCT_FRAME
            picParams.inputWidth = self.encoder_width
            picParams.inputHeight = self.encoder_height
            picParams.inputPitch = self.outputPitch
            picParams.inputBuffer = mappedResource
            picParams.outputBitstream = self.bitstreamBuffer
            if self.frames==0:
                picParams.pictureType = NV_ENC_PIC_TYPE_IDR
                picParams.encodePicFlags = NV_ENC_PIC_FLAG_OUTPUT_SPSPPS
            else:
                picParams.pictureType = NV_ENC_PIC_TYPE_P
            picParams.codecPicParams.h264PicParams.displayPOCSyntax = 2*self.frames
            picParams.frameIdx = self.frames
            picParams.inputTimeStamp = image.get_timestamp()-self.first_frame_timestamp

            with nogil:
                r = self.functionList.nvEncEncodePicture(self.context, &picParams)
            encode_end = time.time()

            lockOutputBuffer.outputBitstream = self.bitstreamBuffer
            with nogil:
                r = self.functionList.nvEncLockBitstream(self.context, &lockOutputBuffer)
            size = lockOutputBuffer.bitstreamSizeInBytes
            self.bytes_out += size
        finally:
            if lockOutputBuffer.bitstreamBufferPtr!=NULL:
                with nogil:
                    r = self.functionList.nvEncUnlockBitstream(self.context, self.bitstreamBuffer)
            with nogil:
                r = self.functionList.nvEncUnmapInputResource(self.context, mapInputResource.mappedResource)
        return None
```

**Comment by robertwb** [comment] 2017-07-06 06:19
Thanks. Looks like this is a duplicate of #1744. Oddly, everyone seems to be able to reproduce this but me (the above code works fine).

**Closed by robertwb** 2017-07-06 06:19 UTC
