### ISSUE TITLE
no attribute __reduce_cython__

### ISSUE THREAD

**Issue by cschramm** [cython/cython#1953] opened 2017-10-28 10:48 UTC
https://github.com/cython/cython/issues/1894#issuecomment-339966952.

I'm getting an `AttributeError` due to a missing `__reduce_cython__` attribute in an embedded environment when I build lxml with Cython 0.26 or 0.27. 0.25(.2) works fine. The issue seems to be triggered by reinitializing the environment but unfortunately I was not able to find a minimal sample that replicates it yet.

I did a git-bisect and found https://github.com/cython/cython/commit/f8b3405e926d2ba9bc2ee24d79848235875ee12e to be the first broken commit.

Will try to find a simple test case, but I'm not sure how soon I'll have a result.

**Comment by scoder** [comment] 2017-10-29 06:34
What Python version are you using?
Is that with the latest lxml release? And does it also fail with the pre-generated C files, i.e. without rerunning Cython?
Could you please provide the complete stack trace of the failure that you get?

**Comment by cschramm** [comment] 2017-10-29 10:13
I was able to isolate it now. 🎉

Python 3.6.3, lxml 3.8.0, Cython 0.26.1

```
Py_Initialize();

PyObject *pName = PyUnicode_FromString("lxml.etree");

PyImport_Import(pName);

Py_Finalize();
Py_Initialize();

if (PyImport_Import(pName) == NULL) {
    PyErr_Print();
    return -1;
} else {
    return 0;
}
```

=>

```
Traceback (most recent call last):
  File "src/lxml/etree.pyx", line 287, in init lxml.etree
    cdef class _TempStore:
AttributeError: type object 'lxml.etree._TempStore' has no attribute '__reduce_cython__'
```

From my previous tests it should be the same for all Cython 0.26 and 0.27 versions while 0.25.2 works.
I did not try other Python versions.
It does *not* affect lxml 4.0.0. I traced that down to https://github.com/lxml/lxml/commit/3e2967ba64dd21b3eb6aab7024f7b581dda42c8f, so I guess recent versions would show the same issue if you re-enable that "auto_pickle" feature.

**Comment by scoder** [comment] 2017-10-29 19:32
Thanks for digging up the details. Extension modules  that support reloading are probably still extremely rare. Definitely not lxml. And the support in Cython is still pending (#1715).

**Comment by cschramm** [comment] 2017-10-30 07:34
Sad to hear that.

I'm not 100 % sure what you mean. Multi-phase initialization isn't necessary for extension modules to support reloading, is it? We didn't ever have any issues with reloading lxml up to now (well, there might be hidden memory leaks of course).

Anyway, now that I know that it's only an issue with lxml (<)= 3.8.0 && Cython >= 0.26.0 it's not a real problem for me (the way to get around it is just to use a recent lxml version if you use a recent Cython version). It would only become a problem again if the lxml project decides to re-enable auto_pickle.

**Comment by jmschrei** [comment] 2017-12-26 21:29
I started seeing this recently as well in my AppVeyor builds. One can be seen here: https://ci.appveyor.com/project/JacobSchreiber/pomegranate/build/1.0.449/job/12bpi71jy7aiwmve

Here is a full error:

```
======================================================================
ERROR: Failure: AttributeError (type object 'pomegranate.base.Model' has no attribute '__reduce_cython__')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\test-environment\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Miniconda3\envs\test-environment\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Miniconda3\envs\test-environment\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Miniconda3\envs\test-environment\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Miniconda3\envs\test-environment\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\Miniconda3\envs\test-environment\lib\imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\projects\pomegranate\tests\test_distributions.py", line 3, in <module>
    from pomegranate import (Distribution,
  File "c:\projects\pomegranate\pomegranate\__init__.py", line 9, in <module>
    from .base import *
  File "pomegranate\base.pyx", line 18, in init pomegranate.base
    cdef class Model(object):
AttributeError: type object 'pomegranate.base.Model' has no attribute '__reduce_cython__'
```

I don't get these issues on the Python 2.7 builds. It uses Cython 0.27 but I'm going to try downgrading to 0.25.

**Comment by chriscainx** [comment] 2018-04-27 19:13
Encountered this too. Using python 3.6.5 and cython 0.27.3

`
>>> import _utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "stringsource", line 103, in init myproject._utils
AttributeError: type object 'myproject._utils.array' has no attribute '__reduce_cython__'
>>> quit()
`

**Comment by chriscainx** [comment] 2018-04-27 19:29
When cythonize _utils.pyx outside somewhere and import there's no problem, but when building it under my package, then open python and import, or install the package then import goes wrong.

`import _utils  
Traceback (most recent call last):  
File "", line 1, in   
File "stringsource", line 103, in init myproject._utils
AttributeError: type object 'myproject._utils.array' has no attribute 'reduce_cython'
quit()`

**Comment by scoder** [comment] 2018-05-04 20:50
@chriscainx: it looks like you're not importing the module from its package but directly as a top-level module from its package directory. It should work if you import it correctly instead. It might be possible to improve something here, but I wouldn't consider it a priority.

@eliaperantoni: Not sure what PyInstaller does different from a normal Python import here. Could you please investigate?

**Comment by eliaperantoni** [comment] 2018-05-04 21:47
@scoder """Solved""" by removing pandas import which I was actually not using, could that be issue? Importing a module but not using it?

**Comment by Hellcat1005** [comment] 2018-05-10 08:45
@eliaperantoni I got AttributeError: type object 'pandas._libs.tslib._TSObject' has no attribute '__reduce_cython__' as well. I solved this problem by using pandas-0.20.3, cython-0.27.3 and python-3.5.

**Comment by eliaperantoni** [comment] 2018-05-10 13:28
@Hellcat1005 I solved the DLL error but now I'm getting 
```
AttributeError: type object 'scipy.interpolate.interpnd.array' has no attribute '__reduce_cython__'
```
which I didn't find a github issue for and I have no idea how to solve.
At this point I think I'm just going to bundle the application another way

**Comment by xianweilv** [comment] 2018-05-18 12:07
@eliaperantoni I  have the same problem with you. Have you solved it?
`AttributeError: type object 'scipy.interpolate.interpnd.array' has no attribute '__reduce_cython__'`

**Comment by eliaperantoni** [comment] 2018-05-18 20:40
No, not yet :(

**Comment by Dnlah** [comment] 2018-05-21 12:54
Any updates? I'm having a similar issue and can't seem to figure out what is wrong.

**Comment by eliaperantoni** [comment] 2018-05-22 12:05
No updates sorry :(

**Comment by szymonmaszke** [comment] 2018-05-24 16:37
@eliaperantoni Import scipy.interpolate.interpnd in your script somewhere, it will fix it. You could create a hook for it, I got not luck with that unluckily.

**Comment by eliaperantoni** [comment] 2018-05-24 17:44
Ok that solved the issue but now I'm getting the fourth error...
File "messagestream.pxd", line 5, in init scipy.spatial.qhull
ModuleNotFoundError: No module named 'scipy._lib.messagestream'

**Comment by eliaperantoni** [comment] 2018-05-24 17:44
Googling it, will post updates

**Comment by szymonmaszke** [comment] 2018-05-24 17:56
@eliaperantoni --hidden-import=scipy._lib.messagestream
And you really should go through PyInstaller's docs.

**Comment by scoder** [comment] 2018-05-25 18:59
Could this problem be related to cyclic import? I.e. a module being reimported elsewhere while its module init function is still executing?

**Comment by scoder** [comment] 2018-05-25 19:05
To clarify: there are multiple different cases in this ticket. I can see at least three different setups that suggest different reasons for this to occur. The initially described module reinitialisation is definitely an issue by its own, so I'm trying to find out what might cause the other reports.

**Comment by scoder** [comment] 2018-05-27 08:28
The underlying reason is most likely this: https://bugs.python.org/issue32973

**Comment by scoder** [comment] 2018-05-27 08:38
BTW, there is a work-around for that CPython issue in 0.28+, see c872937f6c8a784b06b274b8d280ebc5aa806bc4
Could the people in this thread please make sure they have tried the latest release, so that I can be sure that it does not solve the problem?

**Comment by nicoddemus** [comment] 2018-05-29 18:23
I was having this same problem with `scipy 1.0.1`, but updating to `1.1.0` (which I suppose uses a newer `cpython`) fixed this for me. 👍

**Comment by jh0w3l05** [comment] 2018-06-14 00:51
Having 'somehow' the same error:
AttributeError: type object 'cytoolz.itertoolz.remove' has no attribute '__reduce_cython__'
![pyinstaller_attributeerror](https://user-images.githubusercontent.com/40228894/41385732-0237d8c2-6f6d-11e8-9d1f-15600a6747af.png)

I'm using the ff:
Conda 4.5.4
Python 3.6.5
Cython 0.28.3
Scipy 1.1.0

@eliaperantoni or anyone who has an idea:
How did you had a extra-dll on your scipy installation?
On my current scipy install I do not have that.
Thanks.

**Comment by eliaperantoni** [comment] 2018-06-18 11:44
@jh0w3l05 Nothing fancy really. I created a virtual environment and installed scipy. The full path is:
`project_folder/env/env/Lib/site-packages/scipy/extra-dll`

**Comment by scoder** [comment] 2018-06-18 17:16
@jh0w3l05, just having Cython version x.y installed on your system is entirely irrelevant if a certain package that you install was built with an older Cython version that has a bug.

I'll close this ticket now, since the cause was fixed with 0.28. Please open a new ticket if you find a similar problem that occurs in software that was built with 0.28 or later.

**Closed by scoder** 2018-06-18 17:16 UTC

**Comment by cschramm** [comment] 2018-06-19 08:38
I can confirm that I cannot replicate my issue with 0.28.3 anymore. :+1:

**Comment by nicoddemus** [comment] 2018-07-06 11:54
@taosean the libraries you use or depend on that use Cython should be compiled with 0.28+, see https://github.com/cython/cython/issues/1953#issuecomment-398128940.

**Comment by taosean** [comment] 2018-07-09 01:57
@nicoddemus Thank you for your reply. Just as you suggested, I updated my cython to 0.28.3 and recompiled my .pyx file to get .pyd file, and also, I recompiled my caffe with python which installed cython 0.28.3. However, I got no luck and still got the same error. Below is the detailed traceback, any ideas? Thanks!
![default](https://user-images.githubusercontent.com/17960909/42426927-5dab9fb8-835e-11e8-9f54-db53ed10b9d9.PNG)

**Comment by glorioushedgehog** [comment] 2018-07-13 21:46
I've been getting the pyinstaller interpnd error with Scipy 1.1.0, which I need to use tensorlayer. Here is the end of the stack trace:

`  
File "site-packages\scipy\interpolate\interpolate.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "c:\users\paul\insightface_tf\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
  File "stringsource", line 104, in init scipy.interpolate.interpnd
AttributeError: type object 'scipy.interpolate.interpnd.array' has no attribute '__reduce_cython__'
`

I've tried all the solutions offered here. Since Scipy 1.1.0 worked for @nicoddemus , I don't know what else could be going wrong. I'm using python 3.6.6.

**Comment by scoder** [comment] 2018-07-14 04:39
Since further comments on this ticket seem unhelpful and make the relevant comment harder to find, I'll lock the issue. Please read https://github.com/cython/cython/issues/1953#issuecomment-398128940

**Comment by scoder** [comment] 2018-08-01 20:52
One more thing to add, since it came up along the way: calling `Py_Initialize()` after `Py_Finalize()` is not actually supported in CPython: https://bugs.python.org/issue34309
