### ISSUE TITLE
Build broken on git master

### ISSUE THREAD

**Issue by pitrou** [cython/cython#2050] opened 2017-12-20 16:48 UTC
It seems the culprit is changeset e1ae63dd990e5d74a500d4051f0a8a1dd5fbae9b. See https://travis-ci.org/cython/cython/builds/318500666

@scoder

**Comment by scoder** [comment] 2017-12-20 17:16
Hmm, sorry, yes. That changeset should just get reverted. I'll do it tonight.

**Comment by matthew-brett** [comment] 2017-12-21 00:45
Maybe the cause of all the wheel builds failing ? 

https://travis-ci.org/MacPython/cython-wheels/builds/319238051

**Comment by scoder** [comment] 2017-12-21 21:37
Fixed by reverting the commit.

**Closed by scoder** 2017-12-21 21:37 UTC
