### ISSUE TITLE
[BUG] Unknown object types PyComplexObject, incomplete types PyTypeObject, PyLongObject when use -DCYTHON_LIMITED_API

### ISSUE THREAD

**Issue by rekby** [cython/cython#6194] opened 2024-05-11 10:39 UTC
### Describe the bug

Use undefined objects when `-DCYTHON_LIMITED_API` enabled.

```
cython_ydb_extension.c:2067:75: error: unknown type name ‘PyComplexObject’; did you mean ‘PyCodeObject’?
 2067 | static CYTHON_INLINE double __pyx_f_7cpython_7complex_7complex_4real_real(PyComplexObject *__pyx_v_self); /* proto*/
      |                                                                           ^~~~~~~~~~~~~~~
      |                                                                           PyCodeObject

...
cython_ydb_extension.c:6154:10: error: invalid application of ‘sizeof’ to incomplete type ‘PyTypeObject’ {aka ‘struct _typeobject’}
 6154 |   sizeof(PyTypeObject), __PYX_GET_STRUCT_ALIGNMENT_3_1_0a0(PyTypeObject),
      |          ^~~~~~~~~~~~

...
cython_ydb_extension.c:921:38: error: invalid application of ‘sizeof’ to incomplete type ‘PyLongObject’ {aka ‘struct _longobject’}
  921 | #define PyBoolObject                 PyLongObject
      |                                      ^~~~~~~~~~~~

```

### Code to reproduce the behaviour:

https://github.com/rekby/ydb-c/blob/753186e99f165cfaeb3f7c8c48a192634dc661d2/cython_ydb_extension/cython_ydb_extension.pyx

### Expected behaviour

compile the module fine (it is compiled without `-DCYTHON_LIMITED_API`)

### OS

linux

### Python version

3.10.12

### Cython version

3.1.0a0 (commit 72221faa1362c4c5b2fa1d8b4ba1a195e97a5c5f)

### Additional context

The problem existed at 3.0.10 too.

**Comment by da-woods** [comment] 2024-05-11 10:55
Duplicate of https://github.com/cython/cython/issues/5634

**Closed by da-woods** 2024-05-11 10:55 UTC

**Comment by da-woods** [comment] 2024-05-11 11:00
The Limited API on Cython 3.0 isn't useable for anything non-trivial.

On Cython 3.1 we intend to support a lot (but not everything). However right now, many of the changes aren't yet merged. If you want to test out the pending changes (or the understanding that it's an unreviewed testing branch) then look at https://github.com/cython/cython/issues/6082
