### ISSUE TITLE
[BUG] After compiling pyd with pure Python, I can't access properties, but I can access methods.

### ISSUE THREAD

**Issue by 17Reset** [cython/cython#5856] opened 2023-11-21 03:11 UTC
### Describe the bug

I have defined some properties and methods in a class, but after compiling to pyd through cythonize, the object that defines this class, can't access the properties through ,but access the methods.

### Code to reproduce the behaviour:

```cython
# example code
class DocumentCanvas(QWidget):
    def __init__(self):
        super().__init__()

        self.title_label = QLabel('Document Canvas')
        self.pdf_viewer = PdfViewer()
        self._title_label_property()
        self._document_canvas_layout_property()

    def _title_label_property(self):
        self.title_label.setMinimumHeight(INFOBAR_MIN_HEIGHT)
        self.title_label.setMaximumWidth(INFOBAR_MAX_WIDTH)
        self.title_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.title_label.setStyleSheet('background-color: rgb(227, 227, 227);')

    def _document_canvas_layout_property(self):
        grid_layout = QGridLayout()
        grid_layout.setContentsMargins(0, 0, 0, 0)
        grid_layout.setSpacing(0)
        grid_layout.addWidget(self.title_label,  0, 0, 1, 1)
        grid_layout.addWidget(self.pdf_viewer, 1, 0, 1, 1)
        self.setLayout(grid_layout)
```

### OS

WIndows

### Python version

Python 3.12.0

### Cython version

Cython version 3.0.5

**Comment by scoder** [comment] 2023-11-21 05:38
Do you get an error message that you could show here? And what is the code that you produce it with?

**Comment by da-woods** [comment] 2023-11-21 07:28
And where do you import `QWidget` from? (There's at least 2 sensible options)

**Comment by 17Reset** [comment] 2023-11-22 02:22
1. py file will be compiled into pyd file code: cythonize -i -3 document_canvas.py. 
2. pyd file is located in the path added to the Python variable PYTHONPATH 
3. use pycharm editor, in the code to call: 
from document_canvas import DocumentCanvas 
document_canvas = DocumentCanvas() 
document_canvas._title_label_property() -> this code can be recognized by pycharm 
document_canvas.pdf_viewer -> this code can not be recognized by pycharm, it will prompt that the class DocumentCanvas does not define pdf_viewer 
4. So I would like to know that the properties defined in the class, compiled using cython, can not be accessed normally by the outside?

**Comment by da-woods** [comment] 2023-11-22 08:11
Here's a more minimal example **that doesn't demonstrate the bug**

```
class DocumentCanvas:
    def __init__(self):
        self.pdf_viewer = "TEST"
```

Compile with `cythonize -if3 document_canvas.py`

At the command line:

```
>>> from document_canvas import DocumentCanvas
>>> document_canvas = DocumentCanvas()
>>> document_canvas.pdf_viewer
'TEST'
```

So this works.

Unfortunately we don't have the information to investigate your full example because you haven't told us:
* what is `QWidget`? *As I said before, there are multiple modules you could be importing this from*
* what is `PdfViewer`?
* Which of these is important to reproducing the bug?

**Comment by 17Reset** [comment] 2023-11-22 08:59
> Here's a more minimal example **that doesn't demonstrate the bug**
> 
> ```
> class DocumentCanvas:
>     def __init__(self):
>         self.pdf_viewer = "TEST"
> ```
> 
> Compile with `cythonize -if3 document_canvas.py`
> 
> At the command line:
> 
> ```
> >>> from document_canvas import DocumentCanvas
> >>> document_canvas = DocumentCanvas()
> >>> document_canvas.pdf_viewer
> 'TEST'
> ```
> 
> So this works.
> 
> Unfortunately we don't have the information to investigate your full example because you haven't told us:
> 
> * what is ? _As I said before, there are multiple modules you could be importing this from_`QWidget`
> * what is ?`PdfViewer`
> * Which of these is important to reproducing the bug?

Sorry, QWidget -> This is import from PyQt6 library, PdfViewer() is not important for this example, what I want to express is that after cython compilation, after importing the library using PyCharm IDE, the properties defined inside the class are not recognized correctly, but the methods can be recognized, and the functionality is not a problem. The problem is that the IDE will actively report errors, as far as my example above is concerned:
![117556df9fd4b04c213c0616249001b](https://github.com/cython/cython/assets/122418720/992c88d0-d7c1-40e2-a540-ddc1baf208ff)

class CanvasDocument(QWidget):
    """Widget canvas for displaying PDFs."""
    def __init__(self):
        super().__init__()

        self.title_label = QLabel('Document Canvas')
        self.pdf_viewer = XQtPdfViewer()
        self._label_property()
        self._layout_property()

    def _label_property(self):
        self.title_label.setMinimumHeight(LABEL_BAR_HEIGHT)
        self.title_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.title_label.setStyleSheet('background-color: rgb(227, 227, 227);')

    def _layout_property(self):
        grid_layout = QGridLayout()
        grid_layout.setContentsMargins(0, 0, 0, 0)
        grid_layout.setSpacing(WIDGET_SPACING0)
        grid_layout.addWidget(self.title_label,  0, 0, 1, 1)
        grid_layout.addWidget(self.pdf_viewer, 1, 0, 1, 1)
        self.setLayout(grid_layout)

**Comment by 17Reset** [comment] 2023-11-22 09:02
The functionality is fine and works as expected, it's the IDE that can't recognize the attributes in the class and pops up a warning, causing an impact on the development experience.

**Comment by scoder** [comment] 2023-11-22 10:56
Unsurprisingly, Python IDEs cannot look into binary extension modules. And you're probably using the PyCharm Community Edition, and not their paid version that support Cython code.

Try using Python annotations in the class, that might help the IDE understand what's going on. There's also work being done to generate `.pyi` typing stub files for Cython modules (https://github.com/cython/cython/pull/5744), but that's not completed yet.

I'll close this ticket since it's not really a bug in Cython. Cython already goes to great length making this work better than for arbitrary C implemented extension modules.

**Closed by scoder** 2023-11-22 10:56 UTC
Labels: support question
