### ISSUE TITLE
build_ext for distutils compatible setup.py (optional cythonize).

### ISSUE THREAD

**Issue by eyakimov-bbg** [cython/cython#2516] opened 2018-07-24 20:43 UTC
Looking at the documentation [Distributing Cython Modules](https://cython.readthedocs.io/en/latest/src/reference/compilation.html#distributing-cython-modules) and a very brief discussion on [cython-users](https://groups.google.com/forum/#!topic/cython-users/4HW3lTKeEsQ), it seems desirable to support a build workflow that is suitable for both invoking cythonize, as well as a simple build without running cythonize. This presumes that the source is shipped using both the cython files as well as the generated source.

From the documentation ([Distributing Cython Modules](https://cython.readthedocs.io/en/latest/src/reference/compilation.html#distributing-cython-modules))
it seems that to support this workflow, users need to have a rather intrusive changeset to their `setup.py`.

I wanted to propose a build_ext command variant which is optimised for the non-cythonize workflow, and allows `setup.py` to be written as if it was to be built by a non cython `distutils`, and instead do some smart deduction of source discovery/replacement as a pre-build step.

I've mocked up an example of such a build_ext which works this way here: https://github.com/eyakimov-bbg/python-testmodule/blob/cython_build_ext/setup.py

In theory this can be pulled in optionally by setuptools just like the old cython build_ext was, if it is implemented this way then the `setup.py` would not have any cython specific settings at all. Although having said that, being able to specify cythonize parameters in setup.py can be useful, but for this case I would suggest that build_ext command be explicitly set via setup.py's cmdclass property (perhaps conditionally on the presence of cython) with the cythonize parameters bound.

Is this something that would be desirable for cython's build_ext?

**Comment by scoder** [comment] 2018-08-14 04:28
I think it would be nice either as a separate package on PyPI or as a part of setuptools. I hadn't seen your ticket before creating #2531, not sure which is better now.

**Comment by scoder** [comment] 2018-08-15 12:03
Closing this as a duplicate of #2531 (sorry). Please copy anything over that you consider relevant.

**Closed by scoder** 2018-08-15 12:03 UTC
Labels: R: duplicate

**Comment by jdemeyer** [comment] 2018-08-22 15:13
Also a duplicate of #1514
