### ISSUE TITLE
Reference leaks on passing typed memoryviews to Python functions

### ISSUE THREAD

**Issue by pv** [cython/cython#3052] opened 2019-07-23 21:12 UTC
The following code appears to leak references on a Python debug build (python3.7-dbg + Cython 0.29.12):
```
import array

obj = array.array('d', [1.0])
cdef double[:] x = obj

def doit():
    for j in range(10000):
        id(x)
```
I'm not so far sure precisely what is leaked here, apart from seeing that `sys.gettotalrefcount()` increases by one for each loop iteration inside `doit()`. This does not leak memory, though.

Reproducing script:
<details>

```sh
set -e
mkdir tmp
cd tmp
PYTHON=python3.7-dbg

cat <<__EOF__ > refleak.pyx
import array

obj = array.array('d', [1.0])
cdef double[:] x = obj

def doit():
    for j in range(10000):
        id(x)
__EOF__

$PYTHON -mCython.Build.Cythonize -i refleak.pyx

cat <<__EOF__ > run.py
import sys
import refleak

before = sys.gettotalrefcount()
refleak.doit()
after = sys.gettotalrefcount()

print("leaked:", after - before, "refs")
print("OK" if after < before + 5000 else "FAIL")
__EOF__

$PYTHON -mcython --version
$PYTHON run.py
```
outputs for me
```
Cython version 0.29.12
leaked: 10002 refs
FAIL
```
</details>

**Comment by scoder** [comment] 2019-07-24 05:18
Duplicate of #3023

**Closed by scoder** 2019-07-24 05:18 UTC
Labels: R: duplicate

**Comment by pv** [comment] 2019-07-24 12:29
Thanks, sorry, should have checked more carefully.
