### ISSUE TITLE
"This may never happen" on an attempt to declare a const attribute of fused type

### ISSUE THREAD

**Issue by moskupols** [cython/cython#553] opened 2016-08-12 09:17 UTC
```
$ cat /etc/*-release | grep \^NAME; python --version; cython --version   
NAME="Ubuntu"
Python 2.7.6
Cython version 0.24.1
```

``` cython
$ cat some.pyx
ctypedef fused Fused:
    int
    bytes


cdef class FusedWrapper:
    cdef const Fused* fused_ptr
```

```
$ cython some.pyx
Traceback (most recent call last):
  File "/usr/local/bin/cython", line 9, in <module>
    load_entry_point('Cython==0.24.1', 'console_scripts', 'cython')()
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-x86_64.egg/Cython/Compiler/Main.py", line 698, in setuptools_main
    return main(command_line = 1)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-x86_64.egg/Cython/Compiler/Main.py", line 715, in main
    result = compile(sources, options)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-x86_64.egg/Cython/Compiler/Main.py", line 690, in compile
    return compile_multiple(source, options)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-x86_64.egg/Cython/Compiler/Main.py", line 668, in compile_multiple
    result = run_pipeline(source, options, context=context)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-x86_64.egg/Cython/Compiler/Main.py", line 495, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-x86_64.egg/Cython/Compiler/Pipeline.py", line 365, in run_pipeline
    data = phase(data)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-x86_64.egg/Cython/Compiler/Pipeline.py", line 53, in generate_pyx_code_stage
    module_node.process_implementation(options, result)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-x86_64.egg/Cython/Compiler/ModuleNode.py", line 131, in process_implementation
    self.generate_c_code(env, options, result)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-x86_64.egg/Cython/Compiler/ModuleNode.py", line 374, in generate_c_code
    self.generate_declarations_for_modules(env, modules, globalstate)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-x86_64.egg/Cython/Compiler/ModuleNode.py", line 582, in generate_declarations_for_modules
    env, modules, vtab_list, vtabslot_list, typecode)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-x86_64.egg/Cython/Compiler/ModuleNode.py", line 561, in generate_type_definitions
    self.generate_objstruct_definition(entry.type, code)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-x86_64.egg/Cython/Compiler/ModuleNode.py", line 1046, in generate_objstruct_definition
    "%s;" % attr_type.declaration_code(attr.cname))
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-x86_64.egg/Cython/Compiler/PyrexTypes.py", line 2514, in declaration_code
    for_display, dll_linkage, pyrex)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-x86_64.egg/Cython/Compiler/PyrexTypes.py", line 1427, in declaration_code
    return self.const_base_type.declaration_code("const %s" % entity_code, for_display, dll_linkage, pyrex)
  File "/usr/local/lib/python2.7/dist-packages/Cython-0.24.1-py2.7-linux-x86_64.egg/Cython/Compiler/PyrexTypes.py", line 1485, in declaration_code
    raise Exception("This may never happen, please report a bug")
Exception: This may never happen, please report a bug
```

**Comment by jakirkham** [comment] 2018-07-12 20:50
Also running into this with Cython 0.28.3.

**Comment by jakirkham** [comment] 2018-07-12 20:53
Duplicate of issue ( https://github.com/cython/cython/issues/1772 )?

**Comment by scoder** [comment] 2019-09-17 19:55
Yes, duplicate of #1772.

**Closed by scoder** 2019-09-17 19:55 UTC
Labels: R: duplicate
