### ISSUE TITLE
[BUG] Enabling limited API attempts to take the size of an opaque object

### ISSUE THREAD

**Issue by vyasr** [cython/cython#6056] opened 2024-03-03 22:26 UTC
### Describe the bug

I've been trying to add some more support for Python Limited API and I ran into one case that I don't know how to handle. There is a part of [ModuleNode.py](https://github.com/cython/cython/blob/master/Cython/Compiler/ModuleNode.py#L3878) where the size of a struct is computed, and there is some logic for mapping objects to other objects when we really need the `sizeof` a different object. The problem I'm observing is that when the core `cpython.type` module is cimported, the code is attempting to do `sizeof(PyTypeObject)` and `alignof(PyTypeObject)`, which is invalid because [the API defines it as only available as an opaque object](https://docs.python.org/3/c-api/type.html#c.PyTypeObject). In other words, its size cannot be determined because at this stage only a declaration is involved, not a definition. I don't really understand this part of the Cython code and would appreciate some pointers on what the right solution here would be.

### Code to reproduce the behaviour:

```cython
# test.pyx
cimport cpython.type
```

```
# setup.py
from setuptools import setup, Extension
from Cython.Build import cythonize

setup(
    ext_modules = cythonize(
        Extension(
            "test",
            ["test.pyx"],
            define_macros=[("Py_LIMITED_API", "0x03030000"), ("CYTHON_LIMITED_API", None)]
        )
    )
)
```

Results in this compilation error:
```
test.c: In function '__Pyx_modinit_type_import_code':
test.c:1999:10: error: invalid application of 'sizeof' to incomplete type 'PyTypeObject' {aka 'struct _typeobject'}
 1999 |   sizeof(PyTypeObject), __PYX_GET_STRUCT_ALIGNMENT_3_1_0a0(PyTypeObject),
      |          ^~~~~~~~~~~~
test.c:1999:60: error: invalid application of '__alignof__' to incomplete type 'PyTypeObject' {aka 'struct _typeobject'}
 1999 |   sizeof(PyTypeObject), __PYX_GET_STRUCT_ALIGNMENT_3_1_0a0(PyTypeObject),
      |                                                            ^~~~~~~~~~~~
test.c:1442:55: note: in definition of macro '__PYX_GET_STRUCT_ALIGNMENT_3_1_0a0'
 1442 | #define __PYX_GET_STRUCT_ALIGNMENT_3_1_0a0(s) alignof(s)
```

### Expected behaviour

This code should compile. I'm happy to put up a PR with a bit of guidance.

### OS

Linux

### Python version

3.11.8

### Cython version

master branch as of https://github.com/cython/cython/commit/05fd757b1161052291785f80863435a38f8d8674

**Comment by da-woods** [comment] 2024-03-04 07:03
This'll be fixed in https://github.com/cython/cython/pull/5871 I think

**Comment by da-woods** [comment] 2024-03-04 07:05
The current limited API PRs are sufficient to get Cython itself to compile so it'll actually be in a pretty usable state when those are all finished

**Comment by da-woods** [comment] 2024-03-04 08:17
Duplicate of https://github.com/cython/cython/issues/5634

**Closed by da-woods** 2024-03-04 08:17 UTC

**Comment by vyasr** [comment] 2024-03-04 23:44
Ah I'm sorry It took me long enough to zero in on the exact error that I didn't have the presence of mind to check for duplicates once I'd come up with a true MWE. Glad to see the progress, though! Looking forward to those PRs getting in. I'll look through them and see if all my local changes are covered; if not, I can submit a PR with what remains.

**Comment by da-woods** [comment] 2024-03-05 08:34
Any local changes you have would be welcome - thanks. I'd largely stopped work on the limited API after getting Cython to compile itself because it was getting hard to work and test things in standalone branches.

**Comment by vyasr** [comment] 2024-03-06 01:47
Could you elaborate a bit more on that? Were you running into problems with trying to create modular PRs that addressed specific gaps in the limited API coverage in Cython? I agree, that sounds difficult. IMO the best path forward is likely that once you get your PRs merged we go for a while where people make whatever contributions are needed to get their own projects to compile until coverage increases enough over time that a larger scale effort can be made. In the long run I think the only way for Cython to claim full support is probably running the whole test suite with the limited API on, but that is a heavy ask that is presumably a long ways away.

**Comment by vyasr** [comment] 2024-03-06 02:33
I opened https://github.com/cython/cython/pull/6061. I checked that it didn't overlap with any of yours (it only overlaps in one file the ModuleSetupCode.c file, but I'm changing different lines than all your PRs I think) so hopefully they can go in independently.

**Comment by da-woods** [comment] 2024-03-06 07:35
>  Could you elaborate a bit more on that?

It was mostly about testing meaningfully and finding specific gaps.

If the initial work on it I'd created `tests/run/isolated_limited_api.srctree` as a way of testing the little bits that were working.  I think the isolated tests were beginning to outlive their usefulness because it was getting harder to say "I've fixed this specific feature". And because some of the PRs depended on other PRs to actually be usable.

> In the long run I think the only way for Cython to claim full support is probably running the whole test suite with the limited API on, [...]

Yes - we all agree on that. It wasn't really possible to use the full Cython test suite because it was crashing a bit unpredictably (there were/are almost certainly reference counting errors somewhere). Tests failing is OK, but if they crash the test runner doesn't detect it and ends up just timing out.

> [...] but that is a heavy ask that is presumably a long ways away.

My plan for the next thing to do on the limited API was to start turning the tests on. Probably initially going one at a time with a known list of good tests.

> Speaking of which, let me know if there's anything I can do to help your PRs along.

Any review would obviously be helpful. At some point I'm going to get a little more pro-active about just merging some of them myself.

A lot of it is pretty mechanical translation, but some of them have design decisions in that maybe need to be discussed (e.g. #5871 adds ways of conditionally compiling cdef functions. I think that's needed but there might be other ways to solve the underlying problems).

The other thing I'm considering is adding a "limited-api-preview" branch just containing all the unmerged limited API PRs. That would make it easier for anyone interested to test. (I wouldn't release anything, or keep it strictly updated with "master"; it'd just be a branch for anyone interested). I'll do that in a few days - just waiting for one other change before fixing some conflicts.

**Comment by vyasr** [comment] 2024-03-13 22:39
Sounds good. I am happy to try reviewing, but fair warning that it'll probably be a while before my reviews are of any real use since I have limited familiarity with Cython internals (beyond my limited prior contributions) especially on the actual code genor the Python C API. Neither is particularly hard to pick up on as I go, but I'll probably be starting from a place of asking very naive questions as a reviewer.

I do think having a limited API preview branch would be helpful, especially if you foresee your open limited API PRs taking a while to get fully reviewed and merged. I'm currently testing in my own local integration branch and then cherry-picking/rebasing commits into more self-contained PRs to upstream because I need some of the fixes in your open PRs in order to be able to test compiling my code with my additional changes.

**Comment by da-woods** [comment] 2024-03-16 09:47
Right - as discussed I've created a preview branch - https://github.com/cython/cython/issues/6082

It doesn't yet included your in progress PR since I'd like to tidy that up a bit more first.

Hopefully it's of some use.

**Comment by vyasr** [comment] 2024-03-17 17:10
Great thanks! That is helpful. And I agree, no need to merge my branch yet. We can get that cleaned up and finalized first.
