### ISSUE TITLE
cythonize give different result for 10**-9 vs 1e-9

### ISSUE THREAD

**Issue by gst** [cython/cython#2868] opened 2019-02-28 13:28 UTC
```
def foo(x: float=10 ** -9, y: float=1e-9) -> float:
    return x, y
```

when I `cythonize` that I get : 

```
In [1]: import foo                                                             

In [2]: foo.foo()                                                              
Out[2]: (0.0, 1e-09)
```
while I was expecting `(1e-9, 1e-9)`.

If I change `10 ** -9` to `10 ** -9.` then I get the expected result.

cython : latest version 0.29.6
ubuntu 18.04

**Comment by scoder** [comment] 2019-02-28 13:45
Duplicate of #2133.

**Closed by scoder** 2019-02-28 13:45 UTC
Labels: R: duplicate

**Comment by gst** [comment] 2019-02-28 15:56
Thanks for pointing the duplicate.

**Comment by gst** [comment] 2019-02-28 20:39
Though..

#2133 is marked as closed with a link to #2683 which is merged .. so I understand that this should be solved already ?

or do I miss something ?

**Comment by scoder** [comment] 2019-02-28 20:44
Since it's a behavioural change, it's scheduled for the next major release Cython 3.0, which is not released yet.

**Comment by gst** [comment] 2019-03-01 14:08
ho ok. It's a behavioural change regarding cython itself but I find it a bug fix regarding compatibility with CPython.. but anyway given the fix/workaround is straightforward it's not a problem anymore :)

**Comment by scoder** [comment] 2019-03-01 14:19
It's even a behavioural change that can easily pass undetected in user code since it silently changes a value. Definitely not the kind of change to make in a point release.
Also, Cython 3.0 is definitely the right time for fixing Python compatibility problems.
