### ISSUE TITLE
PEP 526 is not implemented for all cases

### ISSUE THREAD

**Issue by 0dminnimda** [cython/cython#4227] opened 2021-06-14 02:37 UTC
**Bug**
I suspect that cython just skips annotations if they are not in a function or in a class, so as a result, the types of variables declared in this way are python objects.

**To Reproduce**
Code to reproduce the behaviour:
```cython
# cython: annotation_typing=True

import cython

a: cython.int
b: cython.int = 5

# cython.typeof(a)  # CompileError - undeclared name not builtin: a
cython.typeof(b)    # Python_object and no indication of it!
```
An easy way to understand this is to use `annotate=True`:
![image](https://user-images.githubusercontent.com/52697657/121831398-04292000-ccd0-11eb-93ed-5e28ac510368.png)

**Expected behavior**
Same as if I compiled this:
```cython
import cython

cdef int a
cdef int b = 5

cython.typeof(a)  # int
cython.typeof(b)  # int
```
![image](https://user-images.githubusercontent.com/52697657/121831658-a6e19e80-ccd0-11eb-907f-701244a57429.png)

That is, so that both `a` and `b` are of type `int`, if for some reason this is not the correct behavior, then either an exception or a warning about it.

**Environment:**
 - OS: Microsoft Windows 10
 - Python version Python: 3.9.0
 - Checked Cython versions: 3.0a7, 0.29.23

**Additional context**
I also checked the rest of the options, here:
```cython
# cython: annotation_typing=True

import cython

# same with pure python analogs,
# e.g. @cython.cclass, @cython.cfunc or @cython.ccall
cdef class Foo:
    cdef int a  # cannot be initialized here
    b: cython.int
    c: cython.int = 4  # on 0.29: AssertionError: Python global or builtin not a Python object
    cython.declare(d=cython.int)  # no initialization functionality in this case
    e = cython.declare(cython.int)  # cannot be normaly initialized here (#4220)

    # or cdef or cpdef; function body code is practically the same
    def bar(self):
        cython.typeof(self.a)  # int
        cython.typeof(self.b)  # int
        cython.typeof(self.c)  # Python_object but warned on compilation with 3.0a7
        cython.typeof(self.d)  # int
        cython.typeof(self.e)  # int


cdef int a
cdef int b = 5
c: cython.int
d: cython.int = 5
cython.declare(e=cython.int)  # no initialization functionality in this case
f = cython.declare(cython.int)
g = cython.declare(cython.int, 5)

cython.typeof(a)    # int
cython.typeof(b)    # int
# cython.typeof(c)  # CompileError - undeclared name not builtin: c
cython.typeof(d)    # Python_object and no indication of it!
cython.typeof(e)    # int
cython.typeof(f)    # int
cython.typeof(g)    # int


def baz():
    cdef int a
    cdef int b = 6
    c: cython.int
    d: cython.int = 6
    cython.declare(e=cython.int)  # no initialization functionality in this case
    f = cython.declare(cython.int)
    g = cython.declare(cython.int, 6)

    cython.typeof(a)  # int
    cython.typeof(b)  # int
    cython.typeof(c)  # int
    cython.typeof(d)  # int
    cython.typeof(e)  # int
    cython.typeof(f)  # int
    cython.typeof(g)  # int
```

**Comment by da-woods** [comment] 2021-06-14 18:20
This is somewhat as designed:

https://github.com/cython/cython/blob/218d8dc7cc4bdcb78967055b89251be576754708/Cython/Compiler/ExprNodes.py#L1977-L1991

The basic issue is that a cdef module variable is no longer accessible from Python code. Therefore using the annotation of a cdef module variable gives a reasonably dramatic change in behaviour. It's actually surprisingly hard (although probably not impossible) to change that and generate "properties" for modules.

**Comment by scoder** [comment] 2021-06-14 18:29
> It's actually surprisingly hard (although probably not impossible) to change that and generate "properties" for modules.

There's [PEP-562](https://www.python.org/dev/peps/pep-0562) in Py3.7 and later, which would make this much easier (assuming Cython can use the function for itself and users don't implement it themselves). But that's Py3.7-only, and typing in Cython is currently for Py2.7/3.5+.

**Comment by 0dminnimda** [comment] 2021-06-14 19:59
> cdef module variable is no longer accessible from Python code. Therefore using the annotation of a cdef module variable gives a reasonably dramatic change in behaviour

Well, as a minimum, we can try to give the opportunity to use this to pure python users. For example using something like `a = cython.declare(cython.int, only_c=Ttue)` | `b: cython.only_c[cython.int]`
Naturally `only_c` is just a name for understanding what I am proposing, and nothing more.

**Comment by 0dminnimda** [comment] 2021-06-14 20:13
> But that's Py3.7-only, and typing in Cython is currently for Py2.7/3.5+.

Well, at least, we can give users the ability to turn on and off some functions, i.e. we an add something like `moduliwise_variables` that will be default as False, like `language_level`. 

Yes, I see a possible problematic place - to come up with something to allow to combine earlier versions of python and our newer functionality, I guess this is the most difficult part.  On the other hand, we can build in a version check, and if it's not 3.7+, then just raise an exception.  (The user will be aware of this with a compile-time warning)

**Comment by scoder** [comment] 2021-06-14 20:17
> > cdef module variable is no longer accessible from Python code. Therefore using the annotation of a cdef module variable gives a reasonably dramatic change in behaviour
> 
> Well, as a minimum, we can try to give the opportunity to use this to pure python users. For example using something like `a = cython.declare(cython.int, only_c=Ttue)` | `b: cython.only_c[cython.int]`
> Naturally `only_c` is just a name for understanding what I am proposing, and nothing more.

If you use `cython.declare()`, then it's equivalent to a `cdef` declaration. So the functionality is already there if you want it.

**Comment by scoder** [comment] 2021-06-14 20:22
> Well, at least, we can give users the ability to turn on and off some functions

We should avoid directives wherever possible. Functionality should be available as part of the language and not require flags.


> if it's not 3.7+, then just raise an exception

Can be done, but should only be done if this feature is really needed. If we wait long enough for someone to come and prove the need, then we may have dropped Py<3.7 support by that time and can just be happy to merge a PR.

**Comment by 0dminnimda** [comment] 2021-06-14 20:24
> If you use `cython.declare()`, then it's equivalent to a `cdef` declaration. So the functionality is already there if you want it.

Yes indeed. For some reason I forgot it ....
Well, then there is only an opportunity to make this functionality more pythonic.

**Comment by 0dminnimda** [comment] 2021-06-14 20:29
> If we wait long enough for someone to come and prove the need, then we may have dropped Py<3.7 support by that time and can just be happy to merge a PR.

Oh, I'm sure it's just a matter of time. Someday these versions will become too unpopular and unclaimed.

The only thing is that this time will be equal to years, and possibly decades, who knows. But in any case, we need to be patient;)

**Comment by 0dminnimda** [comment] 2021-06-14 20:32
> We should avoid directives wherever possible. Functionality should be available as part of the language and not require flags

I don't think I am competent to argue, but why do you think this is a bad idea?

**Comment by scoder** [comment] 2021-06-14 20:32
> we need to be patient

I'd rather lean back and ignore the problem. We did well without it for years. It's unlikely that we will break down without it any time soon.

**Comment by da-woods** [comment] 2021-06-14 20:41
Duplicate of https://github.com/cython/cython/issues/3944

Discussion of how to expose C module variables is in https://github.com/cython/cython/issues/3959

**Closed by da-woods** 2021-06-14 20:41 UTC

**Comment by scoder** [comment] 2021-06-14 20:43
> > We should avoid directives wherever possible. Functionality should be available as part of the language and not require flags
> 
> I don't think I am competent to argue, but why do you think this is a bad idea?

Directives are a tool to reach out for, not something at your finger tips. They increase the amount of things to learn and make the reasoning about code non-local, because they may be defined far away at the top of the file or even outside in a Makefile or `setup.py` script.

When looking at code, it should be obvious what it does. Directives don't give you that.

They also suffer from combinatorial explosion. If we wanted thorough testing, we'd have to run pretty much the entire test suite for the cross product of all directives. Or most of them anyway. That's far too many combinations to ever test completely, so we end up with bugs that people will still run into years from now. Any new directive add to that risk and reduces the overall test coverage of language functionality.

**Comment by 0dminnimda** [comment] 2021-06-14 20:48
> I'd rather lean back and ignore the problem. We did well without it for years. It's unlikely that we will break down without it any time soon.

Fair enough

**Comment by 0dminnimda** [comment] 2021-06-15 16:44
@scoder @da-woods In any case, we can make a warning about this during compilation, that if you want to be able to declare as `cdef`, then in this case use `cython.declare`.

**Comment by da-woods** [comment] 2021-06-15 17:10
Any warning would probably go in the block of code [I linked above](https://github.com/cython/cython/issues/4227#issuecomment-860893980) - we do emit other warnings when annotation typing is ignored so it's probably reasonable to do so here.

I'm not sure this behaviour is documented. It'd probably go in the ["PEP-484 type annotations section"](https://cython.readthedocs.io/en/latest/src/tutorial/pure.html#pep484-type-annotations) of the pure typing tutorial

**Comment by 0dminnimda** [comment] 2021-06-15 17:23
> it's probably reasonable to do so here.

Well, at least it is necessary to do this, just when I encountered the behavior, it was rather strange, and I want other users not to encounter this.

**Comment by 0dminnimda** [comment] 2021-06-16 14:03
> it's probably reasonable to do so here

Should we then open this problem?

**Comment by 0dminnimda** [comment] 2021-06-17 01:32
> > it's probably reasonable to do so here
> 
> Should we then open this problem?

@scoder @da-woods ?

**Comment by da-woods** [comment] 2021-06-17 06:02
> > it's probably reasonable to do so here
> 
> Should we then open this problem?

I don't really think so. I closed this issue because it's a duplicate and I think that's still true
