### ISSUE TITLE
Cython (tested with 0.29) allocates unreachable objects in initialization

### ISSUE THREAD

**Issue by seberg** [cython/cython#2768] opened 2018-12-26 18:00 UTC
In numpy we have errors in mtrand with the same text. This generates code that initializes the same global constant twice. (see also gh-12615)

I doubt this actually makes a difference in practic. But it causes "definitely lost" warnings in valgrind, since only the second version is reachable. A simple snippet that creates such code:
```python

def choice(c):
    if c:
        raise ValueError("A")
    else:
        raise ValueError("A")
```
generates:
```C
    /* "test_error.pyx":3
 * def choice(c):
 *     if c:
 *         raise ValueError("A")             # <<<<<<<<<<<<<<
 *     else:
 *         raise ValueError("A")
 */
    __pyx_t_2 = __Pyx_PyObject_Call(__pyx_builtin_ValueError, __pyx_tuple_, NULL); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 3, __pyx_L1_error)
    __Pyx_GOTREF(__pyx_t_2);
    __Pyx_Raise(__pyx_t_2, 0, 0, 0);
    __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;
    __PYX_ERR(0, 3, __pyx_L1_error)

    /* "test_error.pyx":2
 * def choice(c):
 *     if c:             # <<<<<<<<<<<<<<
 *         raise ValueError("A")
 *     else:
 */
  }

  /* "test_error.pyx":5
 *         raise ValueError("A")
 *     else:
 *         raise ValueError("A")             # <<<<<<<<<<<<<<
 */
  /*else*/ {
    __pyx_t_2 = __Pyx_PyObject_Call(__pyx_builtin_ValueError, __pyx_tuple_, NULL); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 5, __pyx_L1_error)
    __Pyx_GOTREF(__pyx_t_2);
    __Pyx_Raise(__pyx_t_2, 0, 0, 0);
    __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;
    __PYX_ERR(0, 5, __pyx_L1_error)
}
```

**Comment by scoder** [comment] 2018-12-26 18:18
Duplicate of #2750, resolved in 0.29.2.

**Closed by scoder** 2018-12-26 18:18 UTC
