### ISSUE TITLE
[BUG] fail to build yt with Cython 3.0.0a10 (AttributeError: cython_sources)

### ISSUE THREAD

**Issue by neutrinoceros** [cython/cython#4940] opened 2022-07-31 12:14 UTC
**Describe the bug**
I tried building [yt](https://github.com/yt-project/yt) using the latest Cython alpha (3.0.0a10), which failed with

```
AttributeError: cython_sources
```

See an example failed job here for full traceback
https://github.com/yt-project/yt/runs/7598205895?check_suite_focus=true

**To Reproduce**
here's the exact workflow file used https://github.com/neutrinoceros/yt/blob/test_cython_3/.github/workflows/bleeding-edge.yaml

These are the command invoked to build yt in this test env
```
python setup.py build_ext -q -j2                                 # runs fine
python -m pip install -e .[test] --no-build-isolation            # crashes
```

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.4
 - Python version: 3.11.0b5
 - Cython version: 3.0.0a10

**Additional context**

Most recent releases for pip and setuptools are used
- pip 22.2.1
- setuptools 63.2.0

I have very little understanding of the traceback. I *think* the problem comes from Cython because I'm just getting started testing 3.0, and the error also seems to hint that way. I'll happily provide any further details upon request.

**Comment by 0dminnimda** [comment] 2022-07-31 12:52
The test failed on `Collecting PyYAML`, so it's not about the code in the yt, tho the error suggests that it does have something to do with the cython:
```
Collecting PyYAML
  Downloading PyYAML-6.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 34.3 MB/s eta 0:00:00
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-30a1v8vn/PyYAML.egg-info
      writing /tmp/pip-modern-metadata-30a1v8vn/PyYAML.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-30a1v8vn/PyYAML.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-modern-metadata-30a1v8vn/PyYAML.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-30a1v8vn/PyYAML.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/command/dist_info.py", line 35, in run
          egg_info.run()
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 307, in run
          self.find_sources()
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in find_sources
          mm.run()
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 549, in run
          self.add_defaults()
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
          sdist.add_defaults(self)
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 252, in add_defaults
          self._add_defaults_ext()
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 337, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

```

**Comment by scoder** [comment] 2022-07-31 14:12
PyYAML was [hooking into](https://github.com/yaml/pyyaml/blob/8cdff2c80573b8be8e8ad28929264a913a63aa33/setup.py#L204) `old_build_ext` here, which was replaced by `new_build_ext` in 3.0a10 (https://github.com/cython/cython/pull/4498). The [old version](https://github.com/cython/cython/blob/master/Cython/Distutils/old_build_ext.py) had a method called `cython_sources()`.

**Comment by scoder** [comment] 2022-07-31 14:15
Duplicate of #4568.

**Closed by scoder** 2022-07-31 14:15 UTC

**Comment by neutrinoceros** [comment] 2022-07-31 14:37
Thanks for the clarification. Sorry I wasn't able to connect the dots myself.

**Comment by neutrinoceros** [comment] 2022-07-31 16:40
Just to further confirm there wasn't any other incompatibilities for building yt, thanks again !
