### ISSUE TITLE
[BUG] Wrong variable name resolution in comprehensions

### ISSUE THREAD

**Issue by jmd-dk** [cython/cython#4065] opened 2021-03-27 15:45 UTC
**Describe the bug**
Cython fails when naming the loop variable in a list comprehension the same as a local variable, while also using this local variable to create whatever is being iterated over. Example:
```cython
def bug():
    a = 10
    result = [a for a in (a + 1, a + 2)]
```
Running the above in Cython, we get

    UnboundLocalError: local variable 'a' referenced before assignment

**To Reproduce**
Consider the above example, which works fine in Python. The fact that `a` is used for generating the results of the comprehension is not important. Also, the way `a` is used to generate the iterable does not matter. A simpler (though quite synthetic) example is then
```cython
def bug():
    a = 10
    result = [5 for a in f(a)]
```
with an arbitrary definition of `f`. Even `f = None` will do, as the error happens before calling `f`.

The exact way in which this fails depend upon whether this is inside a function or not, and whether `a` is typed. Using e.g.
```cython
def f(x):
    return [x]
def bug():
    cdef int a
    a = 10
    result = [a+5 for a in f(a)]
    print(result)
```
the code now runs, though I get the wrong result `[5]` as opposed to `[15]`. I also get a `maybe-uninitialized` compilation warning, matching this.

**Expected behavior**
In all cases, the name used for the loop variable inside the comprehension should not matter. This variable should be internal to the comprehension and have nothing to do with the surrounding scopes. That is, the first `a` in `[... for a in f(a)]` should be understood as a new variable, completely separate from the second `a`, and indeed separate from all other variables. The second `a` should (and do) refer to some pre-existing variable named `a`.
Adding in two extra `a`'s for completeness, `[r(a) for a in f(a) if c(a)]`, these two new `a`'s should now refer to the comprehension-local `a` *first* (if this is indeed the name used), and *then* look in the outer scopes. This works as expected, though of course it can't be tested fully as long as having `f(a)` doesn't work.

**Environment**
 - OS: Linux Mint 20
 - Python version: 3.9.0
 - Cython version: 0.29.21
 - GCC: 9.3.0

**Additional context**
The same problem exists for `dict` and `set` comprehensions. Minimal not-working examples:
```cython
{0: 0 for a in f(a)}
```
```cython
{0 for a in f(a)}
```
For generator expressions, the `UnboundLocalError` does not appear until the iteration is performed:
```cython
result = (0 for a in f(a))
list(result)  # triggers error
```

**Comment by scoder** [comment] 2021-03-27 15:56
Duplicate of #1159.

**Closed by scoder** 2021-03-27 15:56 UTC
Labels: R: duplicate
