### ISSUE TITLE
Memoryview of boolean ndarrays

### ISSUE THREAD

**Issue by padix-key** [cython/cython#2204] opened 2018-04-18 08:49 UTC
I would like to create a `bint` memoryview of a `numpy.ndarray` with `dtype=np.bool.` Example:

```
cimport cython
cimport numpy as np
import numpy as np

cdef np.ndarray array = np.array([True, True, False, True], dtype=np.bool)
cdef bint[:] array_view = array
```

Unfortunately, running this code raises the following error:

`ValueError: Does not understand character buffer dtype format string ('?')`

**Comment by akaszynski** [comment] 2018-07-12 20:30
I've had a similar problem.  Here's my solution based on:
https://stackoverflow.com/questions/18058744/passing-a-numpy-pointer-dtype-np-bool-to-c

```cython
import numpy as np
cimport numpy as np
from numpy cimport ndarray
ctypedef unsigned char uint8

def booltest(ndarray[np.uint8_t, cast=True] arr):
    """ Sum a numpy np.bool array within cython """
    cdef int i
    cdef int sizearr = arr.size
    cdef int arr_sum = 0

    for i in range(sizearr):
        arr_sum += arr[i]

    return arr_sum

```

**Comment by padix-key** [comment] 2018-07-17 18:10
Thank you. I use a quite similar solution at the moment, but I think it would be convenient to have the type directly supported.

**Comment by 0phoff** [comment] 2018-10-24 15:13
is there any progress towards this issue?
``ndarray[np.uint8_t, cast=True]`` does not allow to define your function as being ``nogil``, which is quite a bummer...

**Comment by scoder** [comment] 2019-05-19 17:46
Duplicate of #2675.

**Closed by scoder** 2019-05-19 17:46 UTC

**Comment by jeybrahms** [comment] 2019-06-27 03:46
I'm not sure why this issue is closed. Though the original code posted by OP is outdated and no longer compiles under cython 0.29.10, the following modification should've worked and it doesn't

file issue2204.pyx:
import numpy as np
array = np.array([True, True, False, True], dtype=np.bool)
cdef bint[:] array_view = array

inside a shell:
% cythonize -a -3 -i issue2204.pyx
% python -c 'import issue2204'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "issue2204.pyx", line 4, in init issue2204
    cdef bint[:] array_view = array
ValueError: Does not understand character buffer dtype format string ('?')

The following link, https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html#arrays-scalars-built-in, shows that '?' is a valid format string for bool.

**Comment by padix-key** [comment] 2019-09-10 12:41
I would like to request to reopen this issue, since #2676 seems not to fix memory views. At least I get still the same runtime error `ValueError: Does not understand character buffer dtype format string ('?')` at Cython 0.29.12
