### ISSUE TITLE
[BUG] dict has been shared when unpacking it in lambda for default dict

### ISSUE THREAD

**Issue by pengwk** [cython/cython#4082] opened 2021-04-02 06:16 UTC
**To Reproduce**
Code to reproduce the behaviour:
```cython
import collections

def just_call():
    defaults = {'a': 0, 'b':0}

    data = collections.defaultdict(lambda: {**defaults})

    for x in range(5):
        if x in (1, 3):
            value = 1
        else:
            value = 4

        data[x]['a'] += value
        data[x]['b'] += value

    print(data)
    return data
```

```
In [1]: import test_default

In [2]: test_default.just_call()
defaultdict(<cyfunction just_call.<locals>.<lambda> at 0x7f588cf9f9a8>, {0: {'a': 14, 'b': 14}, 1: {'a': 14, 'b': 14}, 2: {'a': 14, 'b': 14}, 3: {'a': 14, 'b': 14}, 4: {'a': 14, 'b': 14}})
Out[2]:
defaultdict(<cyfunction just_call.<locals>.<lambda> at 0x7f588cf9f9a8>,
            {0: {'a': 14, 'b': 14},
             1: {'a': 14, 'b': 14},
             2: {'a': 14, 'b': 14},
             3: {'a': 14, 'b': 14},
             4: {'a': 14, 'b': 14}})
```

**Expected behavior**

```
In [1]: import test_default

In [2]: test_default.just_call()
defaultdict(<cyfunction just_call.<locals>.<lambda> at 0x7f98515d3a70>, {0: {'a': 4, 'b': 4}, 1: {'a': 1, 'b': 1}, 2: {'a': 4, 'b': 4}, 3: {'a': 1, 'b': 1}, 4: {'a': 4, 'b': 4}})
Out[2]:
defaultdict(<cyfunction just_call.<locals>.<lambda> at 0x7f98515d3a70>,
            {0: {'a': 4, 'b': 4},
             1: {'a': 1, 'b': 1},
             2: {'a': 4, 'b': 4},
             3: {'a': 1, 'b': 1},
             4: {'a': 4, 'b': 4}})
```

**Environment (please complete the following information):**
 - OS: [Linux]
 - Python version [e.g. 3.6.8]
 - Cython version [e.g. 0.29.21]

**Comment by da-woods** [comment] 2021-04-02 07:11
Duplicate of https://github.com/cython/cython/issues/3227

Thanks for the report. It does look like this is probably a bug

**Closed by da-woods** 2021-04-02 07:11 UTC
